### ISSUE TITLE
Autostart not working on Realme devices

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3351] opened 2020-02-18 10:16 UTC
### Issue Details

- **AdGuard version:**
  -  3.3.230
- **Filtering mode:**
  -  VPN
- **Device:**
  -  Realme 5 Pro
- **Operating system and version:**
  -  9
- **Root access:**
  -  No

### Actual Behavior

The AdGuard application does not start automatically after rebooting.

### Additional Information

User ID: **1639523**
Debug Logs in **NCloud**

**Comment by admitrevskiy** [comment] 2020-07-31 16:16
Can't reproduce this issue, there are no logs from the user. This is most likely due to MIUI restrictions and can be fixed by allowing autostart in system settings for AdGuard app. Moreover 3.4.x version has some improvements for autostart.

Re-open this issue if needed.

**Closed by admitrevskiy** 2020-07-31 16:16 UTC
Labels: P3: Medium, Resolution: Fixed, Status: Resolved
