### ISSUE TITLE
Samsung Android 11: error making AdGuard stop in background

### ISSUE THREAD

**Issue by eduardoaddad** [AdguardTeam/AdguardForAndroid#3803] opened 2021-04-11 16:28 UTC
Version: 3.6.1
Android version: 11
Device: Samsung Galaxy S21 
Background : yes 

Often the application crashes and emits on the main screen or during open applications that AdGuard was closed due to an error

java.lang.IllegalStateException: Not allowed to start service Intent { act=Start cmp=com.adguard.android/.filtering.api.LocalVpnService (has extras) }: app is in background uid UidRecord{867c9ba u0a313 CEM  bg:+1d23h49m15s441ms idle change:cached procs:1 seq(0,0,0)}  (this exception is shown in the log)

Log:

```
13:09:40.382 [protection-pool-13-thread-1] ERROR com.adguard.android.filtering.api.g - An error occurred while starting protection. Making sure that the proxy servers are stopped
13:09:40.382 [protection-pool-13-thread-1] INFO  com.adguard.android.filtering.a.b - Closing the proxy server
13:09:40.383 [protection-pool-13-thread-1] INFO  Native.AGAndroidProxyServer - listener shutdown ok
13:09:40.394 [protection-pool-13-thread-1] INFO  Native.AGAndroidProxyServer - group->join() ok
13:09:40.395 [protection-pool-13-thread-1] INFO  Native.AGIpReachabilityTester - deinit()
13:09:40.395 [protection-pool-13-thread-1] INFO  Native.AGIpReachabilityTester - deinit() ok
13:09:40.395 [protection-pool-13-thread-1] INFO  Native.AGProxyServer - AGProxyServer::stop()
13:09:40.397 [protection-pool-13-thread-1] INFO  Native.AGLocalApiServer - Destroying WebSocket Server...
13:09:40.397 [protection-pool-13-thread-1] INFO  Native.AGLocalApiServer - destroying connections
13:09:40.397 [protection-pool-13-thread-1] INFO  Native.AGLocalApiServer - destroyed
13:09:40.398 [protection-pool-13-thread-1] INFO  Native.AGProxyServer - AGProxyFilter::deinit()
13:09:40.708 [protection-pool-13-thread-1] INFO  Native.AGProxyServer - AGProxyFilter::deinit() ok
13:09:40.709 [protection-pool-13-thread-1] INFO  Native.AGProxyServer - AGProxyServer::stop() ok
13:09:40.797 [protection-pool-13-thread-1] INFO  com.adguard.android.filtering.a.b - The proxy server has been stopped successfully
13:09:40.798 [protection-pool-13-thread-1] INFO  c.a.a.filtering.dns.DnsProxyWrapper - Stopping DnsProxy
13:09:40.799 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.799118] [23624] [DNS proxy] [info] Deinitializing proxy module...

13:09:40.799 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.799259] [23624] [DNS proxy] [info] Shutting down listeners...

13:09:40.799 [Thread-880] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.799544] [5058] [listener(UDP 127.0.0.1:1159)] [info] Finished listening

13:09:40.825 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.825748] [23624] [DNS proxy] [info] Done

13:09:40.826 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.826679] [23624] [DNS forwarder] [info] Deinitializing...

13:09:40.826 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.826954] [23624] [DNS forwarder] [info] Cancelling unstarted async requests...

13:09:40.827 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.827075] [23624] [DNS forwarder] [info] Wait for started async requests to finish...

13:09:40.827 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.827453] [23624] [DNS forwarder] [info] Done

13:09:40.827 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.827565] [23624] [DNS forwarder] [info] All async requests are cancelled

13:09:40.827 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.827678] [23624] [DNS forwarder] [info] Destroying upstreams...

13:09:40.828 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.828353] [23624] [DNS forwarder] [info] Done

13:09:40.828 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.828616] [23624] [DNS forwarder] [info] Destroying fallback upstreams...

13:09:40.829 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.829667] [23624] [DNS forwarder] [info] Done

13:09:40.829 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.829889] [23624] [DNS forwarder] [info] Destroying DNS filter...

13:09:40.830 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.830836] [23624] [DNS forwarder] [info] Done

13:09:40.831 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.831029] [23624] [DNS forwarder] [info] Clearing cache...

13:09:40.831 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.831262] [23624] [DNS forwarder] [info] Done

13:09:40.831 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.831377] [23624] [DNS forwarder] [info] Deinitialized

13:09:40.831 [protection-pool-13-thread-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-11 13:09:40.831645] [23624] [DNS proxy] [info] Proxy module deinitialized

13:09:40.832 [protection-pool-13-thread-1] INFO  c.a.a.filtering.dns.DnsProxyWrapper - DnsProxy has been stopped
13:09:40.854 [protection-pool-13-thread-1] WARN  com.adguard.android.service.a.a - An error occurred on com.adguard.android.service.-$$Lambda$ProtectionServiceImpl$a$fmC09sbBCL4jH83W_GyNBnvih0c@fa553f3 task execution:

java.lang.IllegalStateException: Not allowed to start service Intent { act=Start cmp=com.adguard.android/.filtering.api.LocalVpnService (has extras) }: app is in background uid UidRecord{867c9ba u0a313 CEM  bg:+1d23h49m15s441ms idle change:cached procs:1 seq(0,0,0)}
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1795)
	at android.app.ContextImpl.startService(ContextImpl.java:1740)
	at android.content.ContextWrapper.startService(ContextWrapper.java:738)
	at com.adguard.android.filtering.api.LocalVpnService.a(LocalVpnService.java:289)
	at com.adguard.android.filtering.api.g$a.a(ProtectionManager.java:447)
	at com.adguard.android.filtering.api.g$a.a(ProtectionManager.java:8418)
	at com.adguard.android.filtering.api.g$a.a(ProtectionManager.java:265)
	at com.adguard.android.service.ProtectionServiceImpl$a.a(ProtectionServiceImpl.java:1064)
	at com.adguard.android.service.a.b.b(LongRunningTask.java:1032)
	at com.adguard.android.service.a.a.c(AbstractLongRunningTask.java:101)
	at com.adguard.commons.concurrent.Command.run(Command.java:173)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
13:09:40.855 [protection-pool-13-thread-1] INFO  com.adguard.android.service.a.a - Finished task com.adguard.android.service.-$$Lambda$ProtectionServiceImpl$a$fmC09sbBCL4jH83W_GyNBnvih0c@fa553f3 execution
13:09:49.673 [main] INFO  com.adguard.android.service.s - The event 'on Megazord service disconnected' received
```

**Comment by 123jjck** [comment] 2021-04-12 14:55
Same issue on Samsung Galaxy S20, latest OneUI 3.1 with Android 11. Still occurs on AdGuard 4.0.50
Log:
```15:15:51.150 [Thread-158] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.110366] [15725] [listener(UDP 127.0.0.1:1103)] [info] Finished listening

15:15:51.259 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.259153] [3672] [DNS proxy] [info] Done

15:15:51.261 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.261700] [3672] [DNS forwarder] [info] Deinitializing...

15:15:51.263 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.263195] [3672] [DNS forwarder] [info] Cancelling unstarted async requests...

15:15:51.263 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.263467] [3672] [DNS forwarder] [info] Wait for started async requests to finish...

15:15:51.263 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.263646] [3672] [DNS forwarder] [info] Done

15:15:51.263 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.263839] [3672] [DNS forwarder] [info] All async requests are cancelled

15:15:51.264 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.264019] [3672] [DNS forwarder] [info] Destroying upstreams...

15:15:51.271 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.271375] [3672] [DNS forwarder] [info] Done

15:15:51.271 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.271920] [3672] [DNS forwarder] [info] Destroying fallback upstreams...

15:15:51.272 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.272051] [3672] [DNS forwarder] [info] Done

15:15:51.272 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.272241] [3672] [DNS forwarder] [info] Destroying DNS filter...

15:15:51.275 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.275426] [3672] [DNS forwarder] [info] Done

15:15:51.275 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.275961] [3672] [DNS forwarder] [info] Clearing cache...

15:15:51.276 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.276118] [3672] [DNS forwarder] [info] Done

15:15:51.276 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.276342] [3672] [DNS forwarder] [info] Deinitialized

15:15:51.276 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.276537] [3672] [DNS proxy] [info] Proxy module deinitialized

15:15:51.308 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.308827] [3672] [DNS proxy] [info] Initializing proxy module...

15:15:51.309 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.309621] [3672] [DNS forwarder] [info] Initializing forwarder...

15:15:51.316 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.316392] [3672] [DNS forwarder] [info] Initializing upstreams...

15:15:51.317 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.317318] [3672] [DNS forwarder] [info] Initializing upstream 10.166.244.46...

15:15:51.319 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.319925] [3672] [DNS forwarder] [info] Upstream created successfully

15:15:51.320 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.320593] [3672] [DNS forwarder] [info] Initializing upstream 10.166.244.62...

15:15:51.321 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.321375] [3672] [DNS forwarder] [info] Upstream created successfully

15:15:51.321 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.321916] [3672] [DNS forwarder] [info] Upstreams initialized

15:15:51.322 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:51.322132] [3672] [DNS forwarder] [info] Initializing the filtering module...

15:15:53.183 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.183910] [3672] [100001::filter_100001.txt] [info] Unique domains table size: 67841

15:15:53.184 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.184637] [3672] [100001::filter_100001.txt] [info] Non-unique domains table size: 5

15:15:53.184 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.184919] [3672] [100001::filter_100001.txt] [info] Shortcuts table size: 0

15:15:53.185 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.185119] [3672] [100001::filter_100001.txt] [info] Leftovers table size: 0

15:15:53.185 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.185405] [3672] [100001::filter_100001.txt] [info] Badfilter table size: 0

15:15:53.185 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.185530] [3672] [100001::filter_100001.txt] [info] Approximate memory usage: 1061K

15:15:53.185 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.185648] [3672] [dnsfilter] [info] Filter 100001 added successfully

15:15:53.188 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.188861] [3672] [-3::filter_-3.txt] [info] Unique domains table size: 16

15:15:53.189 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.189568] [3672] [-3::filter_-3.txt] [info] Non-unique domains table size: 1

15:15:53.189 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.189903] [3672] [-3::filter_-3.txt] [info] Shortcuts table size: 0

15:15:53.190 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.190086] [3672] [-3::filter_-3.txt] [info] Leftovers table size: 0

15:15:53.190 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.190325] [3672] [-3::filter_-3.txt] [info] Badfilter table size: 0

15:15:53.190 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.190473] [3672] [-3::filter_-3.txt] [info] Approximate memory usage: 1K

15:15:53.190 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.190605] [3672] [dnsfilter] [info] Filter -3 added successfully

15:15:53.206 [main] INFO  com.adguard.android.AdguardService - Trim memory 15 called
15:15:53.578 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.578784] [3672] [15::filter_15.txt] [info] Unique domains table size: 37061

15:15:53.579 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.579477] [3672] [15::filter_15.txt] [info] Non-unique domains table size: 9

15:15:53.579 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.579782] [3672] [15::filter_15.txt] [info] Shortcuts table size: 323

15:15:53.579 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.579929] [3672] [15::filter_15.txt] [info] Leftovers table size: 23

15:15:53.580 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.580032] [3672] [15::filter_15.txt] [info] Badfilter table size: 0

15:15:53.580 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.580253] [3672] [15::filter_15.txt] [info] Approximate memory usage: 646K

15:15:53.580 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.580358] [3672] [dnsfilter] [info] Filter 15 added successfully

15:15:53.580 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.580493] [3672] [DNS forwarder] [info] Filtering module initialized

15:15:53.580 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.580612] [3672] [DNS forwarder] [info] Forwarder initialized

15:15:53.580 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.580743] [3672] [DNS proxy] [info] Initializing listeners...

15:15:53.582 [threadmanager-cached-pool-18-thread-24] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.582073] [3672] [DNS proxy] [info] Proxy module initialized

15:15:53.595 [Thread-159] INFO  com.adguard.dnslibs.proxy.DnsProxy - [2021-04-12 15:15:53.594491] [6306] [listener(UDP 127.0.0.1:1103)] [info] Listening on 127.0.0.1:1103 (UDP)

15:15:54.780 [main] INFO  com.adguard.android.AdguardService - Trim memory 10 called
15:15:55.734 [main] INFO  com.adguard.android.AdguardService - Trim memory 10 called
15:15:57.321 [main] INFO  com.adguard.android.AdguardService - Trim memory 15 called
15:15:57.723 [main] INFO  com.adguard.android.service.s - The event 'on Megazord service disconnected' received
15:15:57.740 [protection-pool-12-thread-1] INFO  c.a.a.service.ProtectionServiceImpl - Restarting protection...```

**Comment by artemiv4nov** [comment] 2021-04-15 13:27
Oh, I know why the application does it.
This architecture bug a little bit bigger than we could imagine.

It will already totally improved in the 4.0 version.
Please stay on the nightly version. We will deploy a big update soon.

**Comment by artemiv4nov** [comment] 2021-04-15 13:28
As a workaround solution is not to use the app autostart.

**Comment by ameshkov** [comment] 2021-04-21 08:56
@eduardoaddad how often does it happen? Could you please send me full logs once it happens next time to `am@adguard.com`

**Comment by eduardoaddad** [comment] 2021-04-21 12:29
> @eduardoaddad how often does it happen? Could you please send me full logs once it happens next time to `am@adguard.com`

2-4 times a day but not every day

**Comment by ValiumBear** [comment] 2021-07-25 15:31
Is this bug getting fixed soon? It's critical as it stops randomly during idle multiple times per day. Many times I'll only realize after seeing cookie notices (then it's too late and privacy was breached).

Also there's nothing of use in the logs. But it happened after Android 11 update. App is not getting killed, it's in always allowed list of apps.

**Comment by ValiumBear** [comment] 2021-07-25 15:36
Is this bug getting fixed soon? It's critical as it stops randomly during idle multiple times per day. Many times I'll only realize after seeing cookie notices (then it's too late and privacy was breached).

Also there's nothing of use in the logs. 

```
02:05:13.748 [protection-pool-12-thread-1] ERROR com.adguard.android.filtering.api.g - An error occurred while starting protection. Making sure that the proxy servers are stopped
02:09:58.403 [Thread-1484] ERROR Native.AGAndroidProxyServer - onNewConnection: null native inet address
06:56:24.380 [Thread-1621] ERROR Native.AGAndroidProxyServer - onNewConnection: null native inet address
09:08:48.665 [Thread-1653] ERROR Native.AGProxyServer - failed to resolve local.adguard.org (No address associated with hostname)
09:08:48.671 [Thread-1654] ERROR Native.AGProxyServer - failed to resolve dns.adguard.com (No address associated with hostname)
09:19:24.972 [protection-pool-12-thread-1] ERROR com.adguard.android.filtering.api.g - An error occurred while starting protection. Making sure that the proxy servers are stopped
09:24:55.923 [main] ERROR com.adguard.android.a.f - Thread: Thread[main,5,main]; Uncaught exception:

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{6040d64 u0 com.adguard.android/.AdguardService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2240)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8506)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
It happened after Android 11 update. App is not getting killed, it's in always allowed list of apps.
It's very likely the WiFi goes to sleep, but there's no power savings for WiFi enabled.

**Comment by ameshkov** [comment] 2021-07-28 15:29
@ValiumBear @eduardoaddad @123jjck 

Since we cannot reproduce it on our side, it would really help if you could record & send the logs to us.

Once the issue happens again, simply do the following:

1. Settings -> Advanced -> Export logs
2. Send the logs to `devteam@adguard.com`
3. Mention this issue in the email

**Comment by ValiumBear** [comment] 2022-03-08 14:06
It seems the issue is now fixed after Android 12/One UI 4 upgrade. I have not had noticable disconnects since a month. Can others confirm?

**Comment by artemiv4nov** [comment] 2022-11-23 18:56
This issue should be gone in the 4.0 version, please follow updates

**Closed** 2022-11-23 19:00 UTC
Labels: Bug, Resolution: Fixed, Status: Resolved, Version: AdGuard v4.0, Version: AdGuard v4.0 beta 1
