### ISSUE TITLE
Adguard Nighly blocks cellular Internet connection

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdguardForAndroid#4506] opened 2023-03-02 18:19 UTC
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

Adguard Nightly version 4.0 Nighly 58

### Environment

```markdown
- OS:Android 13
- Device:samsung 
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.turn off Wifi 
2.make sure mobile data is on
3.open browser refresh a website 

### Actual Behavior

![Screenshot_20230302_115940_Samsung Internet](https://user-images.githubusercontent.com/96619913/222516998-934b5a69-9838-457d-b6ca-d9c68fa0b457.jpg)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Adguard for the Android Nightly version when enabled won't work on cellular data.

**Comment by jwds1178** [comment] 2023-03-05 00:40
I'm using v4.0 Nightly 59 and it's working with both mobile (TELUS) data and on my home network with fiber (Vianet) data.

**Comment by maxikuzmin** [comment] 2023-03-06 11:37
@Batman2814 duplicate of #4398 
I'm closing this Issue. Let's continue to communicate in that issue

**Closed by maxikuzmin** 2023-03-06 11:37 UTC
