### ISSUE TITLE
User rules in DNS filter section disappear after updating to a new version.

### ISSUE THREAD

**Issue by vadu71** [AdguardTeam/AdguardForAndroid#4420] opened 2023-02-03 18:07 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.41 / 4.0.565

### Environment

```markdown
- OS: Android 13
- Device: Samsung S20 FE
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, RU AdList - Counters

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Disable cache for third-party requests, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Block Flash, Hide your Referrer from third-parties, Hide your User Agent, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1. Create your own user rule in DNS filter section.
2. Update to the latest version.
3. Check DNS section to see it vanished.

### Expected Behavior

User rule should stay untouched.

### Actual Behavior

User rule disappear.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Squall-Leonhart** [comment] 2023-02-04 23:29
Duplicate of #4401

**Comment by vadu71** [comment] 2023-02-09 16:11
Resolved

**Closed** 2023-02-09 16:10 UTC
