### ISSUE TITLE
Traffic stats stops working after statistics reset

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#56] opened 2015-09-22 07:18 UTC
http://forum.adguard.com/showthread.php?6642-%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-Adguard&p=60974&viewfull=1#post60974

**Comment by Revertron** [comment] 2015-09-22 07:27
Duplicate of #31

**Closed by Revertron** 2015-09-22 07:27 UTC
Labels: Bug, Duplicate
