### ISSUE TITLE
When turning on a filter category, filters are not always enabled

### ISSUE THREAD

**Issue by Gitoffthelawn** [AdguardTeam/AdguardForAndroid#2568] opened 2019-02-17 18:44 UTC
Currently testing: AdGuard 3.0.241β

If the user goes to AdGuard Settings -> Content Blocking -> Filters, and then enables a category, corresponding filters are not always enabled.

This makes sense from a programming standpoint, but creates a UX conundrum.

For example, out of the box, no Security filters are enabled.  The user will likely think that enabling the "Security" category will enable all the security filters.  But enabling the category does nothing, because none of the category's member filtersets were previously enabled.

**Comment by lancelot-moon** [comment] 2019-02-17 22:10
No, it doesn't make sense.
I disagree you.
How about specific-languages filters?

**Comment by Gitoffthelawn** [comment] 2019-02-18 00:10
Yes, I'm not sure of the best solution yet.  The example provided by @lancelot-moon is one of the reasons why.  Very few people probably want/need all the language-specific filters enabled.

That said, the UX resulting from the current beta UI design will likely cause problems.  The user will likely think that enabling 'Security' is actually enabling something that helps their security.  But in reality, no filters are actually added when they turn on the 'Security' toggle.

**Comment by lancelot-moon** [comment] 2019-02-18 00:26
No, if only enabling a category but its all filters being disabled, AG app will show ex: "Enabled filters: 0 / 3", which is enough.
I don't think it's a problem.

In a category, some filters are maybe enabled, and others are disabled.
**Enabling a category shouldn't change its filters' original status.**

AG team make some special filters enabled by default on AG for Android, ex: Base filter, Mobile Ads filter...etc.
Others are disabled by default, and let users decide to enable them or not.

**Comment by Gitoffthelawn** [comment] 2019-02-18 03:12
@lancelot-moon I think you are likely misreading what I wrote.  I'm not suggesting anything yet.  To be ***completely*** clear, I'm not suggesting that a toggle turn everything on.

I'm pointing out that there is a UX issue in the beta UI.  I haven't come up with a solution yet, nor have I been asked to do so.

**Comment by ameshkov** [comment] 2019-02-18 09:05
> For example, out of the box, no Security filters are enabled. The user will likely think that enabling the "Security" category will enable all the security filters. But enabling the category does nothing, because none of the category's member filtersets were previously enabled.

Well, yeah, but that's true for Security category only.

You see, when you enable a category for the first time, AdGuard enables filters marked as "recommended" and matching the preferred language. The problem is that we have no filters marked as "recommended" in the Security category at the moment.

**Comment by Gitoffthelawn** [comment] 2019-02-18 10:12
@ameshkov wrote:

> Well, yeah, but that's true for Security category only.

What about 'Other' and 'Custom filters'?

> You see, when you enable a category for the first time, AdGuard enables filters marked as "recommended" and matching the preferred language. The problem is that we have no filters marked as "recommended" in the Security category at the moment.

Thanks Andrey.  That's useful information.  What qualifies a list to be "recommended"?

It's only a single data point, but I've used all three of the filter lists now in the Security section for quite some time, and have not run into any significant issues.

**Comment by ameshkov** [comment] 2019-02-18 10:24
> What about 'Other' and 'Custom filters'?

Same goes for Other.
Custom is a bit different as its empty by default, and filters there are added manually.

> What qualifies a list to be "recommended"?

We choose them based on our experience with the filters and users feedback.

**Comment by ameshkov** [comment] 2019-03-19 14:19
The issue will go away when we finally decide what filters from these categories we can recommend.

**Closed by ameshkov** 2019-03-19 14:19 UTC
Labels: Question
