### ISSUE TITLE
Firewall notifications for individual apps in Adguard 4.0

### ISSUE THREAD

**Issue by githvaik** [AdguardTeam/AdguardForAndroid#4651] opened 2023-05-03 04:07 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4 Beta

### Environment

```markdown
- OS:13
- Device:Redmi K50i
- Firmware:MIUI 14.0.02
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals, Turn off Advertising ID

### Issue Details

Steps to reproduce:
1.Open FIrewall
2.Open custom ruleset
3.Open rules for any app. Option to disable firewall notifications for that particular app is missing. THis feature is present in Adguard 3.96

### Expected Behavior

I require the option for disabling firewall notifications for individual apps.
When this option is not present, using adguard becomes very annoying.

This is annoying because there are some apps which I have permanently blocked, and I don't want notifications everytime these permanently blocked apps try to connect online. In adguard 3.96, I have disabled notifications for these apps.

The option to disable firewall notifications for certain apps is required.
Kindly add this!

### Actual Behaviour

Actual Behaviour -> Everytime an app which I've blocked tries to connect, adguard 4 asks if I want to temporarily unblock it.
This is annoying because there are some apps which I have permanently blocked, and I don't want notifications when these permanently blocked apps try to connect online.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by githvaik** [comment] 2023-06-15 12:54
Hi
Can someone look into this plz?

I realise you have many bugs/stuff to look into
But this issue makes the app unusable.
The unnecessary notifications due to this bug are really annoying!

**Comment by leacha69** [comment] 2023-06-16 11:24
IMO opinion, this missing doesn't make the app unusable but it is annoying to get the notifications about certain apps that you know is blocked.

Please return the option.

**Comment by patrickdrd** [comment] 2023-06-16 11:28
it's not the only thing that's missing IMO, another is the option to disable start and stop when no connection and recconect,
nevertheless I was forced to update by a nag that I received many times a couple of days before,
but I cannot say I like this version, at least not yet..

**Comment by sconim** [comment] 2023-06-16 13:29
Depending on which app was blocked by the firewall, these notifications can turn from "whatever" to annoying and ultimately to frustrating. Some blocked system vendor's apps are in the overly frustrating category.

So, yes, this feature needs to be reimplemented.

**Comment by githvaik** [comment] 2023-06-16 13:33
> Depending on which app was blocked by the firewall, these notifications can turn from "whatever" to annoying and ultimately to overly frustrating. Some blocked system vendor's apps are in the overly frustrating category - with the notifications becoming pretty much ongoing.
> 
> So, yes, this feature needs to be reimplemented.

Indeed, especially the blocked apps which try to connect every few seconds are the most annoying!
This feature really desperately needs to be re-implemented!!!

**Comment by githvaik** [comment] 2023-06-16 13:36
> notifications

Adguard does become unusable.
Check sconim's comment above.

Blocked vendor & bloatware apps keep trying to connect home every few seconds!
Especially true for Xiaomi devices which are know to have tons of bloatware.

And every few seconds, I have an annoying popup asking if I want to temporarily unblock the app which was supposed to be permanently blocked!!!!!!!!!

**Comment by Versty** [comment] 2023-06-16 14:44
@githvaik @sconim @patrickdrd @leacha69 
Hi there! 

We hear your feedback and will discuss the single-app firewall notifications once more. 

For now, we have a temporary solution: disable all firewall notifications, that may be something you are looking for. 

*Settings → General → App notifications → Notification categories → disable the Firewall switch*

**Comment by githvaik** [comment] 2023-06-16 15:14
> @githvaik @sconim @patrickdrd @leacha69 Hi there!
> 
> We hear your feedback and will discuss the single-app firewall notifications once more.
> 
> For now, we have a temporary solution: disable all firewall notifications, that may be something you are looking for.
> 
> _Settings → General → App notifications → Notification categories → disable the Firewall switch_

Hi Diana

Adding to sconim's above comment, I use single app notifications for allowing temporary access for certain apps.
Example - I have an app to use as an AC remote. When travelling & I need to add new models, I open this app and temporarily unblock it in the firewall.
Same applies to other similar apps.

In such situations, single app firewall notifications is very very convenient!!!!

**Comment by Miteirao** [comment] 2023-07-02 20:38
We need per app notifications settings, hurry!

Also, the older clean and fast filtering log

**Comment by sconim** [comment] 2023-07-02 21:28
> We need per app notifications settings, hurry!
> 
> Also, the older clean and fast filtering log

16-17?

**Comment by CodeVerse** [comment] 2023-09-05 17:44
I am also adding to this request.  The feature of individual notifications per app are critical to smooth management of the firewall.

In fact, my issue #4955 highlights the all the key points  why V4 is a step back from V3.  Firewall management in V3 was seamless and easy, V4 is a sad shell of what it used to be.  It is one thing if the application never had the functionality, it is another to have something that worked so well, then distroy it.  Is AdGuard going the way of Microsoft and Google now?

I reverted, and am staying on V3 until these issues are addressed, and for anyone else with the issue who wishes to do the same, you can disable the AdGuard update notifications.

Note you should remember to export your settings when reverting otherwise you will need to set up your rules again.

As of this comment, no one at the AdGuard team is assigned to this bug, and I was asked to come here and "vote" on this item.

**Comment by r0lZ** [comment] 2023-09-12 13:26
I agree that the removal of the per-app control of the firewall notifications is a terrible regression, that should be fixed quickly.

And also, why not reintroduce the list of all apps with the icons for the firewall options, that was so convenient in v3? It was so easy to verify if all apps were configured correctly. Why do you remove such useful features?

**Comment by technocrattobe** [comment] 2023-12-24 18:53
V4.3 missed this feature

**Comment by dallas7** [comment] 2024-01-26 20:51
I echo ALL the sentiments of previous postings here.

The nice folks at AdGuard suggested I post here, so...

On July 30, I emailed AdGuard about this and followed up again on January 20.

In a reply to the first, this notifications re-design was referred to as an "issue," and a "problem" in a reply to the second.  The only issue/problem is that they REMOVED the feature.  (Well, that and everything they did to destroy the efficient, intuitive v3 UI/UX.)

In each reply they noted "we'll soon release a patch for it, so you will be able to turn off firewall notifications individually for each app."  There've been four updates since the June, 2023 release of 4.0. 

I made the mistake of updating v3 to v4 on my google tablet and figured out turning off firewall notifications long before reading here today that "temporary solution."   In the meantime, since that June 16 post, the silence has been deafening.

I'm still running v3 on another google device (aka "phone").   Fortunately, the v4 update can be kept in a disabled state.   I hope that doesn't go away.

As my tablet is going on seven years and I'm buying a new one soon and I'm actually considering side loading the v3.6.11 apk, though I'm not sure if I'll be able to move the license to it or if IT will continue to update filters, etc. while keeping the v4 update dormant.  Sigh.

Otherwise, many kudos for fast replies from support.  

Ref:  Tickets 787274 & 863307, both having been closed.

**Comment by r0lZ** [comment] 2024-01-27 08:58
I fully agree with your comment, dallas7.
I have sideloaded v3.6.11 on my phone, and currently, it works perfectly well. No problem with the license and the filters are still updated regularly.
Maybe I'm missing some recent improvements in v4, but at least, I use the good UI, and the ads and trackers are still perfectly filtered.

**Comment by technocrattobe** [comment] 2024-01-28 17:46
I am sideloading 3.6.11
No upgrade till this is addressed.

**Closed** 2024-05-17 11:32 UTC
Labels: Feature request, Resolution: Done, Status: Resolved, Priority: P3, Version: AdGuard v4.4, Carriage, Highlight
