### ISSUE TITLE
Additional firewall options - traffic limiter

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1363] opened 2017-08-09 14:41 UTC
User asked to implement an option to throttle bandwidth per app while on cellular data. To set a limit for apps that are mainly used on Wi-Fi, but you want to be able to use them on cellular data without eating up all traffic.

Also, a user asked about being able to see how many traffic an app is using while on a cellular network and a separate Wi-Fi section.

**Comment by ameshkov** [comment] 2020-03-20 16:09
Duplicate of #3226 #3227

**Closed by ameshkov** 2020-03-20 16:09 UTC
Labels: Feature request, P4: Low
