### ISSUE TITLE
Update translations of the app

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#1993] opened 2018-07-24 12:04 UTC
<details><summary>when using hotkeys:</summary>

![screenshot_20180724-104732](https://user-images.githubusercontent.com/15856304/43136826-7edef586-8f52-11e8-9177-ae4508ac24ee.jpg)

</details>

<details><summary>automation and crash reporting settings:</summary>

![screenshot_20180724-104542__01](https://user-images.githubusercontent.com/15856304/43136812-70da08a4-8f52-11e8-9c32-a10a0edc3a2c.jpg)

![screenshot_20180724-104558__01](https://user-images.githubusercontent.com/15856304/43136847-91787870-8f52-11e8-9eca-1da2be804dfe.jpg)

</details>

<details><summary>requests for collecting the crashreports :</summary>

![screenshot_20180724-104531__01](https://user-images.githubusercontent.com/15856304/43136901-caf47414-8f52-11e8-8a9f-0d59bd70d0a0.jpg)

</details>

### Your environment

* Adguard version: 2.12.120
* Device model: ONEPLUS A3003
* Operating system and version: 8.0.0

**Comment by ameshkov** [comment] 2018-07-24 12:06
Before publishing the beta version we need to be sure that all the new scripts are available on oneskyapp (and don't forget about screenshots!)

**Comment by lancelot-moon** [comment] 2018-07-24 16:15
Untranslated strings.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/J0KYoRa.png)

![image](https://i.imgur.com/4w3KkVL.png)

![image](https://i.imgur.com/I0VyTI5.png)

![image](https://i.imgur.com/ulcMPIN.png)

![image](https://i.imgur.com/glTzrCL.png)

![image](https://i.imgur.com/1pRzZRh.png)

![image](https://i.imgur.com/QcU7DH3.png)

![image](https://i.imgur.com/PzHFSa0.png)
</details><br/>

**Comment by ameshkov** [comment] 2018-07-29 15:58
Duplicate of #2005

**Closed by ameshkov** 2018-07-29 15:58 UTC
