### ISSUE TITLE
Cloud saved settings

### ISSUE THREAD

**Issue by Hyperbolic7** [AdguardTeam/AdguardForAndroid#5494] opened 2024-10-27 12:50 UTC
### Issue Details

Pls add cloud sync for  our settings  every time we reinstall we have to do all it again

### Proposed solution

Na

**Comment by PACHAKUTlQ** [comment] 2024-10-29 02:27
If cloud settings isn't in high dev priority, are there any alternatives, like manually exporting and importing settings?

**Comment by Lwb828** [comment] 2024-10-29 16:12
In my opinion, you don't actually need cloud backup, you can initialise the application by deleting unnecessary data (referring to the settings of rules, low-level settings and other aspects), which can reduce the frequency of clearing data, as for the transfer settings between devices, you only need to upgrade the backup to full data backup and full data import, of course, the backup settings are still necessary

**Comment by ESurina** [comment] 2024-10-29 17:33
Duplicate of #134

**Closed by ESurina** 2024-10-29 17:33 UTC
Labels: Feature request, Priority: P4
