### ISSUE TITLE
[Android] Spasibo (sberbank) HTTPS issue

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2216] opened 2018-10-29 14:00 UTC
Spasibo (Sberbank) application is not able to work with enabled HTTPS filtering.

Please, add to the exclusion list.

**Comment by admitrevskiy** [comment] 2018-11-14 07:06
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/2106

**Closed** 2018-11-14 09:43 UTC
Labels: Compatibility, SSL
