### ISSUE TITLE
Enable HTTPS notification is visible when certificate is moved to the system store

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#2343] opened 2018-11-22 23:11 UTC
Report from the telegram chat:

> On the latest nightly you've added the notification "Enable HTTPS filtering for better blocking quality".

> When the certificate is moved to the system store on a device with root access that is still there. Is that intentional?

**Comment by nkartyshov** [comment] 2018-12-07 10:43
Cannot reproduce

I think this bug has already fixed in issue https://github.com/AdguardTeam/AdguardForAndroid/issues/2360

**Closed** 2019-02-14 14:43 UTC
Labels: Bug, P2: High
