### ISSUE TITLE
Incompatibility with com.yoha.ahoy

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3080] opened 2019-09-19 18:54 UTC
### Issue Details

- **AdGuard version:**
  - 3.2.150
- **Filtering mode:**
  - Local VPN
- **Device:**
  - HTC U-2u
- **Operating system and version:**
  - Android 6
- **Root access:**
  - No

### Expected Behavior

AdGuard shouldn't interfere with the app.

### Actual Behavior

AdGuard blocks some in-app API calls.

### Screenshots

Not applicable

### Additional Information

Filtering & debus logs available in helpdesk ticket 2316322

**Comment by ameshkov** [comment] 2019-09-21 14:14
@akmLaVx is it a SIP app? Does it work with any other VPN app?

**Comment by yohalabs** [comment] 2019-09-23 10:09
Hello,

It has nothing to do with sip, it's just a plain https api call.

If we:

* Uncheck "Ad blocking", things will work. 😀
* Check "Ad blocking" and check the sub option "HTTPS filtering", things will work😀
* Check "Ad blocking" but Uncheck the sub option "HTTPS filtering", things will NOT work 😫

Seems like AdGuard mis-recognized our api response as an ad or tracker, but if we tell AdGuard to check https deeply, it realized that it's an normal api response ( json string as body )

**Comment by yohalabs** [comment] 2019-09-23 10:17
Below is AdGuard verbose log when the api failed. ( log everything )

You can see AdGuard bypassing the https request, and our server did received request from APP.
But the response from server dropped by AdGuard, the APP never got response and throws Network Failure.

Seems AdGuard bypassing https checks, but block it without checking, otherwise, if we told AdGuard to check https packet, AdGuard will let the response pass to APP.

Tell me if you need more info, thank you

### Log

```
==================================================================================
`AD Blocking` ENABLED with `HTTPS filtering` DISABLED
result: Server response dropped by AdGuard
expect: APP should receive response
==================================================================================

16:17:05.504 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=20] new TCP connection 172.18.11.218:38221 -> X.X.X.X:443
16:17:05.547 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=21] new TCP connection 172.18.11.218:45348 -> X.X.X.X:443
16:17:05.550 [Thread-19298] DEBUG Native.AGIpReachabilityTester - [id=20] operator() Connection to X.X.X.X:443 succeeded
16:17:05.565 [tcpip-stack-pool-3-thread-88] DEBUG c.a.a.filtering.api.LocalVpnService - TCP id=21 onTcpConnectRequest: com.yoha.ahoy /172.18.11.218:45348 /X.X.X.X:443 10264 DEFAULT
16:17:05.567 [tcpip-stack-pool-3-thread-88] DEBUG c.a.android.filtering.commons.b - TCP id=21 com.yoha.ahoy /172.18.11.218:45348 /X.X.X.X:443 10264 DEFAULT redirect /X.X.X.X:443 to /127.0.0.1:1112
16:17:05.569 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=21] complete_tcp_connect_request: redirecting connection
16:17:05.583 [tcpip-stack-pool-3-thread-88] DEBUG c.a.a.filtering.api.LocalVpnService - TCP id=20 onTcpConnectRequest: com.yoha.ahoy /172.18.11.218:38221 /X.X.X.X:443 10264 DEFAULT
16:17:05.598 [tcpip-stack-pool-3-thread-88] DEBUG c.a.android.filtering.commons.b - TCP id=20 com.yoha.ahoy /172.18.11.218:38221 /X.X.X.X:443 10264 DEFAULT redirect /X.X.X.X:443 to /127.0.0.1:1112
16:17:05.597 [Thread-19298] DEBUG c.a.android.filtering.events.u - Creating new stats for com.yoha.ahoy with id 21 and network type MOBILE
16:17:05.600 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=20] complete_tcp_connect_request: redirecting connection
16:17:05.600 [Thread-19298] DEBUG com.adguard.android.d.a.d - TCP id=21 resolveConnectionInfo: sessionId=1000020 connectionInfo=com.yoha.ahoy /172.18.11.218:45348 /X.X.X.X:443 10264 BYPASS_HTTPS
16:17:05.606 [Thread-19298] DEBUG c.a.corelibs.proxy.ProxyServer - New proxy connection /127.0.0.1:55694<->/X.X.X.X:443
16:17:05.608 [Thread-19298] DEBUG Native.AGAndroidProxyServer - completeOnNewConnectionWithInfo: Resolved application name: com.yoha.ahoy
16:17:05.611 [Thread-19298] DEBUG c.a.android.filtering.events.u - Creating new stats for com.yoha.ahoy with id 20 and network type MOBILE
16:17:05.612 [Thread-19298] DEBUG com.adguard.android.d.a.d - TCP id=20 resolveConnectionInfo: sessionId=1000021 connectionInfo=com.yoha.ahoy /172.18.11.218:38221 /X.X.X.X:443 10264 BYPASS_HTTPS
16:17:05.612 [Thread-19298] DEBUG c.a.corelibs.proxy.ProxyServer - New proxy connection /127.0.0.1:55695<->/X.X.X.X:443
16:17:05.613 [Thread-19298] DEBUG Native.AGAndroidProxyServer - completeOnNewConnectionWithInfo: Resolved application name: com.yoha.ahoy
16:17:05.641 [Thread-19298] DEBUG Native.AGProxySession - [id=1000020] Set operating mode to DETECTION
16:17:05.641 [Thread-19299] DEBUG Native.AGProxySession - [id=1000021] Set operating mode to DETECTION
16:17:05.643 [Thread-19298] DEBUG Native.AGProxySession - [id=1000020-ssl] Set operating mode to SSL_BYPASS
16:17:05.643 [Thread-19299] DEBUG Native.AGProxySession - [id=1000021-ssl] Set operating mode to SSL_BYPASS
16:17:05.644 [Thread-19298] DEBUG Native.AGProxySession - [id=1000020-ssl] Bypassed protocol info: proto=4, len=172: 16030100a7010000a303038aff5f91156a05ed9bde2c9f3c1f0202e5fb6c2fdf0079db1b3eef37392c41fe000016c02bc02cc02fc030c013c014009c009d002f003500ff010000640000001a0018000015617069312d6465762e796f68616c6162732e636f6d0017000000230000000d0016001406010603050105030401040303010303020102030010000e000c02683208687474702f312e31000b00020100000a00080006001700180019
16:17:05.644 [Thread-19299] DEBUG Native.AGProxySession - [id=1000021-ssl] Bypassed protocol info: proto=4, len=172: 16030100a7010000a3030396595fa25634893b316dea016fa241db9b8740b2c3445253fc87b6b79f3ea36d000016c02bc02cc02fc030c013c014009c009d002f003500ff010000640000001a0018000015617069312d6465762e796f68616c6162732e636f6d0017000000230000000d0016001406010603050105030401040303010303020102030010000e000c02683208687474702f312e31000b00020100000a00080006001700180019
16:17:05.645 [Thread-19298] DEBUG Native.AGProxySession - [id=1000020-ssl] Detected protocol is SSL but HTTPS interception should not be performed on this connection, bypassing
16:17:05.646 [Thread-19299] DEBUG Native.AGProxySession - [id=1000021-ssl] Detected protocol is SSL but HTTPS interception should not be performed on this connection, bypassing
16:17:05.646 [Thread-19298] DEBUG Native.AGProxySession - [id=1000020-ssl] Set operating mode to PASS
16:17:05.647 [Thread-19299] DEBUG Native.AGProxySession - [id=1000021-ssl] Set operating mode to PASS
16:17:05.648 [proxy-server-pool-3-thread-89] DEBUG com.adguard.android.d.a.d - TCP id=21 onBeforeRequest: null
16:17:05.650 [proxy-server-pool-3-thread-89] DEBUG com.adguard.android.d.a.d - TCP id=20 onBeforeRequest: null
16:17:05.852 [Thread-19298] DEBUG Native.AGProxySession - [id=1000020-pass-ssl] Shutting down session (from=1686)
16:17:05.854 [Thread-19298] DEBUG Native.AGProxySession - [id=1000020-pass-ssl] processDataFromClient: read data of length 0 on session in shutdown state
16:17:05.855 [Thread-19298] DEBUG Native.AGProxySession - [id=1000020-pass-ssl] processDataFromRemote: read data of length 0 on session in shutdown state
16:17:05.855 [Thread-19298] DEBUG Native.AGProxySession - [id=1000020-pass-ssl] Destroying session
16:17:05.856 [proxy-server-pool-3-thread-89] DEBUG com.adguard.android.FilteringLog - TCP id=21 sess=1000020 CONNECT 0  "X.X.X.X" "" com.yoha.ahoy (10264) 215ms 1092 4431
16:17:05.858 [proxy-server-pool-3-thread-89] DEBUG c.a.android.filtering.events.u - Mediating stats for com.yoha.ahoy with id 21 and network type MOBILE
16:17:05.857 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=21] connection reset by remote host
16:17:05.857 [single-pool-3-thread-1] DEBUG c.a.a.service.StatisticsServiceImpl - Increment statistics cache
16:17:05.859 [proxy-server-pool-3-thread-89] DEBUG com.adguard.android.d.a.d - TCP id=21 Connection closed: action=BYPASS_HTTPS sent=1092 received=4431 requestsStarted=1 requestsProcessed=1
16:17:05.860 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=21] TCP connection was closed, 7 active connections left
16:17:05.861 [tcpip-stack-pool-3-thread-88] DEBUG c.a.a.filtering.api.LocalVpnService - TCP id=21 Connection statistic: sent=1212, received=4591
16:17:05.861 [mediator-pool-3-thread-8] DEBUG c.a.a.service.StatisticsServiceImpl - Increment statistics cache
16:17:05.863 [tcpip-stack-pool-3-thread-88] DEBUG c.a.a.filtering.api.LocalVpnService - TCP id=21 onTcpClosed: Connection closed
16:17:05.919 [Thread-19299] DEBUG Native.AGProxySession - [id=1000021-pass-ssl] Shutting down session (from=1686)
16:17:05.925 [Thread-19299] DEBUG Native.AGProxySession - [id=1000021-pass-ssl] processDataFromClient: read data of length 0 on session in shutdown state
16:17:05.926 [Thread-19299] DEBUG Native.AGProxySession - [id=1000021-pass-ssl] processDataFromRemote: read data of length 0 on session in shutdown state
16:17:05.927 [Thread-19299] DEBUG Native.AGProxySession - [id=1000021-pass-ssl] Destroying session
16:17:05.928 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=20] connection reset by remote host
16:17:05.928 [proxy-server-pool-3-thread-89] DEBUG com.adguard.android.FilteringLog - TCP id=20 sess=1000021 CONNECT 0  "X.X.X.X" "" com.yoha.ahoy (10264) 286ms 1045 4915
16:17:05.933 [proxy-server-pool-3-thread-89] DEBUG c.a.android.filtering.events.u - Mediating stats for com.yoha.ahoy with id 20 and network type MOBILE
16:17:05.935 [proxy-server-pool-3-thread-89] DEBUG com.adguard.android.d.a.d - TCP id=20 Connection closed: action=BYPASS_HTTPS sent=1045 received=4915 requestsStarted=1 requestsProcessed=1
16:17:05.930 [tcpip-stack-pool-3-thread-88] DEBUG c.a.a.filtering.api.LocalVpnService - TCP id=20 Connection statistic: sent=1165, received=5075
16:17:05.928 [single-pool-3-thread-1] DEBUG c.a.a.service.StatisticsServiceImpl - Increment statistics cache
16:17:05.929 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=20] TCP connection was closed, 6 active connections left
16:17:05.940 [tcpip-stack-pool-3-thread-88] DEBUG c.a.a.filtering.api.LocalVpnService - TCP id=20 onTcpClosed: Connection closed
16:17:05.943 [mediator-pool-3-thread-8] DEBUG c.a.a.service.StatisticsServiceImpl - Increment statistics cache

```

**Comment by yohalabs** [comment] 2019-09-26 06:21
We've also tried self-signed cert and other valid cert, it makes no difference.

Does AdGuard just drop the response due to an unknow domain name when it is not deep look into https?

Or does this can be fixed simply update the AdGuard maintained rule talbe?

**Comment by ameshkov** [comment] 2019-10-04 15:08
@yohalabs sorry for the late reply, we're looking into it

**Comment by ameshkov** [comment] 2019-10-04 15:21
> Or does this can be fixed simply update the AdGuard maintained rule table?

Hopefully, it can. Is your API IP address static?

We could add a rule like this to the base filter list: `@@192.168.0.1$network` so that AG was doing nothing to it. Please let me know if it helps.

**Comment by yohalabs** [comment] 2019-10-07 08:37
@ameshkov 

Hi, thanks for reply and tips about the filter.

We have tested filters these days, the ip based  filter works, but it has to be domain based filters in the long run.

The domain based filters do work, we've used:

* `@@||yohalabas.com^$important,document`
* `@@||yohalabas.com^$important`
* `@@||yohalabas.com^`

All above rules do not work. And I'm wondering why.

**Comment by ameshkov** [comment] 2019-10-07 08:40
Huh, I don't really understand either.

I've added an unblocking rule for now:
https://github.com/AdguardTeam/AdguardFilters/commit/e006aea71505ab5fe7e8f042f9e6def6c0352c0e

@artemiv4nov please note that in order to reproduce the issue you will need to disable that rule. You can do it by adding this to the user filter: `@@||yohalabas.com^$badfilter`

**Comment by yohalabs** [comment] 2019-10-07 08:42
Does it have something to do with the SNI?
Our client do have SNI during the hand shake.

But the strange situation is:

Request send to server successfully, server send response back successfully, but AdGuard DROP the response.

What it means to me:

* The hand-shake process has succeed and not be blocked.

But during the same https session, AdGuard not block the request but blocked the response.

**Comment by yohalabs** [comment] 2019-10-07 08:43
@ameshkov 

Sorry, it is `@@||yohalabs.com^`, `labs` not `labas`, it's my typo :(

**Comment by yohalabs** [comment] 2019-10-07 08:59
@ameshkov 

Thanks for your help.

Yeh, it was my first guess as well in the initial invistigation, but since I noticed that ip based filter can solve this problem, I've lost from the path then :(

Anyway, we will keep investigating as well.
Thanks again :+1:

**Comment by yohalabs** [comment] 2019-10-14 08:38
Seems there are some unrecognized/invalid headers that causes either server or adguard close the connection immediately. But if use ip based white list filter, it will not be dropped.

We have adjust headers and everything is working now.

You might close this issue for now. Thanks for your helps and tips.

**Comment by ameshkov** [comment] 2019-10-23 11:31
Thank you!

**Closed by ameshkov** 2019-10-23 11:31 UTC
Labels: Compatibility, P3: Medium
