### ISSUE TITLE
AdGuard crashes when reconnecting to internet from Airplane Mode (new in Nightly 7, still present in 9)

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#3687] opened 2020-12-12 17:44 UTC
### Issue Details

- **AdGuard version:**
  -  4.0 Nightly 7 thru 9
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Samsung Galaxy S7 Edge & Samsung Galaxy J3
- **Operating system and version:**
  -  Android 8.0 and 7.0
- **Root access:**
  -  No

### Expected Behavior

I turn on Airplane Mode, sometimes change a setting that causes AdGuard to restart its connection (sometimes it happens even if I don't), and then I enable WiFi or simply turn off Airplane Mode. AdGuard should not crash no matter how many apps are open and waiting for a connection.

### Actual Behavior

Follow the above steps and AdGuard crashes over and over again. The only way to get it to stop is to force close and/or disable as many apps as possible that are waiting to connect to the internet (Signal, browsers, WiFi calling, etc)

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

Sending logs to devteam.

**Comment by Ruslanrem** [comment] 2020-12-14 10:10
@infinitewaveparticle  Hi, unfortunately, the problem doesn't reproduce, attach screenshots of crashing and [logs](https://kb.adguard.com/en/android/solving-problems/log#debug) of the problem, please.

**Comment by Chinaski1** [comment] 2020-12-15 14:32
@infinitewaveparticle 
Unfortunately, I can't find the logs you sent.
Could you do it again and specify the time of dispatch in this task?

**Comment by infinitewaveparticle** [comment] 2020-12-17 08:35
I just now resent them to devteam@adguard.com

The logs only span a few minutes so you should be able to tell when the crash occurred quite easily.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by Chinaski1** [comment] 2020-12-17 12:24
Responded to you in an email

**Comment by Chinaski1** [comment] 2020-12-23 13:33
Hello again.
As I told you in the mail, we still need a bug report of the Android system to diagnose it.
[Here's the instruction](https://developer.android.com/studio/debug/bug-report)
It is also advisable to specify the exact time of the crash. It will be much easier for us to find and diagnose the issue there.

**Comment by Chinaski1** [comment] 2020-12-28 11:48
Since the user does not respond, I am temporarily closing the task.
If the issue still persists, please let me know via email.

**Closed** 2020-12-28 11:48 UTC

**Comment by infinitewaveparticle** [comment] 2021-01-23 08:38
It does still persist. I'll update with your requested logs when I have time. I've been dealing with far too much in life lately.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by infinitewaveparticle** [comment] 2021-01-23 09:08
I will do this as soon as I can. 99% of my time is spent on my very sick kid at the moment, as I am also dealing with new health problems of my own. I rarely even get a few minutes to check my email (first time in 3-4 wks right now). I assure you every bug I've posted is still happening.

Sent from ProtonMail mobile

-------- Original Message --------
