### ISSUE TITLE
Adguard Android suddenly not blocking anymore

### ISSUE THREAD

**Issue by Kusurisan** [AdguardTeam/AdguardForAndroid#3987] opened 2021-10-01 05:33 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **Filtering mode:**
- Local VPN & Proxy

- **Device:**
Samsung Galaxy S6
- **Operating system and version:**
Android 5.1.1
- **Root access:**
yes

### Expected Behavior

Blocking of Ads & using filters to block elements on websites

### Actual Behavior
from one minute to the other Adguard stopped blocking Ads. It stopped blocking ads, and isn't blocking site elements defined in user filters anymore. i didn't changed any setting or installed / removed an app.. it just stopped random working without me doing anything. if i look at the used certificate in the chrome app, it now shows me on most websites an LetsEncrypt cert instead of the normal Adguard cert that always showed up. i already restarted my phone multiple times, removed the cert and installed it again, gave adguard root access again, switched tons of settings on and off again, installed the newest version of Adguard.. nothing helped. i now spend 2 hours real time trying to get it fixed.. but nothing i tried works.

</details>

**Comment by Chinaski1** [comment] 2021-10-01 10:02
To avoid waiting for the next release, you can fix this by installing: https://letsencrypt.org/certs/isrgrootx1.der (rename it to .cer) in the certificate storage.

**Comment by Kusurisan** [comment] 2021-10-01 10:38
the certificate now seems to work after installing the linked cert file, but the user rule i have created a while ago is still not working (website code didn't change). this started not working anymore with this cert issue - is this related or do i need to search for the issue elsewhere? any tipps?

**Comment by ralfi** [comment] 2021-10-01 12:23
> We will work on this in the next update.
> 
> [AdguardTeam/CoreLibs#1525](https://github.com/AdguardTeam/CoreLibs/issues/1525)
> 
> To avoid waiting for the next release, you can fix this by installing: https://letsencrypt.org/certs/isrgrootx1.der (rename it to .cer) in the certificate storage.

Hi, on which directory on my docker-based adguard home server i should copy this cert file to work again?

**Comment by sfionov** [comment] 2021-10-01 12:28
@ralfi 

It should be installed on Android 5.1/6.0/7.0 device in Settings -> Security -> Trust settings -> Install certificate manually.

**Comment by ralfi** [comment] 2021-10-01 12:38
> @ralfi
> 
> It should be installed on Android 5.1/6.0/7.0 device in Settings -> Security -> Trust settings -> Install certificate manually.

Oooops, i am using a android 11 device and want to work with my own docker based virtual server...

**Comment by ralfi** [comment] 2021-10-02 16:12
This issues is related to the latest adguard home docker image because its effected by the Le Root Cert issue from 09/30. Its not a bug from AGH and you can resolve this by modifying your fullchain.pem.

**Comment by Kusurisan** [comment] 2021-10-02 19:52
update: now found out that NO css rules / injected code by adguard (removing elements on the site as an example) work anymore. even after installing the mentioned certificate file here in the thread. please fix it :(

**Comment by ralfi** [comment] 2021-10-04 06:18
> 
> 
> update: now found out that NO css rules / injected code by adguard (removing elements on the site as an example) work anymore. even after installing the mentioned certificate file here in the thread. please fix it :(

Dont think so, imho it is related to experid LE Root Cert from 09/30.

**Comment by Kusurisan** [comment] 2021-10-04 19:53
> 
> 
> > update: now found out that NO css rules / injected code by adguard (removing elements on the site as an example) work anymore. even after installing the mentioned certificate file here in the thread. please fix it :(
> 
> Dont think so, imho it is related to experid LE Root Cert from 09/30.

Even if it is expired, if you install another certificate like mentioned above, shouldn't this work? when i look into which cert is used when i visit websites it is now showing the new cert (Adguard's).. so normally there shouldn't be anything preventing the application of the user css rules for websites. but it isn't working. this started completly random without me changing anything, so its likely that it has to do with the LetsEncrypt Cert.. but it should be still fixable. after all, all Adguard is doing is acting like a proxy which open https connections with its own cert.. and you can do this with a lot of programs and software for analytic purposes. and i don't really get how a invalid cert should initiate this bug.. if its invalid, the site shouldn't load at all.. if adguard is using its own cert and it is working because of this, adguard should still be able to change the sourcecode of the site..

or not? :/

**Comment by Kusurisan** [comment] 2021-10-07 08:23
any update on this?

**Comment by Kusurisan** [comment] 2021-11-03 14:08
any update on this issue?

**Comment by Kusurisan** [comment] 2021-12-06 17:01
hello?

**Comment by Chinaski1** [comment] 2021-12-13 09:35
Hello there! @Kusurisan 

Sorry for the late reply.

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by infinitewaveparticle** [comment] 2022-02-01 13:43
> hello?

AdGuard is a small company compared to major software companies. they are being very nice to you. some issues can be fixed quickly while others can take up to a year depending on a) how difficult it is to pinpoint the root cause, b) how many people it is affecting, and c) how many people and hours they can devote to it... since this is an issue seemingly only affecting one user at the present time it unfortunately wont be fixed extremely quickly. please understand this. they are not ignoring you or the issue... they are doing the best they can.

**Comment by infinitewaveparticle** [comment] 2022-02-01 13:46
you could always create a bug bounty for it

**Comment by maxikuzmin** [comment] 2022-09-13 13:43
@Kusurisan  I am closing the issue. If the issue is relevant in the future, you can reopen the issue

**Closed by maxikuzmin** 2022-09-13 13:43 UTC
