### ISSUE TITLE
AdGuard blocking Wi-Fi calling when using default settings.

### ISSUE THREAD

**Issue by Ketawa757** [AdguardTeam/AdguardForAndroid#3627] opened 2020-10-07 21:10 UTC
My very first bug report, hopefully I don't do anything incorrect.

- **AdGuard version: v3.5.1**
- **Filtering mode: Local VPN**
- **Device: Google Pixel 4 XL**
- **Operating system and version: Android 10.0.0**
- **Root access: No**

### Expected Behavior

I have Google Fi with Wi-Fi calling enabled. My device should use Wi-Fi calling when it offers a better connection than mobile data. It is possible to force Wi-Fi calling by turning on airplane mode, then turning on Wi-Fi. This leaves mobile data off and will force the phone to use Wi-Fi calling, which I confirmed works correctly when AdGuard protection is not enabled.

### Actual Behavior

When AdGuard is enabled, my device will not use Wi-Fi calling. It's difficult to provide evidence of this outside of airplane mode, because the phone still completes calls, it just _never_ uses Wi-Fi calling. When airplane mode is enabled, it will not dial. Instead, it provides a message of "Turn off airplane mode to make a call." I can't figure out what is causing the block by scanning the Filtering Log.

### Screenshots

<details><summary>Screenshot: successful Wi-Fi call with AdGuard disabled</summary>
<img width="720" alt="Screenshot_20201007-165235" src="https://user-images.githubusercontent.com/16880791/95387381-a0d42c00-08be-11eb-9de2-9e34407f4599.png">
</details>

<details><summary>Screenshot: failed Wi-Fi call with AdGuard enabled</summary>
<img width="720" alt="Screenshot_20201007-165315" src="https://user-images.githubusercontent.com/16880791/95387482-c3664500-08be-11eb-9b73-d87e6fad7bd3.png">
</details>

**Comment by TheHasagi** [comment] 2020-10-09 08:54
@Ketawa757 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Ketawa757** [comment] 2020-10-09 16:52
Logs sent as requested, please let me know if there are any issues accessing them.

**Comment by TheHasagi** [comment] 2020-10-12 10:13
@Ketawa757 

Hello, did not receive the logs. Can you send them again and mention it with subject **issues/3627**?

**Comment by Ketawa757** [comment] 2020-10-12 17:39
Resent.

**Comment by admitrevskiy** [comment] 2020-10-28 17:20
@Ketawa757 Hi!
Could you provide me additional info please?
Go to your phone Settings -> Network & Internet -> Mobile Network -> Advanced -> Access Point Names -> Google Fi (?)

I'm interested in the MCC and MNC values

**Comment by Ketawa757** [comment] 2020-10-28 17:33
Hello, I am on Google Fi using eSIM, and there is no way to view APN settings. Here is the menu when I go to Settings -> Network & Internet -> Mobile Network.
![Screenshot_20201028-133031](https://user-images.githubusercontent.com/16880791/97474168-309b5200-1922-11eb-918e-4e6b574f31a7.png)

**Comment by Ketawa757** [comment] 2020-10-28 17:42
Searching settings for Access Point Names takes me to that menu. There isn't anywhere to drill down for MCC and MNC values, and they don't show up anywhere else I can find in settings.

**Comment by admitrevskiy** [comment] 2020-10-28 19:11
There is no drop-down `Advanced` menu? :(

**Comment by Ketawa757** [comment] 2020-10-28 19:29
There is; I expanded it in the screenshot. It only reveals the 3 menu choices under "Calling":
Wi-Fi calling: on/off selector switch, it's on
System select (Change the CDMA roaming mode): "Home only" or "Automatic
Erase SIM: self-explanatory

**Comment by Ketawa757** [comment] 2020-10-29 00:55
I think I had some luck messing with dialer codes. On a Pixel phone, Google Fi can use any of T-Mobile, Sprint, or UScellular. The phone gives me this message when switching to each network: "Switching to MCC/MNC: ______"

T-Mobile: 310260
Sprint: 310120
UScellular: 311580

I have coverage with all 3 at home where I captured my logs, but I was probably on T-Mobile, maybe Sprint.

**Comment by admitrevskiy** [comment] 2020-10-29 08:30
That's something!
Let's try to exclude providers subnets from filtering, it may help

Go to AdGuard Settings -> Advanced -> Low level settings -> pref.ipv4.routes.excluded

And add these subnets to the list:

198.230.0.0/16
 68.24.0.0/13 
208.54.0.0/17
 208.54.128.0/19

**Comment by Ketawa757** [comment] 2020-10-29 12:42
Done, still having the same issue.

**Comment by admitrevskiy** [comment] 2020-11-02 09:49
Let's try other ways to figure out what's going wrong:

1) Try to reproduce this issue with AdGuard 3.4:
https://github.com/AdguardTeam/AdguardForAndroid/releases/download/v3.4-release/adguard-3.4-release.apk

2) If issue is not reproducable go to Settings -> Advanced -> Low-Level Settings -> pref.filtered.ports 
And change it to
`80,443,3128,3130,3143,4443,5443,6443,7275,7443,8000:27010,27012:35880,35882:49151`

3) If issue still exist please try to contact Google Fi support and ask them which port is used for WiFi calling

**Comment by EntropySmoke** [comment] 2020-12-21 18:34
Carrier-based WiFi calling uses its own 3GPP IPSec ePDG VPN tunnels on Android phones and bypass VPN apps. I think it is due to IPTables chain rules that you can only edit on rooted phones after each restart or via Magisk module and/or via AFWall+ custom script. 

Carrier-based WiFi calling doesn't even show up in AdGuard log when I use it. I know it bypasses AdGuard local VPN (or any other VPN client), but a local DNS server, such as AdGuard Home, shows 3GPP domain resolution attempts from devices that want to use carrier-based WiFi calling. 

Google Voice WiFi calling (without a carrier on a phone without a SIM card) also bypasses VPN connections (local or not) and bypasses AdGuard's "Block WebRTC" feature. It forces a direct STUN connection with Google over UDP ports 19302-19305. You can only find that out if you use "TCPDump -i any -vv" dumps.

**Comment by sfionov** [comment] 2021-01-05 07:43
@EntropySmoke On most devices, ePDG tunnel can't choose outgoing interface address for validating, when "system" app and ePDG routes are not excluded (You may see it in logcat - when adguard is on, epdg tunnel rejects every packet because it is not for "0.0.0.0" 😬). 

But resolving ePDG routes by MNC/MCC automatically requires TELEPHONY permission, which AdGuard doesn't have. That's why AdGuard excludes "system". I assume that something else changed here in Android 10, and excluding "system" doesn't help anymore.

**Comment by EntropySmoke** [comment] 2021-01-07 13:35
> 
> 
> @EntropySmoke On most devices, ePDG tunnel can't choose outgoing interface address for validating, when "system" app and ePDG routes are not excluded (You may see it in logcat - when adguard is on, epdg tunnel rejects every packet because it is not for "0.0.0.0" 😬).
> 
> But resolving ePDG routes by MNC/MCC automatically requires TELEPHONY permission, which AdGuard doesn't have. That's why AdGuard excludes "system". I assume that something else changed here in Android 10, and excluding "system" doesn't help anymore.

That is beyond my level of beginner understanding... for now. I don't know what kind of a protocol AdGuard Local VPN uses, but WiFi carrier calling ePDG tunnels on phones always use IPSec protocol. It is a standard. I don't think you can encapsulate IPSec within an OpenVPN or a WireGuard tunnel. I know AdGuard can resolve ePDG domain with whichever DNS you specify, but it doesn't filter IPSec packets. 

It could be an issue with OP's specific carrier. Maybe it uses a non-default port that AdGuard filters by default. On my Android 11 phones, I specify 1:65535 (all ports!) in AdGuard Low Level settings and it doesn't prevent WiFi calling from working. It resolves ePDG tunnel domain with DoH on my Android 11 devices and WiFi carrier calls work. Then again, we have very little control over what mobile phones do, especially if they are not rooted, connected to Google Mobile Services + connected to mobile carriers...

**Comment by ameshkov** [comment] 2021-01-09 20:19
@EntropySmoke a little bit more info on this bug here: https://issuetracker.google.com/issues/124415915

**Comment by ameshkov** [comment] 2021-01-09 20:20
@sfionov check out how it was resolved btw:

> The recommended solution (and the one adopted on Pixel devices) is to create the IPsec SA with the XFRM_OUTPUT_MARK (or XFRM_SET_MARK) netlink attribute set to a value that will bypass the VPN. Since this bug was reported on a Samsung, the Android team cannot fix it. Samsung needs to make this change (or another change) in their code.

**Comment by Jayman007** [comment] 2021-02-25 20:27
I am on Google Fi with a Samsung G20+ 5G on Android 11.  I have this exact same issue.  It has taken me nearly a month to figure out it was Ad Guard that was causing the issue.  Now that I can place wifi calls with adguard disabled and as soon as I enable it then I get the same error I used to get about not being able to place calls in airplane mode.

I was going to open a new bug ticket until I find this one.  Has anything been solved here?  It sounds like the issue is something that Samsung needs to change?  How best to bring it to their attention with the exact fix so they can work to resolve it?

**Comment by Jayman007** [comment] 2021-02-25 20:49
> @Ketawa757 Hi!
> Could you provide me additional info please?
> Go to your phone Settings -> Network & Internet -> Mobile Network -> Advanced -> Access Point Names -> Google Fi (?)
> 
> I'm interested in the MCC and MNC values

I am on the same carrier and have this same issue.

The MCC is 310
The MNC is 260

**Comment by ameshkov** [comment] 2021-02-26 06:18
Well, the bug itself is Samsung-specific so if they haven't fixed it, I doubt anything can help.

We could try excluding wifi calling IP addresses from the VPN tunnel, but it hadn't helped the TC as I recall (yet it should've - maybe another Samsung bug).

In order to figure out what IPs to exclude, please do the following:
1. Enable debug-level logging - settings - advanced - logging level - record everything 
2. Reproduce the issue
3. Export logs via settings - advanced
4. Inspect the logs and find connections to ports 500 and 4500 (or just send the logs to devteam@adguard.com - mention this issue in the email)

**Comment by Jayman007** [comment] 2021-02-26 19:10
I don't believe this is a samsung specific issue.  The OP for this bug is on a Pixel handset.  Even in the [Google bug tracker ](https://issuetracker.google.com/issues/124415915#comment3) it's stated that this is reproducible on any Android handset.  If this fix is required on the device manufacturer level then where do we report this to Samsung so that they can work on a resolution?

[adguard_logs_3.6.11_2502_163737.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/6051869/adguard_logs_3.6.11_2502_163737.zip)
I have attached some logs to look over.  The time I was testing was 1633-1636.  When I looked my previous logs over I didn't find anything on either port 500 or 4500.  As mentioned above, Google Fi might be doing it a different way (using STUN?).

I'm watching the logs on my home firewall and can't seem to identify the traffic being used for the wifi calling.  Nothing on ports 500 or 4500.  However I am seeing traffic using STUN (destination port UDP:19302 used everytime) to ip 172.253.117.127.  I tried excluding this IP in Ad Guard with no luck.

**Comment by ameshkov** [comment] 2021-02-26 19:38
It seems (from their reply) that they've fixed it since then on Pixel devices, but other manufacturers should also do this.

> identify the traffic being used for the wifi calling. Nothing on ports 500 or 4500

That's strange. Let's try logcat then. Here's what needs to be done:

1. Reproduce the issue
2. Capture bug report: https://developer.android.com/studio/debug/bug-report
3. In the bug report archive there'll be a huge txt file that will contain the logcat log
4. Look for records from `eris`, they'll look like this:
```
02-12 16:38:25.547 10731 10772 I eris    : 08[IKE] initiating IKE_SA IMS[38] to 213.87.143.150
02-12 16:38:25.582 10731 10772 I eris    : 08[ENC] generating IKE_SA_INIT request 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) N(HASH_ALG) N(REDIR_SUP) ]
02-12 16:38:25.582 10731 10772 I eris    : 08[NET] sending packet: from 192.168.11.182[59288] to 213.87.143.150[500] (464 bytes)
02-12 16:38:25.626 10731 10770 I eris    : 09[NET] received packet: from 213.87.143.150[500] to 192.168.11.182[59288] (424 bytes)
02-12 16:38:25.626 10731 10770 I eris    : 09[ENC] parsed IKE_SA_INIT response 0 [ SA KE No N(NATD_S_IP) N(NATD_D_IP) N(FRAG_SUP) ]
02-12 16:38:25.633 10731 10770 I eris    : 09[IKE] local host is behind NAT, sending keep alives
02-12 16:38:25.636 10731 10770 I eris    : 09[IKE] establishing CHILD_SA IMS{9}
02-12 16:38:25.636 10731 10770 I eris    : 09[ENC] generating IKE_AUTH request 1 [ IDi N(INIT_CONTACT) IDr CPRQ(ADDR6 DNS6 PCSCF6) N(ESP_TFC_PAD_N) SA TSi TSr N(EAP_ONLY) N(MSG_ID_SYN_SUP) ]
02-12 16:38:25.636 10731 10770 I eris    : 09[NET] sending packet: from 192.168.11.182[51469] to 213.87.143.150[4500] (352 bytes)
02-12 16:38:25.767 10731 10763 I eris    : 12[NET] received packet: from 213.87.143.150[4500] to 192.168.11.182[51469] (160 bytes)
02-12 16:38:25.768 10731 10763 I eris    : 12[ENC] parsed IKE_AUTH response 1 [ N((41101)) IDr EAP/REQ/AKA ]
02-12 16:38:25.768 10731 10763 I eris    : 12[IKE] server requested EAP_AKA authentication (id 0x02)
02-12 16:38:25.770 10731 10763 I eris    : 12[DMN] simID : 0
02-12 16:38:25.912 10731 10763 I eris    : 12[IKE] allow mutual EAP-only authentication
02-12 16:38:25.913 10731 10763 I eris    : 12[IKE] server requested DEVICE_IDENTITY
02-12 16:38:25.913 10731 10763 I eris    : 12[ENC] generating IKE_AUTH request 2 [ EAP/RES/AKA ]
02-12 16:38:25.913 10731 10763 I eris    : 12[NET] sending packet: from 192.168.11.182[51469] to 213.87.143.150[4500] (112 bytes)
02-12 16:38:25.970 10731 10764 I eris    : 11[NET] received packet: from 213.87.143.150[4500] to 192.168.11.182[51469] (80 bytes)
```

**Comment by Jayman007** [comment] 2021-02-27 00:10
I did a bug capture on my device but I am not finding any entries for eris in the large txt file.  I am taking another one now and will email a link for you guys (it's over 25MB, too big for gmail).

I certainly hope we can figure out what to exempt from AdGuard to get this working as I really hate the idea of no longer using AdGuard just to have wifi calling working.

**Comment by ameshkov** [comment] 2021-02-28 07:24
Got it, please send it to `devteam@adguard.com` then. Please mention this issue in the email body.

**Comment by Jayman007** [comment] 2021-02-28 23:20
I sent the file to devteam@adguard.com a few days ago.  Please confirm you received it.  It was over the 25MB limit that gmail allows so I included both a dropbox link as well as a google drive link.

**Comment by ameshkov** [comment] 2021-03-01 06:33
Hm, I don't see it. Could you please also forward it to `am@adguard.com`?

**Comment by ameshkov** [comment] 2021-03-02 06:44
@Jayman007 got your bug report, thank you!

**Comment by Jayman007** [comment] 2021-03-04 04:02
Any luck on figuring out Google Fi's ePDG domains/IPs?  It drives me crazy that I must keep adguard disabled so that wifi calling works.  I love adguard and want to be able to use it again ASAP.

As a temp fix, is it possible to restrict Ad Guard to my cell connection?  Keep the wifi interface from ever using Ad Guard.  I think that might allow me to keep adguard enabled but the connection to the ePDG over wifi will work.

No idea if this will even work but I'd like to test.  At least I could cut ads out of my cellular surfing.

**Comment by ameshkov** [comment] 2021-03-04 07:53
Nothing helpful in the log unfortunately.

But I've found some interesting info on Google Fi: https://wifidevan.wordpress.com/2020/09/14/how-to-setup-your-network-for-wi-fi-calling/

> I tried to find ePDG of Google Fi, who allows the phones select either T-Mobile and Sprint based on the signal strength at the location. After doing multiple packet captures, I was scratching my head unable to find any IPsec packets. My phone still shows the call as a Wi-Fi call, but it doesn’t establish an IPsec tunnel unlike traditional mobile operators. Google takes an interesting approach to establish phone calls. Instead of IPsec tunnel to the ePDG, it initiates all calls (wi-Fi or LTE) as google hangout/talk audio calls. It then sends the packets to the ePDG of T-Mobile or Sprint.

Here's a plan that I suggest:

1. Try completely disabling filtering for IPv4/IPv6. For that check `pref.vpn.ipv4.bypass` and `pref.vpn.ipv6.bypass` in the low-level settings. When these enabled, your whole network will be excluded from filtering as if AdGuard was not working at all. The purpose is to see if excluding routes can potentially help with this problem.
2. If it starts working, then I suggest disabling filtering one by one for all apps in the Apps Management settings (starting with "Android OS" and hangouts). This way we'll find which one is responsible for making calls.


> As a temp fix, is it possible to restrict Ad Guard to my cell connection? Keep the wifi interface from ever using Ad Guard. I think that might allow me to keep adguard enabled but the connection to the ePDG over wifi will work.

Well, you could use Tasker to automate it like that: https://kb.adguard.com/en/android/solving-problems/tasker

**Comment by Jayman007** [comment] 2021-03-04 17:27
This is certainly an interesting find about Google Fi.  I was looking in my home firewall logs and didn't see the hangouts traffic.  I will have to continue testing and look for it.

> Here's a plan that I suggest:

Try completely disabling filtering for IPv4/IPv6. For that check pref.vpn.ipv4.bypass and pref.vpn.ipv6.bypass in the low-level settings. When these enabled, your whole network will be excluded from filtering as if AdGuard was not working at all. The purpose is to see if excluding routes can potentially help with this problem.
If it starts working, then I suggest disabling filtering one by one for all apps in the Apps Management settings (starting with "Android OS" and hangouts). This way we'll find which one is responsible for making calls.
<

I will certainly give this a shot and report back on what works.

**Comment by Jayman007** [comment] 2021-03-19 03:16
As soon as I enable the 2 bypass settings and try to place a wifi call it fails.  If I disable adguard, it works.  Enable it again, still fails.

That's a bummer cause it means there is no route exclusion we could do that would fix the situation with my carrier or maybe even Samsung phones.  

So, how would I go about reporting this to Samsung officially?  I have not seen a bug report site.  I will happily report it and keep pressing them to fix it.  I still have a case with google fi open where I have told them exactly how to reproduce the issue.

**Comment by ameshkov** [comment] 2021-03-19 11:26
> As soon as I enable the 2 bypass settings and try to place a wifi call it fails. If I disable adguard, it works. Enable it again, still fails.

Oh, this means that it's enough just to have an active VPN tunnel and this would break Wi-Fi calling completely regardless of the fact that nothing is routed into that VPN.

> So, how would I go about reporting this to Samsung officially? I have not seen a bug report site. I will happily report it and keep pressing them to fix it. I still have a case with google fi open where I have told them exactly how to reproduce the issue.

Tbh, I am not aware of any normal place to file a bug report. Maybe, it should be sent through their customer support?

**Comment by ameshkov** [comment] 2021-05-11 14:47
@JohnRTitor this is probably a different issue, but anyway.

Could you please take a look in AdGuard filtering log and DNS queries to `3gppnetwork.org ` subdomains. What domain Jio uses?

**Comment by ameshkov** [comment] 2021-05-12 08:22
If wonder if anything changes if you use the same IP as CloudFlare for `epdg.epc.mnc873.mcc405.pub.3gppnetwork.org`.

Try adding this line to the user filter:
```
49.44.59.38 vowifi.jio.com
49.44.59.37 epdg.epc.mnc873.mcc405.pub.3gppnetwork.org 
```

**Comment by JohnRTitor** [comment] 2021-05-12 08:29
Yup and I did. Looks like adding those two addresses in user block list indeed disables Vo-WiFi, even when Cloudflare DNS is active. 
![Screenshot_2021-05-12-13-57-50-280_com adguard android](https://user-images.githubusercontent.com/50095635/117943973-53bfa900-b32a-11eb-83f7-3760ff4295c5.jpg)

**Comment by ameshkov** [comment] 2021-05-12 08:41
I don't get it, the screenshot seems wrong (time is wrong, I see the wrong IPs).

**Comment by JohnRTitor** [comment] 2021-05-12 08:44
> I don't get it, the screenshot seems wrong (time is wrong, I see the wrong IPs).

See my updated comment above. It worked actually, after some time. You replied as soon as I started typing again :P

**Comment by ameshkov** [comment] 2021-05-12 08:45
What you need to do to test this:

1. Add those two rules to your DNS User Filter
2. Use AdGuard DNS

**Comment by JohnRTitor** [comment] 2021-05-12 08:54
> What you need to do to test this:
> 
> 1. Add those two rules to your DNS User Filter
> 2. Use AdGuard DNS

Just did now.


![Screenshot_2021-05-12-14-21-36-608_com adguard android](https://user-images.githubusercontent.com/50095635/117947236-a2bb0d80-b32d-11eb-9d10-eebda8ec29d5.jpg)
![Screenshot_2021-05-12-14-21-31-700_com adguard android](https://user-images.githubusercontent.com/50095635/117947240-a353a400-b32d-11eb-8db1-f85222f3414f.jpg)


![Screenshot_2021-05-12-14-21-41-932_com adguard android](https://user-images.githubusercontent.com/50095635/117947225-a0f14a00-b32d-11eb-9747-ed41b7e2a48a.jpg)

**Comment by ameshkov** [comment] 2021-05-12 08:55
It does not seem that rules were added:
```
49.44.59.38 vowifi.jio.com
49.44.59.37 epdg.epc.mnc873.mcc405.pub.3gppnetwork.org 
```

**Comment by JohnRTitor** [comment] 2021-05-12 08:55
I think those subdomains of Jio changes ip addresses frequently but still within a particular range 🤔

**Comment by JohnRTitor** [comment] 2021-05-12 08:56
> It does not seem that rules were added:
> 
> ```
> 49.44.59.38 vowifi.jio.com
> 49.44.59.37 epdg.epc.mnc873.mcc405.pub.3gppnetwork.org 
> ```

I did. 
![Screenshot_2021-05-12-14-26-06-496_com adguard android](https://user-images.githubusercontent.com/50095635/117947650-09402b80-b32e-11eb-929e-79674c1b6cf4.jpg)

**Comment by ameshkov** [comment] 2021-05-12 08:58
Is that "DNS User rules"? It's in DNS filtering -> DNS requests blocking -> DNS User rules

**Comment by JohnRTitor** [comment] 2021-05-12 09:08
> Is that "DNS User rules"? It's in DNS filtering -> DNS requests blocking -> DNS User rules

My apologies, I misunderstood and placed those rules in content blocking user filters.

But now it works! I have no idea why. I added those in DNS user filter and now Vo-WiFi somehow is working? 
![Screenshot_2021-05-12-14-38-12-878_com adguard android](https://user-images.githubusercontent.com/50095635/117949452-c3846280-b32f-11eb-9981-00eb89e1ed23.jpg)
![IMG_20210512_143055](https://user-images.githubusercontent.com/50095635/117949461-c54e2600-b32f-11eb-8507-4bf97a757c6f.jpg)

**Comment by ameshkov** [comment] 2021-05-12 09:29
Well, the point is that JIO Wi-Fi calling works only with these IPs (probably some geo-specific limitation).

Hopefully, when we add more DNS servers, the situation will improve.

**Comment by nicolassp** [comment] 2021-05-12 09:31
@ameshkov It seems that different resolving is done based on geolocation. If someone, digs hostname inside India for example, then it will resolve to 49.44.59.38, 49.44.59.37 (and 49.44.59.36),

The other ip's are hostname resolved for roaming endpoint. What i could suggest, is that adguard dns should query the hostname ip regionally and then automatically inject it to user filter in order to allow VoWifi automatically.

**Comment by JohnRTitor** [comment] 2021-05-12 14:49
Hmm I get what you are saying. But instead of waiting for a adguard dns server in India, can't adguard app just ignore the domain/adguard and use default DNS to query it?

**Comment by nicolassp** [comment] 2021-05-12 14:57
It could ignore epdg.epc. requests via adguard dns in order to use the default ones, or retrieve the queries on epdg.epc hostnames from cloudflare dns which has regional dns servers and be constant until it has more regional dns servers itself

**Comment by ameshkov** [comment] 2021-05-14 16:17
This problem cannot be solved on AG DNS side without adding a DNS server in India.

It can be solved on the app side though, we can use your system default DNS server for resolve EPDG domain names. That's what we intend to do.

**Comment by TPS** [comment] 2021-05-14 17:38
Is it possible for us to _(low-level?)_ configure _another_ DNS server for these inquiries?  Often, a local (e.g., corporate) DNS would have motive to block/tamper with these.

**Comment by ameshkov** [comment] 2021-05-16 19:53
@TPS we intend to add a low-level setting for configuring which domain names should be resolved via the system default DNS server.

**Comment by JohnRTitor** [comment] 2021-05-16 19:57
I am curious to know if there are plans to add a local DNS server in India. Current Covid-19 situation aside, it's a pretty big country and I am sure other Indian AdGuard users are facing this issue as well.

**Comment by ameshkov** [comment] 2021-05-16 20:02
No, there're no plans as of yet since none of the hosting provs we're using provide servers in India.

**Comment by TPS** [comment] 2021-05-16 22:27
> we intend to add a low-level setting for configuring which domain names should be resolved via the system default DNS server.

@ameshkov Could that low-level setting be further configurable so that _its_ default DNS server value could be `system` but we could change it to another that'd potentially be friendlier to other needs (e.g., VoIP _&_ privacy)?

**Comment by ameshkov** [comment] 2021-05-17 07:56
@TPS probably, yeah, we'd allow customizing the system DNS server.

**Comment by Jayman007** [comment] 2021-05-22 15:46
> > As soon as I enable the 2 bypass settings and try to place a wifi call it fails. If I disable adguard, it works. Enable it again, still fails.
> 
> Oh, this means that it's enough just to have an active VPN tunnel and this would break Wi-Fi calling completely regardless of the fact that nothing is routed into that VPN.
> 
> > So, how would I go about reporting this to Samsung officially? I have not seen a bug report site. I will happily report it and keep pressing them to fix it. I still have a case with google fi open where I have told them exactly how to reproduce the issue.
> 
> Tbh, I am not aware of any normal place to file a bug report. Maybe, it should be sent through their customer support?

I have recently switched from Google Fi to another TMobile mvno named mint mobile.

I continue to text this issue and at first the issues remained.  

Today I started texting wifi calling with openvpn running and wifi calling worked. I then tried ad guard VPN and it again read working with wifi calling. I then tried with just the standard adguard running and low and behold, wifi calling works just fine. 

To confirm, I have airplane mode on and then enable wifi on my Samsung Galaxy s20+ and make sure the VPN is rubbing and then try and place a call. I can see from the call screen that wifi calling is being used.

I have no idea why this is now working. I have filed multiple big reports with Samsung but I don't see any state updates. I'm running the may security update.

I'm just happy to see that this is now working. I'll keep testing and reply back if thinks change again.

**Comment by artemiv4nov** [comment] 2021-05-22 20:15
@Jayman007 glad to know it!

**Comment by JohnRTitor** [comment] 2021-05-23 12:19
> It does not seem that rules were added:
> 
> ```
> 49.44.59.38 vowifi.jio.com
> 49.44.59.37 epdg.epc.mnc873.mcc405.pub.3gppnetwork.org 
> ```

By the way I forgot to ask you this, why they are showing up as "blocked" in AdGuard log? 
![IMG_20210523_174807](https://user-images.githubusercontent.com/50095635/119260169-3672c080-bbef-11eb-9521-d4fb6de5cc9c.jpg)

**Comment by sfionov** [comment] 2021-05-31 08:56
@JohnRTitor "Blocked" status is shown for all queries that matched any rule, even if it is rewrite or hosts rule

**Comment by sfionov** [comment] 2021-05-31 08:58
New nightly is out with known Wi-Fi calling domains directed to fallback by default.

You may now customize it with `pref.dns.fallback.domains` advanced option.

**Comment by JohnRTitor** [comment] 2021-06-13 17:10
> New nightly is out with known Wi-Fi calling domains directed to fallback by default.
> 
> You may now customize it with `pref.dns.fallback.domains` advanced option.

Yup, WiFi calling is working now with AdGuard enabled.

**Comment by JohnRTitor** [comment] 2021-06-18 10:16
> @JohnRTitor "Blocked" status is shown for all queries that matched any rule, even if it is rewrite or hosts rule

Well in my opinion, the "modified" status would be better in this case rather than "blocked"

**Comment by TPS** [comment] 2021-12-11 14:33
Recently, WhatsApp is using `stun` protocol before wifi calls, but AGA is blocking it.  What's to be done?

**Comment by ameshkov** [comment] 2021-12-12 22:21
@TPS there definitely should be a different issue opened about that: https://github.com/AdguardTeam/CoreLibs/issues/1567

**Comment by TPS** [comment] 2022-05-01 13:24
Is this known to be solved?

**Closed** 2022-11-23 18:32 UTC
Labels: Enhancement, Resolution: Fixed, Status: Resolved, Version: AdGuard v4.0

**Comment by Tatuatul** [comment] 2025-05-29 16:35
Same problem with Nubia Redmagic 7, Android 13, when Adguard is disabled, Wi-Fi calls work, but when I enable it, Wi-Fi calls no longer work. Has anyone found a solution?
