### ISSUE TITLE
Firefox preview - Impossible to use HTTPS-filtering?

### ISSUE THREAD

**Issue by Xophile** [AdguardTeam/AdguardForAndroid#2927] opened 2019-07-16 14:09 UTC
### Steps to reproduce

1. Download Firefox preview on Play Store
2. Set as default browser 
3. Start AG and enable HTTPS-filtering 
4. Firefox preview starts but the certificate does not get imported

### Expected behavior

Certificate should get imported. 

### Actual behavior

Nothing happens... 

Also tried exporting the certificate to my local phone storage and import it from there. Does not work either. 
<details><summary>Screenshot:</summary>

</details>

### Your environment

* Adguard version: 3.2.95
* Adguard filtering mode: (e.g. Local VPN / HTTP Proxy (Auto/Manual)) local vpn
* Device model: (e.g. Google Pixel) Samsung Note 9
* Operating system and version: (e.g. Android 7.1.2) Android Oreo
* Root access:  (e.g. Yes / No) no
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?: no

**Comment by Xophile** [comment] 2019-07-16 14:22
Sorry if this is related to Firefox and not AG but I had to start somewhere...

**Comment by sfionov** [comment] 2019-07-16 14:27
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/2861

**Comment by Xophile** [comment] 2019-07-17 12:08
Sorry about the duplicate post. I did contact support via e-mail and they simply asked me to supply logs and screenshots. I then actually searched Github but didn't find anything. My bad!

**Comment by artemiv4nov** [comment] 2019-07-22 13:12
Marked as duplicated #2861

**Closed by artemiv4nov** 2019-07-22 13:12 UTC
