### ISSUE TITLE
About pref.excluded.packages not work

### ISSUE THREAD

**Issue by sandianyue** [AdguardTeam/AdguardForAndroid#3705] opened 2020-12-24 15:03 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [√] I am running the latest version
- [√] I checked the documentation and found no answer
- [√] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v4.0 night9(48)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - OnePlus 7Pro
- **Operating system and version:**
  - Android 10
- **Root access:**
  - Yes

### Expected Behavior

Exclude the uid/gid I added

### Actual Behavior

Not exclude the uid/gid I added

### Screenshots

<details><summary>Screenshot:</summary>

</details>

### Additional Information

I noticed the `pref.excluded.packages` you provided in the low-level settings of the advanced settings. I tried to use it to exclude the executable file of a magisk module [Clash_Premium_For_Magisk](https://github.com/kalasutra/Clash_Premium_For_Magisk) I used. Its uid is `0`, and its gid is `1015`. Try adding `1015` or both `1015` and `0`,but it seems that adguard has not spared it. What I hope to do is that adguard VPN---socks5--->clash--->network (there is no transparent proxy). However, it did not bypass it in the end, which caused the loopback of the network on my mobile phone. In fact, I didn't know the reason at first. When I executed the `ip rule list` through termux, I found that adguard did not give up the `1015` exception that I added. But I noticed that the default `1000` and `1001` seem to be unaffected no matter whether I delete them in `pref.excluded.packages` or not. So I have reason to believe that the current setting item seems to be a decoration? Or is it all a bug? I look forward to your reply to answer my confusion. Thank you!

**Comment by Chinaski1** [comment] 2020-12-28 11:25
Hello there!

The thing is that AdGuard excludes applications by uid and not by gid. Also, ClashPremiumForMagisk is most likely running under uid 0, so you can't exclude it.

But in any case, in this situation, you need to watch the debug log.
Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by zzebrum** [comment] 2021-01-11 13:32
@sandianyue hello! Have you sent the log file?

**Comment by Chinaski1** [comment] 2021-01-18 15:57
I am closing this issue because the user has not responded for a long time.
Reopen it if the task is still relevant.

**Closed** 2021-01-18 15:57 UTC
