### ISSUE TITLE
com.kakao.talk app - HTTPS filtering compatibility issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#960] opened 2016-12-03 10:12 UTC
Kakaotalk, the most used Korean messaging app is blocked with HTTPS filtering. I fixed the issue by adding ' kakao.com ' on HTTPS whitelist. This is an urgent problem since ALL KOREANS are using this application - it may block you either from Koreans!

Store Link : https://play.google.com/store/apps/details?id=com.kakao.talk&hl=en

**Comment by ameshkov** [comment] 2016-12-05 22:18
@seanl-adg could you please take a look? I thought the issue is now fixed with the updated ssl exceptions?

**Comment by ameshkov** [comment] 2016-12-05 22:18
Prev issue link: #929

**Comment by seanl-adg** [comment] 2016-12-06 00:20
It should be fixed, please let the user uninstall Adguard and do a clean install, because ssl exceptions are not updated in beta channel. If the user still faces a problem we need a full log.

**Comment by ameshkov** [comment] 2017-02-16 09:33
@seanl-adg ?

**Comment by seanl-adg** [comment] 2017-02-16 20:55
I'll take a look at this once again, on my end still some error message pops up very rarely.

**Comment by ameshkov** [comment] 2017-03-21 10:22
I guess there're no problems after all?

**Comment by seanl-adg** [comment] 2017-03-22 16:20
Adding 
```
gift.kakao.com
item.kakao.com
talk.kakao.com
katalk.kakao.com
```
seems to be resolving most of the problems.

Last 3 domains were appeared in the log with `Internal TLS error` text.
I couldn't find such lines for `gift.kakao.com`, but unless it was added a certain menu of the app was broken.

The total list of exceptions will be
```
ac-talk.kakao.com
api.kakao.com
channel.kakao.com
clog-aggregator.kakao.com
gift.kakao.com
item.kakao.com
katalk.kakao.com
pf-api.kakao.com
talk.kakao.com
```

**Comment by ameshkov** [comment] 2017-03-23 13:37
@Revertron please update HTTPS exclusions:
https://github.com/AdguardTeam/HttpsExclusions

**Comment by Revertron** [comment] 2017-03-23 13:52
Done.

**Closed by Revertron** 2017-03-23 13:52 UTC
Labels: Compatibility, SSL
