### ISSUE TITLE
Randomly dropping Internet connection @ LineageOS

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1345] opened 2017-07-27 15:46 UTC
### Expected behavior
Using the Internet without any issues.

### Actual behavior
Losing Internet connection at random.

<details><summary>Screenshot:</summary>

![screenshot_20170721-140600](https://user-images.githubusercontent.com/28726429/28678853-211bc728-72fa-11e7-9561-39d5197697cc.png)

</details>

[1166697_logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1180456/1166697_logs.zip)

### Customer ID 
1166697

### Your environment

* Adguard version: 2.9.135
* Adguard filtering mode: Proxy (auto)
* Device model: Wileyfox Swift
* LineageOS 14.1 (Android 7.1.2)

**Comment by ameshkov** [comment] 2017-07-27 15:47
We badly need the system log:
https://kb.adguard.com/en/android/solving-problems/logcat

**Comment by altokarev** [comment] 2017-07-27 15:48
There is one more similar case at our forum: https://forum.adguard.com/index.php?threads/aguard-%D0%BE%D1%82%D1%80%D0%B5%D0%B7%D0%B0%D0%B5%D1%82-%D1%81%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D1%87%D0%B5%D1%80%D0%B5%D0%B7-%D0%B2%D1%80%D0%B5%D0%BC%D1%8F-%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE%D1%8F-%D0%BF%D0%BB%D0%B0%D0%BD%D1%88%D0%B5%D1%82%D0%B0.23703/#post-146024

###Environment

* Adguard version: 2.9.136
* Adguard filtering mode: Proxy (auto)
* Device model: Nexus 7 Gen 2. ASUS
* Lineage OS 14.1-20170725 (Android 7.1.2, kernel 3.4.0)
* Rooted

**Comment by ameshkov** [comment] 2017-07-31 08:14
One more case:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1334#issuecomment-318999205

@altokarev please ask people to collect logcat logs for us:
https://kb.adguard.com/en/android/solving-problems/logcat

**Comment by altokarev** [comment] 2017-07-31 09:02
Yep, I asked everyone already. Now waiting for the response.

**Comment by Xophile** [comment] 2017-07-31 19:08
Hi! 

I am the one who sent the first logs. I'm confirming that I'm running Lineage OS. 

Is this an Adguard or Lineage issue?

**Comment by ameshkov** [comment] 2017-07-31 19:11
@Xophile hi! This is a LineageOS issue for sure. I'd like to file an issue to their repo, but prior to this, I'd like to get the logcat log and look for a possible cause there.

**Comment by ameshkov** [comment] 2017-07-31 21:21
> I'm on vacation until Wednesday but then I can provide logcat log. Never done that before though. Is my personal information of any kind stored inside those logs?

It's human-readable so you'd better examine it before sending to us

**Comment by altokarev** [comment] 2017-08-07 15:58
Got a few logcats:
[2017-08-06-14-42-47.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1205371/2017-08-06-14-42-47.txt)
[2017-08-07-12-00-00.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1205374/2017-08-07-12-00-00.txt)

**Comment by Xophile** [comment] 2017-08-07 20:21
Hi! 

Sorry I have sent mine yet. Car trouble during my holiday which made things complicated to say the least... 

Do you have enough information in this logs or do you need more data from me? 

Is it Adguard or LineageOS? 

If it is LineageOS, how can we proceed to correct it?

**Comment by altokarev** [comment] 2017-08-08 07:00
It's LineageOS, for sure. Adguard works well on the other OSs.

**Comment by Xophile** [comment] 2017-08-08 08:02
Ok, I understand this is not your top priority then. 

Any ideas how this can be reported/resolved by LineageOS?

**Comment by ameshkov** [comment] 2017-08-08 08:04
> Do you have enough information in this logs or do you need more data from me?

Frankly, not enough :( I'd be glad if you can also collect a log.

> Any ideas how this can be reported/resolved by LineageOS?

https://wiki.lineageos.org/bugreport-howto.html

@altokarev regarding these two logs, please tell me when exactly did the problem occur?

**Comment by altokarev** [comment] 2017-08-08 08:13
User did not specify. I already asked for details.

**Comment by altokarev** [comment] 2017-08-08 09:59
Here's another logcat with screenshots of all actions (there are timestamps on screenshots): 
- start recording;
- turn off wi-fi;
- enable "airplane mode";
- disable "airplane mode";
- turn on wi-fi;
- start Adguard UI;
- turn off Adguard protection;
- turn on Adguard protection;
- stop log recording.

[1166697_logcat.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1207577/1166697_logcat.zip)

**Comment by Xophile** [comment] 2017-08-09 07:49
These threads might talk about the same issue? 

https://jira.lineageos.org/plu...rvlet/mobile#issue/BUGBASH-647

https://jira.lineageos.org/plu...et/mobile#issue/REGRESSION-369

**Comment by ameshkov** [comment] 2017-08-13 19:04
@Xophile seems to be unrelated

**Comment by ameshkov** [comment] 2017-08-13 19:18
Or not, the second one might be related.

@Xophile @altokarev guys, what's with the IPv6 configuration? Do you have it enabled?

**Comment by Xophile** [comment] 2017-08-15 06:29
Hi again! 

No, IPv6 is not enabled. 

I know this isn't "Adguard's fault" but I guess you also would like to fix this issue in order to let your users enjoy Adguard on LineageOS. 

What's the next step? 

Many thanks again!

**Comment by ameshkov** [comment] 2017-08-21 21:32
Sorry for the late reply, was quite busy lately:( 

We'll get back to this issue after the next beta release.

**Comment by altokarev** [comment] 2017-08-29 17:16
@ameshkov Seems firmware is forcing an IPv6 to enable.

The user noticed that IPv6 is enabled even if disabled directly on a router.

**Comment by Xophile** [comment] 2017-08-31 13:22
In my case I don't use IPv6 from my ISP and Adguard doesn't have it enabled here.

**Comment by ameshkov** [comment] 2017-09-05 11:32
@altokarev I've tried to come up with a good issue description but failed:(

We need to test it on one of our test devices. 
@vozersky could you plz install LineageOS?

**Comment by vozersky** [comment] 2017-09-08 14:58
@ameshkov sure, I did, but I haven't faced the issue so far. Lineage 14.1-20170905.

**Comment by Xophile** [comment] 2017-09-10 18:30
I have updated to the latest Adguard beta om my tablet and I haven't experienced the issue since. No other changes were made on the tablet (I rarely use it)

Anything you changed in the latest releases that could gave fixed thus issue?

**Comment by ameshkov** [comment] 2017-09-10 18:33
Comparing to the stable version? Beta is VERY different, completely reworked all the local VPN stuff.

**Comment by Xophile** [comment] 2017-09-12 05:52
Ameshkov:

A lot of work for you guys I'm sure. Thanks for great updates!.

Well maybe the reworked VPN fixed the issue then?

Vozersky: did you use the latest beta or stable?

**Comment by ameshkov** [comment] 2017-09-12 07:44
That'd be great if it really helps:) 

@vozersky used the latest beta indeed.

**Closed** 2017-12-04 12:46 UTC
Labels: android bug
