### ISSUE TITLE
License expiry date displayed incorrectly

### ISSUE THREAD

**Issue by Nirineya** [AdguardTeam/AdguardForAndroid#4856] opened 2023-07-19 18:01 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.912

### Environment

```markdown
- OS:Android 8
- Device:Samsung Galaxy A5
- Firmware:A520FXXUGCTKA
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Renew AdGuard AdBlocker license
2. Open AdGuard on Android
3. Go License and check the expiry date

### Expected Behavior

Correct expiration date being displayed

### Actual Behavior

Incorrect expiration date being displayed

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://github.com/AdguardTeam/AdguardForAndroid/assets/119436165/5b79c093-4303-4d7c-bd78-6cac6563bf06)

</details>

**Comment by Versty** [comment] 2023-07-20 08:14
We have found the root cause of this issue. 
The bug will be fixed in the next version of AdGuard For Android.

**Closed** 2023-12-22 08:41 UTC
Labels: Bug, Resolution: Fixed, Status: Resolved, Junior+, Priority: P3, Version: AdGuard v4.3
