### ISSUE TITLE
"Protect from DPI" prevents some websites loading

### ISSUE THREAD

**Issue by trmdi** [AdguardTeam/AdguardForAndroid#4211] opened 2022-08-05 03:31 UTC
When I go to Stealth mode > Custom > enable only Protect from DPI, these sites stop loading.

- https://www.thegioididong.com/
- https://www.dienmayxanh.com/

with the error code: ERR_CONNECTION_CLOSED

**Comment by sfionov** [comment] 2022-08-05 09:18
Thank you for information!

Closing as duplicate of https://github.com/AdguardTeam/CoreLibs/issues/1645

**Closed by sfionov** 2022-08-05 09:18 UTC
