### ISSUE TITLE
Wifi Calling not working when adguard is on :(

### ISSUE THREAD

**Issue by rahulmasal** [AdguardTeam/AdguardForAndroid#3711] opened 2021-01-01 02:52 UTC
**
Mobile Model: 
REDMI NOTE 9 PRO MAX

Operator: 
JIO INDIA/Vodafone IN

Adguard Version: 
v4.0 Nightly 9 (48)

**

Issue: 
When Adguard is Enabled wifi calling not working!

i saw filtering log but no perticular app for wifi calling.

**Comment by EntropySmoke** [comment] 2021-01-03 12:21
WiFi calling through a carrier uses its own IPSec protocol for VPN tunneling over ePDG.  Android enforces that and bypasses any and all VPN protocols, including AdGuard's VPN and AdGuard's Local VPN. WiFi calling does not show up in AdGuard logs. If you device is rooted, you can use HTTP Proxy mode to allow WiFi calling and get most of AdGuard's ad and tracking removal features.

Be careful with carrier WiFi calling. It adds yet another tracking method. When you use carrier tower calling, it tracks you. When you use WiFi calling, your ISP AND your carrier tower tracks you. Only use App-based WiFi calling, such as Signal, Whats App, and Telegram (Full Open Source/F-Droid version).

**Comment by TPS** [comment] 2021-01-05 03:40
I believe #3627 is where progress toward the fix is being tracked.

**Comment by ameshkov** [comment] 2021-01-09 20:16
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Open AdGuard -> Settings -> Advanced -> Set "Logging level" to "Record everything". It's desirable to close all background apps that don't concern the problem beforehand.
2. Reproduce the issue and set the logging level back to "Default".
3. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
4. Open AdGuard -> Settings -> Advanced -> Export Logs
5. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
6. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

Instead of sending these logs to us, you can also inspect them and look for UDP traffic to ports 500 and 4500. The IP addresses there may be added to exclusions in the low-level settings: `pref.routes.exclusions`.

If this helps, we would need to know what IP addresses exactly are used.

**Comment by ameshkov** [comment] 2021-01-09 20:18
Meanwhile, I think this issue can be closed as a duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/3627

**Closed by ameshkov** 2021-01-09 20:18 UTC
Labels: Duplicate
