### ISSUE TITLE
"Network may be monitored" notification due to user certificate

### ISSUE THREAD

**Issue by BooBerry** [AdguardTeam/AdguardForAndroid#334] opened 2016-02-27 00:39 UTC
I get the notification on every boot warning me about the network may be monitored by a third party after enabling HTTPS filtering in the Adguard 3.5 alpha.

However, I was able to fix this myself using the Move Cert! app from here (requires root): https://f-droid.org/repository/browse/?fdid=com.nutomic.zertman

The source code is available here: https://github.com/Nutomic/movecerts

It moves the certificate from user to system, but like I said it requires root. Perhaps for rooted users the certificate can automatically be installed into system instead of user? The source code for Move Cert! should help here. :)

**Comment by ameshkov** [comment] 2016-02-28 10:57
Great, thank you!

I am not yet sure what should we do: add this information to FAQ or implement this feature in the app. Even if we implement it, installing to system storage should be optional.

You see, moving the certificate is only the first part of the problem. The second part is removing it (which I don't see in that app).

If certificate is the system storage, you can't remove it from Android settings, only disable it.

**Comment by BooBerry** [comment] 2016-02-29 14:28
> I am not yet sure what should we do: add this information to FAQ or implement this feature in the app. Even if we implement it, installing to system storage should be optional.

Agreed. But it should be limited to only rooted devices, no?

> You see, moving the certificate is only the first part of the problem. The second part is removing it (which I don't see in that app).

Move Certs! also removed the certificate for me. Worst case, just send a command to delete the certificate from the system storage folder it's moved to if root access is available.

> If certificate is the system storage, you can't remove it from Android settings, only disable it.

Like I said, Move Certs! deleted the certificate for me too, so it's possible.

**Comment by BooBerry** [comment] 2016-02-29 14:42
Also to take into consideration is the locations of the user folder...

For Android 4.x and below: /data/misc/keychain/cacerts-added/

For Android 5.x and above: /data/misc/user/0/cacerts-added/

**Comment by ameshkov** [comment] 2016-03-01 16:29
> Move Certs! also removed the certificate for me. Worst case, just send a command to delete the certificate from the /system/etc/security/cacerts/ folder.

Ah, ok then, I just missed that part in their code.

**Comment by ameshkov** [comment] 2016-03-01 16:38
> Agreed. But it should be limited to only rooted devices, no?

Yep, it is.

Let's summarize.

For rooted devices we should add two more buttons:
**Move certificate to the System certificates storage** -- moves our cert from user to system storage
**Remove certificate** -- removes our certificate from the system storage

I'll plan it on v2.6

**Comment by Alex-302** [comment] 2016-03-01 20:06
I've installed movecerts and moved Adguard certificate. Notification and lockscreen are disabled now, but I have the problem with Chrome and Opera now - "certificate is too long"(more than 3 years):
<details>
 ![screenshot_2016-03-01-22-41-05](https://cloud.githubusercontent.com/assets/8361299/13439986/07362dcc-e001-11e5-8034-129aab0acb03.png)</details><details> 
![screenshot_2016-03-01-22-41-14](https://cloud.githubusercontent.com/assets/8361299/13440005/1682b2be-e001-11e5-809a-ee3ecadc791b.png)
</details>

**Comment by TPS** [comment] 2016-03-02 04:01
The full discussion @ https://bugs.chromium.org/p/chromium/issues/detail?id=431573 seems to be fully relevant here.

**Comment by ameshkov** [comment] 2016-03-02 12:53
@Alex-302 thank you! Moved to an additional issue: #345

**Comment by ameshkov** [comment] 2016-03-18 09:46
There're lots of requests for such feature from alpha testers. We may reassign it to v2.5

**Comment by ameshkov** [comment] 2016-03-23 11:22
**Known issues:**
1. Adguard's certificate will be removed on system update.
2. On some devices reboot is required if you want to reinstall AG certificate. Steps to reproduce: install certificate, move it to system certs, clear AG app data, try to generate & install AG certificate again - it won't work until reboot.

**Comment by ameshkov** [comment] 2016-04-14 15:57
**One more major issue:**
Browser starts to check domain certificates against "Public-Key-Pins" header values. This header is ignored in case of user certificate.

**Comment by ameshkov** [comment] 2016-05-27 10:58
One more known issue (maybe it is also caused by Public-Key-Pins): instagram app does not work when certificate is moved to system certs.

**Comment by vozersky** [comment] 2016-07-11 14:13
Guide on moving cert from Josh Lawton:

[Enable HTTPS Filtering on Android Nougat.pdf](https://github.com/AdguardTeam/AdguardForAndroid/files/357263/Enable.HTTPS.Filtering.on.Android.Nougat.pdf)

**Comment by uBlock-user** [comment] 2017-01-23 10:08
I'm having the same issue on my Android device and it's NOT rooted. Is there an fix for this ?

**Comment by BooBerry** [comment] 2017-01-23 10:14
You can swipe away the notification, that's what I do.

**Comment by uBlock-user** [comment] 2017-01-24 07:47
> You can swipe away the notification
 
I do not want to do that on every reboot and that's not a solution either. That's why I'm asking to make it not appear permanently.

**Comment by BooBerry** [comment] 2017-01-24 10:32
That's the only solution, except rooting the device and moving the certificate to the system store. The only other solution is to disable HTTPS filtering and remove the certificate.

Other than those, it can't be avoided. Personally, I just live with it and swipe it away on reboot.

**Comment by war59312** [comment] 2017-01-24 21:24
Would not be much of a security boundary...

If an app could just hide it.. Would what stop a bad actor (hacker) from doing the same..

**Comment by ameshkov** [comment] 2017-01-26 11:40
> If an app could just hide it.. Would what stop a bad actor (hacker) from doing the same..

First of all, a bad actor cannot install security certificate without user consent.:)

**Comment by war59312** [comment] 2017-01-27 14:04
Security in depth approach. ;)

Assume it's been compromised and warn anyways. :p

People are phished all the time. Good to assume user may have accidently installed the cert. haha

Users are idiots after all. ;)

**Comment by yochananmarqos** [comment] 2018-03-14 01:23
I created a Magisk module to move the certificate from the user store to the system store: https://forum.xda-developers.com/showpost.php?p=75835120&postcount=3039

**Comment by ameshkov** [comment] 2018-03-20 14:50
Awesome!

**Comment by ameshkov** [comment] 2018-11-08 08:04
I guess we don't need to keep this open as AG allows moving cert to system store in 2.12

**Closed by ameshkov** 2018-11-08 08:04 UTC
Labels: Enhancement, P3: Medium, SSL

**Comment by uBlock-user** [comment] 2018-11-08 08:17
> I guess we don't need to keep this open as AG allows moving cert to system store since 2.12

Without root ? How ?

**Comment by ameshkov** [comment] 2018-11-08 08:18
> Without root ? How ?

That feature requires root, unfortunately. There's no solution for unrooted users:(

**Comment by yochananmarqos** [comment] 2018-11-14 01:21
@ameshkov It still can't install the system certificate with Magisk. I'm not the only one, see[ the XDA thread](https://forum.xda-developers.com/showpost.php?p=78139800&postcount=3511).

Without AdGuard installing it's own Magisk Module, I don't see how you expect it to write to /system. My [Move Certificates](https://github.com/Magisk-Modules-Repo/movecert) Magisk Module does the trick.

**Comment by zzebrum** [comment] 2018-11-14 10:10
@yochananmarqos it should be working with latest nightly 3.0.66
