### ISSUE TITLE
AdGuard blocks previews on Avito

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardForAndroid#4183] opened 2022-06-03 10:38 UTC
@maxikuzmin commented on [Thu Jun 02 2022](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/961)

If AdGuard is enabled, not all product photos (previews) are displayed when you scroll through the ads in the Avito app.
Only the original filters are enabled, there are no additional filters. 
When AdGuard is disabled, all pictures (previews) are displayed 
Also sometimes don't displayed pictures in ad 

Android 10 
Don't reproduce on IOS

---

@zloyden commented on [Thu Jun 02 2022](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/961#issuecomment-1144906043)

@maxikuzmin I can't reproduce it on my end with or without our DNS.
Please provide steps to reproduce or show which request needs to be unblocked.

---

@maxikuzmin commented on [Fri Jun 03 2022](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/961#issuecomment-1145656303)

@zloyden connect to a mobile network 

---

@zloyden commented on [Fri Jun 03 2022](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/961#issuecomment-1145769284)

It does not matter whether Wi Fi or mobile network is used. I do not see that their request is blocked.

---

@maxikuzmin commented on [Fri Jun 03 2022](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/961#issuecomment-1145831381)

I tried disabling all filters and DNS, the problem remains

**Comment by maxikuzmin** [comment] 2022-06-08 07:52
the problem has stopped reproduce, I'm closing.

**Comment by zloyden** [comment] 2022-06-21 11:50
https://github.com/AdguardTeam/AdguardFilters/issues/122409

**Comment by ihurin** [comment] 2022-06-23 06:05
Fresh logs [https://adguard.zendesk.com/attachments/token/M1YXpm0T6ylHdY46TowLPnqy1/?name=adguard_logs_3.6.46_2306_085205.zip](url)

**Comment by Alex-302** [comment] 2022-07-25 08:59
https://github.com/AdguardTeam/AdguardForAndroid/issues/4203

**Comment by Alex-302** [comment] 2022-08-04 19:00
New logs in ticket 619473

**Comment by cryptopatik22** [comment] 2022-08-15 07:22
625501 - same issue

**Comment by admitrevskiy** [comment] 2022-08-15 11:50
This issue requires thorough analysis. We will conduct it before long and will return with the results.

**Comment by admitrevskiy** [comment] 2022-08-24 17:05
Due to the logcat, avito is trying to use an IPv6 address in IPv4-only networks. 

DNS filtering was turned off for all users who sent logs. Enabling DNS filtering or IPv6 traffic bypass fixes the issue.

I can't imagine how they got IPv6 addresses and it looks like a bug of some HTTP client they're using.

**Comment by maxikuzmin** [comment] 2022-08-25 10:44
@cryptopatik22 please let me know the result

**Comment by maxikuzmin** [comment] 2022-08-29 12:22
@cryptopatik22 any news? As we know, it's helped some users

**Closed** 2022-09-01 08:22 UTC
Labels: Bug
