### ISSUE TITLE
The ability to make lists of apps to exclude from and/or include in the filtering log

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#3899] opened 2021-07-07 10:20 UTC
Please add the ability for users to make lists of apps to exclude from and/or include in the filtering log (just for what is shown, not what is actually filtered). Some apps don't have trackers or ads at all (but I still want everything filtered). These apps also make up the majority of my filtering log because they are always running in the background (weather app, stocks app, crypto app, Signal, etc). I want them filtered, but I don't always want them cluttering my filtering log - especially since the visible filtering log is a fixed length. It would also be helpful to be able to customize the length of the filtering log either by # of logs or by amount of time. 

### CRM ID

521389

**Comment by artemiv4nov** [comment] 2023-06-15 12:21
It looks like the issue is not so popular, let's close it.

**Closed** 2023-06-15 12:20 UTC
Labels: Feature request, Resolution: Won't Do, Status: Resolved, Priority: P4
