### ISSUE TITLE
Adguard Proxy and Orbot/Orfox

### ISSUE THREAD

**Issue by ezekial52787** [AdguardTeam/AdguardForAndroid#1578] opened 2017-11-05 11:26 UTC
When I enable the adguard proxy to run through ToR, and it works and says the proxy is activated and all, but then when I go back to the main page of adguard, it says adguard is disabled. In adguard 2.10.164 beta. I'm running adguard on a Samsung Galaxy S6 Active with android 7.0

**Comment by vozersky** [comment] 2017-11-17 10:57
@ezekial52787 hi! do you still have this issue with 2.10.171 beta? if so, could you please send us some logs?

**Comment by ameshkov** [comment] 2017-12-04 12:20
Closing as we cannot reproduce

**Comment by ameshkov** [comment] 2017-12-04 12:20
@ezekial52787 please reopen if the problem is still reproducible on your side and you can send us the logs.

**Closed by ameshkov** 2017-12-04 12:20 UTC
Labels: cannot reproduce, waiting for data

**Comment by CiscoKydd2** [comment] 2018-01-06 09:36
Would there be a conflict if I use Orbot proxy and Ad Guard proxy at the same time? If so, which should be the preferred proxy?

**Comment by ameshkov** [comment] 2018-01-07 00:25
> Would there be a conflict if I use Orbot proxy and Ad Guard proxy at the same time? If so, which should be the preferred proxy?

Orbot usually sets up a VPN so you won't be able to use it along with AdGuard **unless** you have root and you use AdGuard in the "proxy with automatic setup" filtering mode. If that so, you'll be able to run Orbot and AdGuard simultaneously.

The other option would be to run AdGuard and configure Orbot integration in AdGuard's proxy settings.

**Comment by CiscoKydd2** [comment] 2018-01-08 16:42
Can you send a link that explains how to do either option?
Thanks.

**Comment by ameshkov** [comment] 2018-01-09 08:23
Here is the default no-root way to use it:
https://kb.adguard.com/en/android/solving-problems/adguard-outbound-proxy

If you have root access, there's an alternative option (proxy mode):
https://kb.adguard.com/en/android/faq#vpn
