### ISSUE TITLE
When you import 2 filter lists to user rules, the second list replaces the first one

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardForAndroid#5005] opened 2023-10-04 00:00 UTC
### Issue Details

When you import your personal filter list from device, and then you import a second personal filter list, this one replaces the first list

### Proposed solution

They should be merged

### Alternative solution

AG should ask if you want to replace the first one or not.

See Content Blocker behavior:

<img width="332" alt="dd" src="https://github.com/AdguardTeam/AdguardForAndroid/assets/1375223/3b351b00-3408-4405-a2f4-b6ac9ef2960a">

https://github.com/AdguardTeam/ContentBlocker/issues/141#issuecomment-418030838

PS:
This feature request regards both Ads Blocker user rules and DNS user rules.

**Comment by ESurina** [comment] 2023-10-04 10:37
Duplicate of #4616 
You can like it to vote for the idea.

**Closed by ESurina** 2023-10-04 10:37 UTC
Labels: Feature request, Priority: P4
