### ISSUE TITLE
Add Android TV / Fire OS optimized UI

### ISSUE THREAD

**Issue by MercuryXIII** [AdguardTeam/AdguardForAndroid#3411] opened 2020-04-17 19:51 UTC
### Prerequisites

Fire TV Cube

### Problem Description

Running AdGuard on the tv gets a tablet like layout hard to navigate with a remote 

### Proposed Solution

Add a ui optimized for tvs and remotes 

### Alternatives Considered

Navigating with mouse toggle for android tv

### Additional Information

My device is a fire TV cube with the latest version of fire is running AdGuard Beta with a lifetime license. An example of an optimized android as locker is blockade which ui adapts to the TV

**Comment by artemiv4nov** [comment] 2020-04-17 20:19
That task is duplicate of #3238 
@MercuryXIII Please try the latest nightly version, UI optimizations have already been done

**Closed by artemiv4nov** 2020-04-17 20:19 UTC

**Comment by MercuryXIII** [comment] 2020-04-18 19:23
Ah! Much better! 

Thanks!

**Comment by oroboros** [comment] 2023-06-12 10:18
> That task is duplicate of #3238 @MercuryXIII Please try the latest nightly version, UI optimizations have already been done

@artemiv4nov Unfortunately a lot of these issues show up again in the v4.0 RC1 on Android TV devices (I've tried to flag them, but things like portrait display and no landscape display, missing launch icon, issues with navigating using DPAD, etc).
