### ISSUE TITLE
Unable to download from Google play

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#549] opened 2016-05-13 09:44 UTC
I am not able to download from Google play, even after allowing Wifi & Mobile Data for 'Download Manager'. I am using Moto g2(2014) with Marshmallow 6.0, UN rooted. Build number MPB24.65-34 System version 24.41.34.titan_retaildsds.retaildsdsall.en.03 retin
As instructed by your mail, I reproduced the issue. Google Play keeps on showing ' downloading' and no further progress. I.e. showing file size, getting downloaded, etc is not happening: 

TTU-136-62568
JDN-573-45640

**Comment by TPS** [comment] 2016-05-14 15:58
This is a long-running, intermittent issue tracked @ #186. :confounded:

**Comment by vozersky** [comment] 2016-05-20 16:57
Any logs? Google Play is excluded from filtering.

**Comment by evgeniy-ADG** [comment] 2016-05-20 16:58
Ща попрошу.

**Comment by evgeniy-ADG** [comment] 2016-05-25 16:35
TTU-136-62568: I have added the download Manager name as "com.android.providers.downloads" to the list and is now downloading without disabling adguard to download from Google Play.
JDN-573-45640: waiting for logs

**Comment by TPS** [comment] 2016-06-09 01:44
Can you all check whether today's ß solved this for anyone else?  [It did for me!](https://github.com/AdguardTeam/AdguardForAndroid/issues/186#issuecomment-224780170)

**Comment by TPS** [comment] 2016-07-11 15:58
& solved again in the last 24 hours.  I'm fairly certain it must be something to do with a filter update that continually alternately blocks & allows _something_ that Android downloading relies upon.

**Comment by ameshkov** [comment] 2016-07-12 10:35
@TPS maybe you're right. Could you please record HTTP requests log next time it happens?

**Comment by ameshkov** [comment] 2016-07-19 10:45
@TPS got the log file. So, how did it look like? Have you tried to install anything from Google Play?

**Comment by TPS** [comment] 2016-07-19 11:17
Looks very much like https://github.com/AdguardTeam/AdguardForAndroid/issues/98#issuecomment-153383133, https://github.com/AdguardTeam/AdguardForAndroid/issues/98#issuecomment-155837998, https://github.com/AdguardTeam/AdguardForAndroid/issues/186#issuecomment-217579146, &c.  Only change was I'm attempting to update [CM Security](http://play.google.com/store/apps/details?id=com.cleanmaster.security), though it could've been anything, really.  Disconnecting AG VPN, updating CMAV, & then reconnecting AG, as mentioned earlier/elsewhere, is my only successfull workaround, other than waiting for a "magical" AG filterset update.

**Comment by ameshkov** [comment] 2016-07-20 10:10
@TPS while reading through your log, i've found a new bug:) https://github.com/AdguardTeam/AdguardForAndroid/issues/705

Regarding the original issue, I don't see any incorrect blocking in the log, so clearly that is not the cause.

Let me tell you what do i see.

First, a few DNS requests for domains used by GP:
```
09:18:55.416 [pool-2-thread-456] DEBUG com.adguard.android.FilteringLog - UDP id=1388 DNS request for android.clients.google.com, request type = 28
09:18:55.430 [pool-2-thread-453] DEBUG com.adguard.android.FilteringLog - UDP id=1389 DNS request for android.clients.google.com, request type = 28
09:18:55.513 [pool-2-thread-456] DEBUG com.adguard.android.FilteringLog - UDP id=1391 DNS request for android.clients.google.com, request type = 1
09:18:55.514 [pool-2-thread-453] DEBUG com.adguard.android.FilteringLog - UDP id=1390 DNS request for android.clients.google.com, request type = 1
09:18:57.961 [pool-2-thread-392] DEBUG com.adguard.android.FilteringLog - UDP id=1396 DNS request for lh3.googleusercontent.com, request type = 28
09:18:57.961 [pool-2-thread-394] DEBUG com.adguard.android.FilteringLog - UDP id=1395 DNS request for lh3.googleusercontent.com, request type = 28
09:18:58.083 [pool-2-thread-392] DEBUG com.adguard.android.FilteringLog - UDP id=1398 DNS request for lh3.googleusercontent.com, request type = 1
09:18:58.083 [pool-2-thread-394] DEBUG com.adguard.android.FilteringLog - UDP id=1397 DNS request for lh3.googleusercontent.com, request type = 1
09:19:06.151 [pool-2-thread-410] DEBUG com.adguard.android.FilteringLog - UDP id=1402 DNS request for lh6.ggpht.com, request type = 28
09:19:06.158 [pool-2-thread-434] DEBUG com.adguard.android.FilteringLog - UDP id=1403 DNS request for lh3.ggpht.com, request type = 28
09:19:06.182 [pool-2-thread-434] DEBUG com.adguard.android.FilteringLog - UDP id=1404 DNS request for lh4.ggpht.com, request type = 28
09:19:06.517 [pool-2-thread-450] DEBUG com.adguard.android.FilteringLog - UDP id=1405 DNS request for lh3.ggpht.com, request type = 1
09:19:06.525 [pool-2-thread-434] DEBUG com.adguard.android.FilteringLog - UDP id=1406 DNS request for lh4.ggpht.com, request type = 1
09:19:06.540 [pool-2-thread-410] DEBUG com.adguard.android.FilteringLog - UDP id=1407 DNS request for lh6.ggpht.com, request type = 1
```

Please note that it requests both A and AAAA records (IPv4 and IPv6).

Further I see a few HTTPS requests, mostly for static content (according to domain names):
```
09:19:14.519 [pool-2-thread-400] DEBUG com.adguard.android.FilteringLog - TCP id=100693 CONNECT http://lh6.ggpht.com/ com.android.vending 703 1004
09:19:14.970 [pool-2-thread-412] DEBUG com.adguard.android.FilteringLog - TCP id=100684 CONNECT http://android.clients.google.com/ com.android.vending 15487 84425
09:19:15.096 [pool-2-thread-434] DEBUG com.adguard.android.FilteringLog - TCP id=100688 CONNECT http://lh3.ggpht.com/ com.android.vending 795 12655
09:19:22.790 [pool-2-thread-395] DEBUG com.adguard.android.FilteringLog - TCP id=100692 CONNECT http://android.clients.google.com/ com.android.vending 8592 29623
09:19:31.945 [pool-2-thread-445] DEBUG com.adguard.android.FilteringLog - TCP id=100681 CONNECT http://cmdts.ksmobile.com/ com.cleanmaster.mguard 1756 5569
09:19:31.946 [pool-2-thread-394] DEBUG com.adguard.android.FilteringLog - TCP id=100687 CONNECT http://android.clients.google.com/ com.android.vending 4257 151
09:19:31.984 [pool-2-thread-392] DEBUG com.adguard.android.FilteringLog - TCP id=100694 CONNECT http://lh5.ggpht.com/ com.android.vending 529 6421
09:19:31.992 [pool-2-thread-417] DEBUG com.adguard.android.FilteringLog - TCP id=100695 CONNECT http://lh5.ggpht.com/ com.android.vending 529 7324
09:19:31.992 [pool-2-thread-413] DEBUG com.adguard.android.FilteringLog - TCP id=100691 CONNECT http://lh6.ggpht.com/ com.android.vending 987 11279
09:19:31.996 [pool-2-thread-412] DEBUG com.adguard.android.FilteringLog - TCP id=100696 CONNECT http://android.clients.google.com/ com.android.vending 4753 1526
09:19:31.996 [pool-2-thread-453] DEBUG com.adguard.android.FilteringLog - TCP id=100686 CONNECT http://lh3.googleusercontent.com/ com.android.vending 1521 20274
```

In a couple of minutes it seems that wi-fi was turned off and on again:
```
09:19:32.126 [main] INFO  c.a.a.r.NetworkStateReceiver - Start NetworkStateReceiver on action android.net.wifi.WIFI_STATE_CHANGED
09:19:32.127 [main] INFO  c.a.android.filtering.filter.e - handleWiFiChanged: oldState = 3, newState = 1
09:19:33.865 [main] INFO  c.a.android.filtering.filter.e - handleWiFiChanged: oldState = 1, newState = 3
```

Resulting in a short period without net connectivity:
```
09:19:35.790 [main] INFO  c.a.a.r.NetworkStateReceiver - Start NetworkStateReceiver on action android.net.conn.CONNECTIVITY_CHANGE
09:19:35.829 [main] INFO  c.a.a.r.NetworkStateReceiver - No current active network info found.
09:19:35.830 [main] INFO  c.a.a.r.NetworkStateReceiver - Network is disconnected
```

Nothing interesting after that (quite a few requests from Amazon app store at 9:22, but almost nothing from GPlay).

So, the question is, when exactly have you tried to install that update?

**Comment by TPS** [comment] 2016-07-20 13:58
This log was collected w/in 15 minutes of an _initial_ attempt of updating CMAV, & just a few minutes after receiving a notification saying it couldn't be updated. I sent the log, disconnected AG, & retried: it updated immediately.  Should I send a log once it starts working while AG is active, for a baseline? :confounded:  How does this look different than logs from #597?

Also, #705's been marked `Invalid` w/o much explanation.…

**Comment by ameshkov** [comment] 2016-07-20 17:07
Everything is ok, I just wanted to know exact timing.

> How does this look different than logs

They have one thing in common: no errors or suspicious requests, no requests from a download manager as well. It just looks as if download request disappeared.

**Comment by TPS** [comment] 2016-07-21 04:14
Just to ask a stupid (probably) question:  There used to be an advanced setting showing all apps excluded from all AG filtering by you folks.  Since #633 landed, that seems to be gone in favor of the new UI, but _that_ seems to be missing some of the system apps.  Particularly, I'd like to find out what's going on w/ `com.android.providers.downloads` (or is it `com.android.providers.download`?) — `com.android.providers.downloads.ui` is there just fine.

**Comment by ameshkov** [comment] 2016-07-21 09:25
> Particularly, I'd like to find out what's going on w/ com.android.providers.downloads (or is it com.android.providers.download?) — com.android.providers.downloads.ui is there just fine.

It is a "Download Manager" app, it should be in the apps list in AG.

**Comment by TPS** [comment] 2016-07-21 13:42
Yes, "Download Manager" (`com.android.providers.downloads.ui`) shows, but not system app "Downloads" (`com.android.providers.download/s`), which runs in the same process, apparently, along w/ "Camera", "Media Storage", & "Videos".

Hmmm, I wonder:  How does AG &/or Android  handle this sort of multi-app process, if wifi & mobile data permissions are denied for _some_ apps in a process (I've "Camera" & "Videos" blocked, I think), another allowed ("Download Manager"), & still another unknown ("Downloads")?  Do y'all think think that could cause this level of weirdness?!

**Comment by ameshkov** [comment] 2016-07-25 10:02
In theory, it should appear as a separate app in that list.

@Revertron could you please elaborate on how we handle such cases?

**Comment by Revertron** [comment] 2016-07-25 10:16
Hm, the interesting finding!
Some apps (particularly system apps) may have one user-id in Android OS. But we detect the app which the connect belongs to by the user-id...

**Comment by TPS** [comment] 2016-07-25 14:02
@Revertron "User-id" in _this_ context seems nebulous at best, since, IIUC, all the apps I mentioned should have the same "user-id" (maybe?), but some appear & some don't, & they all have separate permissions in the AG firewall, but not in Android.  What a weird mess!

**Comment by TPS** [comment] 2016-07-25 17:00
@Revertron "User-id" in _this_ context seems nebulous at best, since, IIUC, all these apps ("Camera", "Videos", "Download Manager", & "Downloads") should have the same "user-id" (maybe?), but some appear & some don't, & they all have separate permissions in the AG firewall, but not in Android.  What a weird mess!

So, what _are_ the AG firewall rules for "Downloads"?

**Comment by ameshkov** [comment] 2016-07-26 12:16
User ID means OS user. In Android userid corresponds to an app. This works almost for every app except some system apps.

> So, what are the AG firewall rules for "Downloads"?

They will work but you won't see the second package name anywhere.

**Comment by TPS** [comment] 2016-07-27 06:12
https://github.com/AdguardTeam/AdguardForAndroid/issues/186#issuecomment-235496008!

**Comment by ameshkov** [comment] 2016-07-28 08:36
I'll leave one issue about it:
https://github.com/AdguardTeam/AdguardForAndroid/issues/186

This issue is now marked as duplicate.

**Closed by ameshkov** 2016-07-28 08:36 UTC
