### ISSUE TITLE
ssh tunnel for socks proxy

### ISSUE THREAD

**Issue by pou-chi** [AdguardTeam/AdguardForAndroid#666] opened 2016-07-04 12:08 UTC
After adding socks proxy functionality, a good step forward is add settings to create own ssh tunnel with dynamic port forwarding and use it as socks proxy server.

It will handy to those who owns VPS servers and uses tools like SSHTunnel to proxying data.

**Comment by ameshkov** [comment] 2016-07-04 13:07
Could you please link some article on how to setup such proxy?

**Comment by pou-chi** [comment] 2016-07-04 13:10
http://www.opennet.ru/tips/info/1691.shtml

**Comment by ameshkov** [comment] 2016-07-07 11:43
Hm, why not just use a separate app for creating an ssh tunnel?

Something like that:
https://play.google.com/store/apps/details?id=org.sshtunnel&hl=en

**Comment by pou-chi** [comment] 2016-07-07 12:14
Because it is not convenient. If sshtunnel is falling, which happens often, and the tunnel is not available adguard loses network access. And so, adguard will monitor the tunnel and to maintain it in working condition. Besides, the app is no longer developed and has a lot of problems with newer versions of android.

**Comment by ameshkov** [comment] 2016-07-08 10:34
Frankly I think that embedding an SSH tunnel feature into AG would take too much time for such a rarely used feature. That's why I am looking for a solution involving more complex configuration.

What about automating this with the tasker app?

**Comment by ameshkov** [comment] 2017-12-04 13:31
Duplicate of #1356

**Closed by ameshkov** 2017-12-04 13:31 UTC
Labels: question
