### ISSUE TITLE
AdGuard not turning on inside Samsung secure folder,  Android 12

### ISSUE THREAD

**Issue by DoucheHellSung** [AdguardTeam/AdguardForAndroid#4073] opened 2021-12-26 13:28 UTC
- [yes] I am running the latest version 
- [yes] I checked the documentation and found no answer 
- [yes] I checked to make sure that this issue has not already been filed 

### Issue Details

Adguard is not able to turn on inside secure folder on samsung s21 plus on latest a droid 12 stable

- **AdGuard version:**
  - v3.6.5) 
- **Filtering mode:**
  - NA
- **Device:**
  - Samsung S21 Plus
- **Operating system and version:**
  - Android 12
- **Root access:**
  - No

### Expected Behavior
Adguard used to work inside secure folder on android 11 on one ui 3.1

### Actual Behavior

It displays error banner ar bottom stating , an error occured please try again later while turning on Adguard 

### Screenshots

Not applicable 

### Additional Information

NA

**Comment by rawJul** [comment] 2021-12-26 13:30
Guys, please pardon me if I did something wrong, this is the first time I created the bug report. Please devs do contact me if any logs are needed.

**Comment by Birbber** [comment] 2021-12-27 08:53
@rawJul Hi! To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Send the file to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by rawJul** [comment] 2021-12-27 14:11
[adguard_logs_3.6.36_2712_192722.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/7780517/adguard_logs_3.6.36_2712_192722.zip)

Attached the logs team please let me know what else is required

**Comment by Chinaski1** [comment] 2021-12-28 12:02
According to the log, the application cannot start protection because it does not have permission to start.

It is possible that the issue is caused by using a [Restricted Mode profile](https://kb.adguard.com/en/android/solving-problems/restricted-profile).

**Comment by rawJul** [comment] 2021-12-28 18:40
> According to the log, the application cannot launch protection because it does not have permission to start.
> 
> It is possible that the issue is caused by using a [Restricted Mode profile](https://kb.adguard.com/en/android/solving-problems/restricted-profile).

I confirm, no solution worked in this case

**Comment by rawJul** [comment] 2021-12-29 04:27
Hi Konstantin,


I tried adb method and other methods but they doesnt work.


Were you able to reproduce the issue? On any samsung device with secure
folder?


Regards
Rajuk

**Comment by Birbber** [comment] 2021-12-29 08:54
@rawJul Getting root privileges didn't help as well?

**Comment by rawJul** [comment] 2021-12-29 09:34
> @rawJul Getting root privileges didn't help as well?

My bad, I don't have root access.

**Comment by Birbber** [comment] 2021-12-29 10:11
@rawJul Seems to be the only option left, so you might wanna try it.

**Comment by rawJul** [comment] 2021-12-29 13:29
People had the same issues earlier but the update fixed it, can it be investigated further if any team member of adguard is having a Samsung phone with android 12, because rooting a phone to run software is a drag in 2021, that too a Samsung phone where know gets tripped

**Comment by kongacute** [comment] 2021-12-31 00:27
Same problem after update to Android 12 in Samsung Note10+. It cannot start the VPN on AgGuard and AdGuard VPN.

**Comment by kongacute** [comment] 2021-12-31 16:52
After asked their support, I found out that their Samsung Max VPN service still works fine but not with 3rd party VPN services.

**Comment by rawJul** [comment] 2021-12-31 19:30
All other vpn services works fine for me , only adguard is giving problem

**Comment by kongacute** [comment] 2022-01-01 01:29
> All other vpn services works fine for me , only adguard is giving problem

I have no idea. Try AdGuard VPN and AdGuard for Android and neither of  them can start or create the VPN.

**Comment by rawJul** [comment] 2022-01-01 04:08
> > All other vpn services works fine for me , only adguard is giving problem
> 
> I have no idea. Try AdGuard VPN and AdGuard for Android and neither of them can start or create the VPN.

Yes,  as i said everything else is working but adguard apps are not working

**Comment by rawJul** [comment] 2022-01-02 12:06
@adguard any update on this one?  Even adguard vpn is not working

**Comment by Chinaski1** [comment] 2022-01-10 11:32
While we are looking for causes and possible solutions to the issue, I would recommend that you save AdGuard somewhere else, not in the Samsung secure folder.

**Comment by rawJul** [comment] 2022-01-14 18:40
Thanks, I hope it gets fixed soon, as I shared error logs with report, to Samsung team and they say problem is app. I feel the same, OfCourse my knowledge is limited, but to my layman eyes the thing which is clearly visible is that other vpn like Ipvanish and Nord works just fine. Even blokada works just fine. I would be happy to assist by providing more logs if there are no samsung A or S series user in adguard team. As this feature is exclusive to those series phone.

**Comment by laafiera** [comment] 2022-01-16 08:08
Any update on this issue, I'm having the same problem after updating to android 12

**Comment by githubBeginner2019** [comment] 2022-01-22 07:38
Same issue for me after updating my Galaxy S20 plus to Samsung One UI 4.0 (Android 12).

Updating to latest version v3.6.6 did not help.

I tried reinstalling the CA Certificate and the Adguard application itself, while no options worked.

Seems all One UI 4 users running Adguard over secure folder are facing the same error..hope AdguardTeam would resolve this soon

**Comment by BBZHub** [comment] 2022-01-22 20:44
Try adding "dns.adguard.com" as your Private DNS, under More Connection settings. Using Note 20 here and it seemed to vloak the secure folder ads. YMMV

**Comment by kongacute** [comment] 2022-01-22 23:27
> Try adding "dns.adguard.com" as your Private DNS, under More Connection Settings. Using Note 20 here and it seemed to block the Secure Folder ads. YMMV. 

DNS solution is never better than AdGuard app solution.

**Comment by rawJul** [comment] 2022-02-02 04:19
@adguard team . Is this issue been looked into?

**Comment by rawJul** [comment] 2022-02-06 05:26
Bumping this

**Comment by Chinaski1** [comment] 2022-02-08 08:55
Sorry for the late reply.
The AdGuard team is looking into the issue.

At first glance, the problem is related to [Restricted Mode profile](https://kb.adguard.com/en/android/solving-problems/restricted-profile) ut its roots may go deeper.
It is also possible that the developers of Samsung phones have changed some of the parameters that lead to the occurrence of the described situation. That's what we're dealing with.

As soon as I get more information about this issue, I'll let you know.

**Comment by rawJul** [comment] 2022-02-08 10:15
Thanks , i thought this bug was dropped.

**Comment by Chinaski1** [comment] 2022-02-09 12:52
We checked a number of tests and this is what we found out:

- When trying to install AdGuard cleanly into the Secure Folder, the protection runs without any issues
- If AdGuard was originally installed in a different directory and protection was running. After transferring to the Secure Folder, you will not be able to run the protection.
- We don't know for sure if completely removing AdGuard and reinstalling it in the Secure Folder will help, but it's worth a try.

Otherwise, we continue to investigate.

**Comment by kongacute** [comment] 2022-02-09 13:42
> We checked a number of tests and this is what we found out:
> 
> - When trying to install AdGuard cleanly into the Secure Folder, the protection runs without any issues
> - If AdGuard was originally installed in a different directory and protection was running. After transferring to the Secure Folder, you will not be able to run the protection.
> - We don't know for sure if completely removing AdGuard and reinstalling it in the Secure Folder will help, but it's worth a try.
> 
> Otherwise, we continue to investigate.
> 

Reinstall AdGuard doesn't work. Moreover, do your mean that you only test with AdGuard in or outside of Secure Folder?

**Comment by rawJul** [comment] 2022-02-09 13:44
> We checked a number of tests and this is what we found out:
> 
> * When trying to install AdGuard cleanly into the Secure Folder, the protection runs without any issues
> * If AdGuard was originally installed in a different directory and protection was running. After transferring to the Secure Folder, you will not be able to run the protection.
> * We don't know for sure if completely removing AdGuard and reinstalling it in the Secure Folder will help, but it's worth a try.
> 
> Otherwise, we continue to investigate.

So here is what i tried . Uninstall adguard completely with certificate from normal profile. Reboot and install adguard freshly inside secure folder. Result is - Adguard not turning on protection

**Comment by danpeig** [comment] 2022-02-16 23:56
Had the same issue, right after updating from Android 11 to 12 on a Samsung Galaxy 10e. Outside secure folder the app works normally.

I believe this is a bug on Secure Folder. I will try running the app on a Android for Work profile to see if it works.

**Comment by danpeig** [comment] 2022-02-17 14:02
Had the same issue, right after updating from Android 11 to 12 on a Samsung Galaxy 10e. Outside secure folder the app works normally.

I believe this is a bug on Secure Folder. I will try running the app on a Android for Work profile to see if it works.

**Comment by sfdkjgh8jgt90** [comment] 2022-02-21 09:11
+1
Netguard & nord working perfectly, pretty sure that's the problem of adguard

**Comment by sfdkjgh8jgt90** [comment] 2022-02-21 09:12
> Had the same issue, right after updating from Android 11 to 12 on a Samsung Galaxy 10e. Outside secure folder the app works normally.
> 
> I believe this is a bug on Secure Folder. I will try running the app on a Android for Work profile to see if it works.

I have tested it in work profile, also not working(adguard/ adguard vpn tested)

**Comment by danpeig** [comment] 2022-02-21 14:33
Confirm that NetGuard is working.

**Comment by ameshkov** [comment] 2022-02-22 08:51
Quick update on this issue.

1. Secure Folder prevents us from using the system API called `getPackagesForUid`. Currently, when this happens AdGuard simply crashes because it considers this functionality crucial.
2. The problem is similar to what happens when Dual Apps is enabled, but the difference is that with Dual Apps there's a better solution available (granting permissions via `adb`). Unfortunately, this is not the case with the new version of Secure Folder.
3. Without access to `getPackagesForUid` AdGuard is not able to detect what app is trying to access the Internet. This limits our capabilities, i.e. we won't be able to apply HTTPS filtering or firewall rules. 

Here's what we're going to do:

1. We'll change the logic a bit so that the app stayed operational even when `getPackagesForUid` fails.
2. We'll also detect that this issue happens on Samsung and alert users that AdGuard has some compatibility issues.
3. This change will keep AdGuard operational but limited in functionality.
4. We'll also file a bug report to Samsung that explains what went wrong.

**Comment by DoucheHellSung** [comment] 2022-02-24 04:21
> Quick update on this issue.
> 
> 1. Secure Folder prevents us from using the system API called `getPackagesForUid`. Currently, when this happens AdGuard simply crashes because it considers this functionality crucial.
> 2. The problem is similar to what happens when Dual Apps is enabled, but the difference is that with Dual Apps there's a better solution available (granting permissions via `adb`). Unfortunately, this is not the case with the new version of Secure Folder.
> 3. Without access to `getPackagesForUid` AdGuard is not able to detect what app is trying to access the Internet. This limits our capabilities, i.e. we won't be able to apply HTTPS filtering or firewall rules. 
> 
> Here's what we're going to do:
> 
> 1. We'll change the logic a bit so that the app stayed operational even when `getPackagesForUid` fails.
> 2. We'll also detect that this issue happens on Samsung and alert users that AdGuard has some compatibility issues.
> 3. This change will keep AdGuard operational but limited in functionality.
> 4. We'll also file a bug report to Samsung that explains what went wrong.
> 
> We should also consider trying using [] to request [createRequestInteractAcrossProfilesIntent](https://developer.android.com/reference/android/content/pm/CrossProfileApps#createRequestInteractAcrossProfilesIntent()), there's a chance that it will simply resolve the issue automatically when the "cross-profile-interaction" permission is granted.

Thank you @ameshkov at least some closure, you can reach out to me if logs and testing is required.

**Comment by DoucheHellSung** [comment] 2022-03-17 19:42
i See the bug status is changed, will it be updated in next build >?? And same is needed for adguard VPN too!

**Comment by Eugene-Savenko** [comment] 2022-05-19 14:57
@AdguardTeam/developers This will be fixed for AdGuard VPN as well, correct? Thank you!

**Comment by artemiv4nov** [comment] 2022-05-20 09:46
That issue has been already fixed for the AdGuard 3.6.8. In AdGuard VPN, we will fix it, also. Follow the link: https://github.com/AdguardTeam/AdGuardVPNForAndroid/issues/182

**Comment by Alex-302** [comment] 2022-08-19 17:48
https://github.com/AdguardTeam/AdguardFilters/issues/127224

**Closed** 2022-08-26 17:00 UTC
Labels: Bug, Resolution: Fixed, Status: Resolved, Version: AdGuard v3.6.8
