### ISSUE TITLE
Check compatibility of v3.6 with Android 12

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3937] opened 2021-08-10 11:52 UTC
There soon will be a new major update of Android and we should check if AG for Android v3.6 is fully compatible with it.

Probably, it is, at least that's my first impression from using Android 12 beta, but we need to be sure. Let's conduct a full test on the new Android.

**Comment by BKBKJBB** [comment] 2021-08-12 03:08
Adguard is definitely not working with Android 12 beta 4. Since updating today all ads are showing in browsing and apps.

**Comment by vladrevers** [comment] 2021-08-12 09:40
https://issuetracker.google.com/issues/196271165

**Comment by Chinaski1** [comment] 2021-08-12 10:45
The same issue is reported on the [AdGuard forum](https://forum.adguard.com/index.php?threads/ads-not-being-blocked-on-android-12-beta-4-spb4-210715-011-released-today.44270/).

**Comment by anastenko** [comment] 2021-08-16 10:29
Same issue reported in ticket [529142](https://adguard.zendesk.com/agent/tickets/529142)

**Comment by Eugene-Savenko** [comment] 2021-08-16 10:54
More logs here: [529144](https://adguard.zendesk.com/agent/tickets/529144)

**Comment by deartvonrud** [comment] 2021-08-24 20:27
One of German user reported the same problem under Android 12: **531413**

**Comment by Chinaski1** [comment] 2021-09-06 13:02
I am closing this task as the issue is no longer reproducible.

**Closed** 2021-09-06 13:02 UTC
Labels: Enhancement, P3: Medium, Resolution: Won't Fix, Status: Resolved, Middle, Version: AdGuard v3.6.3
