### ISSUE TITLE
AdGuard blocks Internet connection

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#2842] opened 2019-06-26 13:45 UTC
When the user switching from Wi/Fi to LTE internet connection is lost.
Need relaunch protection to reconnect. 

"pref.vpn.disable.reconfigure" : true
"pref.vpn.disable.pause" : true

### User ID
2228088

[Logs](https://ncloud.adguard.com/index.php/apps/files?dir=/Support/Issues/Android/QCRM_2228088)

### Your environment

* Adguard version: 3.1.0/3.1.44n
* Adguard filtering mode: Local VPN
* Device model: Xiaomi Mi 9
* Operating system and version: 9
* Root access: Yes

**Comment by ameshkov** [comment] 2019-06-26 21:47
@Chinaski1 "record everything"-level logs are required to troubleshoot

**Comment by Chinaski1** [comment] 2019-07-01 09:50
Same problem : 1557976 Logs in NCloud
**18:25 27|06**

And another one: 2240216 Logs in NCloud

**Comment by Chinaski1** [comment] 2019-07-01 10:46
When switching from 4G to Wi / Fi, the Internet connection is lost

### User ID
1889438

**Logs in NCloud**

### Your Environment

Adguard version: 3.1.0
Device model: Xiaomi Mi A1
Operating system and version: 9
Adguard filtering mode: Local VPN

**Comment by Chinaski1** [comment] 2019-07-01 13:19
One more user **@ev_klzn**
User update from 8 to 9 Android. From time to time the Internet connection is lost
(Both Wi / Fi and LTE)
Device model: Xiaomi Redmi note 5.
**Logs in Ncloud**

**Comment by akmLaVx** [comment] 2019-07-02 16:48
Same issue for user 2240216.
Samsung G960F, Wi-Fi/LTE, issues began quite recently.

**Comment by Chinaski1** [comment] 2019-07-03 12:41
Another one user: 1254045
Connection lost on Wi/Fi and LTE
Device model: SM-G975F
Logs in Ncloud

**Comment by ameshkov** [comment] 2019-07-03 16:40
Also this one:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2872

**Comment by ameshkov** [comment] 2019-07-03 16:44
@Chinaski1 @TheHasagi to figure our what's wrong, we need to get the logcat log:
https://kb.adguard.com/en/android/solving-problems/logcat

It needs to be exported **right after the issue is reproduced**.

**Comment by Eugene-Savenko** [comment] 2019-07-06 09:28
Another report here - 2045896

> На устройстве android после установки adguard начались перебои с работой интернета (не грузятся страницы в браузере гугл хром, не работают приложения, требующие интернет соединения), но при выключении и повторном включении AdGuard, работа восстанавливается.

```
My device : Samsung Galaxy M20 (SM-M205FN)
OS : Android 9
Adguard V. : 3.1.0
Dns filtering : false
Adguard filtering method : Local VPN
Antivirus : n/a
Root access : n/a
```

**Comment by ameshkov** [comment] 2019-07-13 12:06
We cannot reproduce this even on the same test devices.

Here's what we need to troubleshoot:

1. Logcat: https://kb.adguard.com/en/android/solving-problems/logcat
2. AdGuard's own load (settings -> advanced -> export logs)
3. The exact time when it happened

**Comment by patrickdrd** [comment] 2019-07-14 15:33
it happens to me too, 
I'm attaching logcat and log files:

[adguard_logs_3.2.95_1407_183159.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3390087/adguard_logs_3.2.95_1407_183159.zip)

[2019-07-14-18-29-42.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/3390086/2019-07-14-18-29-42.txt)

the time it happened should be around 18:25:
`java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: Connection closed by peer`

**Comment by patrickdrd** [comment] 2019-07-14 15:48
what are all these 

`TLS connection is not HTTPS, adding 'com.facebook.katana#157.240.20.15:443#graph.facebook.com' to exceptions
TLS connection is not HTTPS, adding 'com.facebook.katana#157.240.20.35:443#b-api.facebook.com' to exceptions
TLS connection is not HTTPS, adding 'com.facebook.katana#157.240.20.35:443#b-graph.facebook.com' to exceptions
TLS connection is not HTTPS, adding 'com.facebook.katana#157.240.20.15:443#api.facebook.com' to exceptions
TLS connection may not be filtered because CA cert is not recognized by application, adding 'com.facebook.katana#157.240.20.10:443#edge-mqtt.facebook.com' to exceptions
TLS connection is not HTTPS, adding 'com.instagram.android#157.240.20.63:443#i.instagram.com' to exceptions
TLS connection may not be filtered because CA cert is not recognized by application, adding 'com.instagram.android#157.240.20.19:443#connect.facebook.net' to exceptions`

should I do something about them?

**Comment by akmLaVx** [comment] 2019-07-15 04:44
Progress update:

2228088 reports that the issue cannot be reproduced when his phone is connected to a PC. Asked for clean logcat logs, just for the case.
1557976 had encountered problems while installing ADB/Fastboot; ADB fails to recognize his device.

2240216, 1889438, 1254045, 2045896, 1562409: logs requested. Waiting for response.

**Comment by Eugene-Savenko** [comment] 2019-07-17 07:41
Find a logcat here: 2228088

**Comment by akmLaVx** [comment] 2019-07-17 19:02
One more user with this issue: 2075818. Requested logcats, waiting for reply.

**Comment by Eugene-Savenko** [comment] 2019-07-20 06:54
We have logcat from 1889438

**Comment by ameshkov** [comment] 2019-07-25 13:46
@AdguardTeam/support-team guys, next time please request [this](https://developer.android.com/studio/debug/bug-report) instead of logcat.

It contains all the necessary information + logcat. Besides that, we'll need to get AdGuard logs.

Also, we'll need to know the time when the issue happened.

**Comment by ameshkov** [comment] 2019-07-25 13:47
> I'm running latest nightly on local proxy (root) with cloudflare dns (regular)

Root is different. Most likely, AdGuard was killed by Android.

> should I do something about them?

Nope, these are okay.

**Comment by ameshkov** [comment] 2019-07-25 13:54
> 2228088
Too late to record the logcat:(

Please ask the user to do this:
https://github.com/AdguardTeam/AdguardForAndroid/issues/2842#issuecomment-515050041

Considering that capturing Android bug report is not as complicated and does not require connecting to a computer, it'd be much easier to collect the necessary information.

**Comment by ameshkov** [comment] 2019-07-25 13:55
> 1889438

This one looks very relevant actually:

```
07-18 07:32:42.029 16681 16881 E com.adguard.android.filtering.api.LocalVpnService: [tcpip-stack-pool-3-thread-4] TCP id=919 Unexpected exception in the onTcpConnectRequest handler
07-18 07:32:42.029 16681 16881 E com.adguard.android.filtering.api.LocalVpnService: java.lang.IllegalStateException: Network filter is already closed
07-18 07:32:42.029 16681 16881 E com.adguard.android.filtering.api.LocalVpnService: 	at com.adguard.filter.NativeNetworkFilterImpl.a(NativeNetworkFilterImpl.java:9) ~[na:0.0]
07-18 07:32:42.029 16681 16881 E com.adguard.android.filtering.api.LocalVpnService: 	at com.adguard.android.filtering.filter.d$a.a(ConnectionFilter.java:2) ~[na:0.0]
07-18 07:32:42.029 16681 16881 E com.adguard.android.filtering.api.LocalVpnService: 	at com.adguard.android.filtering.api.LocalVpnService$a.a(LocalVpnService.java:35) ~[na:0.0]
07-18 07:32:42.029 16681 16881 E com.adguard.android.filtering.api.LocalVpnService: 	at com.adguard.android.filtering.api.LocalVpnService$a.onTcpConnectRequest(LocalVpnService.java:15) ~[na:0.0]
07-18 07:32:42.029 16681 16881 E com.adguard.android.filtering.api.LocalVpnService: 	at com.adguard.corelibs.tcpip.NativeTcpIpStackImpl$Callbacks$1.run(NativeTcpIpStackImpl.java:1) ~[na:0.0]
07-18 07:32:42.029 16681 16881 E com.adguard.android.filtering.api.LocalVpnService: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) ~[na:0.0]
07-18 07:32:42.029 16681 16881 E com.adguard.android.filtering.api.LocalVpnService: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) ~[na:0.0]
07-18 07:32:42.029 16681 16881 E com.adguard.android.filtering.api.LocalVpnService: 	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
```

**Comment by patrickdrd** [comment] 2019-07-26 06:59
> Root is different. Most likely, AdGuard was killed by Android.

I didn't say that AG was killed, but my internet connection did,
it has happened twice lately if I'm not mistaken, 
very rare issue, but awfully annoying when it happens

**Comment by ameshkov** [comment] 2019-07-26 09:55
Fix for 1889438 is in `adguard-android/pull-requests/1378`

I am not sure if it resolves other cases because I suspect that we collected several different issues there.

@AdguardTeam/support-team so I am still waiting for https://github.com/AdguardTeam/AdguardForAndroid/issues/2842#issuecomment-515050041

**Comment by Chinaski1** [comment] 2019-07-26 11:44
[Forum](https://forum.adguard.com/index.php?threads/adguard-choking-internet-on-pixel-3-xl.32428/#post-186057)
Logs added to NCLoud

**Comment by Chinaski1** [comment] 2019-07-29 09:34
[Forum](https://forum.adguard.com/index.php?threads/adguard-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D1%83%D0%B5%D1%82-%D0%B2%D0%B5%D1%81%D1%8C-%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D0%BD%D0%B5%D1%82.34043/#post-186071)
Time and Date:
**28.07 | 21:28**
*Logs in Ncloud*

**Comment by ameshkov** [comment] 2019-08-05 17:11
Reassigned to v3.3

> https://forum.adguard.com/index.php?threads/adguard-choking-internet-on-pixel-3-

This one is supposedly fixed in the latest nightly.

> Forum
> Time and Date:
> 28.07 | 21:28

This one needs to be analyzed.

**Comment by izark99** [comment] 2019-08-11 09:04
My Phone: Xiaomi Redmi K20 Pro
Android version: 10
Root: Rooted with Magisk

After I upgrade my phone to Android 10 and rooted it with Magisk, I can't connect to Internet if I choose "Local HTTP Proxy (Local Proxy auto mode)" in Filtering Method. I can connect to Internet if I choose "Local VPN" in Filtering Method.

This problem appear after I upgrade my phone to Android 10. Before that, Android 9 I can choose it normally.

Sorry because my English is not good.

**Comment by ameshkov** [comment] 2019-08-20 19:49
@Chinaski1 @TheHasagi guys, if there are new complaints or if there are any news on this, please post the update here

**Comment by Chinaski1** [comment] 2019-08-22 15:59
New logs from **2075818**
Added to NCloud

**Comment by Eugene-Savenko** [comment] 2019-08-26 08:53
> Столкнулся со следующей проблемой. Установил Adguard на новый телефон. После запуска Adguard сеть на телефоне полностью блокируется. Ни одно приложение сеть не видит. Если ставишь Adguard на паузу, то работа сети возобновляется.

ID: 2295144 (w/ adguard and system logs)
AdGuard version: 3.2.140

**Comment by ameshkov** [comment] 2019-08-28 09:41
@Eugene-Savenko is it still reproduced on the latest beta?

**Comment by ocebir** [comment] 2019-08-29 19:39
I am having the same issue on my samsung s10e and my samsung tab a 10.5

**Comment by ameshkov** [comment] 2019-08-30 10:06
@ocebir could you please collect logs as it's explained in [this comment](https://github.com/AdguardTeam/AdguardForAndroid/issues/2842#issuecomment-515050041)?

**Comment by ocebir** [comment] 2019-08-31 10:05
I have updated to 3.2.150 yesterday, so far the issue has not happened if/when it does I will get the logs. Thanks

**Comment by ocebir** [comment] 2019-09-07 09:56
How do I upload logs for this please?

**Comment by ocebir** [comment] 2019-09-07 09:57
I have emailed them to support@adguard.com. but if there is another email address i can email them to please let me know. Thanks

**Comment by ocebir** [comment] 2019-09-08 17:47
@ameshkov please let me know if there is anything else i can do. Thanks

**Comment by ameshkov** [comment] 2019-09-08 19:38
@ocebir thank you!

Plz forward the same email to `devteam@adguard.com` - this is a shortcut to the developers:)

**Comment by ameshkov** [comment] 2019-09-08 21:58
@ocebir got the logs, thank you!

Unfortunately, it seems that the default AdGuard's logging level is not enough to figure what's going on. I see that connections are timing out, but I can't see why.

Could you please try using AdGuard with the logging level set to "record everything" for some time?

**Comment by ocebir** [comment] 2019-09-08 22:03
@ameshkov no problem i will do this and get back with new logs, thanks

**Comment by SynergiAios** [comment] 2019-09-09 07:12
Just to inform everyone, for me, I was able to solve this issue with what the support sent me.
1) Ensure Battery Save Tasks don't kill/sleep the Adguard Service
2) Make sure Notifications are enabled

For my device:
OnePlus 6 - current OxygenOS

**Comment by ocebir** [comment] 2019-09-13 18:44
@ameshkov I have emailed new logs to devteam@adguard.com. I hope this helps. If anything further is required please let me know. Thanks

**Comment by AdiSimpson** [comment] 2019-10-02 14:33
I have also this Problem with Xiaomi Mi 9T Pro. Often after Wakeup there is WiFi Connection but no Dataflow. Cant Sync Emails, Playstore, Adguard Update and so on. After some Minutes something kicks in and its working like it should.

Interessting is i can fix it shortly by starting Firefox and loading some Pages. It opens the blockage and everything is working.

Every Batterysaving Options are disabled.
I hope you guys find the cause.

**Comment by Chinaski1** [comment] 2019-10-08 15:35
One more user got this issue on model=Mi 9T brand=Xiaomi
**2280133 Logs in NCloud**

**Comment by AdiSimpson** [comment] 2019-10-10 19:42
I think i have to unistall Adware, its blocking often my WiFi connection. On Mi 9T Pro its a pain in the Ass... Tested many Options in Adware that could be the cause, but was not successful. When even Adware cant Update his Filters, there must be something deeper faulty. Mobile Data works...

**Comment by artemiv4nov** [comment] 2019-10-11 14:19
@AdiSimpson this is a very complicated issue, but we dig further.
Can you test on AdGuard v3.3 nightly 12?

**Comment by AdiSimpson** [comment] 2019-10-11 21:36
Iam on Nightly 13 now. I will look into it.

**Comment by AdiSimpson** [comment] 2019-10-18 18:11
Nearly 5 Days without Problems, and now Adguard blocks itself again...i was thinking maybe its fixed. Workaround -> Open Firefox, load/reload Page. Adguard works again.

**Comment by ameshkov** [comment] 2019-10-23 11:24
> Workaround -> Open Firefox, load/reload Page. Adguard works again

Without even restarting AG?

**Comment by AdiSimpson** [comment] 2019-10-23 11:39
When Adguard is blocking i just open Firefox, nothing else. Using Firefox unblocks it, or i can wait some time and Adguard unblocks itself.

**Comment by Chinaski1** [comment] 2019-11-01 10:10
One more user faced this issue: **1600636**
Logs in NCloud.

**Comment by AdiSimpson** [comment] 2019-11-03 21:20
i hope this fix helps...
[Corelibs v1.5.94 Fix] LocalApiServer hanged after long sleep: AdguardTeam/CoreLibs#1060

**Comment by Chinaski1** [comment] 2019-11-05 15:19
Another complaint about this problem from our [forum](https://forum.adguard.com/index.php?threads/ag-turns-itself-off-unexpectedly.35854/#post-190927).
Time: 06.11.2019 | 00:43
Logs in NCloud.

**Comment by AdiSimpson** [comment] 2019-11-12 17:36
I updated to Android 10, was hoping that fixes the behaivor. 10 Days later this morning Data was again blocked with Wifi or slow like a 56K Modem.

**Comment by akmLaVx** [comment] 2019-11-15 10:13
New logs available from user 776566.

**Comment by akmLaVx** [comment] 2019-11-27 01:06
Additional logs available in helpdesk ticket 2344218.

**Comment by akmLaVx** [comment] 2019-11-28 05:22
Additional logs available in helpdesk ticket 1696216.

**Comment by Nazer92** [comment] 2019-12-13 19:32
Всем привет, тоже наблюдается такая проблема, приходится выключать/включать Адгуард чтоб телефон начал получать интернет.  Логи отправлял по тех-поддержке на адрес support@adguard.com.
Тоже хочу присоединиться, если нужны какие то логи, сообщите.
у меня Самсунг А50. Андроид 9. (чистый, не рутированый и так далее)

**Comment by Chinaski1** [comment] 2019-12-17 10:32
And another one: **2426449**
Logs as they should be added to NCloud.
Time: 13:30/12.12.2019

**Comment by akmLaVx** [comment] 2019-12-18 03:46
Another user: **2328199**
Issue only affects LTE connections.
Logs in the helpdesk ticket.

**Comment by akmLaVx** [comment] 2019-12-19 16:30
Another user: **2299011**
LTE only.

**Comment by akmLaVx** [comment] 2019-12-19 16:31
@AdguardTeam/developers Please let us know if you require any additional data. Also, would be great to hear the overall progress on that issue.

**Comment by Chinaski1** [comment] 2020-01-10 07:55
One more: **2485597**
Two files with archives were added to NCloud.

**Comment by Chinaski1** [comment] 2020-01-13 09:21
HelpDesk ID: **2185224**
Time/Date: 13:56/07.01.20

**Comment by akmLaVx** [comment] 2020-01-14 13:54
Helpdesk ID: **2328199**
Time/date: 1.10.2020 / 13:11

**Comment by akmLaVx** [comment] 2020-01-14 18:42
Got a new case: **1269366**
Time/date 1.12.2020 / 20:32

**Comment by akmLaVx** [comment] 2020-01-21 05:03
New case: **2448524**
Time/date: 1.20.2020 / 7:00 - 7:08

**Comment by akmLaVx** [comment] 2020-01-29 10:48
New case: **1106631**
Time/date: 1.27.2020 / 15:36

**Comment by akmLaVx** [comment] 2020-01-31 19:40
New case: **1973342**
Time/date: 1.28.2020 / 18:51

**Comment by Chinaski1** [comment] 2020-02-07 11:14
Another user: 1598194
Time/date: 2.02.2020/16:43
Logs in NCloud

**Comment by Chinaski1** [comment] 2020-03-17 12:59
User ID: 2580549
Time/Date: 11:25-12:29 | 11.03.2020

**Comment by Chinaski1** [comment] 2020-03-18 16:37
User ID: 2595086
Time/Date: 09:55 | 17.03.2020

**Comment by artemiv4nov** [comment] 2020-03-26 09:04
After all, at another one deep study of the problem, we noticed unusual network behavior that told us where the possible bug has been hidden.
The first, unofficial bug fix has appeared in the Nightly 9. We interviewed the AdGuard community members who were most often exposed to this problem and all confirmed the fix is succeeded.
We hope the fix will be a success for you all, also.

**Comment by akmLaVx** [comment] 2020-05-06 14:24
User 2669879 reports that the problem has not gone away. They are running AdGuard 3.4 beta 1.
See support ticket 2669879 for detailed logs.

**Comment by artemiv4nov** [comment] 2020-05-06 19:10
Got the situation from User 2669879, sent an email.

**Comment by quyleanh** [comment] 2020-05-31 17:33
I still have this error sometimes...

**Comment by jineshpatel30** [comment] 2020-06-02 06:21
Internet blocking issue still present on 3.4 stable. Yes, it's less prevalent compared to 3.3 but it's definitely not fixed. 

Also, It's not actually related to switching connections between wifi/LTE because many time it blocks internet access even in same WiFi connection, it's like internet was working a minute ago now no application can connect to internet unless I go to Adguard manually, and disable protection and re-enable it. (quick setting widget turn off/on also don't work to gain internet access back)

I'm on POCO F1 but with custom ROM Android 10, so it's not like MIUI is shutting down adguard.
Plus Battery optimization is disabled
Running in Background allowed fully
Even allowed OOM adjustment via advanced setting with root

But issue stays. **(Same issue was there in stock MIUI Android 10 as well, same setup as described above)**

It's kind of random on daily basis but mostly happens after using device that has been in ideal for some time. Also, it doesn't happen right after waking up ideal device as internet works for sometime and then suddenly nothing connects ! So, manual reconnect is required to get Internet access back as described initially.

Don't know what kind of logs you'll need for this so let know.

**Comment by quyleanh** [comment] 2020-06-02 07:29
@jineshpatel30 Your description is the same with me. I notice that the issue is not happened when using mobile data, it's seems only happen on wifi network.

**Comment by jineshpatel30** [comment] 2020-06-02 07:33
> @jineshpatel30 Your description is the same with me. I notice that the issue is not happened when using mobile data, it's seems only happen on wifi network.

I'm on WiFi for like 99% of time, so what you're saying is highly probable but I can't confirm.

**Comment by quyleanh** [comment] 2020-06-02 07:50
@jineshpatel30 ok. Hope this issue is fix.

**Comment by jineshpatel30** [comment] 2020-06-05 10:29
> @jineshpatel30 ok. Hope this issue is fix.
Hey can you check whether internet blocking issue continues for you if you use "Proxy Blocking" method instead of VPN. (Auto proxy won't work without root but you can still setup manual proxy) Adguard will guide you through steps.

I have an Interesting theory through my experiment yesterday.
https://forum.adguard.com/index.php?threads/what-causes-adguard-to-block-my-internet-connection.29301/post-198917

**Comment by quyleanh** [comment] 2020-06-05 14:04
@jineshpatel30 I am checking now.
There is some work around for this, I think. You can try to pause and resume the protection from notification panel. I did twice and it worked.

**Comment by jineshpatel30** [comment] 2020-06-05 14:13
> @jineshpatel30 I am checking now.
> There is some work around for this, I think. You can try to pause and resume the protection from notification panel. I did twice and it worked.

I tried pause & resume few days back but some time that also doesn't :(
Anyway give Proxy blocking a try, I'm using it for around 12 hours now without any network drop so far. See how it turns out for you and let them know here.

**Comment by quyleanh** [comment] 2020-06-05 14:21
@jineshpatel30 is there any recommended proxy server?
Btw, the ads is not blocked well when I change to proxy mode...

**Comment by jineshpatel30** [comment] 2020-06-05 14:30
> @jineshpatel30 is there any recommended proxy server?
> Btw, the ads is not blocked well when I change to proxy mode...

I don't think so, It's local proxy so there's nothing like different proxy server. Tough, I think Manual Proxy doesn't work with mobile data, You'll need WiFi for manual proxy setup. For me it was auto configured since I have root but here's manual setup guide.
https://kb.adguard.com/en/android/faq#how-to-manually-configure-a-local-http-proxy

**Closed** 2020-08-18 10:36 UTC
Labels: Bug, P2: High, Resolution: Fixed, Waiting for repro
