### ISSUE TITLE
Sync appSetting with profile

### ISSUE THREAD

**Issue by hepin1989** [AdguardTeam/AdguardForAndroid#3466] opened 2020-06-28 02:04 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed

### Problem Description

I hope adguard has a way to sync app settings with profile across devices (PC/Mac/Android)

### Proposed Solution

TBD

**Comment by TheHasagi** [comment] 2020-06-29 08:52
@hepin1989 

This is the duplicate of source [issue](https://github.com/AdguardTeam/AdguardForAndroid/issues/134). We are working on implementation. Please, be patient.

**Closed by TheHasagi** 2020-06-29 08:52 UTC
