### ISSUE TITLE
NPR Freezes

### ISSUE THREAD

**Issue by warmoans** [AdguardTeam/AdguardForAndroid#5101] opened 2023-12-11 02:37 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2.118

### Environment

```markdown
- OS: android 
- Device: pixel 7 pro
- Firmware: December 2023
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, EasyPrivacy, Adblock Warning Removal List

### What Stealth Mode options do you have enabled?

Remove X-client-Data header from HTTP request

### Issue Details

Steps to reproduce:
1. Open NPR
2. Website goes to top of page and freezes

### Expected Behavior

NPR doesn't freeze 

### Actual Behavior

NPR freezds

### Screenshots

https://mega.nz/file/FSJxFIqS#qTlhPrv_bWnK5aJ3G3aunZJg2oA5dkn_pjFvGBccuhs

### Additional Information

Disabling userscripts doesn't change anything.

**Comment by maxikuzmin** [comment] 2023-12-27 21:31
@warmoans you are right, the problem is also reproduced in me, we will solve it in the upcoming updates

**Comment by maxikuzmin** [comment] 2023-12-27 21:42
@warmoans you need to send "Report incorrect blocking" and then specify all the necessary data that is requested to indicate the problem. 
Go to Settings tab -> Support -> Report incorrect blocking
This will help you resolve the issue. For now, I am closing this issue

**Closed by maxikuzmin** 2023-12-27 21:42 UTC
Labels: Bug, Priority: P4

**Comment by warmoans** [comment] 2023-12-28 00:45
@maxikuzmin issue is resolved now.
