### ISSUE TITLE
GCM notification delay, GCM connection interupted

### ISSUE THREAD

**Issue by JhonHuGit** [AdguardTeam/AdguardForAndroid#3956] opened 2021-08-30 10:43 UTC
### Prerequisites

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
3.6.2
- **Filtering mode:**
Local VPN with shadowsocks outbound
- **Device:**
Samsung s20 ultra snapdragon with Chinese rom 
- **Operating system and version:**
Android 11 / oneui 3.1
- **Root access:**
no

### Expected Behavior

This issue is concerned about GCM notification. I cannot connet GCM and most google services due to my local government policy. So I am using shadowsocks as a proxy and adguard as vpn. My mobile network has a 20 mininutes timeout, so I used an app to send a heartbeat package every 5 minutes to keep GCM connection alive. 
I have disabled battery optimization for nearly every app.
GCM connetion will keep alive.

### Actual Behavior

When using mobile network and screen off, GCM disconnets ramdomly. This situation does not happen when screen is on or the phone charges or with wifi. 
Strangely, this disconnetion usually happens when using ipv4, with ipv6 working but not filtered, the problem seems gone.

Logs and fcm diagnostics screenshots are attached below.

### Screenshots

![ipv4_adguard_logs_3 6 23_3008_174100](https://user-images.githubusercontent.com/44264634/131327668-d80d320d-f252-4771-8995-6a9b13c8f64a.jpg)
[ipv4_adguard_logs_3.6.23_3008_174100.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/7076099/ipv4_adguard_logs_3.6.23_3008_174100.zip)
![ipv6_adguard_logs_3 6 23_3008_181059](https://user-images.githubusercontent.com/44264634/131327678-103226d9-a5e2-4c95-bc6c-8006a81ff757.jpg)
[Uploading ipv6_adguard_logs_3.6.23_3008_181059.zip…]()

**Comment by Disqu3-mirOir-qt** [comment] 2021-08-30 16:53
adguard not use GCM (google cloud messaging) it,s use own socket

**Comment by JhonHuGit** [comment] 2021-08-31 01:59
I am sorry if I don't make myself clear. The problem is when using adguard with shadowsocks, adguard seems to break some local connections. And with other current situation of isp(20 minutes heartbeat, lesser than 28 minutes of google heartbeat), it leads to GCM connection/notification problem

**Comment by JhonHuGit** [comment] 2021-08-31 02:19
I find it connects successfully when getting results from '143.95.251.89:80: 128', but when getting results from '143.95.251.89:80: 32', it will fail. 
143.95.251.89:80 is the ip my app trying to reach, so the difference is 128 or 32. I think maybe this is the problem

**Comment by Chinaski1** [comment] 2021-09-01 08:44
It seems to me that this issue may be related to [recent updates](https://www.xda-developers.com/samsungs-one-ui-3-update-annoying-app-killing-behavior/?utm_source=ixbtcom) on the One UI 3.0 and 3.1 shell on Android 11, Samsung changed its policy on closing apps running in the background. 
When the screen is locked, some applications are not able to work correctly.

To make sure your favorite apps don’t get killed unexpectedly and work as intended on your Galaxy device running Android 11, head to Settings > Apps > “Your App” > Battery > Battery Optimization > All Apps > “Your app” > Don’t optimize.

**Comment by JhonHuGit** [comment] 2021-09-01 08:57
I have put almost every app into 'Don’t optimize' status. But the problem is still there.
When enable pref.vpn.ipv6.bypass instead of pref.vpn.ipv6.disable, GCM connection seems to be more stable. The change may be that with pref.vpn.ipv6.bypass, GCM uses ipv6 channel other than ipv4.

**Comment by Chinaski1** [comment] 2021-09-01 09:53
I think you can try enabling AdGuard in Always-on-VPN mode maybe this will help in solving the issue.

**Comment by JhonHuGit** [comment] 2021-09-01 11:57
Tried this, the problem still exists

**Comment by admitrevskiy** [comment] 2021-09-02 12:48
@JhonHuGit Hi!
Could you try to reproduce the issue with only shadowsocks in VPN mode?

**Comment by JhonHuGit** [comment] 2021-09-03 03:03
Tried yesterday evening, shadowsocks alone worked fine. GCM connects steably.

**Comment by JhonHuGit** [comment] 2021-09-23 08:38
Update adguard to 3.6.4, and use another samsung s20 ultra with latest system patch, the problem is gone both in ipv4 and ipv6 environment.

**Comment by Birbber** [comment] 2021-09-23 09:44
@JhonHuGit Thanks for the update! 
I'm closing this issue now. If it reoccurs, please reopen it.

**Comment by JhonHuGit** [comment] 2021-10-02 09:16
update: the problem is back again. Here is how I tried and the results
a) shadowsocks in proxy only mode, adguard with pref.vpn.ipv6.disable enabled. GCM connection is unstable. It will disconnect randomly. 
b) shadowsocks in proxy only mode, adguard with pref.vpn.ipv6.bypass enabled. GCM connects in ipv6 channel and will be much more stable. The problem is not ipv6 is not available everywhere, when disconnected, it will fall back to ipv4 and seldom connect to ipv6.
These two situations have one problem in common, during night time, GCM connection will disconnect.
c) shadowsocks in vpn mode. All problems are gone, except I cannot filter ads. 

I searched the internet and find Samsung has something called local battery policy which has no way to disable except for a foreign SIM card. I first presume that a) and b) problems is related to this stupid policy, but I am wondering why c) is OK. 

Anyway, I will keep trying and update. Hope version 4.0 or Samsung new oneui will somehow solve the problem.

Just saying, is it possible for you to add more filter rules to your public dns, for example, some more Chinese filter rules?  (・ω<)

**Comment by Birbber** [comment] 2021-10-04 12:11
@JhonHuGit Could you file an issue with more details in [filters repository](https://github.com/AdguardTeam/AdguardFilters/issues)? Make sure to mention the domains you'd like to block.

**Comment by JhonHuGit** [comment] 2021-10-05 08:26
I don‘t know exactly what domain is about the ads. Here are the filters I am using. (Sorry about the Chinese because I don't know how to translate them to English)
Adguard 基础过滤器
Adguard 移动广告过滤器
Adguard 防跟踪保护过滤器
Adguard 社交媒体过滤器
在线恶意url拦截列表
spam 404
NoCoin 过滤列表
Adguard 恼人广告过滤器
Adguard 中文过滤器
解除搜索广告和自我推销过滤器
This works well for me, but when I use Adguard dns which is dns.adguard.com only, some ads cannot be filtered, for example ads on www.v2ex.com.

**Comment by Birbber** [comment] 2021-10-05 10:24
@JhonHuGit You can report this issue via **Support** --> **Send feedback** --> **Missed ad or tracker** and mention the webpage/es you faced the issue on. 
Fill the form up with all the information required. The issue will be created on [filters repository](https://github.com/AdguardTeam/AdguardFilters/issues).

**Comment by JhonHuGit** [comment] 2021-11-08 02:03
UPDATE: 
GCM connection seems normal when I enable pref.vpn.ipv4.force.default in lower settings.
I will keep an eye on this issue and update if there the problem comes back.
Meanwhile, would you please do some digging on this problem, maybe it can make adguard better.

**Comment by JhonHuGit** [comment] 2021-11-11 06:09
UPDATE:
the problem is back again, still looking for solutions

**Comment by admitrevskiy** [comment] 2021-11-29 10:08
@JhonHuGit Hi! Is there any news on this issue?
Could you please collect debug logs with the latest stable version?

- Go to Settings -> Advanced -> Logging level -> Record everything;
- Enable pcap file capturing: go to Settings -> Advanced -> Low-level settings -> pref.vpn.capture;
- Reproduce the issue;
- Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file;
- Send received archive to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced;
- It would be nice if you sent FCM diagnostics screenshots as well.

**Closed** 2022-03-02 09:38 UTC
Labels: Question, Resolution: Fixed, Status: Resolved, Version: AdGuard v4.0
