### ISSUE TITLE
[Question] Why doesn't AdGuard show in the recent apps / multitasking menu?

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdguardForAndroid#1552] opened 2017-10-20 18:16 UTC
I'm not sure if it's always been this way or if it's specific to my new phone. I'm on a Pixel 2 XL with AdGuard 2.10.142.

Any time I hit the home button while being in AdGuard, or do a quick double tap to switch applications, AdGuard doesn't go into the recent apps menu. While troubleshooting app filtering issues, etc., it would be nice to do a quick double tap to go back to AdGuard l, but I instead have to re-enter from the app drawer.

The app opens where I left it, so it doesn't seem like it's being destroyed, so I am unsure why it doesn't appear there.

**Comment by Revertron** [comment] 2017-10-20 20:03
Hm, this is interesting. Nothing like that is observable on other phones or tablets...

**Comment by carlylemiii** [comment] 2017-10-20 20:16
I *thought* it was odd, but I wasn't sure!

I made a screen recording so you can see I'm not crazy :-)

https://www.dropbox.com/s/k53ic6wy9khgo0i/mobizen_20171020_151023.mp4?dl=0

**Comment by carlylemiii** [comment] 2017-10-20 20:19
Must have just been a weird quirk; I stopped and restarted AdGuard protection and now everything's fine. I'll re-open if I find rhyme or reason to this.

**Comment by OJ7** [comment] 2020-02-29 15:43
I'm still seeing this issue on v3.3.2 (230-1.5.163cl) using Galaxy S8 Android 9.

**Comment by artemiv4nov** [comment] 2020-03-12 17:39
Need to analyze this issue again.

**Comment by artemiv4nov** [comment] 2020-08-13 08:54
@OJ7 Unfortunately, I can't reproduce this issue. Also, I analyzed the Android OS behavior to show applications in recent apps. We can't change Android OS behavior. I'll close the issue.

**Closed by artemiv4nov** 2020-08-13 08:54 UTC
Labels: Compatibility, P4: Low, Waiting for repro
