### ISSUE TITLE
Cromite browser support

### ISSUE THREAD

**Issue by anuraganand-15** [AdguardTeam/AdguardForAndroid#5190] opened 2024-01-27 09:45 UTC
### Issue Details

Cromite browser is a fork of popular Bromite browser which was discontinued.
Adguard doesn't supports ad blocking in cromite while it does in bromite browser.

### Proposed solution

Please add adblocking support for Cromite browser since Bromite is discontinued.

Cromite repository can be found here : https://github.com/uazo/cromite

**Comment by Versty** [comment] 2024-01-29 12:49
@anuraganand-15 Working on Cromite support! 

Duplicate of #4997

**Closed** 2024-01-29 12:50 UTC
Labels: Feature request, Priority: P4
