### ISSUE TITLE
Mega Application android

### ISSUE THREAD

**Issue by Sergey-Lyapin** [AdguardTeam/AdguardForAndroid#3863] opened 2021-05-31 12:08 UTC
@Bhooty commented on [Fri May 21 2021](https://github.com/AdguardTeam/AdguardFilters/issues/83722)

For some reason, on my mobile (samsung note 8)
Mega App is unable to connect with adguard on
Can u check?

**Comment by Chinaski1** [comment] 2021-05-31 12:09
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/3837

**Closed** 2021-05-31 12:09 UTC
