### ISSUE TITLE
greasy fork 扩展在安卓版adguard上面失效

### ISSUE THREAD

**Issue by Renjh5218** [AdguardTeam/AdguardForAndroid#4144] opened 2022-04-16 20:44 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ Y ] I am running the latest version
- [ Y ] I checked the documentation and found no answer
- [Y ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Filtering mode:**
  - 
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by Birbber** [comment] 2022-04-18 14:18
I'm closing this one as a duplicate of [#4145](https://github.com/AdguardTeam/AdguardForAndroid/issues/4145).

**Closed** 2022-04-18 14:19 UTC
