### ISSUE TITLE
[Bug] Dns filtering doesnt work in local http proxy

### ISSUE THREAD

**Issue by ehzbtrd** [AdguardTeam/AdguardForAndroid#3791] opened 2021-03-28 10:16 UTC
I'm rooted, local proxy is turned on and private dns is turned off
dns requests appear in the filtering log as blocked but they are not really blocked
i tested the issue on multiple devices 
i'm running the latest beta but the issue seems to persistent to previous stable/beta releases too
dns filtering currently works only in the local vpn mode

**Comment by ameshkov** [comment] 2021-03-28 13:24
> dns requests appear in the filtering log as blocked but they are not really blocked

How do you check this?

What do you see when you run `nslookup ad.doubleclick.net` via `adb shell`?

**Comment by Jollfye** [comment] 2021-04-03 12:24
I have the exact same issue, tested on the latest v4.0 nightly 10 (50-1.7.188cl), reported this to Adguard support with logs and screenshots, ticket number is 1103168, hope it gets resolved.

![Screenshot_20210403-160333_Trebuchet](https://user-images.githubusercontent.com/6180818/113478217-814a4480-9498-11eb-984d-1dd2531a1463.png)

**Comment by sfionov** [comment] 2021-04-03 15:40
Can you please say what version if iptables is on your device?

`iptables --version`

**Comment by Jollfye** [comment] 2021-04-03 16:37
> Can you please say what version of iptables is on your device?
> 
> `iptables --version`

I ran the command and the result was: iptables v1.8.4 (legacy).

**Comment by sfionov** [comment] 2021-04-03 20:19
Thank you! Then it seems to be a duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/3782

**Comment by StormPooper** [comment] 2021-04-03 20:22
This has been happening to me too since upgrading my OnePlus 7 Pro to Android 11 the other day. Running the latest stable version of Adguard, working fine in local VPN mode but not in local proxy mode. Can't resolve ad.doubleclick.net in VPN mode, get an IP in proxy mode. iptables also returns `1.8.4 (legacy)`. Wasn't an issue in Android 10.

**Comment by ameshkov** [comment] 2021-04-05 15:40
Yep, it'll be resolved in v3.6.2 alongside #3782

**Closed by ameshkov** 2021-04-05 15:40 UTC

**Comment by Chinaski1** [comment] 2021-04-06 11:44
@StormPooper @Jollfye @ehzbtrd 
Hello!
Would you please email me at k.gretskyi@adguard.com, I will provide you with a build that presumably solves your issue.
