### ISSUE TITLE
DNS via SOCKS4a/SOCKS5 proxy

### ISSUE THREAD

**Issue by tsurf2017** [AdguardTeam/AdguardForAndroid#1282] opened 2017-06-14 16:42 UTC
Hello. I found that AdGuard can't route DNS queries through SOCKS4a/SOCKS5, so it causes dns leak.
I know about `pref.vpn.dns` but it isn't that I need.
Can you add this feature, please?

**Comment by vozersky** [comment] 2017-06-14 20:34
@tsurf2017 hi! you can use [DNSCrypt](https://dnscrypt.org/)

**Comment by vozersky** [comment] 2017-06-15 09:54
@tsurf2017 hi! true, that makes sense, thank you

**Comment by ameshkov** [comment] 2017-06-15 12:48
Yeah, AG is able to forward TCP traffic to SOCKS4/5 proxy, but not UDP indeed, and it's quite hard to implement technically.

Although, we're planning to add DNSCrypt support in the next major update, which should solve the issue partially.

**Comment by pou-chi** [comment] 2017-09-29 09:27
> AG is able to forward TCP traffic to SOCKS4/5 proxy
Can't find how to do that in latest beta.

**Comment by ameshkov** [comment] 2017-10-16 08:11
@pou-chi 

> Can't find how to do that in latest beta.

Sorry for the late reply. Go to Settings -> Proxy settings

**Comment by ameshkov** [comment] 2017-12-04 12:53
Duplicate of #1357

**Closed by ameshkov** 2017-12-04 12:53 UTC
Labels: enhancement, feature request, P3: Medium
