### ISSUE TITLE
AdGuard and WireGuard kernel 

### ISSUE THREAD

**Issue by mono66985** [AdguardTeam/AdguardForAndroid#4652] opened 2023-05-03 09:04 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

3.6.11

### Environment

```markdown
- OS:Android 13
- Device:Xiaomi Redmi Note 10 Pro
- Firmware:14.0.2.0
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable cache for third-party requests, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1. Running Wireguard as kernel backend

### Expected Behavior

Nothing's wrong

### Actual Behavior

1.  After connecting to WireGuard, IP changes only when AdGuard protection is turned off and on once.
2.  Internet response slows down. Internet speed doesn't seem to have much effect.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Wireguard was officially announced to support on the Android kernel and applied.

https://www.xda-developers.com/google-adds-wireguard-vpn-android-12-linux-kernel-5-4/

So if I have rooting phone, I can already use it.

If I run Wireguard as a kernel backend, I don't need VPN settings and AdGuard proxy mode. Therefore, it is possible to use AdGuard local VPN and WireGuard simultaneously. This is an official way to take advantage of all the features of VPN and AdGuard on Android. I use WireGuard and local VPN mode AdGuard at the same time without errors now. However, I hope you fix it because there is such a minor compatibility problem.

**Comment by Versty** [comment] 2023-06-13 10:23
@mono66985 Hi! 
Could you reproduce this issue using AdGuard for Android 4.0 latest beta? 
We have made a lot of tweaks in this version, so compatibility may work much better.

**Comment by mono66985** [comment] 2023-06-15 06:57
Hello.

Although I used AdGuard 4.0. However, as before, Wireguard kernel backend and AdGuard could not be used at the same time.

**Comment by TeaqariaWTF** [comment] 2023-07-22 17:40
Android 13 ArrowOS
Magisk  = Yes 
Adguard Version = 4.1.97
WireGuard version = 1.0.20230707

Adguard does not work with wireguard.

![Screenshot_20230722-180411_Cromite](https://github.com/AdguardTeam/AdguardForAndroid/assets/90970076/a6ea9e79-d0d1-4cbd-abae-ba6977d0440f)
![Screenshot_20230722-194240_AyuGram](https://github.com/AdguardTeam/AdguardForAndroid/assets/90970076/202421f0-e31f-4dc0-a6a6-6ecea27e5e86)
![Screenshot_20230722-203956_WireGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/90970076/d5a7916e-3102-4f6a-9785-0455cf0e0ad0)

**Comment by TeaqariaWTF** [comment] 2023-07-22 17:42
Android 13 ArrowOS
Büyü = Evet
Adguard Sürümü = 4.1.97
WireGuard sürümü = 1.0.20230707

Adguard does not work with wireguard.


![Screenshot_20230722-180411_Cromite](https://github.com/AdguardTeam/AdguardForAndroid/assets/90970076/5d1fe3a5-e20b-4fbf-b115-655f44150fa1)
![Screenshot_20230722-203956_WireGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/90970076/60385b49-e7cc-4363-b279-6c23a28049eb)

**Comment by sfionov** [comment] 2023-08-08 12:11
@TeaqariaWTF 

Hello! Android OS manages outgoing interface of apps. It stores separate routing tables for every network access method, and when VPN is enabled, it also create firewall rules to explicitly use some particular outgoing interface as main interface for VPN exclusions, including VPN app itself. This is done by `netd`, Android OS's network service.

So when you change routes by yourself, `netd` will not be triggered to reconfigure this rules automatically, and old rules will be in the effect for VPN app and VPN exclusions.

So you may need to turn protection off and on when this happen.

However, you may create Tasker automation to handle this.

**Comment by TeaqariaWTF** [comment] 2023-08-08 12:14
@sfionov 

I didn't understand exactly what you mean.

wireguard is enabled as a backend but cannot be used with adguard at all

**Comment by Rtizer-9** [comment] 2023-08-16 08:22
@mono66985 @TeaqariaWTF are you guys able to use both ag and Wireguard in root mode with the kernel backend or are you facing it even now?

**Comment by TeaqariaWTF** [comment] 2023-08-16 19:39
@Rtizer-9 
A new update has been released. I haven't had a chance to try it yet.

**Comment by TeaqariaWTF** [comment] 2023-08-16 21:33
@Rtizer-9 @mono66985 

Wireguard and Adguard work together with the latest beta app

![Screenshot_20230817-003048_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/90970076/edef1fea-6fc7-4040-85b7-09f0bd313c99)
![Screenshot_20230817-003022_Iceraven](https://github.com/AdguardTeam/AdguardForAndroid/assets/90970076/251e5bfe-7c57-4f62-b5ff-e10656c67218)
![Screenshot_20230817-003000_Iceraven](https://github.com/AdguardTeam/AdguardForAndroid/assets/90970076/00879af0-f4b4-4482-bc3c-d30d3e9dd611)

**Comment by Rtizer-9** [comment] 2023-08-18 16:19
@TeaqariaWTF they've been working together since the very beginning but in my case the problem happens when network connectivity changes for even 1 second.

Can you test by changing the network from wifi and mobile and vice-versa and also turning on/off both and also turning on/off both ag and Wireguard.

In my case once the connection gets established, if the network state changes by even 1 bit through the above methods, it takes 20 tries to again make them work together by toggling all settings until I get the right combination.

**Comment by driversti** [comment] 2023-08-20 17:24
After upgrading to the Android 14 Beta 5 on my Pixel 7 Pro WireGuard and AdGuard do not work simultaneously. Has someone apart from me spotted this issue?

**Comment by TeaqariaWTF** [comment] 2023-08-22 16:37
@Rtizer-9 
Yes, I can confirm, it doesn't work when the connection changes.

**Comment by Rtizer-9** [comment] 2023-08-22 16:41
@Versty

**Comment by Versty** [comment] 2023-08-24 16:32
@Rtizer-9 The behaviour when the network connectivity changes is explained in the https://github.com/AdguardTeam/AdguardForAndroid/issues/4652#issuecomment-1669494075 by our dev. 
We currently see no options to handle this case natively, probably this decision will be reconsidered later. 

> After upgrading to the Android 14 Beta 5 on my Pixel 7 Pro WireGuard and AdGuard do not work simultaneously

Highly likely could be an android beta problem.

**Closed** 2023-08-24 16:32 UTC
Labels: Bug, Priority: P4

**Comment by TeaqariaWTF** [comment] 2023-08-24 19:27
@Versty 

This problem exists not only on Android 14 but also on 12 and 13.

**Comment by steupz** [comment] 2023-10-20 09:09
This issue continues with the latest nightlies and updated wireguard client. The workaroubd still works

**Comment by Rtizer-9** [comment] 2023-10-20 09:33
Ag (vpn mode) is working for me with Wireguard kernel mode with 95% stability and regarding IP I think it's quite normal to have that issue since we're trying to use 2 completely different software trying to take control of the same things together.

AG's dns protection and some low level configs and Wireguard's own "allowed ip" and "dns servers" and the iptables created by both of them are bound to create conflicts when used together. As mentioned above the workaround still works. We just need to turn ag once off and on.

**Comment by driversti** [comment] 2023-10-22 15:12
> Highly likely could be an android beta problem.

My phone is running the latest stable version of Android 14, and the issue still exists. I've stopped AdGuard, cleaned all its data, and activated it without any custom changes. No luck.
Can you please set up a temp WireGuard server, a peer (Android 14), and AdGuard? It should help to investigate the issue.
BTW, I have 3 lifetime licenses (26 devices in total) and 2-y AdGuard VPN subscription. Your service is very crucial to me.
Without simultaneous usage of WireGuard and AdGuard, I can't access my home network, servers, and apps, which are all connected via WireGuard. Every time I have to choose: WireGuard or AdGuard.

**Comment by TeaqariaWTF** [comment] 2023-10-25 21:02
I think the only solution is to have a rooted version of Adguard.Like Adaway.

I wonder if this is possible
@Rtizer-9

**Comment by Rtizer-9** [comment] 2023-10-26 04:05
@TeaqariaWTF as I've mentioned above, I'm able use to ag with Wireguard with almost 95% features working as expected so I'm not having any issues.

I'm using ag vpn mode because automatic proxy mode can't filter UDP and thereby http3 doesn't work.

In my setup the leftover spaces of ads aren't also removed when I use Wireguard, other than that almost everything is working.

**Comment by Rtizer-9** [comment] 2023-11-27 15:37
Is there anybody in this thread for whom both ag and Wireguard works simultaneously and even cosmetic filtering works.

The filtering log of ag should show apps icon with html elements and not just domains which is what happening for me with ag and Wireguard regardless of the vpn/root mode for both ag and Wireguard.

It seems like, with Wireguard turned on ag only sees dns requests.
