### ISSUE TITLE
AdGuard v4.0 Nightly - Degradation comparing to v3.x - in a Log entry, tap the app name - nothing happens

### ISSUE THREAD

**Issue by SergeiShir** [AdguardTeam/AdguardForAndroid#4444] opened 2023-02-08 19:25 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0 Nightly 41 (4.0.565)

### Environment

```markdown
- OS: Stock Android 13 (SDK: 33)
- Device: Stock Pixel 6 (oriole)
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, AdGuard Experimental filter, EasyList, EasyList Hebrew, Online Malicious URL Blocklist

### What Stealth Mode options do you have enabled?

Strip URLs of tracking parameters, Self-destruction of third-party cookies, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Remove X-client-Data header from HTTP request

### Issue Details

Steps to reproduce:
1. Open the Log
2. Tap an entry
3. At the top, tap the app name

### Expected Behavior

In versions 3.X, after tapping the app name at the top of a log entry, a page opened with settings that apply only to this specific app

### Actual Behavior

In version 4.0 Nightly, **nothing** happens when tapping the app name at the top of a log entry

**Comment by maxikuzmin** [comment] 2023-02-14 18:36
@SergeiShir thank you! We are already doing it
Duplicate of #4427 
If you notice anything else, be sure to open a new issue :)

**Closed by maxikuzmin** 2023-02-14 18:36 UTC
