### ISSUE TITLE
Moovit app is not compatible with HTTPs filtering

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#492] opened 2016-04-25 13:55 UTC
https://play.google.com/store/apps/details?id=com.tranzmate&hl=ru

I'm using the current beta 2.5.173 for Android. The app "Moovit" doesn't work with HTTPS filtering, it constantly reports "Network connection errors" then. I found that out only after a long trial & error session with different option combinations.

By adding the package name (com.tranzmate) to the app whitelist within in the HTTPS settings it worked perfectly.

**Comment by Revertron** [comment] 2016-04-26 15:04
I need full log!

**Comment by ameshkov** [comment] 2016-04-26 15:34
@Revertron i am pretty sure the issue is again linked to your geo location.

Let's just add it to whitelist for now (until we get the log).

**Comment by Revertron** [comment] 2016-04-26 15:42
Added it to ssl app exceptions, moving to 2.6 milestone until we get the logs.

**Comment by engelhro** [comment] 2016-05-11 21:29
May I ask (as I originally opened the ticket with the problem description via the AdGuard website): from whom do you expect the log? What kind of logs? I'm just a regular user of your app (and the Moovit app) which reported the issue, but I don't know how to proceed here and whether you actually expect something?

Thanks for clarification!

**Comment by ameshkov** [comment] 2016-05-15 16:01
@engelhro in fact I have asked @evgeniy-ADG to ask you to record the log:)

Here is an instruction on how to do it:
https://kb.adguard.com/index.php?/Knowledgebase/Article/View/49/9/collecting-a-full-log-on-adguard-for-android

**Comment by engelhro** [comment] 2016-05-16 16:58
Ah, thanks for the info! Unfortunately I cannot reproduce the problem currently – I've removed the whitelist entry again, but the app (Moovit) still works as before!? I'm confused, because it took me some effort recently to identify the problem recently and trace it back to Adguard…

I'll see whether the problem reappears in the next few days and will give you feedback then. Can we leave the issue open until then? Thanks!

**Comment by ameshkov** [comment] 2016-05-18 17:17
> I'll see whether the problem reappears in the next few days and will give you feedback then. Can we leave the issue open until then? Thanks!

Yep, no problem:)

**Closed** 2016-07-14 14:05 UTC
Labels: Cannot Reproduce, Compatibility, SSL, Waiting For Data
