### ISSUE TITLE
com.google.android.apps.photos - backup issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2955] opened 2019-07-25 13:00 UTC
@adguard-bot commented on [Sat Jun 22 2019](https://github.com/AdguardTeam/AdguardFilters/issues/35645)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.google.android.apps.photos](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.google.android.apps.photos)
### Comment
> Adguard is causing some sort of problem with the Google Photos backup process. I need to turn off Adguard for Google Photos to be able to upload pictures to the cloud.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/hOmcGd6.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/WghuOrW.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9
AdGuard version: | v3.1.0 (1.3.347cl)
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Block third-party Authorization header, Self-destructing third-party cookies (180), Disable cache for third-party requests
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | AdGuard Mobile Ads,<br>AdGuard Annoyances,<br>AdGuard Base,<br>AdGuard Tracking Protection,<br>AdGuard Social Media,<br>AdGuard Spanish/Portuguese

**Comment by admitrevskiy** [comment] 2019-07-29 05:48
Cannot reproduce the issue

**Comment by ameshkov** [comment] 2019-08-01 20:57
Cannot repro as well. Advise user to disable filtering for this app

**Comment by TPS** [comment] 2019-12-17 11:22
I'm still having this issue myself, & have a useful screenshot:
![Screenshot_20191217-061247](https://user-images.githubusercontent.com/185902/70991393-5feffa00-2095-11ea-97e1-aaeb83ddf6ed.png)
Is there anyway to disable *all* blocking when whitelisting an app⁈

**Comment by sfionov** [comment] 2019-12-17 11:46
@TPS At this time, it is blocked unconditionally.
This will be changed when we implement HTTP/3 filtering.

**Comment by TPS** [comment] 2019-12-17 12:08
If so, can this be reopened, pending that &/or matching that milestone?

**Comment by TPS** [comment] 2019-12-22 17:12
Also, is it too much to hope that _optional_ passthrough in such circumstances could be sooner available?

**Comment by TPS** [comment] 2019-12-23 12:09
@artemiv4nov Given the <kbd>Waiting for data</kbd> label you've just added, is there anything else _I_ can provide?  Also, given this breaks functionality, I'm unsure that <kbd>Enhancement</kbd> is _quite_ right.…

**Comment by ameshkov** [comment] 2019-12-25 15:25
We cannot reproduce this issue on our side, and tbh, I really doubt it has anything to do with QUIC.

@sfionov do $network rules take precedence? We could try test it by adding smth like this:
`@@[2607$network,app=com.google.android.apps.photos`

**Comment by TPS** [comment] 2019-12-25 16:54
Give me a set of instructions of how to test a potential workaround (since I _am_ affected), & I'll report back. E.g., ifF that `$network` rule could work, lemme know. 🙇🏾‍♂️

**Comment by TPS** [comment] 2019-12-25 19:14
>We cannot reproduce this issue on our side, and tbh, I really doubt it has anything to do with QUIC

@ameshkov Do you test the Google apps against their "testing" (beta) versions, or only  current releases?  I signup for _every_ testing version I can, & all the last few weeks' updates have used _significantly_ more QUIC (as noted blocked via live AG log) than before, & I'm noticing a correlation to more GApps breakage (YT, Drive, Play Services, Store, &c, @ least intermittently) so I suspect Google's about to flip a big switch on protocols for their services.

**Comment by ameshkov** [comment] 2019-12-25 20:33
Try adding this rule exactly to the usser filter:
`@@[2607$network,app=com.google.android.apps.photos`

> Do y'all test the Google apps against their "testing" (beta) versions, or only current releases?

Tbh, we tested only releases

**Comment by ameshkov** [comment] 2019-12-25 20:34
> so I suspect Google's about to flip a big switch on protocols for their services.

They can't make it QUIC-only. UDP is unreliable and blocked in many networks so they must have a fallback.

**Comment by TPS** [comment] 2019-12-25 22:19
It's _Google_.…  They virtually forced [HTTP/2](https://en.m.wikipedia.org/wiki/HTTP/2) onto the 'Net.  D'y'all _really_ think they'll have much trouble w/ [HTTP/3](https://en.m.wikipedia.org/wiki/HTTP/3)?

I'll try that rule a little while & report back.

**Comment by TPS** [comment] 2019-12-25 22:23
Huh, it's still blocking QUIC for Photos.…  Does adblocking need to re-enabled on the app for the rule to be applied?

**Comment by ameshkov** [comment] 2019-12-26 09:19
@TPS yeah, most likely it does:)

**Comment by ameshkov** [comment] 2019-12-26 09:20
> It's Google.… They virtually forced HTTP/2 onto the 'Net. D'y'all really think they'll have much trouble w/ HTTP/3?

Well, HTTP/2 still falls back to HTTP/1 if unavailable. The same is true for HTTP/3.

**Comment by TPS** [comment] 2019-12-28 13:06
Using the filter rule above, QUIC is _still_ blocked for Photos.

**Comment by TPS** [comment] 2020-01-05 06:50
> They can't make it QUIC-only. UDP is unreliable and blocked in many networks so they must have a fallback.

> Well, HTTP/2 still falls back to HTTP/1 if unavailable. The same is true for HTTP/3.

All I can currently report (watching the AG filtering log live) is that now most of my GApps aren't failing over from QUIC|HTTP/3 (blocked, per log) back to something older.…  They're just failing _outright_: no further request attempted, other than a successful check to https://connectivitycheck.gstatic.com most of the time after such QUIC failures.

___Disabling AG solves it immediately.___ All GApps that were previously failing thereafter  Just Work.

**Comment by ameshkov** [comment] 2020-01-09 17:27
@TPS quick question -- what if you clear the app data for AdGuard (e.g. reset it to default settings). Does it change anything?

**Comment by TPS** [comment] 2020-01-09 17:48
@ameshkov 🤯 Yes, it does.  It works precisely as you describe — `quic` connection fails, then pulls DNS & falls back to normal HTTPS — which I'd _never_ seen before.

I'll investigate further.  Meanwhile, which offline channel should I submit my backed-up settings? (My β-testing license is still in there, else I'd post here.)

**Comment by ameshkov** [comment] 2020-01-09 17:53
> which offline channel

offline? Not sure USPS would accept your backup :)

Try `devteam@adguard.com`, but please mention this Github issue in the text.

**Comment by TPS** [comment] 2020-01-10 03:24
Sent.  Do lemme know if y'all find anything. 🙇🏾‍♂️

**Comment by ameshkov** [comment] 2020-01-10 07:44
@artemiv4nov settings backup is in our nextcloud instance

**Comment by d0x360** [comment] 2022-05-14 20:15
I have a similar issue but instead photos it's with Google One system backup & Samsung Cloud backup

**Comment by artemiv4nov** [comment] 2023-10-14 12:29
A similar problem with other Google apps has been resolved in the 4.0 version, please try it.

**Closed** 2023-10-14 12:29 UTC
Labels: Enhancement, Waiting for data, Cannot reproduce, Resolution: Fixed, Status: Resolved, Priority: P4
