### ISSUE TITLE
Adguard Android and Flipp Flyer Loading Times

### ISSUE THREAD

**Issue by pkyee** [AdguardTeam/AdguardForAndroid#4014] opened 2021-10-31 15:42 UTC
I continue to have the issue that is described in #97 and #98 when using the Android Flipp App. It takes 30-60s to load any flyer. 

I have added flipp.com, f.wishabi, f.wishabi.net, adn wishabi.net under the Allowlist. I also have DNS filters where I am only using OISD but have added @@IIflipp.com, @@||wishabi.net and  @@||f.wishabi^. I have tried switching the DNS server which does not seem to make a difference either. If I chose to not route the application through Adguard the same issue persists. If I pause Adguard then load one flyer, then resume Adguard, all future flyers seem to load properly for a variable duration of time before recurrence of the above issue.

### Steps to reproduce
1. Adguard with no Ad blocking filters on. DNS filtering with AdGuard DNS and OISD basic filter.
2. Allowlist and DNS user rules as above.
3. Flipp application, loads initial flyers to browse, but opening any flyer takes a long period of time.
4. Pausing Adguard allows for loading of flyers, then resuming lets flyers load normally for a variable duration of time.

### Expected behavior
Using the recommended Allow list or white list, flyers should load quickly. Or, if not routing any traffic through Adguard or ad blocking, the flyers should just load normally.

### Actual behavior
Persistent or recurrent prolonged loading times for flyers.

### Your environment
Pixel 4a, Android 11 and the most recent Adguard. Issue exists on different wifi networks and mobile data.

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Adguard
| Device model:| (e.g. Google Pixel) Pixel 4a
| Operating system and version:| Android 11

**Comment by pkyee** [comment] 2021-11-01 10:10
@Birbber Full package name I believe is: com.wishabi.flipp.

**Comment by Birbber** [comment] 2021-11-02 09:24
@pkyee We couldn't reproduce the issue on our end. Could you send us your settings on devteam@adguard.com? 
In order to do that go to **Settings** --> **General** --> **Export settings** and send the exported file to us.

**Comment by pkyee** [comment] 2021-11-02 09:53
@Birbber Attached current settings here.
[adguard_settings_3.6.32_0111_164349.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/7459582/adguard_settings_3.6.32_0111_164349.zip)
.

**Comment by Birbber** [comment] 2021-11-02 09:55
@pkyee Thanks, will try this out.

**Comment by Birbber** [comment] 2021-11-02 10:30
@pkyee Tried with your settings and saw no significant difference. What I've notice is that some flyers take more time to load than others (like 20 seconds), but it doesn't matter if AdGuard is on or off.

Lets see the application logs. Could you record them for us?
Here's how to do it:
- In AdGuard head to Settings → Advanced → Logging level → Record everything
- Reproduce the issue and remember the time when it happened
- Head back to Settings → Advanced → Export logs and system info
- Save an archive, send it to us and tell the time the issue happened
- Set the logging level back to Default

**Comment by pkyee** [comment] 2021-11-02 10:38
Thank you, for me the ads notably load faster without Adguard (5 seconds or so), whereas with it on can take 30 seconds +. Right now everything is working for me (for some odd reason after pausing Adguard and loading one flyer, then restarting Adguard it will work for some variable amount of time). Will try the logging when it reoccurs.

**Comment by Birbber** [comment] 2021-11-02 10:52
Sure, will be waiting.

**Comment by pkyee** [comment] 2021-11-02 10:59
From your initial settings are there filters/DNS that you would recommend or anything I should have had on the whitelist or allow list? I may try doing another install after getting the logs to try on my device to see if the issue persists.

**Comment by Birbber** [comment] 2021-11-02 11:37
I don't think we can suggest anything before seeing the logs in this case. 
Usually AdGuard DNS filter covers most of the situations. When you add some heavy DNS filters (around 30 MB or so), it might cause issues, so it's not recommended.

**Comment by pkyee** [comment] 2021-11-03 10:58
Attached logs below, timing was between 06:46 - 06:48.
[adguard_logs_3.6.32_0311_064901.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/7467043/adguard_logs_3.6.32_0311_064901.zip)

**Comment by Birbber** [comment] 2021-11-08 14:44
@pkyee Sorry for the long wait.
Have you tried disabling filtering for this application? (In Apps Management choose the app and turn the "AdGuard protection" switch off). That should speed up the loading in your case.

**Comment by pkyee** [comment] 2021-11-08 15:02
Yes I have tried this, routing through Adguard but not filtering which unfortunately does not change too much. Will give it another try though!

**Comment by pkyee** [comment] 2021-11-10 11:25
@Birbber Is there any other way to completely whitelist the Flipp app from any ad blocking?

**Comment by Birbber** [comment] 2021-11-10 11:46
@pkyee Try this: go to Settings --> Advanced --> Low Level settings --> pref.excluded.packages --> Add "com.wishabi.flipp" and lets us know the result.

**Comment by Birbber** [comment] 2021-11-22 08:03
@pkyee Did it help?

**Comment by pkyee** [comment] 2021-11-22 10:34
@Birbber unfortunately no changes in the end, I usually just pause Adguard and restart after using the app instead!

**Comment by artemiv4nov** [comment] 2021-11-24 18:02
@pkyee Hi!
Are you sure you changed the "pref.excluded.packages" setting corectly?
The app's traffic even doesn't route to AdGuard in that case, and it's so strange you didn't see any changes

**Comment by pkyee** [comment] 2021-11-24 18:05
@artemiv4nov I think I did but happy to try this again, could you confirm the settings that I should enter for that section?

**Comment by artemiv4nov** [comment] 2021-11-24 18:10
Ok. So, please go to Settings --> Advanced --> Low Level settings --> pref.excluded.packages --> Add "com.wishabi.flipp" on the new line.
After this, please re-check an issue and write the debug logs and send them to devteam@adguard.com

**Comment by pkyee** [comment] 2021-11-24 23:56
Tried the suggestion above with no luck, thank you though! I am fine with the current work around with just turning Adguard off when using the app.

**Comment by artemiv4nov** [comment] 2021-12-14 10:48
All right. I will close this task. If your workaround solution will cease to satisfy you, please re-open the job.

**Closed** 2021-12-14 10:48 UTC
