### ISSUE TITLE
Random restarts when using VPN mode 

### ISSUE THREAD

**Issue by loca-lhost** [AdguardTeam/AdguardForAndroid#4456] opened 2023-02-12 02:28 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.590

### Environment

```markdown
- OS:Android 12
- Device:Note 11 Pro 5G
- Firmware:MIUI 13.0.5.0
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter

### Issue Details

Steps to reproduce:
1.
2.
3.

### Actual Behavior

VPN randomly restarts.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment] 2023-02-15 18:34
@loca-lhost could you be more specific, are crashes caused by AdGuard?
Please clarify, what are the steps to reproduce the problem?
Also, what version of AdGuard VPN are you using?

**Comment by loca-lhost** [comment] 2023-02-15 19:14
Been using adguard in vpn mode and set it as always on vpn. That is how I see these crashes and restarts. It's so random. I can send logs to see if they can be resolved.

**Comment by jwds1178** [comment] 2023-02-17 02:33
I've noticed this behaviour myself.

I have a Tasker profile that automagically restarts AdGuard.  I've noticed that AdGuard intermittently, with some frequency, is being restarted by Tasker to keep it running.

Offhand, I'm not exactly sure with which build/version I noticed this start happening.  I've not noticed any specifically reproducible pattern to cause it.  But, it does happen with a seemingly random frequency though.

**Comment by maxikuzmin** [comment] 2023-02-17 17:56
@loca-lhost yes, please.
Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment] 2023-02-20 18:58
@loca-lhost any news?

**Comment by loca-lhost** [comment] 2023-02-21 17:07
I have submitted some logs yesterday and today!

**Comment by maxikuzmin** [comment] 2023-02-27 17:50
@loca-lhost thank you! We'll look at your logs, we need some time

**Comment by loca-lhost** [comment] 2023-02-28 08:53
I have further observed that I can't put adguard in no restrictions mode. It defaults back to battery saver mode all the time. All other apps can be changed except adguard.

**Comment by maxikuzmin** [comment] 2023-04-03 09:01
@loca-lhost is the problem still recurring? Can I ask you to email your settings to devteam@adguard.com?
You need to go to the Settings tab and in the context menu (in the upper right corner) click "Export settings"

**Comment by loca-lhost** [comment] 2023-04-04 04:30
I have emailed it. Issue still occurs!

**Comment by maxikuzmin** [comment] 2023-04-10 10:14
@loca-lhost I don't see your settings in our mail. Did you send your settings to [devteam@adguard.com](mailto:devteam@adguard.com)? Is this also repeated on the last nightly version 83?

**Comment by loca-lhost** [comment] 2023-04-13 08:14
I have enabled it. A crash happened one time. But it's being stable for now. I will keep monitoring

**Comment by maxikuzmin** [comment] 2023-04-17 09:34
@loca-lhost ok, let me know when it happens again and you send a bug report

**Comment by loca-lhost** [comment] 2023-04-19 12:16
It's been crashing again... Randomly

**Comment by maxikuzmin** [comment] 2023-04-26 16:40
@loca-lhost I apologize for the long reply. It would be nice, if when the crash happens again, you could remember the time and post it here so we can track the bug report. You have "Automatic crash reporting" enabled, right?

**Comment by loca-lhost** [comment] 2023-04-26 16:45
I think it's due to my device defaulting adguard back to battery optimization mode Even if i choose other no restriction. Honestly I have no idea why it does that. Other apps works fine though! Will try and use adb to set the option and revert!

**Comment by maxikuzmin** [comment] 2023-04-26 17:22
@loca-lhost okay, let me know about the result

**Comment by loca-lhost** [comment] 2023-04-26 17:32
> @loca-lhost okay, let me know about the result

Using adb to change battery optimization revert is back to battery saver! Am using a xiaomi.eu rom.

**Comment by maxikuzmin** [comment] 2023-05-11 14:21
@loca-lhost any news?

**Comment by maxikuzmin** [comment] 2023-05-17 16:59
@loca-lhost we didn't find any reports sent from you. Did you send from kabamfo mail?
If it happens again, could you send the report again and write the approximate time here?

**Comment by loca-lhost** [comment] 2023-05-19 13:22
![adguard_logs_4.0.853_1905_131658.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/11517275/adguard_logs_4.0.853_1905_131658.zip)

Restart occurred at 11:40 AM.

**Comment by maxikuzmin** [comment] 2023-05-23 12:46
@loca-lhost you have "Automatic crash reporting" enabled, right? We will check if the crash report was sent at 11:40

**Comment by maxikuzmin** [comment] 2023-06-01 14:56
@loca-lhost any news?

**Comment by loca-lhost** [comment] 2023-06-02 03:26
Sending additional logs and time of crash

**Comment by maxikuzmin** [comment] 2023-06-09 17:13
@loca-lhost we'll check it out

**Comment by maxikuzmin** [comment] 2023-06-21 11:06
@loca-lhost please check this on the latest nightly version. Is it still repeating? 
If it repeats, please also write down and send us the time of the repetition so that we can track your report

**Comment by loca-lhost** [comment] 2023-06-21 18:33
> @loca-lhost please check this on the latest nightly version. Is it still repeating? If it repeats, please also write down and send us the time of the repetition so that we can track your report
[adguard_logs_4.1.16_2106_170832.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/11822384/adguard_logs_4.1.16_2106_170832.zip)
Time of crash is 5:04

**Comment by maxikuzmin** [comment] 2023-06-26 13:45
@loca-lhost could you clarify what you mean by "Crashes"? Do you mean restarting the application? Or is it that the protection turns itself off?

**Comment by loca-lhost** [comment] 2023-06-26 13:58
> @loca-lhost could you clarify what you mean by "Crashes"? Do you mean restarting the application? Or is it that the protection turns itself off?

Random restarts

**Comment by maxikuzmin** [comment] 2023-06-26 15:11
@loca-lhost we are looking into the cause of restarts, there are already some similar problems

**Comment by maxikuzmin** [comment] 2023-06-28 08:17
@loca-lhost after a restart, does the protection come back on?

We already discussed a similar topic about protection restarts [here](https://github.com/AdguardTeam/AdguardForAndroid/issues/4510)

The protection can restart due to a variety of reasons for working "under the hood" or changing any settings. This can happen, for example, due to changes in settings, network changes, filter updates and many other reasons

**Comment by loca-lhost** [comment] 2023-06-28 08:34
> @loca-lhost after a restart, does the protection come back on?
> 
> We already discussed a similar topic about protection restarts [here](https://github.com/AdguardTeam/AdguardForAndroid/issues/4510)
> 
> The protection can restart due to a variety of reasons for working "under the hood" or changing any settings. This can happen, for example, due to changes in settings, network changes, filter updates and many other reasons

Yes protection turns back on. It's not due filter updates or network changes.

**Comment by maxikuzmin** [comment] 2023-06-30 14:26
@loca-lhost then I suggest closing your issue as a duplicate, and dialog in another issue https://github.com/AdguardTeam/AdguardForAndroid/issues/4707
There are many users with the same question, it will improve communication

**Closed by maxikuzmin** 2023-06-30 14:26 UTC
Labels: Priority: P4
