### ISSUE TITLE
Adguard temporarily shows windows in places where ads were removed

### ISSUE THREAD

**Issue by U0101100** [AdguardTeam/AdguardForAndroid#4236] opened 2022-09-05 17:07 UTC
[adguard_logs_4.0.79_0509_185655.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/9491381/adguard_logs_4.0.79_0509_185655.zip)
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Filtering mode:**
  - 
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by maxikuzmin** [comment] 2022-09-06 15:54
@U0101100 "Adguard temporary showing windows with: the adv is blocked in that site, in places where ads were removed, in the size of the ad.Chrome application version 104.0.5112.97 Android 12 operating system; SM-N975F Build / SP1A.210812.016"

What actions do you perform before you see the problem? Could you reproduce the actions, and take a screenshot of your problem? We need to understand what you are seeing and under what conditions.

**Comment by maxikuzmin** [comment] 2022-09-12 11:55
@U0101100 any news?

**Comment by maxikuzmin** [comment] 2022-09-13 13:38
@U0101100 I am closing the issue. If the issue is relevant in the future, you can reopen the issue

**Closed by maxikuzmin** 2022-09-13 13:38 UTC
