### ISSUE TITLE
Unable to set the value in settings (stealth-mode)

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2788] opened 2019-06-10 19:44 UTC
It is unable to set the value in settings in Stealth mode. (See attachments)

Also, the value menu always requires a "domain name" field to fill.

### Steps to reproduce

1. Open AdGuard
2. Go to Settings - Stealth mode - TTL of third-party cookies / TTL of first-party cookies
3. Try to set the value to 160

<details><summary>Screenshots:</summary>

![img](https://uploads.adguard.com/TheHasagi09r0t.jpg)

![img](https://uploads.adguard.com/TheHasagiemefy.jpg)

</details>

### Your environment

* Adguard version:  3.1.10n (1.4.13cl)
* Adguard filtering mode: Local VPN
* Device model: Google Pixel
* Operating system and version: Android 10 (Q)

**Comment by admitrevskiy** [comment] 2019-06-20 13:07
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/2808

**Closed** 2019-07-20 14:30 UTC
Labels: Bug, P2: High
