### ISSUE TITLE
Norton 360 doesn't trust AdGuard certificate

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardForAndroid#4447] opened 2023-02-09 08:35 UTC
@adguard-bot commented on [Thu Feb 09 2023](https://github.com/AdguardTeam/AdguardFilters/issues/142394)

### Issue URL (Annoyance)
 [http://www.etnow.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Fwww.etnow.com)

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/tQ17yYK.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v3.6.11+(54)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Self-destructing first-party cookies (0), <br>Self-destructing third-party cookies (0), <br>Block WebRTC, <br>Block Location API
DNS filtering: | server: `https://family.adguard-dns.com/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>EasyList, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>Peter Lowe's Blocklist, <br/>Legitimate URL Shortener, <br/>Fanboy's Anti-Facebook List, <br/>Fanboy's Anti-thirdparty Fonts, <br/>Fanboy's Enhanced Tracking List, <br/>AdGuard URL Tracking, <br/>EasyPrivacy, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>Fanboy's Annoyances, <br/>AdGuard Popups, <br/>Adblock Warning Removal List, <br/>AdGuard Other Annoyances, <br/>AdGuard Widgets, <br/>I don't care about cookies, <br/>AdGuard Annoyances, <br/>AdGuard Cookie Notices, <br/>Dandelion Sprout's Annoyances List, <br/>Web Annoyances Ultralist, <br/>EasyList Cookie List, <br/>AdGuard Mobile App Banners<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/>Filter unblocking search ads and self-promotion, <br/>AdGuard Experimental, <br/>AdGuard DNS<br/><br/><details><summary><b>Language-specific:</b></summary>EasyList Italy, <br/>ABPindo, <br/>Greek AdBlock Filter, <br/>EasyList Germany, <br/>Xfiles, <br/>Polish Annoyances Filters, <br/>YousList, <br/>EasyList Dutch, <br/>xinggsf, <br/>road-block, <br/>IndianList, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>ROLIST2, <br/>Hungarian, <br/>EasyList Spanish, <br/>Icelandic ABP List, <br/>AdGuard Turkish, <br/>AdGuard French, <br/>AdGuard Chinese, <br/>Bulgarian list, <br/>ABPVN List, <br/>AdGuard Dutch, <br/>Persian Blocker, <br/>EasyList Czech and Slovak, <br/>Dandelion Sprout's Serbo-Croatian List, <br/>AlleBlock, <br/>EasyList China, <br/>Polish Anti-Annoying Special Supplement, <br/>AdGuard Spanish/Portuguese, <br/>AdBlockID, <br/>CJX's Annoyances List, <br/>EasyList Thailand, <br/>Frellwit's Swedish Filter, <br/>Polish GDPR-Cookies Filters, <br/>Polish Anti Adblock Filters, <br/>Adblock List for Finland, <br/>EasyList Lithuania, <br/>KAD - Anti-Scam, <br/>Latvian List, <br/>EasyList Hebrew, <br/>Liste FR, <br/>ADgk Mobile China list, <br/>Liste AR, <br/>ROList, <br/>RU AdList: Counters, <br/>AdGuard Japanese, <br/>Estonian List, <br/>AdGuard German, <br/>Polish Social Filters, <br/>EasyList Polish, <br/>Dandelion Sprout's Nordic Filters, <br/>AdGuard Russian, <br/>List-KR</details>
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js,<br>https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js
Other extensions used: | Norton 360

---

@zloyden commented on [Thu Feb 09 2023](https://github.com/AdguardTeam/AdguardFilters/issues/142394#issuecomment-1423816635)

I don't see that on the site.

**Comment by maxikuzmin** [comment] 2023-02-14 18:16
@zloyden in the screenshot I see a notification that the Norton 360 app does not trust our certificate. The problem is that when running the two apps: Norton 360 VPN and AdGuard the site does not open or the browser does not work completely?
Please give me more information

**Comment by zloyden** [comment] 2023-02-15 06:13
> The problem is that when running the two apps: Norton 360 VPN and AdGuard the site does not open or the browser does not work completely?

@maxikuzmin It can be, but I don't know. I'm not the original reporter.

**Comment by maxikuzmin** [comment] 2023-02-15 16:03
@zloyden unfortunately, I need more context. Browser version, Norton apps, also Norton has quite a few products that are also usually on board the device.
Can you clarify this with the user?

**Comment by zloyden** [comment] 2023-02-16 06:25
@maxikuzmin I left a message in the original task. Unfortunately, the user did not leave the github name.

**Comment by maxikuzmin** [comment] 2023-02-16 17:32
@zloyden this is pity( 
then I will close the issue. If the user makes himself known again, please reopen the issue

**Closed by maxikuzmin** 2023-02-16 17:32 UTC
