### ISSUE TITLE
When Android system language is Chinese (or Portuguese), auto detection for AG's language interface is failed.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#2684] opened 2019-04-07 06:42 UTC
In now situation, the setup wizard is English after first time of installation.
But translators actually have translated the setup wizard.

Please show language selection and then go to the setup wizard after first time of installation.
Or AG will automatically detect Android system language and show the translated setup wizard.

**Comment by ameshkov** [comment] 2019-04-07 19:20
> Or AG will automatically detect Android system language and show the translated setup wizard.

Well, AG does detect the Android system language and show the translated wizard, how else could it be.

> In now situation, the setup wizard is English after first time of installation.
> But translators actually have translated the setup wizard.

I cannot reproduce this

**Comment by sfionov** [comment] 2019-04-07 22:49
May be related to https://github.com/AdguardTeam/AdguardForAndroid/issues/2651

**Comment by lancelot-moon** [comment] 2019-04-08 01:18
@ameshkov 

Try to switch your Android system language to Traditional Chinese.

I think @sfionov may be right.
There is a bug there.

> Currently it is a problem only for Chinese and Portuguese locales.

1. When Android system language is Traditional Chinese, the initial setup wizard is English.
2. When Android system language is Traditional Chinese, AG app shows the system language is English.

**Comment by lancelot-moon** [comment] 2019-04-08 06:07
@northis
@Stillness-2

May you check if AG for Windows/Mac has the same issue.

I mean AG for PC may not normally detect system language so that the setup wizard is English, not localized.

**Comment by TheHasagi** [comment] 2019-04-08 13:18
Successfully reproduced.

**Comment by ameshkov** [comment] 2019-04-08 17:59
Reassigned to v3.1

**Comment by lancelot-moon** [comment] 2019-05-01 04:37
@artemiv4nov 

@sfionov is correct.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2651

**This is fixed in v3.0.344η.**

a. When Android system language is Traditional Chinese (zh-TW), the initial setup wizard is Traditional Chinese.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/VzTS3tg.png)

![image](https://i.imgur.com/bxzciMp.png)

![image](https://i.imgur.com/rKtvHBa.png)

![image](https://i.imgur.com/fN3pf4K.png)
</details><br/>

b & c. After my first time of installation, AG app automatically sets **system (Traditional Chinese)** as its language interface.
When Android system language is Traditional Chinese, old AG app wrongly showed system (English).
But AG v3.0.344η can correctly show 系統 (繁體中文) = system (Traditional Chinese) .
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/qQXw7ZY.png)
</details><br/>

d. The blocking page can be Traditional Chinese in v3.0.344η.
Well, I ever requested to update the translations of blocking page.
https://github.com/AdguardTeam/CoreLibs/issues/805
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Bw5HIVV.png)
</details><br/>

**Closed** 2019-05-29 09:25 UTC
Labels: Bug, Localization, P3: Medium, UI
