### ISSUE TITLE
AdGuard blocks apps from accessing internet for ~10 seconds

### ISSUE THREAD

**Issue by infinitewaveparticle** [AdguardTeam/AdguardForAndroid#3560] opened 2020-08-30 02:24 UTC
Issue Details

- **AdGuard version:**
  -  4.0 Nightly 1*
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Kindle Fire HD 10 7th Edition
- **Operating system and version:**
  -  Android 5.1.1
- **Root access:**
  -  No

*Note: This bug has been happening for a very long time and in several previous versions.

### Expected Behavior

AdGuard should allow apps to make successful connections when the internet connection is on and no settings are blocking the connections.

### Actual Behavior

Immediately after turning the internet connection on any app that is waiting to auto-update (antivirus, weather, etc) has its connections blocked for roughly 10 seconds or so. Only then can they successfully connect. The DNS connections are successful, but the data connections are blocked for no reason given in the Filtering Log (and listed as blocked tcp connections to IP addresses/ports).

### Screenshots

<details><summary>Screenshot:</summary>
![blockedTrafficBug1](https://user-images.githubusercontent.com/29090831/91649814-f4dd2c80-ea45-11ea-80d2-922bb96330ce.jpg)

![blockedTrafficBug1a](https://user-images.githubusercontent.com/29090831/91649827-1dfdbd00-ea46-11ea-9c21-c632e7402b7d.jpg)

![blockedTrafficBug2](https://user-images.githubusercontent.com/29090831/91649834-25bd6180-ea46-11ea-954f-84cad14b9070.jpg)

![blockedTrafficBug2a](https://user-images.githubusercontent.com/29090831/91649839-2fdf6000-ea46-11ea-8f07-533737475078.jpg)

</details>

### Additional Information

I have logs saved for this happening. Just let me know where to send them. Also, for some reason, in Github Issues there is no reply option for me... so this may be the only post I can make on this thread. I will try a different browser next time because I'm not allowed to reply to my own threads either.

**Comment by TheHasagi** [comment] 2020-09-01 10:39
@infinitewaveparticle 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Chinaski1** [comment] 2020-09-22 10:18
Since the user does not answer and the issue is not reproduced on our side.
I’m closing the task, If more information is provided, I will reopen it.

**Closed by Chinaski1** 2020-09-22 10:18 UTC
