### ISSUE TITLE
"Add new rule" button is missing in user filter 

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1302] opened 2017-06-28 17:13 UTC
Adguard beta 2.9.132

There is no 'plus' badge to add new rule when rules are already exist in UF
expected result: <details>
![screenshot_2017-06-28-20-10-20-894_com adguard android](https://user-images.githubusercontent.com/23637588/27650591-0cfc39a8-5c3e-11e7-91d4-38921f601c17.png)

</details>

actual result: 
<details>

![screenshot_2017-06-28-20-10-11](https://user-images.githubusercontent.com/23637588/27650595-101c47d6-5c3e-11e7-9594-cf5d8498c94b.png)

</details>

**Comment by vozersky** [comment] 2017-06-28 17:16
I agree, It's by design, but it is not convenient for a user

**Comment by ameshkov** [comment] 2017-06-29 12:46
We should have a floating "plus" button in both user filter and whitelist.

**Comment by Revertron** [comment] 2017-07-25 09:22
The review AFA-CR-53 was approved, will be merging as soon as it will be checked in the build.

**Comment by Revertron** [comment] 2017-08-07 16:16
Done. Merged.

**Closed by Revertron** 2017-08-07 16:16 UTC
Labels: P2: High, UI
