### ISSUE TITLE
FarmVille 2 - can't login in FB(without filters and DNS filtrations)

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#45] opened 2015-09-15 11:32 UTC
https://play.google.com/store/apps/details?id=com.zynga.FarmVille2CountryEscape&hl=ru

**Comment by Alex-302** [comment] 2015-09-16 08:10
Логи PCV-456-92605

**Comment by Revertron** [comment] 2015-10-02 15:22
Added an exception for now.

**Comment by ameshkov** [comment] 2015-10-04 11:52
@Revertron would be great if you post here research details (broken PUT request and such). May be useful in future.

**Comment by Revertron** [comment] 2015-10-05 08:57
The PUT request was somehow broken indeed. Here is some log:

TCP id=90 Writing HTTP request to remote client
TCP id=90 PUT /storage/v1/app/5002607/blob/summary/user/71133265001 HTTP/1.1 writing body Content-Length: 247
TCP id=90 Reading HTTP response
TCP id=90 Read 402 bytes from socket channel
TCP id=90 HTTP/1.1 400 Bad Request
    Server: pbr-release-1.4.2-145/pbr-web-45.ca2
    Content-Length: 182
    Cache-Control: no-cache, no-store
    Request-Id: pbr-ab5171457db5c80b
    Connection: keep-alive
    Content-Type: application/json

**Comment by Revertron** [comment] 2015-10-05 12:03
[farmville.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/7631/farmville.txt)
Full log.

**Comment by ameshkov** [comment] 2015-10-16 13:25
I belive this is now fixed because it was also caused by #98 
We need to re-test it.

**Comment by ameshkov** [comment] 2015-10-16 14:41
Fixed, thanks to #98

**Comment by ameshkov** [comment] 2015-10-16 20:36
Not so fast:(

pcap:
https://yadi.sk/d/9gQoxyvmjnjoM

**Comment by ameshkov** [comment] 2015-10-19 18:51
Finally fixed in 2.1.212

**Closed by ameshkov** 2015-10-19 18:51 UTC
Labels: Bug
