### ISSUE TITLE
elearning.ual.pt does not open with "Protect from DPI"

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardForAndroid#4451] opened 2023-02-10 09:45 UTC
@adguard-bot commented on [Thu Feb 02 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783)

### Issue URL (Incorrect Blocking)
 [https://elearning.ual.pt/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Felearning.ual.pt%2F)
### Comment
> the only temporary fix is to disable strip parameters and dpi, and then the website loads

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/lzlfezR.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/RxbaM35.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.12
Browser: | Opera
AdGuard driver: | TDI
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Block third-party Authorization header, <br>Self-destructing first-party cookies (20), <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Block Flash, <br>Hide your IP address (254.254.254.254)
DNS filtering: | server: `adguard dns adblocking`<br>filters: `oisd: full, basic and extra, goodbye ads and adguard dns filter`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>EasyList<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking, <br/>EasyPrivacy, <br/>Peter Lowe's Blocklist, <br/>Fanboy's Enhanced Tracking List, <br/>Legitimate URL Shortener<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>AdGuard Cookie Notices, <br/>AdGuard Popups, <br/>AdGuard Other Annoyances, <br/>Fanboy's Annoyances, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List<br/><br/><b>Security:</b><br/>NoCoin Filter List<br/><br/><b>Other:</b><br/>AdGuard DNS<br/><br/><b>Language-specific:</b><br/>AdGuard German, <br/>AdGuard Spanish/Portuguese, <br/>AdGuard French, <br/>AdBlockID, <br/>EasyList Spanish, <br/>KAD - Anti-Scam, <br/>road-block
Custom filters: | oisd basic,<br>oisd full
Userscripts: | adguard assistant, extra, pop up blocker and web of trust
Other extensions used: | it only happens with stealth mode enabled, option protect with dpi and strip parameters

---

@zloyden commented on [Thu Feb 02 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1413853148)

Fixed, update should be available in 2-3 hours.

---

@gcautonoma commented on [Thu Feb 09 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1424053037)

hi thank you so much, but on pc fully fixed but on mobile still happens, and note that i am using duckduckgo but other browsers it happens aswell

---

@zloyden commented on [Thu Feb 09 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1424094577)

The site opens fine on my end with our filters, DNS or stealth mode. What exactly causes it?

---

@gcautonoma commented on [Thu Feb 09 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1424201346)

its the same connection closed when enabled strip parameters and dpi, also just to note that i have both dns filter enabled on adguard and android dns set the adguard dns server

---

@zloyden commented on [Thu Feb 09 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1424252496)

Could you disable DNS, leave only protection from dpi in stealth options and AdGuard Base? Then update the filters in the app, clear cache in the browser, restart it and open the site.
It was fixed by this rule and I can't reproduce it anymore

```adblock
@@||elearning.ual.pt^$stealth
```
@BlazDT @AdamWr please also check this.

---

@gcautonoma commented on [Thu Feb 09 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1424315302)

may be an incompatibility from the website it self, just saying

---

@gcautonoma commented on [Thu Feb 09 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1424321644)

sorry for delay in response but after messing around that no matter what the only thing that causes it to not load is dpi with the rest on and that setting disabled it works

---

@zloyden commented on [Fri Feb 10 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1425465046)

That's strange. Does the rule above helps in User rules? I mean this one https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1424252496.

---

@AdamWr commented on [Fri Feb 10 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1425471978)

> @AdamWr please also check this.

Website works fine on my Android device with `Stealth mode` and `Protect from DPI` option enabled.
I can reproduce this issue only if I disable `@@||elearning.ual.pt^$stealth` rule.

Please ensure that filter lists are up to date.

---

@gcautonoma commented on [Fri Feb 10 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1425474170)

ok, will check for updates

---

@gcautonoma commented on [Fri Feb 10 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1425483390)

on my phone it keeps happening maybe other app or android setting is probably interfering, just leave it be

---

@AdamWr commented on [Fri Feb 10 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1425493477)

If issue still occurs and it's caused by `Stealth mode` - `Protect from DPI`, then please try to add this rule:
```adblock
@@||elearning.ual.pt^$stealth
```
to user rules and then check if website loads correctly.

---

@gcautonoma commented on [Fri Feb 10 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1425501115)

i added that and still nothing

---

@gcautonoma commented on [Fri Feb 10 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1425503559)

![WhatsApp Image 2023-02-10 at 09 32 35](https://user-images.githubusercontent.com/121224147/218055944-699a772a-4359-4d08-8bf6-d63c8d89d607.jpeg)

---

@AdamWr commented on [Fri Feb 10 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1425513499)

Do I understand correctly that website loads fine if you disable `Protect from DPI` option in `Stealth mode`? 

---

@gcautonoma commented on [Fri Feb 10 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1425520756)

yes

---

@zloyden commented on [Fri Feb 10 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1425525974)

Seems there is a problem with the app. I'll move it to another repo.

---

@gcautonoma commented on [Fri Feb 10 2023](https://github.com/AdguardTeam/AdguardFilters/issues/141783#issuecomment-1425526586)

ok

**Comment by maxikuzmin** [comment] 2023-02-13 18:21
@gcautonoma @zloyden I have this recurring, but the @@|||elearning.ual.pt^$stealth rule helped solve the problem.
Is this repeated in all browsers? I also noticed that at first the rule didn't work for me until I reopened the browser, try it

**Comment by gcautonoma** [comment] 2023-02-14 09:10
yes it happens on all mobile browsers, its still not working, only with dpi off

**Comment by maxikuzmin** [comment] 2023-02-14 16:31
@gcautonoma I should clarify, are you using AdGuard version 3.6.11?

**Comment by gcautonoma** [comment] 2023-02-14 20:15
can i send logs or should i send screen shots of the settings?

**Comment by gcautonoma** [comment] 2023-02-14 20:15
AdGuard version 3.6.11, yes

**Comment by maxikuzmin** [comment] 2023-02-15 13:58
@gcautonoma to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

To unload the settings, you need to go to Settings -> General -> Export settings 
You can attach the settings to the debug logs

**Comment by gcautonoma** [comment] 2023-02-15 23:08
sure i will do that

**Comment by gcautonoma** [comment] 2023-02-15 23:32
done already sent the email

**Comment by maxikuzmin** [comment] 2023-02-16 17:24
@gcautonoma thank you! We need some time

**Comment by gcautonoma** [comment] 2023-02-16 19:04
no problem!

**Comment by maxikuzmin** [comment] 2023-03-01 10:48
@gcautonoma please go to AdGuard settings -> Content Blocking -> Allowlist
Uncheck elearning.ual.pt or just turn off Allowlist, that should help.
We will fix this behavior in AdGuard version 4.0, which is already being actively tested and will be released in beta version soon, then in release version

**Comment by gcautonoma** [comment] 2023-03-01 12:08
thank you it now works !!, as requested in the email could the logs and bug report that i sent be deleted since it contains sensitive information?

**Comment by maxikuzmin** [comment] 2023-03-03 12:54
@gcautonoma yes, of course. Your logs and bug report have been deleted.

**Comment by gcautonoma** [comment] 2023-03-03 14:46
but again my grateful thank you for solving this issue 👍

**Closed** 2023-04-10 08:46 UTC
Labels: Resolution: Fixed, Status: Resolved, Version: CoreLibs v1.11
