### ISSUE TITLE
Adguard restarts sometimes when opening app fresh

### ISSUE THREAD

**Issue by jordanswrld94** [AdguardTeam/AdguardForAndroid#5062] opened 2023-11-05 15:04 UTC
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3 Nightly 25

### Environment

```markdown
OS: Android 13
Device: Galaxy S23 Ultra


Sometimes when opening a fresh instance of adguard (closed from tray) the vpn icon disappears from status bar then reappears.
```

### Root access

- [ ] Yes, I have it.

#### Prerequisites 
- AdGuard is running 
- Protection is enabled 

#### Steps:
1. Remove AdGuard from minimized applications list (AdGuard is still running in the background at this point) 
2. Wait a while
3. Reopen

### Expected Behavior

Vpn icon stays in status bar

### Actual Behavior

The vpn icon disappears then reappears

### Screenshots

https://github.com/AdguardTeam/AdguardForAndroid/assets/118186787/cee6f3e7-452e-4091-b975-d2b8fc453440

**Comment by jordanswrld94** [comment] 2023-11-05 15:06
It may take a while to reproduce as it it doesnt happen everytime.

**Comment by maxikuzmin** [comment] 2023-11-07 07:44
@jordanswrld94 how often does this happen? It sounds like you had a filter update check happening. The restart happens because the configuration changes. Once the filters are updated, the protection is restored again

**Comment by jordanswrld94** [comment] 2023-11-07 14:13
I dont think its a filter update. Because i have filter updates set to 24 hours. This happens id say if i leave the app closed for like an hour. Then reopen it restarts.

**Comment by jordanswrld94** [comment] 2023-11-07 22:56
I reproduced it. How can i send the log?

**Comment by maxikuzmin** [comment] 2023-11-09 20:41
@jordanswrld94 please follow these steps:

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Debug

- Reproduce the issue related to the button behaviour, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

- Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):

mention the 5062 number in the subject
specify the exact time when the issue occurred

**Comment by jordanswrld94** [comment] 2023-11-13 23:41
Sent

**Comment by maxikuzmin** [comment] 2023-11-15 16:33
@jordanswrld94 did I understand correctly that you have the app already enabled in the background and when you open AdGuard, the protection reloads? Or does the protection reload when you initially start the app?

**Comment by jordanswrld94** [comment] 2023-11-15 16:40
If i have it open in the app drawer it doesnt restart. Its after closing it from the app drawer and opening say an hour later

**Comment by maxikuzmin** [comment] 2023-12-01 16:42
@jordanswrld94 seems like a settings conflict, we need some more time to look into this issue

**Comment by MySoul182** [comment] 2023-12-26 08:39
@maxikuzmin The same goes for my device. When will it be fixed?

**Comment by maxikuzmin** [comment] 2023-12-26 19:59
@maxikuzmin this will be fixed in the next 4.4 update

**Comment by Versty** [comment] 2024-01-23 14:06
@jordanswrld94 @MySoul182 
Does the issue still persist with latest AdGuard for Android nightly version (4.4 nightly 9)?

**Comment by jordanswrld94** [comment] 2024-01-23 15:16
> willl test and let u know

**Comment by jordanswrld94** [comment] 2024-01-23 15:25
Yes just happened. On latest version

**Comment by Deneno** [comment] 2024-02-02 12:41
@jordanswrld94 Greetings.
When returning to AdGuard after more than 30 minutes, we check whether the internal AdGuard configuration needs to be updated, including checking for changes in the list of installed applications.
According to the logs, we see that during the period under review there were changes in the list of installed applications (various applications were removed or installed), which is why the restart occurs.

**Closed by Deneno** 2024-02-02 12:41 UTC
Labels: Bug, Junior+, Priority: P4, Version: AdGuard v4.4

**Comment by jordanswrld94** [comment] 2024-02-02 16:23
This happens when no changes have been made as well though
