### ISSUE TITLE
The URL in about wrongly includes the front words (zh-TW)

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#3654] opened 2020-11-12 18:50 UTC
https://crowdin.com/translate/adguard-applications/17634/en-zhtw#3867606

The url should be only AdGuard.com, but it includes the front words and becomes a wrong url (保留所有的權利。AdGuard.com).
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ocG8GZw.jpg)
</details><br/>

**Comment by lancelot-moon** [comment] 2020-12-01 11:30
https://crowdin.com/translate/adguard-applications/17634/en-zhtw#3867606

Why was Chinese period symbol changed to English period symbol?
Are your developers not able to solve URL wrongly includes the front words in the program codes?

**Comment by ameshkov** [comment] 2021-12-29 16:27
"About" page is to be reworked a lot in v4.0, we'll incorporate the feedback there.

v3.X UI is effectively frozen at this point.

**Comment by lancelot-moon** [comment] 2021-12-29 16:44
> "About" page is to be reworked a lot in v4.0, we'll incorporate the feedback there.
> 
> v3.X UI is effectively frozen at this point.

In v4.0 nightly, this isn't solved.
Maybe you can use break line, like so.

保留所有的權利。
AdGuard.com

It's ok.
I don't know how the new UI will be.
After all, this issue is just a trifle.

**Comment by ameshkov** [comment] 2021-12-29 17:03
> In v4.0 nightly, this isn't solved.

These nightlies are still on the old UI.

The **real** 4.0 is in a different branch that we don't publish to testers yet.

**Comment by ameshkov** [comment] 2022-03-27 14:16
Okay, guys, only now I realize that the problem is not just that text is underlined.

The URL is wrong as well, it simply does not lead to `adguard.com` 😮 

Re-assigned this to v3.6.8.

**Comment by lancelot-moon** [comment] 2022-05-01 01:57
Your engineer added a space after Chinese period for solving the issue, like so:
保留所有的權利。 &lt;a href="%s"&gt;AdGuard.com&lt;/a&gt;

Can you not solve this without a space after Chinese period?
保留所有的權利。&lt;a href="%s"&gt;AdGuard.com&lt;/a&gt;

**Comment by ameshkov** [comment] 2022-05-03 13:00
@lancelot-moon surprisingly, this is quite hard. Due to an Android bug the dot is required.

We could change this if we split that string in two parts, but that would require changing all existing translations and we'd rather avoid this in the current version.

**Closed** 2022-05-06 16:56 UTC
Labels: Localization, Resolution: Fixed, Status: Resolved, Version: AdGuard v3.6.8
