### ISSUE TITLE
Firefox Based Browsers don't work right

### ISSUE THREAD

**Issue by SyCoREAPER** [AdguardTeam/AdguardForAndroid#5243] opened 2024-02-29 16:45 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.x.x

### Environment

- OS version: Android 14
- Device: Samsung S23 Ultra and Tab S8 Ultra

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, EasyList Cookie List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Other

AdGuard DNS filter, AdGuard Experimental filter

### Which DNS server do you use?

Cloudflare for Families - Malware Blocking

### DNS protocol

DNS-over-HTTPS

### Issue Details

Steps to reproduce:
1. Enable Developer Options
2. Turn on 3rd Party Certificate

### Expected Behavior

Block everything the same way it does on Chromium based browsers. 

### Actual Behavior

AdGuard misses tons of ads and the ones it removes often leaves a blank space. It borderline feels like it doesn't work.

The extension works correctly but I don't want the extension bloat, just the main paid app. 

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Tried Firefox Beta, Firefox Nightly, Fennec, Mull, IceRaven. All behave the same.

**Comment by maxikuzmin** [comment] 2024-03-06 10:02
@SyCoREAPER Firefox requires you to confirm in the settings to install third-party certificates. Did you do that? 
You need to do this by going to:
Context menu -> settings -> About Firefox -> click many times on the Firefox icon to enable the developer menu -> go back to Settings -> tap Secret settings -> enable the "Use third party CA certificates" switch

**Comment by SyCoREAPER** [comment] 2024-03-06 15:09
> @SyCoREAPER Firefox requires you to confirm in the settings to install third-party certificates. Did you do that? 
> You need to do this by going to:
> Context menu -> settings -> About Firefox -> click many times on the Firefox icon to enable the developer menu -> go back to Settings -> tap Secret settings -> enable the "Use third party CA certificates" switch 

As stated in the report, I did that.

**Comment by maxikuzmin** [comment] 2024-03-11 13:27
@SyCoREAPER could you please clarify which sites you are testing this problem on? 
Is it recurring on all sites or some sites?

**Comment by SyCoREAPER** [comment] 2024-03-11 15:18
My default test site is apkmirror.com because it has large ads but is a safe site.

**Comment by maxikuzmin** [comment] 2024-03-11 15:53
@SyCoREAPER I think you had an older version of AdGuard. I remember we recently added Firefox to default HTTPS filtering, previously Firefox was not filtered by default due to some incompatibilities. 
I checked your problem and everything is fine now, the problem is not recurring. I also tried disabling HTTPS filtering for Firefox, and the problem started to reproduce as you described.
You can test this theory to see for yourself.
I am closing this issue for now

**Closed by maxikuzmin** 2024-03-11 15:53 UTC
Labels: Bug, Priority: P4

**Comment by Prankish8407** [comment] 2024-03-13 12:22
I have the exact same issue, also enabled developer mode --> and checked the certificate box.
When i run chrome on android, everything is blocked as expected, when i run firefox all blocked sites / ads go trough.

**Comment by Prankish8407** [comment] 2024-03-13 13:23
To add this is the docker-compose file i use --> the ports are commented out as the host network will use predefined ports:

`  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    # ports:
    #   - 53:53/tcp
    #   - 53:53/udp
    #   - 67:67/udp
    #   - 68:68/udp
    #   - 80:80/tcp
    #   - 444:443/tcp
    #   - 444:443/udp
    #   - 853:853/tcp
    #   - 853:853/udp
    #   - 3000:3000/tcp
    #   - 5443:5443/tcp
    #   - 5443:5443/udp
    #   - 6060:6060/tcp
    network_mode: host
    volumes:
      - /volumes/adguardhome-work:/opt/adguardhome/work
      - /volumes/adguardhome-config:/opt/adguardhome/conf
    restart: always`

**Comment by SyCoREAPER** [comment] 2024-03-13 14:41
Not saying that's wrong but opening that many ports doesnt seem like a good idea. Also I'm not sure how that would have helped FF block correctly (if you want to share do t have to though)

**Comment by Prankish8407** [comment] 2024-03-13 18:32
Small update with a little further testing:

Apart from the normal Firefox app i downloaded firefox nightly on android (developers firefox) the same issue occurs,
I've tested it with ports temporary forwarded in the router and using the public IP as DNS on mobile data, same issue occurs, and still works for chrome.

I've delete all cache, even cookies etc, for firefox, firefox nightly and chrome.
chrome still blocks as expected, both firefox versions ignore and dns blocks or parent control, firefox still does not show up in the adguard dashboard, yet all chrome blocks show up as shown in previous post.
I did re-enable CA option in developer mode after smashing firefox logo 5 times, also tested it with it being disabled, same result.


I wrote down all the docker containers running on this specific server with some details:

```
Port:               Stack:              Container:              Networkmode:            Cloudflare:         Cloudflare SSO:             Comments:
53                  admin_tools         adguardhome             host                    no                  n/a                         adguard
67                  admin_tools         adguardhome             host                    no                  n/a                         adguard
68                  admin_tools         adguardhome             host                    no                  n/a                         adguard
80                  admin_tools         adguardhome             host                    yes                 no                          adguard
82                  admin_tools         vaultwarden             docker                  yes                 no                          bitwarden
443                 admin_tools         adguardhome             host                    no                  n/a                         adguard
853                 admin_tools         adguardhome             host                    no                  n/a                         adguard
3000                admin_tools         adguardhome             host                    no                  n/a                         adguard
3020                admin_tools         openvscode-server       host                    yes                 yes                         vscode
3040                chromium            gluetun                 docker                  no                  n/a                         chrome
4533                mediaserver         navidrome               docker                  yes                 no                          navidrome
5055                mediaserver         gluetun                 vpn                     yes                 no                          overseerr
5443                admin_tools         adguardhome             host                    no                  n/a                         adguard
6060                admin_tools         adguardhome             host                    no                  n/a                         adguard
6767                mediaserver         gluetun                 vpn                     yes                 yes                         bazarr
7878                mediaserver         gluetun                 vpn                     yes                 yes                         radarr
8080                mediaserver         gluetun                 vpn                     yes                 yes                         sabnzbd
8123                homeassistant       homeassistent           host                    yes                 no                          homeassistant
8181                mediaserver         tautulli                docker                  yes                 yes                         tautulli
8191                mediaserver         gluetun                 vpn                     no                  n/a                         flaresolver
8200                backup              duplicati               docker                  no                  n/a                         duplicati
8888                backup              resilio                 docker                  no                  n/a                         resilio
8989                mediaserver         gluetun                 vpn                     yes                 yes                         sonarr
9091                mediaserver         gluetun                 vpn                     yes                 yes                         transmission
9696                mediaserver         gluetun                 vpn                     yes                 no                          prowlarr
51413               mediaserver         gluetun                 vpn                     no                  n/a                         transmission
55555               backup              resilio                 docker                  no                  n/a                         resilio
```

i've stopped all containers and restarted adguard same issue occurs.

**Comment by Prankish8407** [comment] 2024-03-22 22:37
Is there anything else needed? or has the issue been found?
I've noticed that DNS rewrites also dont work in firefox android.

it feels / seems like firefox has a set DNS server for there mobile browser, ill test this out in the weekend with wireshark to see if i can pick anything up.

**Comment by ilsubyeega** [comment] 2024-08-22 17:11
Tested with Iceraven, Android 14, Adguard 4.6.2 with HTTP3 filtering enabled.

I found that disabling HTTP3, by setting `network.http.http3.enable = false`, allowed Adguard to filter the website, which was not happening otherwise. Although the `local.adguard.org` script was injected into the website, it did not remove any ads. The recent activity in the Adguard app shows that the content of `https://[domain].com` was modified, but it does not provide any specific endpoints (e.g., `/refresh.php?par=meters`). 

May relate to https://github.com/AdguardTeam/AdguardForAndroid/issues/5276.


> I remember we recently added Firefox to default HTTPS filtering, previously Firefox was not filtered by default due to some incompatibilities.

@maxikuzmin I couldn't find related in the changelog, do you know of any details about that?

**Comment by SyCoREAPER** [comment] 2024-08-23 13:23
> Tested with Iceraven, Android 14, Adguard 4.6.2 with HTTP3 filtering enabled.
> 
> I found that disabling HTTP3, by setting `network.http.http3.enable = false`, allowed Adguard to filter the website, which was not happening otherwise. 

What's "the website"? Any HTPS site? I haven't encountered any blocking issues.

**Comment by ilsubyeega** [comment] 2024-08-23 13:53
> What's "the website"? Any HTPS site? I haven't encountered any blocking issues.

It is tricky to say. All I can say is that It was using a Cloudflare WAF at that moment. I can email you more details if you need them. 


I tested it again (both iceraven and firefox nightly) and can't reproduce at this moment and shows endpoint in metrics now, but if it happens again in the future, I will report this again.

**Comment by SyCoREAPER** [comment] 2024-08-23 14:16
I'm not an admin or mod, so as much as I'd like to try and help, I don't know if any of the logs have personal or identifiers baked in. I'm just being completely transparent so you don't give a random (but trustworthy, yeah everyone says that I know) person anything that is personal. 

Best to let @maxikuzmin examine. I was just curious only so I could try and reproduce. 

Perhaps a DNS issue that day? Cloudflare has been having a rough few months with outages. Depending which server you use (regular, anti-malware, or no prøn) perhaps they sent a malformed site if you are using one of their modifier servers. Just a thought, could be way off but it came to mind.

**Comment by SyCoREAPER** [comment] 2024-08-23 14:35
> > What's "the website"? Any HTPS site? I haven't encountered any blocking issues.
> 
> It is tricky to say. All I can say is that It was using a Cloudflare WAF at that moment. I can email you more details if you need them. 
> 
> 
> I tested it again (both iceraven and firefox nightly) and can't reproduce at this moment and shows endpoint in metrics now, but if it happens again in the future, I will report this again.

GD it! It showed a double post so I deleted one and it deleted both...

Short version of a detailed message I'm only the OP, not a mod or admin. Don't want you sending any logs that might have private info to a stranger but would otherwise be glad to help.

**Comment by SyCoREAPER** [comment] 2024-08-23 15:09
Original comment recovered:

I'm not an admin or mod, so as much as I'd like to try and help, I don't know if any of the logs have personal or identifiers baked in. I'm just being completely transparent so you don't give a random (but trustworthy, yeah everyone says that I know) person anything that is personal. 

Best to let @maxikuzmin examine. I was just curious only so I could try and reproduce. 

Perhaps a DNS issue that day? Cloudflare has been having a rough few months with outages. Depending which server you use (regular, anti-malware, or no prøn) perhaps they sent a malformed site if you are using one of their modifier servers. Just a thought, could be way off but it came to mind.
