### ISSUE TITLE
AG v2.10 causes the frequent disconnections from Bulletin Board System (BBS).

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForAndroid#1520] opened 2017-10-10 01:49 UTC
@ameshkov
@vbagirov

Hi,
1. AG v2.10 causes the frequent disconnections from Bulletin Board System (BBS).
BBS:
https://ru.wikipedia.org/wiki/BBS

In Taiwan, many people use a mobile BBS app for visiting PTT.
PTT BBS:
https://en.wikipedia.org/wiki/PTT_Bulletin_Board_System

Such like:
JPTT:
https://play.google.com/store/apps/details?id=com.joshua.jptt

PiTT:
https://play.google.com/store/apps/details?id=com.ihad.ptt

PTT+:
https://play.google.com/store/apps/details?id=com.pttplus

Mo PTT:
https://play.google.com/store/apps/details?id=mong.moptt&hl=zh_TW

isPTT:
https://play.google.com/store/apps/details?id=com.ismiya.isptt&hl=zh_TW

PTTNOW: (Website mode. Don't need an account for login. Only reading mode.)
https://play.google.com/store/apps/details?id=whitebird.ptt_now&hl=zh_TW

PTT HOT: (Website mode. Don't need an account for login. Only reading mode.)
https://play.google.com/store/apps/details?id=com.jiecode.ptt&hl=zh_TW

and so on.

The default port setting in those mobile BBS apps is 443.
Maybe AG also uses port 443.
When enabling AG, it's hard to connect to BBS.
For solving the issue, we can change the port setting in those mobile BBS apps from 443 to 23 (or others) or enable Secure Shell (SSH) for connection.

SSH:
https://ru.wikipedia.org/wiki/SSH

With AG v2.9, there is no disconnection when surfing on BBS.
But AG v2.10 causes the frequent disconnections when using those BBS apps for surfing on BBS.
May you solve it?
You don't have an account for login into PTT.
Maybe it's a little trouble understanding the frequent disconnections from BBS.

You can use PTTNOW or PTT HOT for viewing what PTT is.
That's website mode.
Don't need an account for login.
But only reading mode because actually we don't login into PTT.
https://www.ptt.cc/index.html

Or you can use a Windows app for visiting BBS.
PCMan:
http://pcman.ptt.cc/windows.html
https://github.com/pcman-bbs/pcman-windows/releases/download/9.4.2/PCMan.exe
Interface:
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/uRAG4Wu.png)
</details><br/>

Address: ptt.cc
Type "guest" for login into PTT.
But you are usually unable to login into PTT because there are limited connections for guest accounts.
Only try more times when Taiwanese people are sleeping... (Moscow time 20:00 PM ~ 01:00 AM)
There should be more chances to login into PTT with a guest account during that period.
After login into PTT, this is the operating interface.
There were 87379 accounts online.
There are also some articles about AdGuard on PTT.
AdGuard is popular for Taiwanese net friends.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/OBtj45f.png)
</details><br/>

@AdamWr
2.  Block ads in those mobile BBS apps.
Please add the under ad domains or path into AG filter.

||graph.facebook.com/network_ads_common^
||pagead2.googlesyndication.com^
||ad-specs.guoshipartners.com^
||ad2iction.com^
||ads.mopub.com^
||aotter.net^
||doubleclick.net^

Thanks a lot!

**Comment by ameshkov** [comment] 2017-10-10 08:50
How does the disconnection look like?

**Comment by lancelot-moon** [comment] 2017-10-10 11:53
Hi,
For example, I use JPTT for login into PTT (BBS).
When I read articles on PTT, JPTT shows "disconnection occurred".
On the above of JPTT, it shows a red banner which reminds "disconnection occurred".
But I'm unable to save the screenshot in time.
It's because JPTT will soon automatically re-connect to PTT.
On the above of JPTT, it shows a yellow banner which reminds "connecting".
Such as the below.
![Image of Yaktocat](https://i.imgur.com/DAv8cQK.jpg)

**Comment by AdamWr** [comment] 2017-10-12 15:59
> Please add the under ad domains or path into AG filter.
||graph.facebook.com/network_ads_common^
||pagead2.googlesyndication.com^
||ad-specs.guoshipartners.com^
||ad2iction.com^
||ads.mopub.com^
||aotter.net^
||doubleclick.net^

`||graph.facebook.com/network_ads_common^` - we have more wide rule in our Mobile ads filter.
`||pagead2.googlesyndication.com^`,` ||ads.mopub.com^` ,`||doubleclick.net^` -  we have these rules in filter.
`||ads.ad2iction.com^` - this rule is in `Simplified domain names filter`/`AdGuard DNS`

`||aotter.net^` - it doesn't look like only ads domain, could you please tell me in which app there are ads from this domain?

Added:
`||ad-specs.guoshipartners.com^`

**Comment by lancelot-moon** [comment] 2017-10-12 17:24
Hi,
Those are mobile BBS apps' ad domains.
BBS:
https://en.wikipedia.org/wiki/Bulletin_board_system

After you login into BBS, you can see those ads in the mobile BBS app.

"graph.facebook.com/network_ads_common" is one of PTT+'s ad domains.
Ad in PTT+:
![Image of Yaktocat](https://i.imgur.com/J2i87sZ.jpg)

You know that viewing facebook might be abnormal if blocking graph.facebook.com.
I found the ad path.
If blocking graph.facebook.com/network_ads_common, PTT+ has no ad.
Android version of AdGuard can not only block domains but also paths.

"aotter.net" has not only ads but also trackers.
You should block it.
"aotter.net" is JPTT, MO PTT and PTTNOW's ads and trackers domain.

**Comment by AdamWr** [comment] 2017-10-12 17:47
Hi,
We have this rule:
`||graph.facebook.com/network_ads`
in [Mobile Ads filter](https://github.com/AdguardTeam/AdguardFilters/blob/203f1dd97df52acdfb3fe70577610ce5320f3e1b/MobileFilter/sections/general_url.txt#L51), so in my opinion it is not necessary to add this:
`||graph.facebook.com/network_ads_common^`

> "aotter.net" has not only ads but also trackers.

I mean that they have "normal" website, for example -  https://agirls.aotter.net/post/51953 which will be broken if I add this rule.
If you add `||aotter.net^$third-party` ads are blocked?

I will install PTT+ and PTTNOW and check, but I need some time for it.
By the way, please next time report ads here - https://github.com/AdguardTeam/AdguardFilters/issues

**Comment by lancelot-moon** [comment] 2017-10-12 17:52
Hi,

You can try MO PTT.
https://play.google.com/store/apps/details?id=mong.moptt&hl=zh_TW

But you don't have an account for login into PTT BBS.
It's trouble understanding where ads are in app.

Sorry, I'll report ads there next time.

**Comment by AdamWr** [comment] 2017-10-12 18:02
> Another thing...
Have you add "m.104.com.tw/api/1.0/ad/" in your filter?
AdguardTeam/AdguardForiOS#496

Yes, this rule was added - https://github.com/AdguardTeam/AdguardFilters/blob/692201f17dd66ec2a2e7c5193baa51a117e5a6bd/MobileFilter/sections/specific_app.txt#L69

**Comment by lancelot-moon** [comment] 2017-10-23 06:51
@ameshkov

Hi ameshkov,

I update AdGuard to v2.10.150 RC.
But the disconnection from BBS still occurs.
Do you need helps?
Can Russian people understand what BBS is?
BBS is a social community, such like facebook and VK.

**Comment by ameshkov** [comment] 2017-11-03 17:33
We understand, it's just the problem seems rather complicated, the fix is planned for v2.11.

Temporary solution would be to disable AG for BBS until the fix arrives.

**Comment by lancelot-moon** [comment] 2017-11-04 12:27
Hi ameshkov,
If necessary, I can privately lend you an account for login into PTT BBS by email.
aalpatkina knows my email address.
You can let aalpatkina give me your email address.

Or if you can solve the issue without a PTT BBS account for test, it's ok.

Hope that the disconnections from BBS can be solved in v2.11.
Temporary solution... we suggest using v2.9.
Thanks for your great work!

**Comment by ameshkov** [comment] 2017-11-07 05:24
> For solving the issue, we can change the port setting in those mobile BBS apps from 443 to 23 (or others) or enable Secure Shell (SSH) for connection.
> Is it because AdGuard's local VPN immovably also uses port 443?

No, that's because AG does not filter connections to ports less than 80

**Comment by lancelot-moon** [comment] 2017-11-07 06:16
> No, that's because AG does not filter connections to ports less than 80

Really?

As what you have known, the default port setting in those mobile BBS apps (JPTT, Mo PTT and so on) is 443.
Except for port 443, port 23 is also available.
Using other ports causes failed connection.
If we don't change the port 443 setting in those mobile BBS apps in advance, we are unable to connect to BBS.
Or we don't need to change port 443.
Some mobile BBS apps provide Secure Shell (SSH) for connection.
SSH:
https://ru.wikipedia.org/wiki/SSH

After enabling SSE for connection, we can connect to BBS via mobile BBS apps.
Does AdGuard not filter SSH?

You said that AG does not filter connections to ports less than 80.
But AdGuard actually filters ads after we use port 23 or SSH connection for login into BBS.
Do you not need an PTT BBS account for test?

Use Mo PTT app (port 23).
MO PTT app's ad domains:
flurry.com
doubleclick.net
aotter.net

Without AdGuard:
You can see ads banners in Mo PTT app.
https://imgur.com/a/RjEs2

With AdGuard:
No ad.
AG still filters ads even if I use port 23 in Mo PTT app.
https://imgur.com/a/qCZmb

B/R

**Comment by ameshkov** [comment] 2017-11-07 06:17
Port 23 is used for the BBS connection, but not for third-party connections (ads and tracking), that's why they are blocked okay.

**Comment by lancelot-moon** [comment] 2017-11-07 06:31
I'm using AdGuard for Android v.2.10.164 RC.
AdGuard still causes the disconnection from BBS in MO PTT app and other mobile BBS apps.
This is the screenshot.
![Image of Yaktocat](https://i.imgur.com/ih7em9J.png)

MO PTT doesn't provide automatic re-connecting. 
That means
"Oh!
There is something wrong which causes disconnection.
Wish to re-connect?"

I knew that the repair is planned for v2.11.
Those mobile BBS apps are Traditional Chinese interface.
If you need helps, please let me know.

Thanks a lot!

**Comment by lancelot-moon** [comment] 2017-11-07 07:20
Ah,

Some Taiwanese net friends don't know that they need to change a mobile BBS app's port setting or enable SSE for login into BBS with AdGuard.
May you design that AG doesn't block the BBS connection but ads when using port 443?
It's better.

Thank you. :3

**Comment by lancelot-moon** [comment] 2017-11-13 05:09
@AdamWr 

> ||pagead2.googlesyndication.com^,||ads.mopub.com^ ,||doubleclick.net^ - we have these rules in filter.

Hi AdamWr,

isPTT:
https://play.google.com/store/apps/details?id=com.ismiya.isptt&hl=zh_TW

pagead2.googlesyndication.com is one of isPTT's ad domains.
It's in AdGuard English filter and other filters, but not in Simplified domain names filter.
It causes AdGuard for Android can block ads from pagead2.googlesyndication.com, but AdGuard Pro for iOS with AdGuard DNS server can't block them.

I also reported some missed ad domains in the section of AdguardFilters last weekend.
https://github.com/AdguardTeam/AdguardFilters/issues/7595
https://github.com/AdguardTeam/AdguardFilters/issues/7596
https://github.com/AdguardTeam/AdguardFilters/issues/7593

Maybe you'll add them in English filter or Mobile ads filter.
May you also not forget to add all of them in Simplified domain names filter for iOS users?

Thanks a lot!

**Comment by lancelot-moon** [comment] 2017-11-13 06:30
@ameshkov 
@AdamWr

Hi,

You can try Mo PTT for login as a guest.
Mo PTT: A mobile BBS app.
for iOS:
https://itunes.apple.com/tw/app/mo-ptt/id804745434?l=zh&mt=8

for Android:
https://play.google.com/store/apps/details?id=mong.moptt&hl=zh_TW

Please click there.
It means:
I don't have an account. Visit as a guest.
![image](https://i.imgur.com/V91OP3q.png)

After entering PTT BBS, the message tells that you only can read articles and don't have complete features because you don't have an account.
![image](https://i.imgur.com/7squNy0.png)

Mo PTT has added some boards in the favorites.
![image](https://i.imgur.com/5ldJwGT.png)

For example:
Visit Android board.
You can read my article whose date is 3rd November on Android board of PTT BBS.
![image](https://i.imgur.com/7SHbEQ9.jpg)

If you want to visit the total boards for reading more articles on PTT BBS, you click "Classified boards".
![image](https://i.imgur.com/HpAR73F.png)

But it's strange that the disconnection from BBS seems not occur if login as a guest via Mo PTT app with AdGuard.

If having an account for login into PTT BBS, the disconnection from BBS occurred via Mo PTT app with AdGuard.

If needing any helps, please let me know.
Thanks for your great work!

**Comment by ameshkov** [comment] 2017-11-16 11:48
This bug should be resolved in the coming patch.

Probably caused by this: https://github.com/AdguardTeam/AdguardForAndroid/issues/1547#issuecomment-344866651

**Closed by ameshkov** 2017-11-16 11:48 UTC
Labels: compatibility

**Comment by lancelot-moon** [comment] 2017-11-16 12:22
‧★,:*:‧\(￣▽￣)/‧:*‧°★*

Hi,
Thanks for your great work! ( ￣□￣)/ <(￣ㄧ￣ ) <(￣ㄧ￣ ) отдать должное
https://github.com/AdguardTeam/AdguardForAndroid/releases
Now the latest version of AdGuard for Android is v2.10.164.
Will the 2.10 patch be used in the next version of v2.10 beta?
I'll try if it's valid.
B/R

**Comment by lancelot-moon** [comment] 2017-11-17 05:14
Hi,

I updated to v2.10.171 RC.
https://github.com/AdguardTeam/AdguardForAndroid/releases/tag/v2.10.171-rc

It's valid. There is already no disconnection from BBS.
Thank you very much!

You had known that if enabling AdGuard before login into BBS, we need to first go to setting for enabling SSH connection or changing to use port 23 on those mobile BBS apps.
Is it possible that we don't need to enable SSH connection or change to use port 23 for login into BBS with AdGuard for Android / AdGuard Pro for iOS?

B/R

**Comment by ameshkov** [comment] 2017-11-17 13:22
Should we disable HTTPS filtering for these apps by default?

**Comment by lancelot-moon** [comment] 2017-11-17 17:40
Hi,

I disabled AdGuard's HTTPS filtering in advance.
And then I tried to login into BBS via the default port setting 443 without SSH connection.
If using JPTT, I have to wait for 2 minutes for login.
The waiting time is too long.

If using Mo PTT, I was unable to connect to BBS server.
Mo PTT showed the error,
"Oh! The server has no response, please try again later."

Disabling HTTPS filtering is absolutely not the solution.
A risk of being unable to connect to PTT BBS.

You told me.
> No, that's because AG does not filter connections to ports less than 80

Or can AdGuard simply not filter PTT BBS server by default even if any mobile BBS apps use the default port setting 443 for connecting to PTT BBS?

**Comment by lancelot-moon** [comment] 2017-11-18 08:39
Привет ameshkov,

Here is the information about PTT BBS.

https://github.com/ptt/pttbbs
If you have advanced questions, you can try to ask them there.
https://github.com/ptt/pttbbs/issues

> mainly used in telnet / ssh protocol, currently web-interface is used only for reading articles, no other interactions.

> SSH connection: bbs@ptt.cc
Telnet unsafe connection: telnet://ptt.cc
Website: www.ptt.cc

AdGuard is unable to filter SSH connection, right?
How does AdGuard deal with Telnet protocol?
The problem is unsafe Telnet connection with AdGuard.
I tried to disable HTTPS filtering.
But it's useless.
There is still the risk of being unable to connect to PTT BBS if using the default port 443 for mobile BBS apps.

Can you design that AdGuard doesn't filter the 3 servers of PTT Telnet BBS by default?
PTT Telnet BBS has 3 associated servers.
telnet://ptt.cc <- (批踢踢實業坊) (Main server)
telnet://ptt2.cc <- (批踢踢兔) 
telnet://ptt3.cc <- (批踢踢參)

The allowed ports for connecting to PTT BBS are only 23, 443 and 3000~3010.
For example:
telnet://ptt.cc:443
telnet://ptt.cc:3005

> No, that's because AG does not filter connections to ports less than 80

Does it seem that AG also does not filter connections to ports above 3000?

The general default port setting of telnet is 23.

But most of mobile BBS apps use port 443 as the default port setting, such as JPTT, Mo PTT...etc.

A few BBS apps don't use unsafe Telnet connection.
They use SSH connection as the only way of connecting to PTT BBS, such as PTT+, PiTT, isPTT, PTTopia...etc.

Спасибо!

**Comment by lancelot-moon** [comment] 2017-11-19 18:58
Hi,

May you mark this issue with "Re-open" label?
I worry that you forget it since the issue was closed.

Thanks.
