### ISSUE TITLE
Apply custom app filtering rules to newly installed apps

### ISSUE THREAD

**Issue by akmAa** [AdguardTeam/AdguardForAndroid#1667] opened 2017-12-25 20:22 UTC
The customer wants AdGuard to apply custom app filtering rules (i.e. do not use SSL) in newly installed apps by default.

Customer id is 1703543

**Comment by ameshkov** [comment] 2018-01-02 21:15
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/1069

**Closed by ameshkov** 2018-01-02 21:15 UTC
