### ISSUE TITLE
GPS & Root https filtering error notification on rooted android

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForAndroid#4170] opened 2022-05-19 16:23 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -  4.0 nightly 34 (75)
- **Filtering mode:** 
  -  locall https proxy
- **Device:**
  - samsunng sm-g973f
- **Operating system and version:**
  -  12
- **Root access:**
  -  yes

### Expected Behavior

Despite the fact that AG protection for "root" and "GPS" apps is off, I still receive the https filtering error.### Actual Behavior

notification spam

### Screenshots

![image](https://user-images.githubusercontent.com/40741745/169349617-7abdae06-1f54-496b-bc7e-938e913b22f0.png)
![image](https://user-images.githubusercontent.com/40741745/169349741-b5e3bbf6-6061-49c3-890d-f66df2458ed4.png)

</details>

### Additional Information

i have **Adguard Certificate** module installed on my phone FYI

[adguard_logs_4.0.75_1905_205215.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/8732133/adguard_logs_4.0.75_1905_205215.zip)

**Comment by aliafshany** [comment] 2022-06-03 13:51
Hello, I sent you a log, but it's not set to Record Everything.
I should also mention that I cannot make this notification appear on purpose; it appears on its own.
Although, according on what I've learned, this occurs when a random app tries to use GPS or root access to work.

Allow me to log again, and then I'll give you a better one with more specifics and a specific time and date.

**Comment by aliafshany** [comment] 2022-06-03 14:36
i tried to open an app that requires GPS to start, and as i was suspected, i got those notifications.
please look up 19:03 - 19:04 o'cloc of this log. ( log's been set to record everything )

[adguard_logs_4.0.75_0306_190435.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/8833064/adguard_logs_4.0.75_0306_190435.zip)

**Comment by Birbber** [comment] 2022-06-16 09:12
@aliafshany Any news?
Still it's curious what exact applications you want to disable filtering for. And what do you want to achieve by turning the filtering for them?

**Comment by aliafshany** [comment] 2022-06-16 09:49
@maxikuzmin 
@Birbber 

Please accept my apologies for the delay.
Please let me know if you want a list of all the apps I'm trying to exclude HTTPS Filtering from.

The reason for turning this off is that unless you exclude specific apps, HTTPS Filtering will prevent them from running.

But, if you're referring to the "Root" and "GPS" apps, I should point out that they appear to be system programs that I didn't install manually.
Because I'm getting spam notifications for both apps, I turned off HTTPS Filtering to prevent spam notifications.

**Comment by maxikuzmin** [comment] 2022-06-23 07:57
@aliafshany I do not see such applications in the app settings on the 12 android. 
Nevertheless, according to the name of these applications, it is also not clear what kind of spam "Root" and "GPS" can show. 
Maybe the error appears because you are trying to disable "AdGuard protection" just for "Root" and "GPS".
If you enable "AdGuard protection" for "Root" and "GPS", there will be no error.
You still haven't answered for which applications you are trying to disable filtering? The system applications are part of the system, try to disable filtering just for the applications you need (not the system ones).

**Comment by aliafshany** [comment] 2022-06-24 07:06
i don't see either but i get those notifications so there must be something.

even if i turn on filtering for those apps i still would get those notifications in a much higher frequent.

samsung push service
sagernet
Freedome
CaptivePortalLogin
samsung cloud
google play store
google duo
photos
DNS ( i disbaled this app specially due to realy high battery draining, after disabling this one, my battery consumption got so much better )

**Comment by maxikuzmin** [comment] 2022-06-27 09:22
@aliafshany please answer, what kind of spam are you trying to block? Are you getting banners, video ads? You are talking about notifications, are there ads in these notifications? What exactly are you trying to block? In which applications do you see spam?

**Comment by aliafshany** [comment] 2022-06-29 15:52
i see spam notifications in **Notification bar**
adguard sends many annoying notifications about this matter.
please see this screenshot, i have highlighted what i mean

![image](https://user-images.githubusercontent.com/40741745/176480885-3d030793-84ba-4f2b-861d-8d3526f5341c.png)

**Comment by maxikuzmin** [comment] 2022-06-30 13:16
@aliafshany to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment] 2022-07-18 08:06
@aliafshany ping

**Comment by aliafshany** [comment] 2022-07-18 08:11
oh hi🤦🏻‍♂️
I forgot that, sorry.

I sent logs for the VPN; these are two different issues. None of these issues got mixed up, and the records are for the required apps.

I will collect the log files you need asap.

Thank you for reminding

**Comment by maxikuzmin** [comment] 2022-07-20 10:51
@aliafshany we don't have access to the files you sent in the mail. Please resend with open access

**Comment by aliafshany** [comment] 2022-07-20 10:58
@maxikuzmin, I remember giving access to anyone who has the link.

If you want, I can send it via Telegram, if you prefer.

**Comment by maxikuzmin** [comment] 2022-07-28 08:14
@aliafshany while we figure it out

**Comment by aliafshany** [comment] 2022-07-28 08:16
@maxikuzmin ok then
take your time, thank you

**Comment by maxikuzmin** [comment] 2022-08-09 09:54
@aliafshany I noticed that on the new update, "Root" and "GPS" are missing from Apps Management. Is this the same for you? I don't see them on the list to choose from

**Comment by maxikuzmin** [comment] 2022-08-09 10:16
@aliafshany what do you want to achieve by disabling https filtering for GPS and Root? Maybe we can give another workable solution for you

**Comment by aliafshany** [comment] 2022-08-09 16:24
@maxikuzmin 
i got those errors again
please see this video demo:


https://user-images.githubusercontent.com/40741745/183705856-99df001a-3764-44bf-a1b7-f9ed88b84f31.mp4

**Comment by maxikuzmin** [comment] 2022-08-10 10:57
@aliafshany spam messages are GPS and Root notifications? But if you turn filtering back on, there will be no notifications. In the video you have GPS open first, then it is not in the list of applications. Why? How did you get to GPS before that?

**Comment by aliafshany** [comment] 2022-08-10 11:17
@maxikuzmin 
i urge you and encourage you to read this issue from the beginning because we have discussed all your questions before.

- yes, spam messages are GPS and Root notifications.
- "But if you turn filtering back on, there will be no notifications" read the carefully https://github.com/AdguardTeam/AdguardForAndroid/issues/4170#issuecomment-1209195787
- idk know why there is no GPS or Root app there. You are devs of this app. maybe it's a glitch.
- How did you get to GPS before that?  please see this comment's video in order to see how i managed to get there. https://github.com/AdguardTeam/AdguardForAndroid/issues/4170#issuecomment-1209601547

**Comment by maxikuzmin** [comment] 2022-08-11 08:42
@aliafshany we see this behavior because it's not the GPS app, but another app
The GPS application and several others have the same unique identifier. By disabling filtering for one application, we don't disable filtering for another, even though they have unique identifiers
But when we can't filter HTTPS traffic for another app, we just take the first app in the list that has the same identifier
that's why the notification for gps is shown even though it's turned off
This is a flaw in the existing algorithm in 3.6, they already fixed it in 4.0, wait for 4.0, it's coming soon

**Comment by aliafshany** [comment] 2022-08-11 09:30
@maxikuzmin 
thank you for this thorogh explaination
this was the answer i was looking for.

FYI, I am using AG 4.0 nightly 35
it's not release version.

should i wait for another release or what?

**Comment by maxikuzmin** [comment] 2022-08-11 09:34
@aliafshany  yes, I saw that you wrote about the AG 4.0 nightly 35 version. We have to wait for the release

**Comment by aliafshany** [comment] 2022-08-11 09:36
@maxikuzmin  thank you
i will wait then.
if you'd like you may close this issue then

best

**Comment by maxikuzmin** [comment] 2022-08-11 09:39
@aliafshany  we'll wait for the release to see if everything works

**Comment by maxikuzmin** [comment] 2022-08-29 13:50
@aliafshany did you download version 3.6.10?  Is the issue still relevant?

**Comment by aliafshany** [comment] 2022-08-29 14:16
@maxikuzmin 
no i have the latest nightly version.
if you'd like me to install that version, please tell me how to completely uninstall the current version so i have a clean install

**Comment by maxikuzmin** [comment] 2022-08-29 14:29
@aliafshany just find AdGuard in your phone's system settings in the list of apps, clear AdGuard data, then uninstall it. Then install version 3.6.10, and check

**Comment by maxikuzmin** [comment] 2022-08-31 08:17
@aliafshany any news?

**Comment by maxikuzmin** [comment] 2022-09-01 07:26
@aliafshany sorry. The fix for this problem has already been implemented in version 4.0, it's hard to say yet when version 4.0 will be released, but we have to wait for it.

**Closed by maxikuzmin** 2022-09-01 07:26 UTC

**Comment by aliafshany** [comment] 2023-02-10 11:54
@Rtizer-9 
it seems that in the last nightly version, they fixed it. but unfortunately, idk why I can't use sagernet and Adguard at the same time, although I have given AG the root access.
it's working for a bit and then stops and blocks everything. I can't even browse. so I decided to write an issue so that they could investigate it.

**Comment by Rtizer-9** [comment] 2023-02-10 13:43
Sagernet sometimes turn off by itself. Also, there are way too many settings in sagernet and other similar apps which needs to be inline with the whole setup for it to make a route which data can actually follow without being blocked at some level. You can try the newly introduced root automatic proxy mode and try experimenting with all those configs in sagernet. In my case it's working.

**Comment by Rtizer-9** [comment] 2023-02-10 14:06
I haven't used vmess so I can't really comment. Again, you might wanna experiment with those under the hood settings of sagernet like dns, sniffing etc.

**Comment by Rtizer-9** [comment] 2023-02-10 14:15
By the way just in case by mistake you've forgot please check if the operation modes of adguard and sagernet is different. Sagernet by default operates in VPN mode iirc which you one needs to change to proxy only mode if other VPN is working.

**Comment by gitthangbaby** [comment] 2023-04-21 17:52
> @aliafshany sorry. The fix for this problem has already been implemented in version 4.0, it's hard to say yet when version 4.0 will be released, but we have to wait for it.

It's almost one year of constantly swiping the error away on all mobiles, I wish this annoyance was added to the current version.
