### ISSUE TITLE
Android 14 kills AdGuard (root) - AdGuard fails to start again

### ISSUE THREAD

**Issue by Utini2000** [AdguardTeam/AdguardForAndroid#5056] opened 2023-10-31 07:14 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.2

### Environment

```markdown
- OS: Android 14
- Device: Pixel 8 Pro
- Firmware: October build
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter, EasyList, EasyList Germany, EasyList Cookie List

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies

### Issue Details

Steps to reproduce:
1. Do a hardware heavy task (I edited a big picture with magic eraser in google photos and saved it)
2. I believe Android tries to free up RAM and starts to kill apps including Adguard
3. Adguard restarts itself
4. Internet connection is notnpossible anymore though
5. I have to manually open AdGuard and enable protection to get everything resolved

### Expected Behavior

AdGuard shouldn't be killed (root access available) and even if so, restart correctly.

### Actual Behavior

See above. Log files will be sent to devteam

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment] 2023-11-09 19:08
@Utini2000 could you please clarify what you mean by "big picture"? I tried with a 39 MB 6200x6200 image, but this error did not occur again

**Comment by Utini2000** [comment] 2023-11-10 08:02
@maxikuzmin nice to see you here again.

I am just taking a random picture that my Pixel 8 Pro made.
Here is one attached. Then use a lot of "Magic eraser" in google photos until the app crashes while trying process the file when saving.

![PXL_20231016_103004574 NIGHT](https://github.com/AdguardTeam/AdguardForAndroid/assets/14877663/9a17a434-9f52-413f-9bfb-155137cc7e1d)

**Comment by maxikuzmin** [comment] 2023-11-10 17:05
@Utini2000 me too. It's a beautiful view. My image was significantly larger, but I'll try with your image. 
There's a good chance that it's a system problem with the device, but it would be good if you repeat these steps with debug logs and email [devteam@adguard.com](mailto:devteam@adguard.com), mention the 5056 number in the subject
specify the exact time when the issue occurred

**Comment by Utini2000** [comment] 2023-11-10 17:08
@maxikuzmin I already sent a log file. Did you get it? I can make a few more ceashes/logs though.

**Comment by Utini2000** [comment] 2023-11-13 04:48
@maxikuzmin this morning I woke up and noticed that Fairmail showed up an error about not being able to connect to the mail servers.

Websites in the browser wouldn't load.

I opened AdGuard and saw that it said "Restarting protection". Once that was done "Protection Enabled" my internet worked again.

Adguard has root, unrestrticted battery and network usage.

**Comment by maxikuzmin** [comment] 2023-11-15 16:40
@Utini2000 I see your logs, we will look into it. Please open a new issue about Fairmail problem

**Comment by maxikuzmin** [comment] 2023-12-05 15:50
@Utini2000 looks like a native crash. It would be nice to get a bug report after the problem recurs.
Please, after repeating the problem, compile a bug report by [instruction](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/#capture-a-bug-report-from-a-device), and send it to the email devteam@adguard.com

**Comment by Utini2000** [comment] 2023-12-06 18:46
@maxikuzmin I just re-produced the issue, created a bug report, uploaded it to my webserver and provided the link via mail.

**Comment by maxikuzmin** [comment] 2023-12-11 13:07
@Utini2000 we need some more time, please wait

**Comment by Utini2000** [comment] 2023-12-14 07:44
@maxikuzmin sure!

**Comment by maxikuzmin** [comment] 2023-12-18 17:54
@Utini2000 a rather large file with a lot of requests. It would be nice to have the playback time of the problem in the logs. 
Could you repeat the problem, record the logs and specify the time when the problem was reproduced?

**Comment by maxikuzmin** [comment] 2023-12-22 15:05
@Utini2000 any news?

**Comment by maxikuzmin** [comment] 2023-12-26 20:00
@Utini2000 for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Comment by Utini2000** [comment] 2023-12-26 20:07
@maxikuzmin sorry I didn't notice your replies. I caused the error/crash and instantly made the log afterwards. Does that help?

**Comment by maxikuzmin** [comment] 2023-12-27 20:24
@Utini2000 the problem is that your logs have a large quantity of requests and the size of the logs is large. Please repeat the problem with extended logs, then send logs also to mail to us and be sure to specify the time of reproduction of the problem

**Comment by Utini2000** [comment] 2023-12-27 20:27
@maxikuzmin the issue happens 30-60 seconds before the end of the log. I create the log right after the issue happens. Does that help?

**Comment by maxikuzmin** [comment] 2023-12-27 20:45
@Utini2000 yes, okay

**Comment by maxikuzmin** [comment] 2023-12-28 17:16
@Utini2000 were you able to reproduce the bug?

**Comment by Utini2000** [comment] 2023-12-28 18:03
@maxikuzmin yes of course, right before I exported the log in AdGuard.

**Comment by maxikuzmin** [comment] 2024-01-15 16:15
@Utini2000 it looks like the system needs to get a lot of resources and the application is being forced closed. Could you please do it again and record debug logs so we can make sure?

**Comment by maxikuzmin** [comment] 2024-01-22 18:13
@Utini2000 any news?

**Comment by Utini2000** [comment] 2024-01-23 22:01
@maxikuzmin sorry I have AdGuard disabled/uninstalled until this major issue gets fixed: https://github.com/AdguardTeam/AdguardForAndroid/issues/5057

**Comment by maxikuzmin** [comment] 2024-01-26 18:55
@Utini2000 I hope this problem is solved soon

**Comment by maxikuzmin** [comment] 2024-02-12 18:41
@Utini2000 as far as I understand the problem has not been resolved yet? What about this issue?

**Comment by Utini2000** [comment] 2024-02-13 06:47
@maxikuzmin I have uninstalled AdGuard for Android until this major issue gets fixed: https://github.com/AdguardTeam/AdguardForAndroid/issues/5057

Can't help on solving this issue for now.

**Comment by maxikuzmin** [comment] 2024-02-15 18:57
@Utini2000 as I understand it, the problem #5057 cannot be reproduced yet?
At the moment I will close this issue, please reopen the issue as soon as issue 5057 is resolved and we can continue

**Closed by maxikuzmin** 2024-02-15 18:57 UTC
Labels: Bug, Resolution: Cannot Reproduce, Status: Closed, Priority: P4
