### ISSUE TITLE
Add Data Limit For Apps

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdguardForAndroid#3237] opened 2019-11-30 02:58 UTC
### Problem Description

Some people (such as myself) don't have a lot of mobile data to spare.

### Proposed Solution

It would be amazing if you could add an input field in the 'Firewall' section of the app that we can use to limit the amount of data an app is allowed to use and when it reaches that limit, the connection should be cut off. It would probably be set in Megabytes and could be set to reset on specific dates (for when your data resets). It would only work on data as to not cause problems when on wifi.

**Comment by artemiv4nov** [comment] 2019-12-01 10:18
It's duplicate of #3226 and #3227

**Closed by artemiv4nov** 2019-12-01 10:18 UTC
