### ISSUE TITLE
com.economist.darwin doesn't work with HTTPs filtering

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#587] opened 2016-05-25 17:40 UTC
Works fine once added to the HTTPs apps exceptions list.

**Comment by Revertron** [comment] 2016-06-02 07:42
https://github.com/AdguardTeam/AdguardForAndroid/wiki/Resolving-HTTPS-compatibility-issues

**Comment by gshumihin** [comment] 2016-06-06 16:47
Looks like app dowsn't work because we block espresso.economist.com beacuse of this request:
```
06-06 16:13:29.720 D/com.adguard.android.FilteringLog( 3194): [pool-2-thread-43] TCP id=100119 GET ads=1 "https://espresso.economist.com/api/v1/ad/logo/EU/json" 500 0 8ms "null" "okhttp/2.5.0" com.economist.darwin 455 4298
```

**Comment by gshumihin** [comment] 2016-06-06 16:49
@Alex-302 recommended to add this rule to userfilter
```
||espresso.economist.com/api/v1/ad/logo/*/json$replace=/advertName/BBvertName\,/i
```
with this rule app works, but ads are not filtered.

**Comment by gshumihin** [comment] 2016-06-06 17:03
Here's .har-file:
[economisthar.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/300929/economisthar.txt)

**Comment by Alex-302** [comment] 2016-06-06 17:12
Caused by
```
/ad/logo/*
```
Excluded from English filter.
Added to mobile filter:
```
||espresso.economist.com/api/v1/ad/*/json$replace=/html/abcd\,/i
```
@evgeniy-ADG 
передай юзеру чтоб проверил и отписался.

**Comment by evgeniy-ADG** [comment] 2016-06-14 11:51
я проверил, у меня работает

**Comment by evgeniy-ADG** [comment] 2016-06-14 11:54
обновился, убрал из исключений
![image](https://cloud.githubusercontent.com/assets/15856304/16041741/d5b28b88-323f-11e6-8bfb-b91d2e6dd91e.png)
при отключении adg, все ок

**Comment by gshumihin** [comment] 2016-06-14 13:20
From user: Done. Works perfectly now, thank you!

**Closed** 2016-06-14 13:19 UTC
Labels: Compatibility, SSL, Waiting For Data
