### ISSUE TITLE
Unable to turn the app on on sub profiles after upgrading to Android 12

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdguardForAndroid#4018] opened 2021-11-02 17:18 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
 v3.6.4 (32)
- **Filtering mode:**
 Local VPN
- **Device:**
Google Pixel 3
- **Operating system and version:**
Android 12
- **Root access:**
No

### Expected Behavior

Able to turn AG on

### Actual Behavior

Unable to turn it on

### Screenshots

<details><summary>Screenshot:</summary>

![SS](https://user-images.githubusercontent.com/58900598/139913093-e3376659-de99-497f-ae0e-ea0f66a7f8e3.png)

</details>

### Additional Information

After upgrading to Android 12, I can't turn AG on anymore on sub Android profiles. That is, on main or phone-owner profile there's no problem, it occurs only on non-owner profiles. Not only automatic launch, manual launch also fails with the message in the screenshot "An error occured during operation. Try it agiain later.". Rebooting or uninstall and reinstall the app didn't help. I created a fresh new profile without any modification and installed AG, again failed. Obviously it's not https://github.com/AdguardTeam/AdguardForAndroid/issues/3937.

**Comment by Chinaski1** [comment] 2021-11-08 10:51
Hello there!

I was able to reproduce the above issue with running protection on a secondary user profile.
We need some time to understand the reasons for its occurrence.

Thank you for the report!

**Comment by Birbber** [comment] 2021-11-11 08:06
@Yuki2718 Seems like your issue is similar to [#3529](https://github.com/AdguardTeam/AdguardForAndroid/issues/3529). A good explanation is given [here](https://github.com/AdguardTeam/AdguardForAndroid/issues/3529#issuecomment-673382634). Try giving the permission via ADB and let us know the result.

**Comment by Yuki2718** [comment] 2021-11-12 11:40
@Birbber You're right, `pm grant --user (ID) com.adguard.android android.permission.INTERACT_ACROSS_USERS` solved the issue.

**Comment by Birbber** [comment] 2021-11-12 13:04
@Yuki2718 Great to hear that. I'm closing this issue then.

**Closed** 2021-11-12 13:05 UTC
Labels: Bug, P3: Medium, Resolution: Done, Status: Resolved, Version: AdGuard v4.0
