### ISSUE TITLE
VPN can not be established on MIUI 9

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#1568] opened 2017-10-26 14:02 UTC
The bug was files to Xiaomi: http://en.miui.com/thread-977018-1-1.html

### Customer ID 
Me

### Your environment
* Adguard version: 2.10.*
* Adguard filtering mode: VPN
* Device model: Any Xiaomi
* Operating system and version: 7.0-7.1.1 MIUI 9
* Rooted or not? N/A
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? None

**Comment by ameshkov** [comment] 2017-10-26 14:05
```
java.lang.SecurityException: get package uid: Neither user 10150 nor current process has android.permission.INTERACT_ACROSS_USERS.
```

Does that mean that you operate under a restricted user account there?

**Comment by Revertron** [comment] 2017-10-26 15:11
No, all users with this error say that they do not have any additional accounts, just the owner.

**Comment by ameshkov** [comment] 2017-11-07 06:21
People report that the issue is resolved in the latest update:
http://4pda.ru/forum/index.php?s=&showtopic=601691&view=findpost&p=66633822

**Comment by ameshkov** [comment] 2017-11-16 22:48
Reported as fixed

**Closed by ameshkov** 2017-11-16 22:48 UTC
Labels: android bug
