### ISSUE TITLE
Restore incomplete certificate chain in server connections

### ISSUE THREAD

**Issue by Revertron** [AdguardTeam/AdguardForAndroid#315] opened 2016-02-20 15:57 UTC
In our https-filtration mechanism we need to restore incomplete certificate chain like browsers do.

**Comment by ameshkov** [comment] 2016-02-23 20:35
Example:
https://incomplete-chain.badssl.com/

We consider this certificate - invalid, while all modern browsers are able to filter it.

**Comment by ameshkov** [comment] 2016-02-23 20:35
One more issue (could be caused by the same):
https://cloud.jamm.me

**Comment by ameshkov** [comment] 2016-04-12 12:27
So, we've learned how other browsers work and resolve this issue.

They put intermediate certificates to some sort of a cache and then use it to restore the certificates chain. We could do it the same way.

Anyway, the issue does not seem to be very important, reassigning it to v2.6

**Comment by ameshkov** [comment] 2016-04-21 17:35
Haha, I have accidentally made it:)

**Closed by ameshkov** 2016-04-21 17:35 UTC
Labels: SSL
