### ISSUE TITLE
Native stack is not properly closed sometimes when adguard is auto-restarted

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForAndroid#1336] opened 2017-07-24 16:01 UTC
Part of log is in attached file. (From network switch to unusable proxy server)
[adguard.log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1170381/adguard.log.txt)

### Your environment

* Adguard version: 2.9.138beta
* Adguard filtering mode: VPN
* Device model: Xiaomi mi5s (capricorn)
* Operating system and version: Android 6.0.1 (MIUI 8.5)
* Not rooted

**Comment by sfionov** [comment] 2017-07-25 09:41
Another log
[adguard-2.log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1172694/adguard-2.log.txt)

**Comment by sfionov** [comment] 2017-07-31 10:23
On the corelibs side, the following thing may be added to prevent ignoring Thread.interrupt():
https://stackoverflow.com/questions/29330955/how-do-i-write-native-code-which-responds-to-thread-interrupt

**Comment by ameshkov** [comment] 2017-08-14 07:30
@sfionov could this error be caused by this issue?
```
09:32:35.507 [VpnService-main] ERROR c.a.a.f.vpn.FilteringVpnService - Error building vpn interface

java.lang.RuntimeException: Can't create tcpip context
	at com.adguard.corelibs.tcpip.NativeTcpIpStackImpl.init(Native Method) ~[na:0.0]
	at com.adguard.corelibs.tcpip.NativeTcpIpStackImpl.<init>(NativeTcpIpStackImpl.java:31) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.setupVpn(FilteringVpnService.java:250) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.access$000(FilteringVpnService.java:48) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService$1.run(FilteringVpnService.java:158) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
```

**Comment by sfionov** [comment] 2017-08-16 14:52
Yes. New tcpip stack instance can't be created if previous isn't closed, and that's actually happen.

**Comment by sfionov** [comment] 2017-08-24 11:07
Another log with new build. TCP stack was not properly closed after switching off wifi.
[tcpfail.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1248559/tcpfail.txt)

**Comment by ameshkov** [comment] 2017-08-24 11:15
@sfionov I guess we should solve it once and for all from the Java-code side

**Comment by ameshkov** [comment] 2017-08-25 18:57
Fixed in `adguard-android/pull-requests/8`

**Closed by ameshkov** 2017-08-25 18:57 UTC
Labels: P2: High, VPN
