### ISSUE TITLE
Unable to access Korean site after latest version update

### ISSUE THREAD

**Issue by sssh7710** [AdguardTeam/AdguardForAndroid#5120] opened 2023-12-23 06:32 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3

### Environment

```markdown
- OS: Android 13
- Device:Galaxy a33
- Firmware:A336NKSS5CWK2/A336NOKR5CWK2/A336NKOU5CWH1
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard DNS filter, List-KR, YousList

### What Stealth Mode options do you have enabled?

Protect from DPI

### Issue Details

Steps to reproduce:
1.Update the app to the latest version
2.Access to the Korean site
3.DNS_PROBE_FINISHED_NXDOMAIN (error)

### Expected Behavior

Ads blocked and access normally

### Actual Behavior

DNS_PROBE_FINISHED_NXDOMAIN (error)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
![Screenshot_20231223_144441_Chrome](https://github.com/AdguardTeam/AdguardForAndroid/assets/98168192/e6445646-f767-4397-a980-9fdcde1d0338)
![Screenshot_20231223_144455_Chrome](https://github.com/AdguardTeam/AdguardForAndroid/assets/98168192/eb05ffe5-9cc1-4cd5-a295-f7c53eb83603)

### Additional Information

[adguard_logs_4.3.194_2312_144547.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/13758231/adguard_logs_4.3.194_2312_144547.zip)

**Comment by sfionov** [comment] 2023-12-23 07:18
@sssh7710 Hello! We've found an issue with our rule checking code.

The problem is triggered by the fact that you have List-KR in DNS filters list. List-KR is normal filter, it is recommended to add normal filters only to main filter list. 

To workaround this issue, please disable it in DNS filters list, and use it in Adblocking filter list instead.

**Comment by sssh7710** [comment] 2023-12-23 07:29
> @sssh7710 Hello! We've found an issue with our rule checking code.
> 
> The problem is triggered by the fact that you have List-KR in DNS filters list. List-KR is normal filter, it is recommended to add normal filters only to main filter list. 
> 
> To workaround this issue, please disable it in DNS filters list, and use it in Adblocking filter list instead.
> 
> 

The same problem keeps happening

**Comment by sfionov** [comment] 2023-12-23 08:09
@sssh7710 Can you please try to restart your browser? According to your log, disabling this filter in DNS filters list should help. If not, can you please collect new log and send it to devteam@adguard.com ?

**Comment by ameshkov** [comment] 2023-12-24 15:24
Closing for now as it duplicates https://github.com/AdguardTeam/AdguardForAndroid/issues/5123

**Closed by ameshkov** 2023-12-24 15:24 UTC
Labels: Bug, Priority: P4
