### ISSUE TITLE
AdGuard v4.0 Nightly - The apps and browsers no internet connecting when turnning on ad blocking

### ISSUE THREAD

**Issue by Carlos920** [AdguardTeam/AdguardForAndroid#4437] opened 2023-02-08 10:54 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

nightly 4.0.578

### Environment

```markdown
- OS: Android 13
- Device: Xiaomi
- Firmware: MIUI 14
```

### Root access

- [x] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Social Media filter

### Issue Details

Steps to reproduce:
1. turnning on ad blocking
2. view website on browser 
3.

### Expected Behavior

the ad blocking is work 

### Actual Behavior

the browser no internet connecting

### Screenshots

<details><summary>Screenshot 1:</summary>

https://user-images.githubusercontent.com/32257015/217509744-4428dc35-0339-4470-bae9-218b0af4c139.mp4
</details>

**Comment by maxikuzmin** [comment] 2023-02-10 16:18
@Carlos920 I don't have this problem repeated. Is it repeated with other browsers?

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Carlos920** [comment] 2023-02-12 03:27
> @Carlos920 I don't have this problem repeated. Is it repeated with other browsers?
> 
> To troubleshoot this issue, we need to get additional logs.
> 
> Here's what we need you to do:
> 
> * Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
> * Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
> * Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
> * Send both files to [devteam@adguard.com](mailto:devteam@adguard.com). Mention the Github issue number and the exact time when the issue was reproduced.

Has been send.

This problem i also repeat with chrome ; (Almost all programs are like this)
all iquic are blocked

**Comment by maxikuzmin** [comment] 2023-02-13 16:25
@Carlos920 thank you! We'll check your logs

**Comment by maxikuzmin** [comment] 2023-02-14 11:59
@Carlos920 what browser version are you using? If we are talking about Chrome and Via?

**Comment by Carlos920** [comment] 2023-02-14 12:10
> @Carlos920 what browser version are you using? If we are talking about Chrome and Via?

[via](https://viayoo.com): 4.4.7
chrome: 110.0.5481.64

**Comment by maxikuzmin** [comment] 2023-02-14 12:41
@Carlos920 I noticed one peculiarity - by default https filtering is not enabled for Via browser. Also after enabling https filtering for Via browser - the browser shows "Certificate is not trusted" notifications, which means that you need root access on your device to use Via browser.
Could you also record a video of the screen with Chrome and Firefox (or any other browser for comparison)

**Comment by Carlos920** [comment] 2023-02-14 12:58
> @Carlos920 I noticed one peculiarity - by default https filtering is not enabled for Via browser. Also after enabling https filtering for Via browser - the browser shows "Certificate is not trusted" notifications, which means that you need root access on your device to use Via browser. Could you also record a video of the screen with Chrome and Firefox (or any other browser for comparison)

On this device, I have not enabled https filtering for the application, which is also true in v3 version and works normally in v3 version.
My device has not unlocked the system. All certificates cannot be moved to the system directory.

> Could you also record a video of the screen with Chrome and Firefox (or any other browser for comparison)
Does this need to enable https filtering?

**Comment by Carlos920** [comment] 2023-02-14 13:19
> @Carlos920 I noticed one peculiarity - by default https filtering is not enabled for Via browser. Also after enabling https filtering for Via browser - the browser shows "Certificate is not trusted" notifications, which means that you need root access on your device to use Via browser. Could you also record a video of the screen with Chrome and Firefox (or any other browser for comparison)

<details><summary>video:</summary>

https://user-images.githubusercontent.com/32257015/218750520-9129db7f-f9f9-46c2-88ac-4394a6cf28d2.mp4


</details>

**Comment by maxikuzmin** [comment] 2023-02-14 16:06
@Carlos920 you can read more about https filtering [here](https://adguard.com/kb/general/https-filtering/what-is-https-filtering/)
As far as I know, the latest version of Chrome is 109.0.5414.117.
The "110" versions are identified as for PC. Where did you download this version from? Is it an official update?
Have you tried to repeat the steps with a different browser? Try downloading some third browser and repeat the same please.
Is this only repeated with browsers or with other applications as well?

**Comment by Carlos920** [comment] 2023-02-15 11:30
> @Carlos920 you can read more about https filtering [here](https://adguard.com/kb/general/https-filtering/what-is-https-filtering/) As far as I know, the latest version of Chrome is 109.0.5414.117. The "110" versions are identified as for PC. Where did you download this version from? Is it an official update? Have you tried to repeat the steps with a different browser? Try downloading some third browser and repeat the same please. Is this only repeated with browsers or with other applications as well?

1.  I update Chrome from google play store
2.  In edge and firefox it have the same problem.

<details><summary>video:</summary>

https://user-images.githubusercontent.com/32257015/219014974-a87e2d63-0427-4749-9243-5f3bf97baac1.mp4

</details>

<details><summary>Screenshot:</summary>

![Screenshot_2023-02-15-19-21-58-290_com miui securitycenter](https://user-images.githubusercontent.com/32257015/219015668-cd236c65-1da5-4593-8374-a336f469a21d.jpg)

</details>

**Comment by maxikuzmin** [comment] 2023-02-15 13:31
@Carlos920 to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

I'd also like to see your settings. Please export your settings and attach them to your email

**Comment by Carlos920** [comment] 2023-02-16 12:12
> @Carlos920 to troubleshoot this issue, we need to get additional logs.
> 
> Here's what we need you to do:
> 
> * Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
> * Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
> * Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
> * Send both files to [devteam@adguard.com](mailto:devteam@adguard.com). Mention the Github issue number and the exact time when the issue was reproduced.
> 
> I'd also like to see your settings. Please export your settings and attach them to your email

Has been sent

**Comment by maxikuzmin** [comment] 2023-02-16 17:16
@Carlos920 thank you! We need some time

**Comment by maxikuzmin** [comment] 2023-03-22 16:38
@Carlos920 please clarify, does it work with outbound proxy and DNS turned off?
Try repeating the steps with one of these functions disabled, and both.  We need debug logs with these configurations

**Comment by maxikuzmin** [comment] 2023-03-29 16:14
@Carlos920 we already know about this problem [here](https://github.com/AdguardTeam/AdguardForAndroid/issues/4545).
Does it work with outbound proxy and DNS turned off?
Did you send logs with outbound proxy and DNS turned off?

**Comment by maxikuzmin** [comment] 2023-04-10 10:01
@Carlos920 any news?

**Comment by Carlos920** [comment] 2023-04-11 00:01
> @Carlos920 any news?

Sorry, I've been busy recently.
log has been sent.
It works fine when dns protection is off, but if I want to access sites blocked by Great Wall I have to use both dns protection and proxy.

By the way, when I use Automatic proxy and dns protection, it works fine, but it is not stable when the network is switched.

**Comment by maxikuzmin** [comment] 2023-04-17 09:30
@Carlos920 thank you, we will need some more time

**Comment by Carlos920** [comment] 2023-04-27 00:17
> @Carlos920 problem is probably caused by the fact that the dns proxy cannot bootstrap servers, because bootstrap requests are dropped. Try setting a secure bootstrap, such as https://1.1.1.1/dns-query. If 1.1.1.1 is banned, then you need to try another one, the main thing is to have ip in the address instead of hostname. Please let us know the result

I tried with google dns and cloudflare dns but it doesn't work in local vpn mode

**Comment by maxikuzmin** [comment] 2023-05-11 14:17
@Carlos920 could you be more specific about which addresses you tried to connect? Have you tried IP addresses?

@nzube11 have you tried what is described above?
Try setting a secure bootstrap, such as https://1.1.1.1/dns-query. If 1.1.1.1 is banned, then you need to try another one, the main thing is to have ip in the address instead of hostname.
Please let us know the result

**Comment by nzube11** [comment] 2023-05-13 15:21
> @Carlos920 could you be more specific about which addresses you tried to connect? Have you tried IP addresses?
> 
> @nzube11 have you tried what is described above? Try setting a secure bootstrap, such as https://1.1.1.1/dns-query. If 1.1.1.1 is banned, then you need to try another one, the main thing is to have ip in the address instead of hostname. Please let us know the result

@Carlos920 How would I try setting that in the Android app?

**Comment by maxikuzmin** [comment] 2023-05-17 16:48
@nzube11 are you talking about adding a DNS server?
@Carlos920 any news?

**Comment by Carlos920** [comment] 2023-05-18 11:29
> @nzube11 are you talking about adding a DNS server? @Carlos920 any news?

It seems that the traffic request of vpn has not passed through dns.

https://github.com/AdguardTeam/AdguardForAndroid/assets/32257015/0572b38a-7377-4dc7-940b-5ff305c228d2

Perhaps there can be another dns configuration dedicated to vpn.

**Comment by maxikuzmin** [comment] 2023-05-18 15:28
@Carlos920  problem is probably caused by the DNS proxy cannot bootstrap servers, because bootstrap requests are dropped. It happens that some DNS server addresses in some countries are blocked.  In the video, you choose a DNS from a list. Please try setting a secure bootstrap manually, for example add https://1.1.1.1/dns-query to the DNS manually. If 1.1.1.1 is banned, then you need to try another one, the main thing is to have ip in the address instead of hostname.
Please let us know the result

**Comment by Carlos920** [comment] 2023-05-19 11:46
> @Carlos920 problem is probably caused by the DNS proxy cannot bootstrap servers, because bootstrap requests are dropped. It happens that some DNS server addresses in some countries are blocked. In the video, you choose a DNS from a list. Please try setting a secure bootstrap manually, for example add https://1.1.1.1/dns-query to the DNS manually. If 1.1.1.1 is banned, then you need to try another one, the main thing is to have ip in the address instead of hostname. Please let us know the result

It dosn't work.

The Chinese network environment sometimes cannot use these dns, so I need to access the dns service of Clash, but it cannot work normally in adguard, and other software does not have this problem.

https://github.com/AdguardTeam/AdguardForAndroid/assets/32257015/86af89c5-b20d-41c4-a295-973dfec46d98

**Comment by maxikuzmin** [comment] 2023-05-23 12:33
@nzube11 @Carlos920 would be nice to see your logs as well.
Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Carlos920** [comment] 2023-05-31 01:34
> @nzube11 @Carlos920 would be nice to see your logs as well. Here's what we need you to do:
> 
> * Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
> * Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
> * Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
> * Send both files to [devteam@adguard.com](mailto:devteam@adguard.com). Mention the Github issue number and the exact time when the issue was reproduced.

Has been sent

**Comment by maxikuzmin** [comment] 2023-06-06 12:16
@Carlos920 thank you! We'll check it out and come back later with feedback

**Comment by maxikuzmin** [comment] 2023-06-26 16:03
@Carlos920 it looks like https://github.com/AdguardTeam/AdguardForAndroid/issues/4769
Please try checking on version 4.1 nightly 7 or 8

**Comment by Carlos920** [comment] 2023-06-27 04:54
> @Carlos920 it looks like #4769 Please try checking on version 4.1 nightly 7 or 8

it dosn't work in local vpn model; Chrome shows `ERR_NAME_NOT_RESOLVED`

**Comment by maxikuzmin** [comment] 2023-06-28 09:15
@Carlos920 please repeat the same steps and record logs with the last nightly version.
Attach them here or send them to [devteam@adguard.com](mailto:devteam@adguard.com)

**Comment by maxikuzmin** [comment] 2023-06-30 14:21
@Carlos920 any news?

**Comment by maxikuzmin** [comment] 2023-07-03 17:58
@Carlos920 for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Closed by maxikuzmin** 2023-07-03 17:58 UTC
Labels: Priority: P4

**Comment by sfionov** [comment] 2023-10-26 07:59
Outbound proxy has "filter DNS" is on, which prevents using localhost DNS upstreams.

Fixed in DnsLibs 2.3, in which localhost DNS upstreams are not routed through proxy by default.
