### ISSUE TITLE
Kill Switch in Integrated mode 

### ISSUE THREAD

**Issue by TechieFsn** [AdguardTeam/AdguardForAndroid#5011] opened 2023-10-08 14:09 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1 (APK from AdGuard Website)

### Environment

```markdown
- OS: Android 13
- Device: Samsung S23 Ultra
- Firmware: WHD

Adguard VPN v2.5.5 (26) from Google Play
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, EasyPrivacy, Peter Lowe's Blocklist, Online Malicious URL Blocklist

### Issue Details

Ticket #500 opened, waited 5 days for follow-up answer.  Open a new request for help ticket.

Install AdGuard, certificate, HTTPS filtering, enable App Tracking plus all other homescreen icons enabled.  

Install AdGuard VPN, run in integrated mode.  Both AdGuard and AdGuard VPN work fine, block ad's well.

Try to enable Android Settings for VPN, and turn on android "Always-on VPN" for AdGuard VPN as well as "Block connections without VPN", AdGuard VPN works fine..though it blocks most (but not all ad's with AdGuard VPN, even when using AdGuard DNS.)  (Obviously can't run AdGuard with AdGuard VPN running as VPN instead of in Integrated Mode due to limitations of Android.)

Disable Adguard VPN.  Turn off both Android switches for AdGuard VPN.  Turn AdGuard Adblocker back on, confirm Run in Integrated Mode.  Turn Android "Always-on VPN" switch on for AdGuard Adblocker.  Turn on AdGuard VPN via icon in AdGuard Adblocker, confirm run in Integrated Mode.  Verify AdGuard VPN is on.  Try to turn on "Block Connections" for AdGuard VPN, AdGuard VPN disconnects with "Not Available" when trying to pick any VPN server. 

Can't seem to use "Block Connections without VPN" in Android for AdGuard Adblocker or it breaks AdGuard VPN.  Frustrated, because I sold Apple phone because at the time I did so many VPN providers were reporting problems to Apple about apps (both third party and Apple apps) bypassing their VPN (they use use the Mobile connection.)  Just one thread (there are many, ProtonVPN, etc.) https://www.michaelhorowitz.com/VPNs.on.iOS.are.scam.php

Explore AdGuard forum's, note that AdGuard can be run as Socks5 if Portal is provided by VPN manufacturer.  Confirm my Express VPN license for wife's Apple devices does not support proxy.  Confirm my license with NordVPN has expired, open ticket, confirm I can re-license it and am eligible for a 30 day trial.  That said, I have lifetime license(s) for AdGuard Adblocker, plus 5 more years licensed for NordVPN, don't really want to switch to NordVPN but will if I must to block Apps bypassing VPN.

### Expected Behavior

Want to be able to run both AdGuard Adblocker and AdGuard VPN, with both Android VPN switches running.  Don't seem to be able to do so.

### Actual Behavior

AdGuard VPN will not connect with both android switches enabled while running in Integrated Mode.  With Block Connections andriod switch off I believe this is allowing AdGuard to block ads in Apps while in Integrated mode, also allows VPN to work, but is NOT stopping apps from using Mobile connection instead of going through VPN/Router connection.  (Not certain, but am pretty sure.)

Debating dropping AdGuard VPN on my Apple iPad, Android devices, Windows computer(s), MacBook Pro, and Bootcamp on MacBook Pro and going back to NordVPN.  Been there and done that though, NordVPN does not block ad's nearly as well as AdGuard AdBlocker, though I see they also have an APK now (and proxy address) that your forums say does allow their VPN to run through AdGuard Adblocker.  

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by TechieFsn** [comment] 2023-10-08 14:25
To be clear, I turned on Block Connections in Android for Adguard VPN running alone (AdGuard AdBlocker disabled), AdGuard VPN works fine.  I try to run both AdGuard Adblocker and Adguard VPN in integrated mode, turn the block connections switch on in AdGuard Adblocker and AdGuard VPN immediately shows VPN Server not available, and internet access is then not available.

Restart Android device (leaving both android switches on for AdGuard AdBlocker).  Adguard Adblocker works fine, internet works, but dnsleaktest shows I am not running VPN (as does AdGuard VPN app.)

**Comment by maxikuzmin** [comment] 2023-10-10 13:54
@TechieFsn duplicate of #5000 
I replied to you in that issue. Please try this and follow the instructions

**Closed by maxikuzmin** 2023-10-10 13:54 UTC
Labels: Bug, Priority: P4
