### ISSUE TITLE
Adguard crashing/restarting, Samsung Pay App detected message and blocking internet randomly and needs force stop

### ISSUE THREAD

**Issue by Zainzzkk** [AdguardTeam/AdguardForAndroid#4493] opened 2023-02-21 13:32 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Android v4.0 Nightly 39

### Environment

```markdown
- OS: Android 12
- Device: Samsung 
- Firmware: Galaxy S10
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard Annoyances filter

### Issue Details

Steps to reproduce:
1. Open adguard
2. Samsung pay app detected message shows up and cleared manually
3. Adguard restarts and message shows up
4. Adguard randomly blocks internet after phone not used for some time
5. Cannot switch off protection from switch and cannot quit app from settings menu
6. Force close app and internet works again

### Expected Behavior

Adguard should stop when the switch is pressed.
Should not keep showing Samsung pay app detected message

### Actual Behavior

Adguard does not stop when using the switch on home page or using quit and continues blocking internet sometimes

### Screenshots

<details><summary>Screenshot 1:</summary>

![image](https://user-images.githubusercontent.com/51957827/220358392-063152c7-02a9-4856-afb6-6cebf8c7b6f6.png)

</details>

**Comment by Versty** [comment] 2023-02-22 09:19
@Zainzzkk Hi! 
Please update to the latest nightly version (4.0 nightly 53) and check if the issue with internet blockage persists.

**Comment by Zainzzkk** [comment] 2023-02-22 09:28
@Versty mine says I'm already using the latest version. No option to update to 53

**Comment by Versty** [comment] 2023-02-22 09:39
@Zainzzkk Got it, the best option would be to uninstall and download the latest version from [this link](https://agrd.io/android_nightly). You can transfer the settings using the Export/Import options in the context menu of the Settings tab.

**Comment by Versty** [comment] 2023-03-01 08:04
@Zainzzkk Does the update resolve the crashes and unintended internet blocking issue?

**Comment by Zainzzkk** [comment] 2023-03-01 09:17
The internet blocking issue is fixed.  However, it still regularly crashes/switches off adguard protection and the Samsung pay app detected message keeps showing up

**Comment by Versty** [comment] 2023-03-01 09:57
@Zainzzkk Samsung Pay app notification is working as intended. If you click it instead of clearing, it will disappear and won't pop up again next time.

Would you mind enabling `Auto-report crashes` and `Send technical and interactional data` options, so we can analyse crashes from your device? 

*Settings tab -> General -> Advanced*

**Comment by Zainzzkk** [comment] 2023-03-01 10:00
Those are both enabled and have been enabled for a while I think.

There is also a message about app conflict - Notifications about applications not supported by adguard or conflicting with it.  When I click on it, nothing happens

**Comment by Versty** [comment] 2023-03-01 10:23
Could you provide the screenshot of this second notification?

**Comment by Zainzzkk** [comment] 2023-03-01 10:30
![Screenshot_20230301_095915_One UI Home.jpg](https://user-images.githubusercontent.com/51957827/222113793-a67e4291-28d0-457b-8aca-5ec1e980b37a.jpg)

Here

**Comment by Versty** [comment] 2023-03-28 12:49
@Zainzzkk Hi! 
> Adguard randomly blocks internet after phone not used for some time

This issue should be fixed in the latest nightly, could you confirm?

**Comment by Versty** [comment] 2023-04-03 11:15
@Zainzzkk Closed due to no response. 
Please, reopen if needed.

**Closed** 2023-04-03 11:16 UTC
