### ISSUE TITLE
Adguard in proxy mode wont filter when using mobile data

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#558] opened 2016-05-17 12:58 UTC
When Adguard is in VPN mode, everything works as expected, but when it's put into proxy mode, it only filters on WiFi. Mobile data is not filtered.

User has his Nexus 6P running Pure Nexus ROM rooted. 

Ticket ID (logs inside): VIW-697-58365

Original thread: 
https://forum.adguard.com/index.php?threads/10423

**Comment by yochananmarqos** [comment] 2016-11-15 05:20
Why is this issue still open? I can post logs if needed. I think I'm having the same issue.

**Comment by vbagirov** [comment] 2016-11-15 15:25
@yochananmarqos I've added a milestone to speed things up. 

@Revertron can anything be done about this? Do we need anything else from yochananmarqos?

**Comment by ameshkov** [comment] 2016-11-15 22:23
@yochananmarqos the main question is the same I asked in the original forum thread: do you have any proxy in the APN settings?

**Comment by yochananmarqos** [comment] 2016-11-15 22:29
No, there is no proxy to my knowledge. The Project Fi APN is configured
automatically, I'm not able to access the setting.

**Comment by TPS** [comment] 2016-11-16 00:43
According to https://www.google.com/amp/s/amp.reddit.com/r/ProjectFi/comments/522sqm/traveling_with_project_fi/, it's likely _all_ Project Fi mobile data is proxied via US Google servers.  I'm not sure whether this is separate from [Wifi Assistant](https://support.google.com/nexus/answer/6327199?hl=en)'s VPN feature, which'd obviously be a problem, as well.

**Comment by ameshkov** [comment] 2016-11-16 17:30
@TPS I doubt it has anything to do with wi-fi assistant as it won't work until you're connected to any hotspot.

We should somehow figure out how exactly your traffic is routed. Could you please capture `tcpdump` output for us?

Here is what you need to do:
1. Connect to your device with `adb shell` command
2. While you're on mobile data, switch to root user with `su -` command and run `tcpdump` tool (you may need to get it first: http://www.androidtcpdump.com/)
3. Open the test page, reload it a few times.
4. Grab the `tcpdump` output and post it here.

**Comment by yochananmarqos** [comment] 2016-11-16 20:14
I ran `tcpdump -i any -p -s 0 -w /sdcard/capture.pcap`, hope that helps. 

I think I may have an idea. I'm using Magisk Hide & the phh superuser module. There is currently a known issue with root access being lost occasionally. Rebooting resolves the issue until it happens again. I had just rebooted before capturing the tcpdump, so it probably looks normal.

[capture.pcap.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/595796/capture.pcap.txt)

**Comment by ameshkov** [comment] 2016-11-16 21:05
@yochananmarqos could you please tell me what were happening while you've recorded it?

**Comment by yochananmarqos** [comment] 2016-11-16 21:09
I reloaded the Adguard test page a few times like you asked.

**Comment by ameshkov** [comment] 2016-11-16 21:24
I just see a few AG proxy connections and nothing suspicious (i suspected there will be some udp connections maybe). That's  just weird.

Could you please redo the test and collect Adguard logs as well? I'll compare it with the pcap.

**Comment by yochananmarqos** [comment] 2016-11-16 22:26
Here you go:
[adguard.log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/596064/adguard.log.txt)

**Comment by ameshkov** [comment] 2016-11-21 08:59
@yochananmarqos sorry for the late reply.

1. Do you have "data compression" enabled in Chrome settings?
2. Does it help to manually stop/start AG protection **right after** you have switched to the mobile data?

Also I meant to collect both pcap and corresponding AG log. The thing is that I'd like to compare them in order to understand which connections are missing in AG log.

**Comment by yochananmarqos** [comment] 2016-11-23 18:32
@ameshkov 

1. Yes
2. No

I figured out that Adguard works while on Wi-Fi and Sprint, but does not work while on T-Mobile. I suspect it's due to the default APN protocol is set to IPv6 instead of IPv4/IPv6. Apparently it causes issues with OpenVPN as well: https://www.reddit.com/r/ProjectFi/comments/3selvy/editing_apn_settings_on_fi/

I recorded a tcpdump & full Adguard log while disconnecting from Wi-Fi, reloading the Adguard test page a few times while connected to T-Mobile, then turning Wi-Fi back on & refreshed it again.

[capture.pcap.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/609703/capture.pcap.txt)
[adguard.log.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/609704/adguard.log.txt)

**Comment by ameshkov** [comment] 2016-11-25 18:14
@yochananmarqos yeah, IPv6 may be the culprit.

You see, in proxy mode Adguard uses `iptables` to perform traffic redirect. The first problem is that `iptables` does not control IPv6 traffic, so it slips through.

The second problem is that `ip6tables` does not support traffic redirection. It could be used for a bit different TPROXY redirect which is much more complicated (that's why we still didn't implement it). 

So, as a temporary solution, we've implemented a low-level setting for blocking ipv6 completely. However, i am not sure if it is safe to use it when APN is set to IPv6.

**Comment by ameshkov** [comment] 2017-06-01 08:16
Marked as duplicate of this issue:
https://github.com/AdguardTeam/AdguardForAndroid/issues/580

**Closed by ameshkov** 2017-06-01 08:16 UTC
Labels: Duplicate, Question
