### ISSUE TITLE
Adguard Android lost internet on some apps while others are working

### ISSUE THREAD

**Issue by sdugoten** [AdguardTeam/AdguardForAndroid#5191] opened 2024-01-27 12:07 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.1

### Environment

```markdown
- OS: Android 14
- Device: Pixel 8 Pro
- Firmware:UQ1A.240105.004
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. Install Adguard and login with my username and password
2. Turn on Adguard and have HTTPS filtering enabled
3. Just use as usual, and it works when it is installed
4. Leave the phone idle for 15 mins or so without using it
5. Some apps would lose Internet access, for example I know the following apps would be affected, might be more but I didn't test.
https://play.google.com/store/apps/details?id=com.apple.android.music&hl=en&gl=US
https://play.google.com/store/apps/details?id=com.flightradar24free&hl=en&gl=US
https://play.google.com/store/apps/details?id=com.lihkg.app&hl=en&gl=US

Browser like Chrome is working just fine, just some of the apps would not have Internet access.  Recent activity also show no trace of that app until I turn off Adguard completely.

### Expected Behavior

It should work on all apps

### Actual Behavior

Lost Internet access on some apps listed in issue details.  Restarting the phone also would NOT fix the issue.   

### Screenshots

<details><summary>Screenshot 1:</summary>

none

</details>

### Additional Information

_Logs have been deleted for privacy reasons._

See debug log here.  I enabled the debug and then tried to access apps that is known not working

**Comment by yayyayyay7** [comment] 2024-01-28 12:14
I have the same thing, oppo neo9

**Comment by maxikuzmin** [comment] 2024-01-29 16:27
@sdugoten @yayyyayyayyay7 how often does this happen? Does it recur consistently or randomly? 
Try disabling HTTPS filtering for these apps. Will that fix the problem?

**Comment by sdugoten** [comment] 2024-01-29 16:45
As mentioned earlier, recent activity also not showing anything for those affected app.  That means those apps is not able to route to Adguard correctly somehow and therefore lost Internet access.

You can *sometimes* to get those apps working again by keep opening and closing the affected app.   Eventually, the app would load and Internet access is back...........until you leave the phone idle again.

**Comment by Real1tys** [comment] 2024-02-06 09:13
Microsoft Teams seems to suffer from this too... randomly Internet works again but for the most part it doesn't. As soon as I disable AdGuard it works again.

**Comment by maxikuzmin** [comment] 2024-02-06 16:52
@Real1tys unfortunately, there is not much information in the logs. Could you please repeat the steps, wait until the internet stops working for one of the applications, and then upload the logs and send them to [devteam@adguard.com](mailto:devteam@adguard.com)?

Please don't forget to enable Debug logging level, and also in the email include the time the problem was reproduced and issue number 5191

**Comment by maxikuzmin** [comment] 2024-02-12 15:31
@Real1tys any news?

**Comment by maxikuzmin** [comment] 2024-02-15 18:51
@Real1tys for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Closed by maxikuzmin** 2024-02-15 18:51 UTC
Labels: Bug, Priority: P4
