### ISSUE TITLE
AdGuard icon flickering between dark and light variants

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#1744] opened 2018-03-02 01:45 UTC
The AdGuard icon is flickering between dark and light variants when viewing the notification drawer. Either switches depending on the drawer status, or flickers in particular circumstances. 

### Steps to reproduce
1. Enable AdGuard
2. Open and close the notification drawer to see the issue

### Expected behavior
Icon remains in its previous state due to the same environment, no icon modification required.

### Actual behavior
Icon switches to a light variant depending on the height of notification. Managed to get it stuttering or flickering really fast at one point, before recording it.

### Video recording
https://ufile.io/6xqkr

### Environment
* Adguard version: 2.10
* Adguard filtering mode: VPN
* Device model: Nokia 6, TA-1033
* Operating system and version: Android Oreo 8.0.0
* Rooted or not? No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? None

**Comment by Revertron** [comment] 2018-03-02 07:12
Did you see the system notification icon on your video?
It behaves the same - changes from gray to blue, and to gray again :)
It seems that it is a "feature" of Android OS you are using.

**Comment by planet0** [comment] 2018-03-02 07:25
> Did you see the system notification icon on your video?
> It behaves the same - changes from gray to blue, and to gray again :)

That was me manually expanding and minimising the system icon by tapping on it, not Android itself. It shows blue when I decide to expand the system notification.

I've uploaded another recording as I was able to capture the flickering. This time I didn't touch the system icon to show you that it is only Adguard behaving this erratically. Before this new recording, I updated from stable to Nightly 2.11.32.

Definitely something not right with Adguard's icon as no other app I use does this with their notification icon.

https://ufile.io/26weu

**Comment by planet0** [comment] 2018-03-02 07:52
> Did you see the system notification icon on your video?
> It behaves the same - changes from gray to blue, and to gray again :)

@Revertron, that was me manually expanding and minimising the system icon by tapping on it, not Android itself. It shows blue when I decide to expand the system notification.

--

I've uploaded another recording as I was able to capture the flickering. This time I didn't touch the system icon to show you that it is only Adguard behaving this erratically. As a side note, before this new recording, I updated from stable to Nightly 2.11.32.

Definitely something not right with Adguard's icon as no other app I use does this with their notification icon. LastPass for example works without any issue.

https://ufile.io/5w05u

**Comment by Revertron** [comment] 2018-03-02 07:56
I don't get your logic.
When you touch system icon it changes it's color (it doesn't bother you). When you touch AdGuard's icon it changes it's color too (it bothers you).
What is the difference and the problem?

**Comment by planet0** [comment] 2018-03-02 08:03
> I don't get your logic.

When I expand the system notification, the icon turns blue and stays blue. When I want to minimise the system notification, the icon then turns back to gray. That's fine, it's expected.

When I try to expand or minimise the entire Android notification drawer, AdGuard's icon flickers super fast (as you can see in the video) even though I'm not interacting with AdGuard's notification, I'm just slowly expanding or exiting the entire Android notification drawer.

To behave like all the other icons, it should remain gray since all I'm doing is viewing Android's notification drawer. For me, the icon flicking between gray and white every 1 millisecond, and for the AdGuard icon being the only one to do so, even though I'm not doing anything with the notification in the first place, doesn't seem right at all.

**Comment by Revertron** [comment] 2018-03-02 08:19
Hm, I didn't see the flickering for the first time. It really is strange...

**Comment by ameshkov** [comment] 2018-03-03 23:50
That's a gray overlay that Android draws over the white icon we use for the notification. I wonder do you see anything like that with other apps that have a persistent notification?

**Comment by planet0** [comment] 2018-03-04 02:35
> I wonder do you see anything like that with other apps that have a persistent notification?
I haven't seen it occur with any other icon as of yet in Oreo. The other persistent notifications on my device so far have been Twilight, LastPass and Android system.

**Comment by admitrevskiy** [comment] 2018-04-05 08:46
@planet0, hello! Do you observe the same behavior in the latest beta-version?

**Comment by planet0** [comment] 2018-04-05 09:18
Hi @admitrevskiy, I do, and I found it easy to replicate when playing a song on Spotify and Spotify displays their notification with controls and album art.

**Comment by admitrevskiy** [comment] 2018-04-05 11:14
@planet0, are the notifications from LastPass and Twilight gray or colored? You wrote that there is no problems with this apps.

**Comment by planet0** [comment] 2018-04-10 12:27
@admitrevskiy This might help — I found that the AdGuard icon turns white at a certain point, and is the only app to do so. Perhaps this may be an underlying cause for the flickering between normal state and this white 'minimised' state.

So here is the normal state, icon fine.

![screenshot_20180410-221214 2](https://user-images.githubusercontent.com/36845626/38556488-3583e4ce-3d0d-11e8-83f7-9a0be3a7ea34.png)

Then I start to swipe up to minimise the notifications. The AdGuard icon turns white. It should not change.

![screenshot_20180410-221201 2](https://user-images.githubusercontent.com/36845626/38556727-09d8d70c-3d0e-11e8-9e17-467a95d254f6.png)

I keep swiping up... Should be gray at this point.

![screenshot_20180410-221458 2](https://user-images.githubusercontent.com/36845626/38556763-26a5086a-3d0e-11e8-9234-55d82bb354bc.png)

Bit more, and the icon turns into a white dot. It should be a grey dot.

![screenshot_20180410-221510 2](https://user-images.githubusercontent.com/36845626/38556789-3bf211b8-3d0e-11e8-9cee-fa21cc27551d.png)

Finally, all notifications are minimised, including the system notification which is a grey dot. AdGuard, however, is still white.

![screenshot_20180410-221526 2](https://user-images.githubusercontent.com/36845626/38556819-4dc7bbea-3d0e-11e8-9c10-4e9cbd1e344d.png)

**Comment by ameshkov** [comment] 2018-06-21 07:47
We still cannot reproduce this issue and tbf I've no clue what could it be:(

Marking as "Cannot reproduce" for now.

**Closed** 2020-03-20 16:22 UTC
Labels: Bug, Cannot reproduce, P3: Medium, UI
