### ISSUE TITLE
No internet when using AdGuard along with the OpenVPN Connect app

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#1656] opened 2017-12-18 17:34 UTC
After AdGuard update, when using VPN app ([OpenVPN Connect' app](https://play.google.com/store/apps/details?id=net.openvpn.openvpn)), the internet does not work. I tried disabling app management in AdGuard but couldn't too. If I turn off AdGuard, VPN works well. I'm using 'high-quality filtering method' and 'HTTPS filtering' and 'automatic
local proxy setup mode' in AdGuard. The exact time is pm 5:03~5:04 KST

[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1568893/debug.txt)

### Customer ID 
1503049

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: Proxy(auto)
* Device model: Samsung hlte
* Operating system and version 7.1.2
* Rooted or not? +
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? N/A

**Comment by zebrum** [comment] 2017-12-26 14:30
@nkartyshov @Revertron please take a look. 
I can't reproduce the issue.

**Comment by zebrum** [comment] 2017-12-27 14:20
@evgeniy-ADG aks user if filtering enabled for Open VPN Connect app in  Apps Management?

**Comment by ameshkov** [comment] 2018-01-02 21:25
@evgeniy-ADG any update?

Meanwhile, I'll close this issue as I'm pretty sure it's caused by misconfiguration.

**Closed by ameshkov** 2018-01-02 21:25 UTC
Labels: cannot reproduce
