### ISSUE TITLE
Critical Error: Deadlock caused by slow write operations

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#238] opened 2015-12-17 15:46 UTC
User consistently gets critical errors. Log is attached.

[debug (54).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/65573/debug.54.txt)

OKE-297-69864

**Comment by ameshkov** [comment] 2015-12-17 15:49
That's what causing it:
```
Thread:	15035	pool-3-thread-10	RUNNABLE
-2 libcore.io.Posix.sendtoBytes(Native Method)
198 libcore.io.Posix.sendto(Posix.java:198)
270 libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:270)
527 libcore.io.IoBridge.sendto(IoBridge.java:527)
403 java.nio.SocketChannelImpl.writeImpl(SocketChannelImpl.java:403)
361 java.nio.SocketChannelImpl.write(SocketChannelImpl.java:361)
-1 com.adguard.commons.io.SocketChannelOutputStream.write(Unknown Source)
-1 com.adguard.android.filtering.vpn.BaseVpnConnection.writeToServer(Unknown Source)
-1 com.adguard.android.filtering.vpn.VpnTcpConnection$2.onReceived(Unknown Source)
-1 com.adguard.android.filtering.lwip.TcpConnectionImpl.tcpReceive(Unknown Source)
-1 com.adguard.android.filtering.lwip.TcpConnectionImpl.tcpProcessEstablished(Unknown Source)
-1 com.adguard.android.filtering.lwip.TcpConnectionImpl.tcpProcess(Unknown Source)
-1 com.adguard.android.filtering.lwip.TcpConnectionImpl.tcpInput(Unknown Source)
-1 com.adguard.android.filtering.vpn.VpnTcpConnection.tcpInputOpened(Unknown Source)
-1 com.adguard.android.filtering.vpn.VpnTcpConnection.addBrowserInputPacket(Unknown Source)
-1 com.adguard.android.filtering.vpn.BaseVpnConnection$1.run(Unknown Source)
1112 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
587 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
818 java.lang.Thread.run(Thread.java:818)
```

**Comment by ameshkov** [comment] 2015-12-17 15:56
@vbagirov i suppose stable version should work good

**Comment by vbagirov** [comment] 2015-12-17 16:15
@ameshkov No, he probably hasn't. I will suggest him to try it out.

**Comment by ameshkov** [comment] 2015-12-17 16:39
@vbagirov please notify me of any updates on this

**Comment by ameshkov** [comment] 2015-12-19 10:49
@vbagirov any update?

**Comment by evgeniy-ADG** [comment] 2015-12-19 16:22
@ameshkov an update from the customer 
[debug (5).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/67517/debug.5.txt)
KGQ-582-54420

**Comment by ameshkov** [comment] 2015-12-21 16:16
@evgeniy-ADG or @vbagirov 

Please ask user to try the latest beta version (2.1.344). The issue should be resolved in this version.

**Comment by vbagirov** [comment] 2015-12-22 11:45
No reply so far.

**Comment by ameshkov** [comment] 2015-12-29 09:15
@vbagirov still no reply?

**Comment by vbagirov** [comment] 2015-12-29 11:43
According to user, everything is fine in the latest beta. No critical errors.

**Comment by ameshkov** [comment] 2015-12-29 12:13
Great, thank you!

**Comment by vbagirov** [comment] 2016-02-29 16:57
[debug (68).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/151337/debug.68.txt)

Looks like the issue is back in this case:
XTJ-416-98442

**Comment by ameshkov** [comment] 2016-02-29 21:31
Not a bug (and it definitely should be a new issue, no need to reopen this one).

The issue is caused by "java.net.ConnectException: failed to connect to /104.244.43.7 (port 80): connect failed: EMFILE (Too many open files)"

"Too many open files" error means that there are too many open connections. Seems that some app goes mad.

To find out which app has done it I need to see full log file, not enough data in the one you have attached.

@vbagirov one more thing, do not attach log files to issues, it may contain user's private data.

**Closed by ameshkov** 2016-02-29 21:31 UTC
Labels: Bug

**Comment by vbagirov** [comment] 2016-03-01 15:36
This was very not smart from me - attaching a debug file here. I will create a new issue once user sends a full log.
