### ISSUE TITLE
Magisk Module for System Certificate

### ISSUE THREAD

**Issue by liweichen6** [AdguardTeam/AdguardForAndroid#1919] opened 2018-06-11 18:34 UTC
Since more users are using Magisk as their root method, why not create a Magisk module to install system certificate? This way the true system folder is not touched, and it's pretty simple to install/uninstall.
What we need: \system\etc\security\cacerts\88cba841.0

Using the template I created this example in few minutes.
Tested on my device and so far so good.

[Adguard System Certificate.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2091237/Adguard.System.Certificate.zip)

**Comment by ameshkov** [comment] 2018-06-26 08:29
Closed as duplicate of #1928

**Closed by ameshkov** 2018-06-26 08:29 UTC
Labels: duplicate
