### ISSUE TITLE
Unable to exit from Send Feedback activity

### ISSUE THREAD

**Issue by sviperz** [AdguardTeam/AdguardForAndroid#2293] opened 2018-11-13 12:47 UTC
### Steps to reproduce
1. Go to _Support > Send Feedback_
2. Try to exit activity via back arrow in the top left corner or via system back button

### Expected behavior
The app should back to previous activity.

### Actual behavior
Nothing happens until any of _Feedback types_ is chosen.

Also, it helps to switch off screen and switch it on again, then _Feedback types_ list is disappear and all methods to go back to previous activity start working as expected.

### Environment
* Adguard version: v3.0.56
* Adguard filtering mode: VPN
* Device model: Google Pixel 3
* OS: Android 9
* No root

**Comment by ameshkov** [comment] 2018-11-13 13:00
Duplicate of #2273

**Closed by ameshkov** 2018-11-13 13:00 UTC
Labels: Duplicate
