### ISSUE TITLE
AdGuard 3.0.241 crashes when accessing the Language-specific filters section 

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2563] opened 2019-02-16 10:05 UTC
ID: 2117035

> While opening filter section and clicking on other language section, the app crashes (before clicking language section) I enabled all of the other filters, but on clicking language filter the app crashes

ID: 2117444

> Specific language filters not working, its shows AdGuard stopped working. Please solve this issue as soon as possible. Thank you...

ID: 1099564

> Unable to open "language specific" under "filter content"

ID: 1968599

> The first time I opened the Language-specific filters tab it worked flawlessly. Every time since then it has resulted in a crash before even opening the list.

### Steps to reproduce

1. Update to the first v.3.x beta
2. Go to AdGuaard > Settings > Content Blocking > Filters > Language-specific
3. If needed, repeat step 2

### Expected behavior

The Language-specific filters settings are opened

### Actual behavior

AdGuard stops responding

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/52898110-b3c65400-31e2-11e9-8015-c4ce5368d40d.png)

</details>

### Customer ID 
multiple reports, see some of the tickets' numbers above

### Your environment

* Adguard version: 3.0.241
* Adguard filtering mode: VPN
* Device model: Pixel 2 XL, ASUS_X01BDA, SM-C900F
* Operating system and version 8.0.0, 8.1.0, 9
* Rooted or not? n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by ameshkov** [comment] 2019-02-18 09:02
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/2555

**Closed by ameshkov** 2019-02-18 09:02 UTC
