### ISSUE TITLE
Tasker does not work with version 4.0

### ISSUE THREAD

**Issue by whyisthisbroken** [AdguardTeam/AdguardForAndroid#4395] opened 2023-01-31 15:27 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Latest 4.0 nightly

### Environment

```markdown
- OS:Android 13
- Device: Google Pixel 5
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Tasker can't deactivate or activate the DNS Protection Mode.
Before was no problem. 

I set a new tasker command but nothing happens.

### Expected Behavior

Tasker can switch DNS Protection On \ Off

### Screenshots

![Screenshot_20230131-162614](https://user-images.githubusercontent.com/96284773/215802930-f0405a57-e6d9-4d3d-bea4-42839ef68fb7.png)

**Comment by whyisthisbroken** [comment] 2023-02-05 01:28
Since the nightly is out and 2 updates further - tasker didn't work.
Got now answer here or support. Nice.
I don't know but this release should be back rolled. It's a complete nightmare...
Not only with the functionality with tasker. 50% doesn't work anymore

**Comment by maxikuzmin** [comment] 2023-02-07 18:02
@whyisthisbroken could you please specify which version of Tasker you use, and what type of task you choose to deactivate or activate the DNS Protection Mode?

**Comment by whyisthisbroken** [comment] 2023-02-07 18:05
Tasker : https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm

And then the task like the description in the Adguard help.
See here:
https://adguard.com/kb/adguard-for-android/solving-problems/tasker/

**Comment by TPS** [comment] 2023-02-07 23:03
I'm reasonably certain _none_ of the Tasker integration works anymore, as that's how my setup is acting.

**Comment by maxikuzmin** [comment] 2023-02-08 10:11
@whyisthisbroken as far as I know, the functionality with the Tasker app has been transferred to 4.0. We need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment] 2023-02-08 10:34
@whyisthisbroken @TPS in version 4.0 a different API, so this behavior is now observed with the Tasker application. 
A bit later we will provide a build to work with the Tasker application

**Comment by TPS** [comment] 2023-02-08 11:29
Wow!  I thought this was mainly UI changes recently, not backend rewrite also.  This automation is important for my setup, so I do hope to get that soon!

**Comment by maxikuzmin** [comment] 2023-02-08 17:44
@whyisthisbroken It actually turned out better than that. You have an error in "Class". It shouldn't have an S in receivers.
Write in the Class field: com.adguard.android.receiver.AutomationReceiver

**Comment by maxikuzmin** [comment] 2023-02-08 17:46
@TPS let's see what is written in your "Action", the problem is not in the API after all. Please send a screenshot of your "Action"

**Comment by TPS** [comment] 2023-02-10 03:47
These used to work flawlessly before v4.0n39:
<details>
![Tasker AG Update.png](https://user-images.githubusercontent.com/185902/217995603-738480f6-be33-4ae8-b755-6d2aa3cbd61b.png)
</details>
<details>
![Tasker AG Start.png](https://user-images.githubusercontent.com/185902/217995604-fb777956-4e9e-4d64-bdd6-adac0c2095f5.png)
</details>

**Comment by jwds1178** [comment] 2023-02-10 10:11
> @TPS let's see what is written in your "Action", the problem is not in the API after all. Please send a screenshot of your "Action"

As I'd mentioned in issue #4449, I was having the same problem with AdGuard not responding to Tasker's intents.  After reading your response regarding the Class, I checked mine, and indeed it had `com.adguard.android.receivers.AutomationReceiver` configured for its Class.

Given that, I changed the Class of my Tasker intents to `com.adguard.android.receiver.AutomationReceiver`.  They started working once I made the Class change.

With that said, when I configured these new intents, I'd done so using [your knowledgebase article](https://adguard.com/kb/adguard-for-android/solving-problems/tasker/) as a guide.  At the end of its [Available Actions](https://adguard.com/kb/adguard-for-android/solving-problems/tasker/#available-actions) section, the article specifies the Class should be `com.adguard.android.receivers.AutomationReceiver`.

**Comment by maxikuzmin** [comment] 2023-02-10 14:22
@whyisthisbroken @TPS @jwds1178 I'm glad we got this issue sorted out.
We'll be sure to correct the information in the knowledge base

**Comment by TPS** [comment] 2023-02-10 18:40
That solves me, also.  Thanks!

**Closed** 2023-02-13 12:39 UTC

**Comment by DrSuSE** [comment] 2023-04-08 04:34
Managed to find my way here while having the same issue. As a reminder, the documentation is still incorrect.
