### ISSUE TITLE
Issue while activation with wrong license key

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3110] opened 2019-10-04 14:03 UTC
The application informs about an app error while you trying to activate it with a wrong license key in case it does not appear the same way if you try to activate with wrong credentials in the Account section.

**Steps to reproduce**

1. Open AdGuard - License - License Key
2. Try to enter random symbols 
3. Hide the keyboard and tap on Activate

<details>

![image](https://user-images.githubusercontent.com/37797229/66213575-ba013600-e6c8-11e9-8eae-b90f93880084.png)

</details>

**Expected result:**

It should inform you about wrong credentials without displaying an error

**Actual result:**

The error appears (see the screenshot)

**Comment by artemiv4nov** [comment] 2019-10-11 15:44
Partly duplicate of #3118

**Closed by artemiv4nov** 2019-10-11 15:44 UTC
Labels: Bug, P3: Medium, UI
