### ISSUE TITLE
HTTPS filtering is breaking Nimses app functionality

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1273] opened 2017-06-11 18:10 UTC
HTTPS filtering is breaking Nimses app functionality
https://play.google.com/store/apps/details?id=com.nimses&hl=en
<details>

![image](https://user-images.githubusercontent.com/25711093/27013322-6397d6d4-4eea-11e7-8dc5-1c14d12cde0f.png)
</details>
CustomerID:1277354

**Comment by zebrum** [comment] 2017-06-13 16:00
confirmed
need to exclude com.nimses from https filtering @nkartyshov

**Comment by vozersky** [comment] 2017-06-13 17:39
@Michael23456  they use certificate pinning, won't fix, tell the user to disable https filtering for the app, we will exclude it in the next build

**Comment by Michael23456** [comment] 2017-06-16 05:18
forwarded to the customer

**Comment by ameshkov** [comment] 2017-06-19 09:30
Disabled by default for this app since new build

**Closed by ameshkov** 2017-06-19 09:30 UTC
Labels: Compatibility, SSL
