### ISSUE TITLE
Speedtest doesn't work correctly with Adguard on.

### ISSUE THREAD

**Issue by Fridrix** [AdguardTeam/AdguardForAndroid#741] opened 2016-08-06 09:19 UTC
<details>
![image](https://cloud.githubusercontent.com/assets/20476168/17455921/b9e37cfa-5bcf-11e6-9f97-c7e39ffa4406.png)
![image](https://cloud.githubusercontent.com/assets/20476168/17455922/c052df68-5bcf-11e6-8d2c-d16b4b84347c.png)
![image](https://cloud.githubusercontent.com/assets/20476168/17455924/c5d7351a-5bcf-11e6-9ba6-bf22d9aa96f0.png)
My screenshots
</details>
[Downloads.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/404947/Downloads.zip)
Costumer video.

**Comment by evgeniy-ADG** [comment] 2016-08-08 09:57
We have a bunch of similar request in support as well. Please check: 1387316, 1373915 (we have screencasts here), 1388935

**Comment by ameshkov** [comment] 2016-08-08 12:02
@evgeniy-ADG please ask users to change the "pref.vpn.mtu" value to something smaller (like 4000 for instance).

**Comment by Fridrix** [comment] 2016-08-09 13:01
@ameshkov  tested. download speed was increased up to 6 Mb/s. Upload is correct (3.8 Mb/s). With Adguard disabled download: 14.79, upload 3.91.

**Comment by ameshkov** [comment] 2016-08-09 13:14
@Fridrix what exact device does the customer use?

**Comment by Fridrix** [comment] 2016-08-09 14:09
@ameshkov  i tested on my device - Lenovo S860. Issue persists also on Samsung and HTC ONE X devices.

**Comment by ameshkov** [comment] 2016-08-09 14:14
@Fridrix Android KitKat on all these devices right?

**Comment by Fridrix** [comment] 2016-08-09 14:23
@ameshkov  Android 6.0.1 version all the devices.

**Comment by ameshkov** [comment] 2016-08-09 14:29
Ok, that is something new. Assigned to v2.8 milestone.

**Comment by Fridrix** [comment] 2016-08-09 16:07
@ameshkov i will notice you if i notice other details.

**Comment by TPS** [comment] 2016-11-01 15:08
I always wondered:  Various speedtests measure speed (in part) by ↑/↓loading something, right?  What's the _payload_ of these transfers?  Ads, sometimes, maybe?

**Comment by ameshkov** [comment] 2016-11-02 11:03
Nope, it just downloads some random txt files.

Btw, it seems that the issue is resolved on the speedtest app side.

**Closed by ameshkov** 2016-11-02 11:03 UTC
Labels: Bug
