### ISSUE TITLE
Far EasTone (Taiwan) WiFi calling doesn't work

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/AdguardForAndroid#2443] opened 2019-01-18 14:09 UTC

**Comment by ameshkov** [comment] 2019-02-18 13:37
Duplicate of #2550

**Closed by ameshkov** 2019-02-18 13:37 UTC
Labels: Compatibility, P3: Medium

**Comment by lancelot-moon** [comment] 2019-03-05 04:42
@ameshkov

Have you exclude the IP range of Far EasTone Wi-Fi calling (Taiwan) from the filtering?

Solved in v3.0.264 nightly?
Or did you not get the log so you didn't solve this?

The Taiwanese user reported that AG team still didn't solve the issue.
He contacted and gave the log to AG support, but nothing was solved during that 1 month.
Finally he gave up because he felt tired.

**Comment by ameshkov** [comment] 2019-03-05 09:40
No, it's `pref.excluded.uids` that does the job.

> Maybe they all use AG v2.12...

Most likely they are.
