### ISSUE TITLE
[Feature Request] Randomise MAC and IP when pinging / connecting to a wifi point

### ISSUE THREAD

**Issue by versavius** [AdguardTeam/AdguardForAndroid#2913] opened 2019-07-11 07:44 UTC
I know we can fake the IP address in adguard, but just a thought what about randomising the IP address and Mac address every time we ping or connect to a wifi point?

You are getting companies like this one below which is tracking people by IP address:

https://www.theregister.co.uk/2019/07/10/netlify_log_analytics/

and TFL tracking by mac address:

https://www.wired.co.uk/article/london-underground-wifi-tracking

So it looks like its just a matter of time before companies start tracking by IP and mac address as above so if we started randomising these then on top of the current stealth devices we really should be difficult to track online.

**Comment by Revertron** [comment] 2019-07-11 07:46
Duplicate of #2899.

**Closed by Revertron** 2019-07-11 07:46 UTC
Labels: Duplicate, Wontfix
