### ISSUE TITLE
AG via proxy tile

### ISSUE THREAD

**Issue by ham3dt** [AdguardTeam/AdguardForAndroid#1878] opened 2018-05-19 09:32 UTC
tapping on adguard via proxy tile connect the orbot/tor but it don't turn orbot off if you tap on it again, so i think it would be a cool feature if the integration can turn on/off orbot with adguard via proxy tile.

**Comment by ameshkov** [comment] 2018-05-21 07:55
Sounds like a duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/1858

This one should've been resolved in the latest nightly, could you please verify it?

**Closed by ameshkov** 2018-05-21 07:55 UTC
