### ISSUE TITLE
Lost internet connection v.4.39 Nightly 

### ISSUE THREAD

**Issue by U0101100** [AdguardTeam/AdguardForAndroid#4398] opened 2023-01-31 20:55 UTC
_Logs have been deleted for privacy reasons._
[###]Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.39 Nightly 

### Environment

```markdown
- OS:Android 12
- Device:SM-N975F 
- Firmware: Samsung

Network connection not working properly when adguard is on .
Connection has been stopped working and crashing .
I must restarting phone and / or paused protection.
Now I used the Quit function to get the connection back at all.
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, Adblock Warning Removal List, Online Malicious URL Blocklist, Spam404, Polish GDPR-Cookies Filters, Polish Social Filters, I don't care about cookies, Polish Anti Adblock Filters

### What Stealth Mode options do you have enabled?

Hide your search queries, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Disable WebRTC, Block Push API, Block Location API, Block Flash, Disable Windows Telemetry, Turn off Advertising ID, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Protect from DPI

### Issue Details

Completely lost any Internet connection when adguard working.  

### Expected Behavior

Fix this 

### Screenshots

Not created

**Comment by maxikuzmin** [comment] 2023-02-06 18:25
@U0101100 thank you! We are aware of this problem and have already received some information from the users about it. If you manage to reproduce it again, please record the debug logs.

Here's what we need you to do:


- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by Batman2814** [comment] 2023-02-17 16:37
I believe this problem is on the stable version of Adguard for Android where I'm having internet problems seeing connected without internet

**Comment by maxikuzmin** [comment] 2023-03-01 09:59
@U0101100 @Batman2814 is this problem still recurring on the latest nightly version?

**Comment by Batman2814** [comment] 2023-03-01 17:15
Yes just installed the Nightly happen when I turned on adguard vpn then no internet connection.

**Comment by Batman2814** [comment] 2023-03-01 18:22
also, it only happens when using my cellular data. it works fine when I am on my wi-fi.

**Comment by Batman2814** [comment] 2023-03-02 12:50
Just lost an internet connection on my wifi network when Adguard for Android Nightly is enabled. Had to disable adguard to connect to the internet.

**Comment by Batman2814** [comment] 2023-03-02 12:50
This needs to be fixed with the next update.

**Comment by maxikuzmin** [comment] 2023-03-03 12:27
@Batman2814 hmm, I don't have this problem repeatedly. Can I ask you to repeat this and send debug logs with the time of the problem to devteam@adguard.com?

**Comment by Batman2814** [comment] 2023-03-03 13:56
Logs have been sent

**Comment by maxikuzmin** [comment] 2023-03-06 11:26
@Batman2814 thank you!

**Comment by maxikuzmin** [comment] 2023-03-06 11:33
@Batman2814 I think it would also be helpful to record record logs from the AdGuard VPN if you say it repeats after you turn on the VPN

**Comment by Batman2814** [comment] 2023-03-06 16:24
when I said Adgaurd VPN might be the cause it was because I had Adgaurd VPN on all the time so, when I turned off Adgaurd VPN and just left Adguard Nightly on and had it on cellular connection Internet connection, was blocked so for me to get internet connection on cellular connection had to disable Adguard for Android Nightly.

**Comment by maxikuzmin** [comment] 2023-03-07 17:12
@Batman2814 okay, we'll need some time to consider this problem

**Comment by Batman2814** [comment] 2023-03-07 20:55
did you guys get the logs that I sent or do I need to send them again?

**Comment by Batman2814** [comment] 2023-03-07 20:58
how much time to consider this a problem there is defiantly a problem because whenever I am on cellular data I have to disable Adguard and that doesn't protect my privacy.

**Comment by maxikuzmin** [comment] 2023-03-09 15:20
@Batman2814 yes, we got your logs, we are still investigating the problem.
Could you also export your settings and mail them to [devteam@adguard.com](mailto:devteam@adguard.com)? I think that would also help.
Also, what operator are you using? Is this repeated with other operators?

**Comment by Batman2814** [comment] 2023-03-09 20:13
I'm currently with Bell Service.

**Comment by Batman2814** [comment] 2023-03-09 20:17
What do you mean export my settings and mail them to you?

**Comment by Batman2814** [comment] 2023-03-09 22:29
So I figured out that I can have Adguard for Android enabled but I have to disable the whole DNS toggle for me to get an internet connection on my cellular data with Bell Mobility service. So hope this information helps.

**Comment by admitrevskiy** [comment] 2023-03-13 13:41
@Batman2814 Hi!

Could you please try this?

1. Choose any regular unencrypted DNS server (except for the 'System' one)
2. Choose any encrypted DNS server and specify Bootstrap upstreams (Settings -> General -> Advanced -> Low-level settings -> Bootstrap upstreams) manually as 8.8.8.8 or 1.1.1.1

**Comment by admitrevskiy** [comment] 2023-03-14 14:51
8.8.8.8 is Google DNS upstream. With nightly 65 you can remove it :)

**Comment by Batman2814** [comment] 2023-03-14 14:54
I'm still having trouble accessing the internet on cellular data when using my Adguard private dns with bootstrap upstreams left empty in space so the issue is still there.

**Comment by admitrevskiy** [comment] 2023-03-14 15:24
It's very strange. Could you please send the logs?

**Comment by Batman2814** [comment] 2023-03-14 16:21
logs have been sent to devteam@adguard.com with the Github issue number.

**Comment by admitrevskiy** [comment] 2023-03-14 16:40
I've received it, thanks!
Could you try to reproduce the issue with the following IP in 'Bootstrap' section? 94.140.14.140 (it's AdGuard DNS Non-filtered)

**Comment by Batman2814** [comment] 2023-03-14 17:10
when I inputted Adguard DNS Non-filtered into bootstrap everything was loading had access to the internet on cellular data.

**Comment by Batman2814** [comment] 2023-03-15 01:00
Do you need me to send logs of Adguard DNS Non-filtered in bootstrap to the email address also?

**Comment by admitrevskiy** [comment] 2023-03-15 09:25
@Batman2814 Tell me, is the problem repeating only in the integration mode with AdGuard VPN or standalone mode is also affected?

**Comment by Batman2814** [comment] 2023-03-15 11:12
I always have it in Intergration mode, but I can check to see if it is in standalone later.

**Comment by admitrevskiy** [comment] 2023-03-15 12:27
I think, I've found the cause of the issue. Please try new nightly when it becomes available.

**Comment by Batman2814** [comment] 2023-03-15 17:06
So I updated Adguard Nightly 66 today, and it is still not fixed, but it will work on cellular data with Adguard VPN on while Adguard for Android is on. When I turn Adgaurd VPN off on cellular data and just have Adguard for Android on while set to my Adguard Private DNS, that's when it won't work.

**Comment by admitrevskiy** [comment] 2023-03-16 08:45
Did you set AdGuard Private DNS in system settings or in AdGuard? 

Could you please repeat the issue and send debug logs to devteam@adguard.com?

**Comment by Batman2814** [comment] 2023-03-16 11:10
I set it up in Adguard for Android.

**Comment by Batman2814** [comment] 2023-03-16 21:50
Logs have been sent.

**Comment by admitrevskiy** [comment] 2023-03-17 11:25
Looks like it's your ISP issue. Did you have this problem on version 3.6 with the same configuration?

**Comment by Batman2814** [comment] 2023-03-17 13:05
It was fine on version 3.6. I was on cellular data, not my wifi.

**Comment by Batman2814** [comment] 2023-03-17 13:05
It was fine on version 3.6. I was on cellular data, not my wifi.

**Comment by Batman2814** [comment] 2023-03-21 15:27
any update yet?

**Comment by maxikuzmin** [comment] 2023-03-21 17:35
@Batman2814 thanks, we got your logs! Now we'll need some time to look into the problem

**Comment by admitrevskiy** [comment] 2023-03-22 09:20
@sfionov Could you please take a look?

In v3.6 DoQ upstream was bootstrapped successfully while in v4.0 logs there are a bunch of `Failed to resolve host`, `Sockets error` and `network is unreachable` errors.

**Comment by admitrevskiy** [comment] 2023-03-22 10:17
@Batman2814 Do you have one or more SIM cards installed?

**Comment by Batman2814** [comment] 2023-03-22 11:12
Just have one sim card. I'm on nighly again. Do I have to uninstal Nightly to put the stable Adguard on my phone.

**Comment by Batman2814** [comment] 2023-03-23 00:11
![Screenshot_20230322_191011_AdGuard](https://user-images.githubusercontent.com/96619913/227066367-cfe470e9-c905-4299-80bd-f654fd379ede.jpg)

**Comment by Batman2814** [comment] 2023-03-24 15:46
Can you guys give me an update on this issue and when it will be fixed? I'd appreciate it. Please and thank you.

**Comment by admitrevskiy** [comment] 2023-03-27 14:08
@Batman2814 Hi!
Could you please try the latest nighty 74?

**Comment by Batman2814** [comment] 2023-03-27 14:48
Seems to be fixed.

**Closed** 2023-03-30 10:46 UTC
Labels: Bug, Resolution: Fixed, Status: Resolved, Middle, Version: AdGuard v4.0
