### ISSUE TITLE
Unable to resolve .onion domain

### ISSUE THREAD

**Issue by gzleangle** [AdguardTeam/AdguardForAndroid#4272] opened 2022-11-13 09:25 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - v4.0 nightly 35 (79)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung S22
- **Operating system and version:**
  - Android 12
- **Root access:**
  - No

### Expected Behavior

Access .onion sites through a Tor proxy.

### Actual Behavior

Unable to resolve .onion domain.

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_Chrome](https://user-images.githubusercontent.com/83969164/201514523-c8ece96a-5d85-4a16-983a-199f7a1e6424.jpg)

</details>

### Additional Information

Running Tor in Termux.
Configure Tor proxy in adguard.
Exclude Tor programs in app management of adguard.
Non-.onion websites can be accessed normally via Tor when adguad is enabled.
The .onion website can be accessed normally via Tor without adguad enabled.

**Comment by gzleangle** [comment] 2022-11-15 18:01
> @gzleangle did I understand correctly that, you want to set up a Tor proxy and exclude Tor from filtered applications? And the problem is that after that you have no access to the .onion domain? Could you write where exactly you have no access to check this? Give me the link please

1. Iinstall [Termux](https://termux.dev/en/).
2. Execute `pkg  install tor` in Termux.
3. Execute `tor` to run tor.
4. Exclude Termux in adguard's app management.
5. Configure socks5 proxy `127.0.0.1:9050` in adguard.
6. Open Chrome and visit a .onion site such as Z-Library ([zlibrary​24tuxziyiyfr7​zd46ytefdqbqd2axkmxm​4o5374ptpc52fad.onion](http://zlibrary24tuxziyiyfr7zd46ytefdqbqd2axkmxm4o5374ptpc52fad.onion/)).

**Comment by sfionov** [comment] 2022-11-21 09:28
Hello! We have feature request for this in the CoreLibs repo

https://github.com/AdguardTeam/CoreLibs/issues/1386

However, there is no ETA for now.

**Comment by maxikuzmin** [comment] 2022-11-23 11:39
@gzleangle duplicate of <https://github.com/AdguardTeam/CoreLibs/issues/1386>

**Closed by maxikuzmin** 2022-11-23 11:39 UTC
