### ISSUE TITLE
AdGuard is now blocking Gmail Attachments

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3724] opened 2021-01-21 12:31 UTC
@XtremeMaC commented on [Tue Jan 19 2021](https://github.com/AdguardTeam/AdguardFilters/issues/72612)

Hi, don't know the exact date/time issue started, but at least for the past 1-2 days I open an email with Gmail App and it doesn't preview or download any attachments.
Turned off AdGuard. Killed Gmail. Works.

I thought culprit was AdGuard DNS filter, but turns out it's not. Still going thru log to find out. 

Edit: I belive the screenshot below is the culprit. Created an exception and attachments are working now..
![Screenshot_20210119-000446_AdGuard](https://user-images.githubusercontent.com/11046475/104990476-b4794d80-59ea-11eb-86dc-4669d5000149.png)

Edit. Maybe not.. I'll hunt this in the morning... 

FYI

**Comment by Alex-302** [comment] 2021-01-21 12:32
@AdguardTeam/qa-team

**Comment by Chinaski1** [comment] 2021-01-22 10:44
@XtremeMaC

Not reproduced on my side.
Could you please open AdGuard settings -> General -> Import settings -> Send received file to k.gretskyi@adguard.com
Also, please specify what version of AdGuard you are using?

**Comment by Chinaski1** [comment] 2021-01-26 08:47
@XtremeMaC
If you send the settings config please let me know in this task.

**Comment by Chinaski1** [comment] 2021-02-04 09:29
I am closing this task as I can't reproduce the issue on my side and the user has not responded for a long time.
Reopen it if it is necessary.

**Comment by ScratMan** [comment] 2021-02-08 23:05
I'm facing exactly the same issue. If I disable Adguard protection I can download attachment and reopen them from cache after switching Adguard on.

Settings attached.

**Comment by XtremeMaC** [comment] 2021-02-08 23:58
Sorry for the lack of follow ups. Been super busy thus decided to just reset my settings. However, I haven't changed any settings for months, hence I think it's either filter updates or app updates or possibly misconfig on my end that broke with updates...

Unable to attach my settings now..

**Comment by Chinaski1** [comment] 2021-02-09 09:00
@ScratMan 
In that case, I would ask you to upgrade to the Nightly (agrd.io/android_nightly) version and check if the issue persists.

**Comment by debmaj2** [comment] 2021-02-09 12:00
I'm on Nightly. The issue cannot be reproduced on my end.

![Screenshot_2021-02-09-17-29-42-172_com android chrome](https://user-images.githubusercontent.com/22155707/107360799-714b5f80-6afc-11eb-8779-68066f0e4e02.jpg)
(Stealth Mode is active as well)

**Comment by Chinaski1** [comment] 2021-02-09 15:19
@ScratMan @XtremeMaC 

There is another method you can try:
- AdGuard settings -> Advanced -> Low-level
- Remove 1000 and 1001 from pref.excluded.apps

**Comment by ScratMan** [comment] 2021-02-11 23:27
I tried to load the configuration file from my wife's phone, and it fixed the issue.
I then cleared Adguard data and reconfigured the so from scratch. Still working.
So for sure it depends on a setting that might not be removed by data clear, but by loading another working configuration

**Comment by artemiv4nov** [comment] 2021-04-26 10:26
I'll close this issue because it has already been investigated in the #3516 issue.

**Closed by artemiv4nov** 2021-04-26 10:26 UTC
Labels: Bug, High, Version: AdGuard v3.6.2
