### ISSUE TITLE
ipv6 issues with root mode and minor problem on language

### ISSUE THREAD

**Issue by sklynic** [AdguardTeam/AdguardForAndroid#4591] opened 2023-04-18 09:45 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 nightly 89

### Environment

```markdown
- OS: Android 13 (CrDroid 9.3, non-official firmware)
- Device: Redmi
- Firmware: munch
- Root: magisk 26.1(26100)
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

NoCoin Filter List, Others

### Issue Details

Steps to reproduce:
1. switch adguard's Routering mode from Local VPN to Automatic proxy
2. open https://test-ipv6.com/ (or other sites/apps using ipv6)

### Expected Behavior

For the ipv6: the ipv6 test passed and ipv6 works normal.
For the language: display only one language (if currently only supports English, then no other language should be displayed)

### Actual Behavior

For ipv6, on Automatic proxy mode, ipv6 doesn't work.
For the language, currently adguard only supports English but some pages/buttons display my system language (zh-CN), which is really weird

### Screenshots

<details><summary>Screenshot 1:</summary>
Automatic proxy mode, which works abnormal

![Screenshot_20230418-171552_Via](https://user-images.githubusercontent.com/39230198/232733490-e3715d46-b2de-4934-b1ef-e67bd929025f.png)

</details>

<details><summary>Screenshot 2:</summary>
Local VPN mode, works normal

![Screenshot_20230418-172026_Via](https://user-images.githubusercontent.com/39230198/232733877-0dccc8d9-c771-4d04-bfe7-46692f5f8a3c.png)

</details>

<details><summary>Screenshot 3:</summary>
Mixed language display

![Screenshot_20230418-174217_AdGuard](https://user-images.githubusercontent.com/39230198/232738566-a2e44eb4-e132-42b2-88db-f6b9a81a842d.png)

</details>

### Additional Information

The ipv6 issue happened on both wifi and mobile data.

**Comment by Versty** [comment] 2023-04-25 13:12
@sklynic Thank you for the feedback.
The issue related to the ipv6 reproduces on our side as well. We will look for a solution. 

Translations to zh-CN should be completed in the latest nightly version (v4.0 nightly 94). Would you mind checking?

**Comment by sklynic** [comment] 2023-04-25 14:51
Sorry I made a mistake--zh-CN is fine, thanks. However I accidentally set to zh-SG instead of zh-CN before and on that language setting, language is still mixed (I also observed this behavior in other apps). 
I'll switch back to zh-CN and if there does have anyone use the "zh-SG", maybe they need this to be fix.

**Comment by artemiv4nov** [comment] 2023-05-19 11:03
I just retested it on the latest nightly version and ipv6 worked well. I'm going to close this task.

**Comment by sklynic** [comment] 2023-05-19 15:42
But ipv6 on my side still don't work (with automatic proxy mode, a.k.a. root mode). Should I send adguard's logs through email or what else should I do?
________________________________
发件人: Artyom Ivanov ***@***.***>
发送时间: 2023年5月19日 19:04
收件人: AdguardTeam/AdguardForAndroid ***@***.***>
抄送: sklynic ***@***.***>; Mention ***@***.***>
主题: Re: [AdguardTeam/AdguardForAndroid] ipv6 issues with root mode and minor problem on language (Issue #4591)


I just retested it on the latest nightly version and ipv6 worked well. I'm going to close this task.

―

**Comment by Versty** [comment] 2023-05-29 10:32
@sklynic Hi! Yes, the logs from your device would help a lot. Please follow the steps below. 

1. Make sure that the `IPv6 filtering` option is enabled in the Low-level settings 
*Settings -> General -> Advanced -> Low-level -> Protection section* 

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Sent this file to devteam@adguard.com:
      - mention the `4591` number in the subject
      - specify the exact time when the issue occurred

**Comment by Versty** [comment] 2023-05-29 12:39
@sklynic Could you confirm that we have understood you correctly? IPv6 is working on the device in the Local VPN mode and not working in the Auto proxy mode on the same network with the same settings, right?

**Comment by sklynic** [comment] 2023-05-29 12:50
> @sklynic Could you confirm that we have understood you correctly? IPv6 is working on the device in the Local VPN mode and not working in the Auto proxy mode on the same network with the same settings, right?

That's correct.

**Comment by sklynic** [comment] 2023-05-29 13:38
> @sklynic When you collected the debug logs today
18:52 for wifi and 18:53 for mobile data

>did the problem occur on both Wi-Fi and mobile data?
Yes

(I think I already explained this in mail. :)

**Comment by christantoan** [comment] 2023-06-16 10:56
I'm experiencing this as well though I only tested with Wi-Fi as I'm currently unable to test with IPv6 mobile data.

Additional notes: when connected to a VPN server with available IPv6 address (I'm using Mullvad via Wireguard IPv4), test-ipv6.com results in pass 10/10 but adguard.com/en/test/html shows that AdGuard app is not running.

**Comment by shugo-chara** [comment] 2023-10-03 06:22
As of today (2023/10/03)
The bug is still not fixed. It is not clear what the fix plan is and how it is scheduled.
@Versty

**Comment by Rtizer-9** [comment] 2023-10-06 20:37
I'm experiencing the same issue. IPv6 works perfectly on vpn mode but not on automatic proxy mode.

**Comment by shugo-chara** [comment] 2023-10-18 04:12
@androidacy-user 
@Versty 
I don't recognize expecting the adguard team to solve the ipv6 filtering problem. Instead, I just want to be able to allow all, not block all, ipv6 requests in root mode. Because this makes any ipv6 request blocked in root mode.

This obviously poses a serious problem in certain regions and countries where ipv6 connections are predominant. However, the adguard team is still reluctant to make improvements.

**Comment by shugo-chara** [comment] 2023-10-26 01:24
@androidacy-user 
Not really. In another related thread, the adguard team had also given the suggestion of trying to turn on/off the ipv6 filtering tab in the advanced settings.
However, in root mode, ipv6 connections are blocked regardless of turning on/off the ipv6 filtering switch. It is also not possible to access any ipv6 address. This is still the case until today with the latest version (updated every night).
That's why we are urgently requesting root mode to support ipv6 connections, even if it can't filter it.
![Screenshot_2023-10-26-10-18-39-742_com chrome beta-edit](https://github.com/AdguardTeam/AdguardForAndroid/assets/20610965/8e43d893-80a2-40bc-9cae-19628111e9a6)

**Comment by sklynic** [comment] 2023-10-26 15:24
> That's why we are urgently requesting root mode to support ipv6 connections, even if it can't filter it. 

I don't think dev team will do this, as they blocked all quic/iquic connections because it can't be filtered for now. I hope they can figure this out.

Also, I just found a new problem about ipv6, if I enter the "Recent Activity" page, then click a http/https connections that is using ipv6 and **the ipv6 address is not quoted with "[" "]" symbol** (I don't know why, it doesn't make any sense) (tcp connections with ipv6 don't have this problem) , then the "Request details" page is totally blank. Nothing displayed.

**Comment by christantoan** [comment] 2023-10-29 03:21
Perhaps it's simply not possible to do proper IPv6 filtering on some devices due to missing kernel features.

For example, when I tried to execute
`ip6tables -F -t nat`, I got `ip6tables v1.8.4 (legacy): can't initialize ip6tables table 'nat': Table does not exist (do you need to insmod?)
Perhaps ip6tables or your kernel needs to be upgraded.` because my kernel is missing `CONFIG_NF_NAT_IPV6` option when it was compiled.

CMIIW though.

**Comment by Rtizer-9** [comment] 2023-10-29 04:19
I think ipv6 is perfectly working it's just that some testing websites might be using something else which is causing a bug and ends up showing that ipv6 doesn't work but it actually does.

Ipv6-test.com doesn't work but test-ipv6.com does.

pinging google.com in termux also works with an ipv6 so of course there is no proof that ipv6 isn't working.

All this is tested on the latest nightly.

**Closed** 2023-10-31 14:28 UTC
Labels: Bug, Resolution: Won't Fix, Status: Resolved, Middle, Priority: P3

**Comment by shugo-chara** [comment] 2023-11-03 06:36
@Rtizer-9 
Despite your insistence that the ipv6 functionality is working fine, the fact is that over the past few years, I have changed phones several times and kept up to date with Android, and my ipv6 has never worked properly in root mode.

I'm in Tokyo, Japan and ipv6 access is very ubiquitous. So additional configuration of ipv6 when deploying networks on all my devices is something I've been doing.
The fact is that ipv6- with test-ipv6, and any ipv6 websites are not accessible on root mode android. All ipv6 requests are blocked or unrequested.
I also had several feedbacks or this issue over the last years and often various solutions, apparently it involves adg internals and cannot be solved. I have applications that use adguard on many platforms, the best by far is adguardhome which clearly has the best support for ipv6.

So on Android I switched to vpn mode early on, even if it wasn't inconvenient for my work.
I have no way of knowing what is going on with users who say ipv6 works fine under root. But at least I am plagued with this problem with my close friends.

So I wouldn't really expect it to change any more. But I just want to make it clear that facts are facts and this can't be changed.

**Comment by Rtizer-9** [comment] 2023-11-03 07:31
@shugo-chara I understand, I was having the same issue earlier for which I even commented but now with latest nightly the issue is completely gone for me so I just made that comment. 

I think you must have already tried testing on a fresh configuration with no modification. If the problem persists then you should definitely reopen this issue or a new one. 

Obviously I'm not aware of the networking your ISP is using so I've no idea what's going on. I would also advise you to look into "behind NAT"... and all those things which ISP employs to lock down the network which somehow interferes with such things.

If ipv6 test on all websites not just few is working perfectly when ag is not used and then they ALL stops working with ag being used in a completely fresh state then yeah definitely there's some issue.

Here's one more website with detailed info to test ipv6 which I really like:

https://ipv6.bieringer.net/

Please also look at other options like geo test etc.

**Comment by Rtizer-9** [comment] 2024-06-03 18:59
@Versty ipv6 has stopped working on root mode again. @shugo-chara @androidacy-user @christantoan @artemiv4nov
