### ISSUE TITLE
Move certificate to system store failure

### ISSUE THREAD

**Issue by Logster9982** [AdguardTeam/AdguardForAndroid#2941] opened 2019-07-20 04:19 UTC
When you attempt to filter https for non browser apps, it will repeatedly keep asking for root ascess until you permanantly allow it, resulting in the error "error moving certificate to the system store" (LineageOS, Pixel XL, nightly build)

# Steps to reproduce

-  go to certificate status
-  click "move to system store"
-  allow root acess and remember choice

# Expected result

Https being filtered in all apps

# Actual result

Error message

# Details

-  Adguard version: 3.2.98β
-  Filtering mode: Local Vpn
-  Model: Pixel XL
-  Kernal: 3.18.131-lineageos
-  root acess: YES
-  Conflicting apps: Orbot, AFwall+

**Comment by admitrevskiy** [comment] 2019-07-23 17:19
@Logster9982 hi! We cannot reproduce this issue on our side.
Can you please do the following:
-Set `Record everything` log level (Settings -> Advanced -> Record everything)
-Reproduce the issue (try to move cert to the system store)
-Export logs (Settings -> Advanced -> Export logs) and send it to`devteam@adguard.com`

**Comment by artemiv4nov** [comment] 2019-11-05 07:04
The certificate's moving to the System store broken on Android 10.
I was able to reproduce on OnePlus 6T and Google Pixel.

There are following steps to reproduce:
1) Go to "Settings" -> "Network" -> "Https filtering" -> "Security certificate" -> "Move to the system store"
2) Touch to the button "Move"
3) You got the error about certificate's moving

**Comment by admitrevskiy** [comment] 2019-11-05 15:11
Done.

Notification was changed to inform user to use Magisk to move certificate to the system store.

**Closed** 2019-12-10 09:03 UTC
Labels: Bug, P3: Medium, Waiting for data
