### ISSUE TITLE
AdGuard Firewall Feature Request

### ISSUE THREAD

**Issue by Elenve** [AdguardTeam/AdguardForAndroid#1847] opened 2018-05-01 12:49 UTC
We've received a couple of requests from the customer, see below:
"
1. A filter (maybe even automatic) to configure the list of applications in the firewall. ATM the list includes ALL installed applications that only exist on the device, including "disabled" and in the end it is very large. So, you need the ability to disable displaying the "turned off" applications in the firewall. They are not active, and therefore they do not need to be configured. The list will be more compact.

2. A filter for the firewall, which would separate the system and user applications. For example, a separate button-switch, having 3 positions (switching in the horizontal plane): all, system and user. You need to place it right above the list of applications, there is a lot of space. Traffic statistics can be made expandable (down). This will release some space under the button. "

**Comment by ameshkov** [comment] 2019-03-21 13:00
Duplicate of #1110

**Closed by ameshkov** 2019-03-21 13:00 UTC
Labels: Feature request, P3: Medium
