### ISSUE TITLE
Update white list DNS Filter . Can't do that .

### ISSUE THREAD

**Issue by U0101100** [AdguardTeam/AdguardForAndroid#5401] opened 2024-07-17 13:55 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.33 beta

### Environment

- OS version: Android 14
- Device: SM-N975F

### HTTPS filtering

- [X] yes, I do

### Root access

- [X] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Security

Online Malicious URL Blocklist

### Language-specific

EasyList Polish, Polish Annoyances Filters, Polish Anti Adblock Filters, Polish Anti-Annoying Special Supplement, Polish Social Filters

### Other

AdGuard DNS filter, AdGuard Experimental filter

### Which DNS server do you use?

Quad9

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Block ETag and If-None-Match headers, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1. Adguard ON
2. Open web.norstatsurveys.com 
3.Seen that page cannot be opened or blank site 
4.Turn off protection and go to site normally 
5. On Recent activity browser address is green but www sites is not opened 

### Expected Behavior

Fully Opened site with active adguard protection. 
Don't needed turning it off. 
All working normally .

### Actual Behavior

Turned off adguard protection to open that site . 
Address added to withe list DNS user Rules 
Recent activity green pole 
Browser: chrome beta android 
Chrome Beta 127.0.6533.41
Android 14; SM-G998B Build/UP1A.231005.007

### Screenshots

![SmartSelect_20240717_153823_AdGuard](https://github.com/user-attachments/assets/3d15c246-dd7b-4efa-9052-603bd3cb9216)
![SmartSelect_20240717_153750_AdGuard](https://github.com/user-attachments/assets/d93c0a80-c0a1-481d-92d6-4b9a9ac36b47)
![SmartSelect_20240717_153804_AdGuard](https://github.com/user-attachments/assets/d099f97e-5b4f-4775-93fe-d0141aecf8f4)

### Additional Information

Not any

**Comment by maxikuzmin** [comment] 2024-07-31 09:45
@U0101100 I checked it on incognito tab to avoid cache saving: this site is "empty" even without AdGuard protection. Even when I closed AdGuard completely - the website still remained "empty". 
Please check this. I think the problem is not with AdGuard

**Comment by maxikuzmin** [comment] 2024-08-01 11:09
@U0101100 any news?

**Comment by maxikuzmin** [comment] 2024-08-02 16:36
@U0101100 for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Closed by maxikuzmin** 2024-08-02 16:36 UTC
Labels: Bug, Priority: P4
