### ISSUE TITLE
Adguard does not start automatically

### ISSUE THREAD

**Issue by dnaug** [AdguardTeam/AdguardForAndroid#5389] opened 2024-07-06 07:59 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.5.17

### Environment

- OS version: Android 14
- Device: Motorola g24

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Social

AdGuard Social Media filter

### Language-specific

AdGuard German filter

### Which DNS server do you use?

Automatic DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers

### Issue Details

Steps to reproduce:
1.
2.
3.

### Actual Behavior

I use Adguard on the Motorola g24. Everything works so far, but Adguard does not start automatically when I turn on the Motorola. The "Start Adguard when system starts" switch is activated (green). If I start Adguard manually after the system starts, I can still see Adguard turning itself on from red to green), then the protection is activated. Why is Adguard not starting automatically when the smartphone starts?

### Screenshots

<details><summary>Screenshot 1</summary>

![Screenshot_20240630-144356](https://github.com/AdguardTeam/AdguardForAndroid/assets/174619635/ab8f9daf-7ac8-4ed6-8fa9-73028496a7fa)

file:///home/dn/Bilder/Bilder%202024/Screenshot_20240630-144413.png
![Screenshot_20240630-144337](https://github.com/AdguardTeam/AdguardForAndroid/assets/174619635/620f62a3-22b9-4779-952e-1db8befbcdc7)

![Screenshot_20240630-144413](https://github.com/AdguardTeam/AdguardForAndroid/assets/174619635/08474f22-d696-4ebb-bcf8-4439be72fbc4)

</details>

### Additional Information

I use Adguard on the Motorola g24. Everything works so far, but Adguard does not start automatically when I turn on the Motorola. The "Start Adguard when system starts" switch is activated (green). If I start Adguard manually after the system starts, I can still see Adguard turning itself on from red to green), then the protection is activated. Why is Adguard not starting automatically when the smartphone starts?

**Comment by maxikuzmin** [comment] 2024-07-08 13:45
@dnaug please clarify, did you allow "Background" in system settings as [instructed](https://adguard.com/kb/adguard-for-android/solving-problems/background-work/)?

**Comment by dnaug** [comment] 2024-07-08 15:17
Yes, it is allowed!

**Comment by slythrn** [comment] 2024-07-09 10:10
I have this problem as well on my Motorola. I'm also on Android 14.

**Comment by maxikuzmin** [comment] 2024-07-10 09:43
@dnaug @slythrn unfortunately I don't have a Motorola device. Could you please record the HAR logs as [instructed](https://adguardteam.github.io/KnowledgeBase/adguard-for-android/solving-problems/har/) and send to devteam@adguard.com?
Please be sure to include the time the problem recurred and the issue number 5389

**Comment by maxikuzmin** [comment] 2024-07-10 10:10
@dnaug @slythrn

Could you please record debug logs?

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Debug

- Reproduce steps, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):
mention the 5389 number in the subject
specify the exact time when the issue occurred

**Comment by slythrn** [comment] 2024-07-13 10:30
I sent in my logs. Just waiting for a response now.

**Comment by maxikuzmin** [comment] 2024-07-17 14:04
@slythrn thanks, we will look into your logs, it will take us some time

**Comment by maxikuzmin** [comment] 2024-07-18 09:05
@slythrn the logs show that AdGuard started at 06:04:33 
Could you please record new logs with time indication, because without timings it's hard to understand. 
Also clarify, when you start the device there is also no information in the system tray that AdGuard is running?

**Comment by slythrn** [comment] 2024-07-18 15:06
I ended up returning the Motorola phone and switching back to Samsung.

**Comment by maxikuzmin** [comment] 2024-07-25 16:46
@slythrn you won't be able to test it again on the motorola device?

**Comment by dnaug** [comment] 2024-07-26 15:43
I tried again with program version 4.6.1. It still doesn't work.
To clarify again, Adguard starts but is not activated. When I tap the app, the switch jumps from red to green. This applies to the Motorola g24.
On the Motorola Edge 40 Neo, Adguard works perfectly and starts completely automatically when the smartphone starts.

**Comment by maxikuzmin** [comment] 2024-07-29 14:50
@dnaug please repeat the steps and record new logs, don't forget to specify the time of reproduction of the problem. As I wrote earlier, it is difficult to understand the problem without understanding the time of problem repetition

**Comment by maxikuzmin** [comment] 2024-07-30 13:19
@dnaug any news?

**Comment by dnaug** [comment] 2024-07-31 09:42
> @dnaug any news?

I have created a new protocol.[Uploading adguard_logs_4.6.61_3107_112141.zip…]()

11:17 a.m. device switched on

11:18 a.m. PIN entered

11:21 a.m. Adguard app tapped
                    (protection is activated)

**Comment by maxikuzmin** [comment] 2024-08-01 11:32
@dnaug I think the logs were uploaded incorrectly judging by the word "Uploading" :) 
Please attach the logs to the issue again or send us an email at devteam@adguard.com

**Comment by maxikuzmin** [comment] 2024-08-02 16:39
@dnaug any news?

**Comment by dnaug** [comment] 2024-08-02 17:38
I sent everything to _devteam@adguard.com_ as requested.

**Comment by slythrn** [comment] 2024-08-07 10:44
I noticed that adguard won't start automatically if you have a lock screen security feature enabled (pattern, pin, fingerprint, etc). If you just use "swipe to unlock" or have no lock screen at all, adguard loads automatically.

**Comment by JazzJohannes** [comment] 2024-08-26 19:55
I have the same issue actually but i am on motorola g pro stylus 2020 with android 12. It switches on but gets disabled immediately again.

**Comment by maxikuzmin** [comment] 2024-08-27 11:20
@dnaug @slythrn did you manage to reproduce the problem? 
@JazzJohannes if you are also having this problem repeatedly, could you please send also the logs to our email [devteam@adguard.com](mailto:devteam@adguard.com) as mentioned in the instructions above?

**Comment by JazzJohannes** [comment] 2024-08-27 12:15
> @dnaug @slythrn did you manage to reproduce the problem? @JazzJohannes if you are also having this problem repeatedly, could you please send also the logs to our email [devteam@adguard.com](mailto:devteam@adguard.com) as mentioned in the instructions above?

I have noe reported it as a bug within the app. And additionally the switch for conmecting to adguard vpn switches off right away as well btw. I have reported it for dguard vpn on top now as well

**Comment by maxikuzmin** [comment] 2024-09-05 14:19
@JazzJohannes could you elaborate on the ticket number?

**Comment by maxikuzmin** [comment] 2024-09-30 09:03
@dnaug @JazzJohannes @slythrn we need a system bug report to resolve the issue. Please get a system bug report as described in the [instructions](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/) and send it to email [devteam@adguard.com](mailto:devteam@adguard.com).

**Comment by maxikuzmin** [comment] 2024-10-03 16:32
@dnaug @JazzJohannes @slythrn  any news?

**Comment by maxikuzmin** [comment] 2024-10-21 12:41
@dnaug @JazzJohannes @slythrn for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Closed by maxikuzmin** 2024-10-21 12:41 UTC
Labels: Bug, Priority: P4
