### ISSUE TITLE
Digitally Imported Radio doesn't work

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#269] opened 2016-01-10 15:22 UTC
https://play.google.com/store/apps/details?id=com.audioaddict.di&hl=en

How it looks: http://prntscr.com/9octwb
Disabling ad filtering for the app doesn't help.

NIM-371-56422

**Comment by ameshkov** [comment] 2016-01-10 19:40
And what about "pref.net.exclusions"? Does it help?

**Comment by evgeniy-ADG** [comment] 2016-01-10 22:36
Works fine but there're tons of ads. Also, if you add it to the low level settings, let it download some data and then remove it from the pref.net.exclusions, you have the app working and ads blocked.

**Comment by ameshkov** [comment] 2016-01-10 22:47
Weird that disabling ad filtering does not help.

Do you use VPN or proxy mode?

**Comment by evgeniy-ADG** [comment] 2016-01-11 09:20
Oops, seems to be working fine at my end in both filtering modes if you disable ad filtering.

**Comment by ameshkov** [comment] 2016-01-11 09:22
So the issue is in ad filter after all. Then it would be better if you create an issue in "ExperimentalFilter" project and close this as duplicate.

**Closed** 2016-01-11 11:04 UTC
Labels: Duplicate

**Comment by evgeniy-ADG** [comment] 2016-01-11 11:07
https://github.com/AdguardTeam/ExperimentalFilter/issues/1268
