### ISSUE TITLE
PocketCasts compatibility issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#935] opened 2016-11-27 23:00 UTC
https://play.google.com/store/apps/details?id=au.com.shiftyjelly.pocketcasts&hl=en

> PocketCasts cannot connect to server to stream when Adguard is on

http://forum.xda-developers.com/showpost.php?p=69822544&postcount=1891

**Comment by nkartyshov** [comment] 2017-02-14 08:25
@vozersky Please, test it. I cannot reproduce.

**Comment by vozersky** [comment] 2017-02-14 14:05
Was not able to reproduce. Could be a specific filtering rule problem?

**Comment by nkartyshov** [comment] 2017-02-15 10:46
No, it isn't filters. 
@ameshkov Can close this task?

**Closed** 2017-02-20 11:42 UTC
Labels: Cannot Reproduce, Compatibility
