### ISSUE TITLE
Need to incorporate Anti-AdBlock Feature

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdguardForAndroid#29] opened 2015-08-28 07:12 UTC
Some are pretty comprehensive solutions, like https://github.com/reek/anti-adblock-killer.

Some are subscriptions only, like https://raw.github.com/reek/anti-adblock-killer/master/anti-adblock-killer-filters.txt (which incorporates https://easylist-downloads.adblockplus.org/antiadblockfilters.txt & a whole lot more) which the above uses.

But more & more sites are wising up, & _intentionally_ crippling AdGuard, &c, so counter-countermeasures should be available.

**Comment by ameshkov** [comment] 2015-08-28 15:45
In Desktop AG you can even install reek's userscript as AG extension.

This feature will be covered after we add userscripts support to android version.

**Comment by TPS** [comment] 2015-08-29 02:43
Yes, #13 (or pethaps even #12, if you all roll in an official subscription directly) would solve that subscription-only version.

However, if I'm understanding correctly, the need for an _extension_ to the desktop version (which I'm completely unfamiliar with, admittedly) seems to agree with my experience with using anti-adblock-killing subscriptions — it's not comprehensive enough.

Hence the need for something like (as mentioned) https://github.com/reek/anti-adblock-killer, which combines the subscription with some JavaScript magic to exert the best possible control over such.

**Comment by ameshkov** [comment] 2015-08-31 08:59
I don't mean we can include reek's solution.

What I am talking about is that Reek's Anti-Adblock is a userscript (https://github.com/OpenUserJs/OpenUserJS.org/wiki/Userscript-Beginners-HOWTO) and desktop AG allows you to install and use any userscript. The same thing we should do in android version.

**Comment by TPS** [comment] 2015-08-31 13:36
I *think* I understand!  Since #12 & #13 are about subscriptions, is there a separate bug tracking the userscript enhancement?

**Comment by ameshkov** [comment] 2015-09-01 17:19
I've just added it:
https://github.com/AdguardTeam/AdguardForAndroid/issues/34

I haven't yet assigned a milestone, the task is huge, enough for whole major release.

**Comment by TPS** [comment] 2015-10-08 14:23
@ameshkov Should this be closed in favor of #12, #13, & #34?

**Comment by ameshkov** [comment] 2015-10-08 16:02
You are right, this issue is a duplicate of these

**Closed by ameshkov** 2015-10-08 16:02 UTC
