### ISSUE TITLE
Adguard automatically starts despite having autostart box unchecked in settings.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#577] opened 2016-05-23 14:48 UTC
please refer to GHU-832-56315 for logs and details

**Comment by vozersky** [comment] 2016-05-24 13:35
I've just got an update from the user.
After reinstalling Adguard (the same build 2.1.196) the issue was gone.

**Comment by ameshkov** [comment] 2016-05-24 16:30
Yep, the issue was introduced in v2.5

**Comment by Revertron** [comment] 2016-06-10 11:31
Didn't we fix it?

**Comment by ameshkov** [comment] 2016-06-10 11:35
Nope

**Comment by ameshkov** [comment] 2016-07-28 08:41
Closing as we cannot reproduce it.

**Closed by ameshkov** 2016-07-28 08:41 UTC
Labels: Bug, Cannot Reproduce
