### ISSUE TITLE
Error HTTPS filtering

### ISSUE THREAD

**Issue by minsk21** [AdguardTeam/AdguardForAndroid#3285] opened 2019-12-26 16:04 UTC
Optional ability to disable notifications about this error

<details>

![Пример](https://i.imgur.com/ySeIwLE.jpg)

</details>

Adguard 3.3.228

**Comment by ameshkov** [comment] 2019-12-26 16:05
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/3225

**Comment by admitrevskiy** [comment] 2019-12-26 16:06
For now you can disable `all` notifications about this warning with `pref.notify.on.unknown.ca` in Low-level settings

**Closed by ameshkov** 2019-12-26 16:05 UTC
