### ISSUE TITLE
Whitelist is not working

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#1504] opened 2017-10-02 16:34 UTC
Whitelisting is not working. Element hiding is not disabled, when domain is added to whitelist.
Exclusion works(added to mobile filter):
```
stevengoh.com#@#.header-ad
```

### Steps to reproduce

1. Go to stevengoh.com

### Actual behavior
Blank screen.

Original issue:
https://forum.adguard.com/index.php?threads/adguard-v2-10-whitelist-english-filter-android.25567/#post-154072

### Your environment

* Adguard version: 2.10

**Comment by vozersky** [comment] 2017-10-02 16:36
reproduced

**Comment by ameshkov** [comment] 2017-10-02 22:40
This might be happening due to `Connection: Upgrade` header, which is invalid btw. Anyway, should be tested.

**Comment by nkartyshov** [comment] 2017-10-03 11:55
@ameshkov It's not because of Connection: Upgrade header.

**Comment by ameshkov** [comment] 2017-10-03 12:06
This is a CoreLibs bug, found it

**Comment by ameshkov** [comment] 2017-10-03 12:30
https://github.com/AdguardTeam/CoreLibs/issues/90

**Comment by ameshkov** [comment] 2017-10-03 12:53
Resolved in `adguard-android/pull-requests/131`

**Closed by ameshkov** 2017-10-03 12:53 UTC
Labels: bug
