### ISSUE TITLE
Blahdns not working in adguard for mobile

### ISSUE THREAD

**Issue by Techguyprivate** [AdguardTeam/AdguardForAndroid#3023] opened 2019-08-24 17:55 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version Yes
- [ ] I checked the documentation and found no answer Didn't found answer.
- [ ] I checked to make sure that this issue has not already been filed Yes, checked.

### Issue Details

- **AdGuard version:** 3.2.141
  - 
- **Filtering mode:** Vpn
  -  Realme 2 pro 
- **Operating system and version:**
  -  Android 9 
- **Root access:**
  - No

### Expected Behavior

Blahdns should work . Putting address given in blahdns.com should work. 

Go to setting, then dsn section in adguard .
Put either doh or dot or dnscrypt address for blahdns in dns setting. . E.g  " https:// doh-jp-blahdns.com/dns-query" ( without the quote of course. ) . 

Click save &select. 

It should save it. 
### Actual Behavior
 Saying no connection.

Putting the address of blahdns showing no connection in red letter. 
### Screenshots
![Screenshot_2019-08-24-22-14-37-09_a93965f46c4a4b0ed1be737bdf2bc8fc](https://user-images.githubusercontent.com/43615747/63641106-6a2a5a80-c698-11e9-9014-b2980028b056.png)

<details><summary>Screenshot:</summary>

</details>

**Comment by ameshkov** [comment] 2019-08-28 09:33
Their DOT server does not seem to be operational:
```
$ ./dnslookup example.org tls://doh-jp.blahdns.com
dnslookup undefined
2019/08/28 12:32:29 Cannot make the DNS request: Failed to read a request from doh-jp.blahdns.com:853, cause: unexpected EOF
```

Their DOH server works okay:
```
./dnslookup example.org  https://doh-jp.blahdns.com/dns-query
dnslookup undefined
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 32507
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; QUESTION SECTION:
;example.org.	IN	 A

;; ANSWER SECTION:
example.org.	86313	IN	A	93.184.216.34

;; ADDITIONAL SECTION:

;; OPT PSEUDOSECTION:
; EDNS: version 0; flags: ; udp: 4096
```

Tested with https://github.com/ameshkov/dnslookup

**Comment by ameshkov** [comment] 2019-08-28 09:35
Ah, my bad, DOT is also okay:
```
./dnslookup example.org tls://dot-jp.blahdns.com
dnslookup undefined
dnslookup result:
;; opcode: QUERY, status: NOERROR, id: 4412
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;example.org.	IN	 A

;; ANSWER SECTION:
example.org.	86267	IN	A	93.184.216.34
```

And I've been able to reproduce this issue indeed.

**Comment by Techguyprivate** [comment] 2019-08-29 10:40
Blahdns works with other apps or softwares. For example, blah dns works with 

1. Nebulo, an open source app for dns encryption

2. Intra from Google.

3. Stubby dns 

4. Technitium dns

5. Adguardhome in pc 

But doesn't work for some reason with adguard for mobile . Tried most of the thing like clearing cache, uninstalling & imstalling again,reboot, using different ports etc. 

 Is it to do anything with strict esni ? Blah dns supports strict esni i.e. encrypted server name indiactor.

**Comment by ameshkov** [comment] 2019-08-30 10:05
Yeah, that's why I marked it as a bug:)

This is actually very strange because AdGuard Home uses the very same DNS library as AdGuard for Android.

**Comment by admitrevskiy** [comment] 2019-09-06 10:38
I've found the out root cause of this issue. We use `ipv4only.arpa.` as DNS question name. 2/3 of blah dns servers do not have records for this name and it's weird :)

AGHome uses `google-public-dns-a.google.com.` as a question name during upstreams test. @ameshkov should we use the same question name for mobile lib?

**Comment by ameshkov** [comment] 2019-09-06 15:42
Can they maybe fix this instead? It's really strange to not resolve it

**Comment by ameshkov** [comment] 2019-09-06 15:43
@admitrevskiy plz report it there:
https://github.com/ookangzheng/blahdns

**Closed by ameshkov** 2019-09-06 15:43 UTC
Labels: Bug, P3: Medium

**Comment by admitrevskiy** [comment] 2019-09-06 16:04
Here is the report for Blah DNS: https://github.com/ookangzheng/blahdns/issues/60
