### ISSUE TITLE
Apps disappear from app management.

### ISSUE THREAD

**Issue by knasiotis** [AdguardTeam/AdguardForAndroid#4800] opened 2023-06-16 20:44 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0

### Environment

```markdown
- OS: MIUI 14 
- Device: Mi 11 ULTRA
- Firmware: EU rom stable 14.09

Apps like instagram and facebook sometimes appear in app management section of filtering and sometimes they don't. I do not understand the inconsistency. I cannot set per app filtering that way, they just don't exist as entries.

I have confirmed that nothing is going wrong with LSposed hidemyapplist.
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, Filter unblocking search ads and self-promotion, Greek AdBlock Filter, Online Malicious URL Blocklist, NoCoin Filter List

### Issue Details

Steps to reproduce:
1. Open adguard
2. Go to filtering
3. Go to apps
4. Go to app management
5. search for instagram for example
6. may appar
7. may not appear

### Expected Behavior

Instagram and many other apps should be visible

### Actual Behavior

They ain't

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment] 2023-07-07 11:33
@knasiotis thanks for the long wait. 
I don't have this problem. I checked on several devices.
How often does it recur? Can you make a video of a screen replay of this situation? You can attach it right here or email it to devteam@adguard.com

**Comment by knasiotis** [comment] 2023-07-08 21:02
@maxikuzmin Hi, I have not managed to replicate the issue, however to follow my initial issue. 
I opened the app I went to "filtering" -> apps -> app management and only system apps appeared. I force closed adguard, reopened it and it was functioning properly. It listed instagram for example, but before I did that it didn't

**Comment by maxikuzmin** [comment] 2023-07-12 09:16
@knasiotis please set the logging level to "Debug" and if the problem recurs, upload the logs, then email them to us with the time and issue number. 
It would also of course be nice to record a video of the screen

**Comment by knasiotis** [comment] 2023-07-21 17:51
@maxikuzmin It has happened again! The problem persists on Version v4.1 nightly 24 (I tried updating to the nightly channel in hopes it got fixed). I tried to open coinbase, which is set to route traffic through adguard.
I am attaching a video and the logs.

https://github.com/AdguardTeam/AdguardForAndroid/assets/5351129/3a7df3ab-3863-4da3-bade-8307c8910f9d
[adguard_logs_4.1.90_2107_204217.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/12131179/adguard_logs_4.1.90_2107_204217.zip)

**Comment by knasiotis** [comment] 2023-07-26 01:46
I also got to mention that when this occurs it's like the apps are malfunctioning, to be more precise, if I open instagram while this issue has occured it will not load anything

**Comment by maxikuzmin** [comment] 2023-07-31 20:31
@knasiotis thank you! We'll look into your logs, it will take us some time

**Comment by maxikuzmin** [comment] 2023-08-22 15:29
@knasiotis thanks for waiting. It seems to be a problem with MIUI. Please see if there is any system settings permission management for apps other than the default read/write. Maybe there is something semantically related to QUERY_ALL_PACKAGES

**Comment by knasiotis** [comment] 2023-08-22 15:39
@maxikuzmin Most rooted devices tend to have an LSPosed module named HideMyApplist, which could be related to the issue.
However, the template I've created only hides certain LSPosed modules and Magisk from a list of very few apps, banking related. Adguard is not affected by anything. Also google play gms is set to get a restricted list of packages, is that possible to cause problems?

**Comment by maxikuzmin** [comment] 2023-09-01 10:41
@knasiotis maybe. Try changing the settings in Google Play gms and reproduce the steps.
At this time, I'm closing this Issue

**Closed by maxikuzmin** 2023-09-01 10:41 UTC
Labels: Bug, Priority: P4
