### ISSUE TITLE
AdGuard 4.0.638 Internet connection drops when auto-updating AdGuard filter.

### ISSUE THREAD

**Issue by NoName926** [AdguardTeam/AdguardForAndroid#4508] opened 2023-03-04 10:18 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.638

### Environment

```markdown
- OS: android 13
- Device: A53
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Self-destruction of first-party cookies, Disable cache for third-party requests, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Block Flash

### Issue Details

1. Install any app that does real-time network communication and wait for AdGuard to update automatically.

2. Internet disconnection when AdGuard auto-updates

### Actual Behavior

Internet connection drops when auto-updating AdGuard filter.

### Screenshots

![Screenshot_20230305_103525_Clash of Clans](https://user-images.githubusercontent.com/99063049/222938103-37693c5c-ef9d-4657-b0e5-3d0c935674d3.png)

![Screenshot_20230304_190842_Clash Royale](https://user-images.githubusercontent.com/99063049/222894299-0842a41f-dc13-448c-84ca-bbc8411162b2.png)

**Comment by maxikuzmin** [comment] 2023-03-06 16:15
@NoName926 how did you figure out that the problem is related to auto-update filters?
What auto-update interval do you have selected?
What application do you use for network communication?

**Comment by maxikuzmin** [comment] 2023-03-07 18:08
@NoName926 what is the name of the program you are using to do real-time network communication? Is it repeatable without using this program?
Did I understand correctly that after force stopping the application and then starting the application again, the Internet connection is broken after exactly one hour? 

Anyway, it would be nice to have a look at your logs.
Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by U0101100** [comment] 2023-03-14 17:44
Can't auto -updates any of filters on Adguard .
https://github.com/AdguardTeam/AdguardForAndroid/issues/4513#issue-1617470634

**Comment by maxikuzmin** [comment] 2023-03-17 14:15
@NoName926 for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists
@U0101100 you have a different problem, I'll answer you in your issue a little later.

**Closed by maxikuzmin** 2023-03-17 14:15 UTC
