### ISSUE TITLE
Missing ad in Podcast Addict app

### ISSUE THREAD

**Issue by Primokorn** [AdguardTeam/AdguardForAndroid#3484] opened 2020-07-11 08:01 UTC
### Issue Details

https://github.com/AdguardTeam/AdguardFilters/issues/57724

Allow Internet access before opening the app.

- **Device:**
  - Oneplus 3T
- **Root access:**
  - Yes

**Comment by TheHasagi** [comment] 2020-07-13 11:06
@Primokorn 

What's the version of AdGuard do you use? DNS is enabled? If you have root access have you tried installing the certificate in the system storage already?

**Comment by Primokorn** [comment] 2020-07-14 07:55
@TheHasagi AdGuard v3.4
DNS filtering is enabled with AdGuard DNS as the provider.
HTTPS is disabled since I changed my custom ROM. It never worked with my apps (never allowed).

Don't you see ads on your device?

**Comment by Revertron** [comment] 2020-08-14 09:14
1. I'm unable to reproduce this issue.
2. Need more data about user device setup.
3. @Primokorn, did you try it with AdGuard's latest beta 3.5?

Closing for now, if you have this issue in 3.5, then feel free to reopen it.

**Comment by Primokorn** [comment] 2020-08-28 07:07
@Revertron Did you forget me?

**Comment by Primokorn** [comment] 2020-08-30 12:15
@Revertron Reopen the issue.

**Comment by TheHasagi** [comment] 2020-09-01 12:40
@Primokorn 

Please, install the latest beta version and clear the cache in Podcast Addict app. Check that ad is no longer visible.

**Comment by Primokorn** [comment] 2020-09-04 17:05
@TheHasagi No changes.
![Screenshot_20200904_190424_temp](https://user-images.githubusercontent.com/5938828/92267828-9ac6e600-eee1-11ea-98a4-788798338da8.png)

**Closed** 2020-09-09 18:32 UTC
Labels: Bug, P3: Medium, Resolution: Cannot Reproduce, Status: Closed

**Comment by Primokorn** [comment] 2020-09-19 13:24
@TheHasagi Why is this issue closed again???

**Comment by Primokorn** [comment] 2020-10-03 12:53
@TheHasagi ???
