### ISSUE TITLE
AdGuard does not create a local VPN. Protection does not start

### ISSUE THREAD

**Issue by Daviteusz** [AdguardTeam/AdguardForAndroid#4269] opened 2022-11-05 16:00 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [*] I am running the latest version
- [*] I checked the documentation and found no answer
- [*] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  -   v3.6.10 (51)
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  OnePlus 8T, OnePlus 6T
- **Operating system and version:**
  -  Android 13
- **Root access:**
  -  Yes

### Expected Behavior

 Enabling protection and VPN service

### Actual Behavior

Protection does not start, and neither does the VPN service.

### Screenshots

<details><summary>Screenshot:</summary>

https://user-images.githubusercontent.com/11527277/200128655-d0404132-c654-4ff9-8de3-ddad2b66de51.mp4

</details>

### Additional Information

The notification shows:
Preparing to start protection. Please wait...

**Comment by maxikuzmin** [comment] 2022-11-08 16:40
@Daviteusz it's because the "Kill switch" is enabled.  You need to disable it for AdGuard VPN and enable it for AdGuard

**Comment by Daviteusz** [comment] 2022-11-08 21:16
@maxikuzmin Restore the old title, because now it is wrong

 I did not have Adguard VPN enabled, I just had it installed.

After killing the Adguard, it started working again until next device reboot.
This is not the first time this has happened. The problem always occurs on Android 12+ stock or custom rom.

Android 12+ has some problems with the permissions controller (removes granted permissions after tens of minutes or hours, or reboot)

Problem not occurs on A11.

**Comment by maxikuzmin** [comment] 2022-11-09 16:31
@Daviteusz let's take a look at your logs, go deeper into the situation. I don't have this on repeat. Did you confirm the setup of a local VPN during the installation?
Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by latsson** [comment] 2022-11-10 06:31
I had the same problem on my Pixel 6 Pro. Reboots didn't help. Swiping AdGuard didn't help.
I managed to fix it by doing a force stop on the app info view (like what Daviteusz wrote), then when trying to start AdGuard I got the system dialog to approve, then I had to click once more to turn it on.

**Comment by Daviteusz** [comment] 2022-11-15 13:03
@maxikuzmin Sorry, I switched back to android 11, and I can't reproduce this issue for now. Maybe @latsson will send needed logs. 
I will ask more users to check this, maybe they also have this problem.

**Comment by maxikuzmin** [comment] 2022-11-15 16:12
@latsson any news?

**Comment by maxikuzmin** [comment] 2022-11-24 08:01
@Daviteusz has the problem not happened again?

**Comment by maxikuzmin** [comment] 2022-11-24 13:07
@Daviteusz @latsson for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Comment by Daviteusz** [comment] 2022-12-08 04:50
> @Daviteusz has the problem not happened again?

The problem repeated, I sent logs to email.

**Comment by maxikuzmin** [comment] 2022-12-08 11:05
@Daviteusz okay, we will check it

**Comment by Daviteusz** [comment] 2022-12-16 07:15
@maxikuzmin When protection can't start, the VPN profile is not present there. Killing the app helps, but after several device reboot the problem comes back again.

I also tried reinstalling adguard, configuring cleanly, but it didn't help and problem returned after several device reboots.

**Comment by maxikuzmin** [comment] 2022-12-21 17:33
@Daviteusz we need some time, please wait a little longer

**Comment by maxikuzmin** [comment] 2023-01-09 15:13
@Daviteusz probably a problem with the OnePlus firmware. Doesn't sound like our problem. We don't control the state of the system window, we just request it from the OS. If it doesn't appear, the issue is with the firmware manufacturer. Try updating the firmware to the latest version if the manufacturer has released the appropriate firmware

**Comment by Daviteusz** [comment] 2023-01-09 16:16
OxygenOS11-13 (Android 11-13):
- No problem

A11 Custom Roms (OOS11 FW):
- No problem

Custom Roms A12-13 (OOS11 or 12 FW)
- VPN sometimes doesn't start after restarting the device
  Tested on OnePlus 6T and 8T with root, mods and without mods and root

Custom Roms A13 QPR1 (OOS12 or 13 FW)
- No problem so far

The problem also occurs on other devices I tested:
- Redmi 3S, Mi Mix 2S (Android 12.1)

I've currently been testing crDroid 13 (Android 13 QPR1) for the past two days and so far the VPN starts after device reboots. 

This problem is hard to diagnose, but sometimes it occurs. Killing adguard, starting and enabling protection solves the problem for a few or a dozen more reboots. If you can't reproduce this, I'll try to plow through the android and adguard logs myself, maybe I will find the moment when adguard tries to turn on the VPN and why he can't do it...

**Comment by admitrevskiy** [comment] 2023-01-09 21:22
@Daviteusz hello!

If this looks like an AOSP issue, you'd better report the issue to the Google team: https://issuetracker.google.com/issues/new

Highly-likely they'll ask you to get a bugreport. You can follow this instruction: https://kb.adguard.com/en/android/solving-problems/logcat#capture-a-bug-report-from-a-device or use the `adb bugreport` command if you're familiar with ADB.

 BTW can you check this issue with other VPN apps?

**Comment by maxikuzmin** [comment] 2023-01-13 18:25
@Daviteusz we solved your problem in the 3.6.11 Beta 1 update. Please update to this version and check it out. Let us know the result

**Comment by maxikuzmin** [comment] 2023-01-18 17:14
@Daviteusz any news?

**Comment by Daviteusz** [comment] 2023-01-19 09:14
I installed beta1 one hour after your message. I did about 20 reboots and it was OK but while I was writing this message, I did a reboot and...
<img src="https://user-images.githubusercontent.com/11527277/213397285-8ea89bc1-8c58-4735-b90b-85b65f8d1e11.jpg" width="200">
And again applications lost access to all files...
In that case, it's definitely an android bug, not adguard.
<img src="https://user-images.githubusercontent.com/11527277/213398437-197ca917-3cbe-4f62-a81a-06e35dc686a4.png" width="200">

Here new logs:
[adguard_logs_3.6.52_1901_094617.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/10455095/adguard_logs_3.6.52_1901_094617.zip)
[logs-2023-01-19-09-49-49.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/10455096/logs-2023-01-19-09-49-49.zip)

Thanks for trying to solve this.

**Comment by maxikuzmin** [comment] 2023-01-24 11:09
@Daviteusz you are right, this problem is because of your firmware. You need to send a bug report to them.
I hope you manage to solve this problem.

**Closed by maxikuzmin** 2023-01-24 11:09 UTC
Labels: Bug, Resolution: Fixed, Status: Resolved, Middle, Version: AdGuard v3.6.11

**Comment by latsson** [comment] 2023-02-01 13:20
Sorry I never replied. I haven't used Github in a while 😄 
I haven't noticed the problem on my Pixel Pro 6 ever since.
