### ISSUE TITLE
Field to reply doesn't load on androidpit.de

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardForAndroid#1747] opened 2018-03-05 18:13 UTC
### Steps to reproduce

1. Disable all filter lists
2. Go here - https://www.androidpit.de/forum/767967/samsung-galaxy-s8-daten-sichern-wie-am-besten-vorgehen
3. Log in
4. Click on "ANTWORTEN" button

### Expected behavior

There should be a field to reply.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/36990805-1223ff74-20a6-11e8-84ba-afa7d038ac1b.png)

</details>

### Actual behavior

Field to reply doesn't load.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29142494/36990402-e8e46ca8-20a4-11e8-9f6a-9e7d2417b330.png)

</details>

### Your environment

* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: LG G3
* Operating system and version: Android 6.0
* Rooted or not? not
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? -

https://github.com/AdguardTeam/AdguardFilters/issues/12595

**Comment by JustlnTime** [comment] 2018-03-09 15:58
I can confirm the bug mentioned above.

I can also confirm, that it's not possible to mark forum as read, when Adguard is enabled.

**Comment by zebrum** [comment] 2018-05-14 14:08
@AdamWr can't reproduce. Is the issue persist on 2.11.81?

**Comment by AdamWr** [comment] 2018-05-14 14:33
Yes, it's. I still can reproduce it even with all disabled filter lists. I'm not sure, but it seems that it doesn't happen always.
It happens for example here - https://www.androidpit.de/forum/771925/windows-10-fruehjahrsupdate-1803-build-17134-48
I clicked on "Antworten" button in first post.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/40003043-a15c40b6-5792-11e8-8a07-57f577b18e95.png)

</details>

**Comment by nkartyshov** [comment] 2018-05-18 10:09
@JustlnTime  @AdamWr Please, add rule '@@integrator.js^$domain=www.androidpit.de' to the user filter and try to reproduce problem again.

**Comment by JustlnTime** [comment] 2018-05-18 12:11
@nkartyshov Thanks for commenting.

Added this rule with no effect. Same behavior as before.

**Comment by ameshkov** [comment] 2018-06-08 20:28
@AdamWr is it still reproducible with CoreLibs version of AG?

**Comment by AdamWr** [comment] 2018-06-08 20:58
It seems that it works fine with AdGuard 2.12.52n and I can't reproduce it.

**Comment by ameshkov** [comment] 2018-06-08 21:35
Awesome, so it's fixed in CoreLibs then :)

**Closed by ameshkov** 2018-06-08 21:35 UTC
Labels: question
