### ISSUE TITLE
Fails to add adguard.apk in Intune (Azure)

### ISSUE THREAD

**Issue by CryptoRES** [AdguardTeam/AdguardForAndroid#4290] opened 2022-12-05 11:43 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 
- **Filtering mode:**
  - 
- **Device:**
  - 
- **Operating system and version:**
  - 
- **Root access:**
  - 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by CryptoRES** [comment] 2022-12-05 11:45
When adding private app in managed appstore (Azure Intune), error "The package name com.adguard.android is already used by another application."

There is no other application similar to Adguard.

How to get it right?

**Comment by maxikuzmin** [comment] 2022-12-05 16:19
@CryptoRES are you trying to add adguard.apk to Microsoft Azure or Play store?

**Comment by CryptoRES** [comment] 2022-12-05 16:24
> @CryptoRES are you trying to add adguard.apk to Microsoft Azure or Play store?

Trying to add adguard.apk in Intune (Azure)

**Comment by maxikuzmin** [comment] 2022-12-06 14:09
@CryptoRES since Azure is not related to us, try to check with Azure support first to see what the problem might be. 
First we need to figure out whose side the problem is. 
Please let me know what Microsoft Azure has said

**Comment by maxikuzmin** [comment] 2022-12-14 14:04
@CryptoRES for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Closed by maxikuzmin** 2022-12-14 14:04 UTC
