### ISSUE TITLE
HTTPs Filtering suddenly broken

### ISSUE THREAD

**Issue by Murgeye** [AdguardTeam/AdguardForAndroid#3142] opened 2019-10-15 14:33 UTC
### Issue Details
- **AdGuard version:**
  - v3.3 nightly 14, v3.3.64.0 (Beta)
- **Filtering mode:**
  - Local Proxy Auto Mode
- **Device:**
  - OnePlus 6
- **Operating system and version:**
  - Android 9
  - OxygenOS 9.0.9
- **Root access:**
  - Yes (Magisk 20.0, Magisk Manager 7.3.5)
### Expected Behavior

HTTPs Filtering works and does not throw an error for every app.
### Actual Behavior

(Almost?) Every app on my phone started rejecting the Adguard HTTPs certificate after updating to the new beta version. The problem persists for v3.3 nightly 14. Everything still seems to work in 3.2.150 (1.4.138cl).

The afflicted apps are unable to open any HTTPs connections.

The certificate is moved to the system store using the "Move Certificates" Magisk Module.

If you need any more Info, I will be glad to provide it.

### Screenshots

![Screenshot_20191015-155143](https://user-images.githubusercontent.com/16648242/66840895-0f5f0200-ef69-11e9-8eb4-d54e359dbfc8.jpg)

**Comment by artemiv4nov** [comment] 2019-10-15 15:49
Duplicate of #3052

**Closed by artemiv4nov** 2019-10-15 15:49 UTC
