### ISSUE TITLE
Loss of Network Connection After Certain Apps Are Used

### ISSUE THREAD

**Issue by christantoan** [AdguardTeam/AdguardForAndroid#4222] opened 2022-08-23 08:49 UTC
### Issue Details

- **AdGuard version:**
  - v3.6.9 (48)
- **Filtering mode:**
  - HTTP Proxy (Auto)
- **Device:**
  - OnePlus 7 Pro
- **Operating system and version:**
  - Oxygen OS 11.0.9.1.GM21BA
- **Root access:**
  - Yes

### Expected Behavior

Network connection for apps filtered through AdGuard continues to work.

### Actual Behavior

Network connection for apps filtered through AdGuard stops working.

### Screenshots

N/A

### Additional Information

There are some apps (one of them is my banking app, https://play.google.com/store/apps/details?id=id.co.cimbniaga.mobile.android) that when used while AdGuard is active, most of the time, several minutes after the app is closed, will cause other apps that is filtered through AdGuard to lose network connection.

The main symptom other than the loss of connection is that I can't disable AdGuard through normal method (it keeps showing the circular logo while trying to stop) and have to use Force Stop.

The almost random nature and delayed effect of the bug make diagnosing harder.

I have also reported this bug through in-app form and gotten 631485 as the ticket number.

Other setting details: https://github.com/AdguardTeam/AdguardFilters/issues/127893#issue-1347524454

**Comment by maxikuzmin** [comment] 2022-08-24 15:42
@christantoan did I understand correctly that after you start your banking application and then close it, your internet connection stops working after a while? Do you have internet connection in the beginning? Did you check other apps before launching the banking app? Do you have internet connection until you start the banking app? Can you send us a video on email devteam@adguard.com with the steps you take to close AdGuard? We need to understand exactly what you are clicking on

**Comment by christantoan** [comment] 2022-08-24 16:10
> @christantoan did I understand correctly that after you start your banking application and then close it, your internet connection stops working after a while?

Yes, but not always, and only on apps filtered by AdGuard. Since your reply, I've been trying to trigger the problem to give you the logs of when the connection drops however, no luck so far.

> Do you have internet connection in the beginning?

Yes.

> Did you check other apps before launching the banking app?

Yes, I checked Chrome, some WebView apps, and other online native apps such as WhatsApp. They all stop having Internet connection when this occurs. Other apps that are not filtered through AdGuard, continues to work online.

> Do you have internet connection until you start the banking app?

Yes.

> Can you send us a video on email [devteam@adguard.com](mailto:devteam@adguard.com) with the steps you take to close AdGuard? We need to understand exactly what you are clicking on

I'm still trying to trigger the problem. I'll send it after I got to trigger it.

**Comment by maxikuzmin** [comment] 2022-08-29 13:34
@christantoan we're looking into the problem. Please wait

**Comment by maxikuzmin** [comment] 2022-08-31 16:44
@christantoan please try updating to version 3.6.10 and repeat the problem. Is it still repeating with the new version?
Also you can see in the logs that the protection is running, but it didn't get to launch, logs were exported earlier, can you record them a little longer please? If there is still a problem, repeat logs please

**Comment by christantoan** [comment] 2022-08-31 23:27
Yes, it still happens on version 3.6.10.

Here are the new longer recording and logs (logs are exported after the recording is done): 

https://user-images.githubusercontent.com/7300310/187802180-96676daa-ad2d-4fe9-8d4b-933cc77d79e3.mp4

[adguard_logs_3.6.51_0109_062242.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/9465686/adguard_logs_3.6.51_0109_062242.zip)

**Comment by maxikuzmin** [comment] 2022-09-01 08:14
@christantoan thank you! But in the video, do you just disable protection and have the app hang? Do any apps end up affecting this, or does it happen on its own? What steps do you take before it hangs?

**Comment by christantoan** [comment] 2022-09-01 08:19
Yes, I didn't record the previous part because the bugh doesn't always happen. I started recording when I was sure the bug was happening.

Like what I had written on the issue, I only opened my bank app, did some transactions, and then closed it. After that, my apps lost network connection.

**Comment by maxikuzmin** [comment] 2022-09-12 11:52
@christantoan do you have a recurring problem in VPN mode? To understand: the problem is autoproxy or something else. The logs are not debug.
To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by christantoan** [comment] 2022-09-12 12:42
@maxikuzmin From my quick test, VPN mode doesn't seem to have this bug however I didn't test extensively.
I have sent the bug report and debug log to the dev team.

**Comment by maxikuzmin** [comment] 2022-09-20 08:44
@christantoan so did the "go to VPN mode" solution work for you? Does it work?

**Comment by christantoan** [comment] 2022-09-21 02:57
@maxikuzmin Yes, it solves the problem. I just tested it for roughly 1 day. However, I can't use my VPN connection when AdGuard's VPN is active.

**Comment by maxikuzmin** [comment] 2022-10-05 14:41
@christantoan we need the debug logs. Could you repeat the error, unload the debug logs and resend them? Preferably with the time of login and logout of the application

**Comment by christantoan** [comment] 2022-10-05 15:03
@maxikuzmin Just sent a newly captured log together with a timeline. Hope it helps.

**Comment by maxikuzmin** [comment] 2022-10-14 08:17
@christantoan this feature will be redesigned in version 4.0, no exact release date is known yet, but it will be very soon. Please wait for version 4.0. If the problem recurs, you can reopen the issue

**Closed by maxikuzmin** 2022-10-14 08:17 UTC
