### ISSUE TITLE
Add Yandex Browser Alpha as a browser filtered by default 

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForAndroid#198] opened 2015-11-26 15:36 UTC
Package name: com.yandex.browser.alpha

GCV-856-85213

**Comment by TPS** [comment] 2015-11-27 08:17
Duplicate of #192?

**Comment by ameshkov** [comment] 2015-11-27 11:53
Closing as duplicate

**Closed by ameshkov** 2015-11-27 11:53 UTC
Labels: Duplicate
