### ISSUE TITLE
HTTPS filtering causes hackernews reader app Harmonic to crash

### ISSUE THREAD

**Issue by foundObjects** [AdguardTeam/AdguardForAndroid#4261] opened 2022-10-24 18:23 UTC
HTTPS filtering is causing my hackernews reader to crash in certain circumstances. Problem app can be found here: https://play.google.com/store/apps/details?id=com.simon.harmonichackernews

Reproduction: 
* Install app
* Log in to hn via app
* Go into any post and upvote or clear a vote for a comment
* App will crash

Mitigation:
* In Adguard Android: app management > disable https filtering for harmonic
* Retry hn comment voting
* Voting should succeed

What I expect to happen:
Voting for comments in-app shouldn't cause the app to crash with HTTPS filtering enabled.

Why this is a pain and HTTPS off isn't a good workaround:
The app uses custom tabs to display the article/page under discussion, these can be absolutely littered with ads.

Other mitigations attempted:
I've tried unblocking all app traffic to ycombinator.com, firebase and any other domain that looked relevant to app function. Nothing resolves the app crash except disabling HTTPS filtering entirely.

### Issue Details

- **AdGuard version:**
  - 4.0 Nightly 35 (79) (all devices tested)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Various including OnePlus 7T, Samsung Galaxy Tab S6, etc
- **Operating system and version:**
  - Android 11, 12, 12.1
- **Root access:**
  - Yes

**Comment by maxikuzmin** [comment] 2022-10-25 13:23
@foundObjects what error do you see? Because every time I try to click on "Vote", I see the error "Bad login", even if AdGuard is completely removed from the device. 
Also when I try to access the profile, I see the error "Loading failed". 
Maybe the error is not in our application, but you say that everything works correctly when you disable filtering? 
Anyway, we need debug logs

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

Also, repeat the steps you described and take screen shots of the filtering log. It will be good to see which requests are blocked. Send it in devteam@adguard.com too.

**Comment by maxikuzmin** [comment] 2022-10-31 10:43
@foundObjects any news?

**Comment by maxikuzmin** [comment] 2022-11-02 10:33
@foundObjects for the moment, I'm closing this issue. You can reopen the issue in the future if the problem persists

**Closed by maxikuzmin** 2022-11-02 10:33 UTC
