### ISSUE TITLE
AdGuard App Crashes

### ISSUE THREAD

**Issue by Varsity4763** [AdguardTeam/AdguardForAndroid#5164] opened 2024-01-13 03:52 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.199

### Environment

```markdown
- OS: Android 13
- Device: POCO M2 Pro
- Firmware:
Running PixelExperience Plus (Custom ROM)
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Install Adguard on Android
2. Run the app--->App asks for agreeing T/C and then asks to create a local vpn
3. The app now freezes and then crashes 

### Expected Behavior

The Adguard should run smoothly with no crashing issue

### Actual Behavior

The Adguard app crashes after the app is run for 10sec

<details><summary>Screenshot</summary>

![Screenshot_20240113-085729_AdGuard](https://github.com/AdguardTeam/AdguardForAndroid/assets/156095573/d9a3ceef-5e55-4294-9e65-161f03c11823)

</details>

### Additional Information

The issue was not there in earlier version Adguard 4.3 Nightly 20, but now it is an issue for all the versions I tried installing on my phone

**Comment by Versty** [comment] 2024-01-15 12:51
@Varsity4763 Hi! 

Please remove your AdGuard version and download the latest version from [this link](https://agrd.io/apk). Then try to install downloaded .apk file. 

If the crash persists, please [collect a system bug report](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/) and send it to devteam@adguard.com. In the subject line mention the issue number `5164` and in the description specify the time when the crash occurred.

**Comment by Versty** [comment] 2024-01-22 08:14
@Varsity4763 Hi! 
The logs from you have been received. We would like you to provide some details. 
If you launch AdGuard application but do not enable Protection, will the crash occur then?

**Comment by Versty** [comment] 2024-01-23 08:19
@Varsity4763 Thank you, we are investigating.

**Comment by Versty** [comment] 2024-01-23 09:28
@Varsity4763 Please try removing AdGuard VPN profile from the system settings (Settings -> More connection settings -> VPN -> AdGuard -> Delete VPN profile). Then launch AdGuard, check if it keeps crashing or not, and let me know the result.

**Comment by Versty** [comment] 2024-01-23 11:33
@Varsity4763 The video will be useful, please provide it if possible via link or zip.

**Comment by Versty** [comment] 2024-01-23 12:21
@Varsity4763 Please reinstall AdGuard application and check all three checkboxes on the first screen of the application. 
Then go to the Home tab and wait for the crash to occur. 
This actions are important in order to fix the problem. 

<p align="left">
<img src="https://github.com/AdguardTeam/AdguardForAndroid/assets/107266340/b629acdb-a9fe-404d-baae-e9757b43d296" width="300" >
</p>

**Comment by Versty** [comment] 2024-03-05 11:19
@Varsity4763 Hi! 
My apologies for the long wait. Could you please check if the issue is fixed in the latest AdGuard for Android nightly version?

The version is available to download via [this link](https://agrd.io/android_nightly).

**Closed** 2024-06-19 15:43 UTC
Labels: Bug, Resolution: Fixed, Status: Resolved, Priority: P2
