### ISSUE TITLE
No access when using Proxy mode + another VPN + Block WebRTC on

### ISSUE THREAD

**Issue by alexdonh** [AdguardTeam/AdguardForAndroid#3369] opened 2020-03-05 12:24 UTC
### Issue Details

I believe the title says it all. I have no access when I use proxy mode (auto), another VPN and have Block WebRTC enabled in Settings -> Stealth Mode.

I have just only tested on NordVPN as I am currently using it. Not sure other VPNs having the same problem.

I also think it has something to do with IPv6. I will try to disable my IPv6 and report back.

- **AdGuard version:**
  - 3.3.2
- **Filtering mode:**
  - HTTP Proxy (Auto)
- **Device:**
  - Samsung Galaxy S10+
- **Operating system and version:**
  - Android 10 One UI 2.0
- **Root access:**
  - Yes

### Expected Behavior

Have internet access.

### Actual Behavior

No internet access.

**Comment by TheHasagi** [comment] 2020-03-06 11:56
@alexdonh 

Hello!

Can you check with the latest [Nightly](https://agrd.io/android_nightly)?

**Comment by alexdonh** [comment] 2020-03-13 15:32
@TheHasagi 

Sorry for late reply. I was in middle of something.

I tried with latest nightly build 3.4 nightly 8 looks like it been fixed.

**Comment by akmLaVx** [comment] 2020-06-11 19:03
We've got a fresh reproduction of the issue.
See case 1787304 for logs.

**Comment by Revertron** [comment] 2020-08-14 13:37
Tested all the protocols and extra options in NordVPN and can't reproduce the issue. The only issue may be that you need to disable HTTPS filtration for NordVPN as it does not trust our CA.
Closing for now, but if someone still has this issue and has new logs and/or info feel welcome to reopen.

**Closed by Revertron** 2020-08-14 13:37 UTC
Labels: Question, Status: In Progress, Waiting for data
