### ISSUE TITLE
Unable to update Amazon, Aurora, Smart Home Apps, Banking apps with AdGuard protection enabled

### ISSUE THREAD

**Issue by SyCoREAPER** [AdguardTeam/AdguardForAndroid#5361] opened 2024-06-14 04:55 UTC
Least to most important:

- Github still shows an all black version (old version) of AdGuard, can we get all black back?

- New Version group of Nightlies breaks numerous apps. Why? I don't know. Looked at the logs and see nothing odd. Either don't have any internet access or cripples resources to a minimal functional app. Amazon, Aurora, Smart Home Apps, Banking BUT not everything. Rolled back to stable, all work as expected. 

- Hugely important. Google AI Overview. I've been working on numerous filters of my own doing, had GPT generate a few, I can't get them to work.

Came across below, any updates on getting rid of this crap? 

https://adguard.com/en/blog/google-ai-overviews-bad-ad.html

**Comment by maxikuzmin** [comment] 2024-06-14 16:57
@SyCoREAPER 

>Github still shows an all black version (old version) of AdGuard, can we get all black back?

We'll be changing the screenshots on GitHub soon

>New Version group of Nightlies breaks numerous apps. Why? I don't know. Looked at the logs and see nothing odd. Either don't have any internet access or cripples resources to a minimal functional app. Amazon, Aurora, Smart Home Apps, Banking BUT not everything. Rolled back to stable, all work as expected.

Could you please clarify more exact steps and clarify what exactly is the problem? Describe the problem and steps to replicate, such as for Amazon, so I can check this out

>Hugely important. Google AI Overview. I've been working on numerous filters of my own doing, had GPT generate a few, I can't get them to work.

Google AI Overview is still under review, we should be able to test this soon

**Comment by SyCoREAPER** [comment] 2024-06-14 17:44
@maxikuzmin

Boo, lol. So no black planned? Old school dark mode aka AMOLED Mode called these days has really stuck with me.

As for misbehaving apps, just one very specific example becauee I remember how to replicate it without installing currently Nightly and having to revert back.
     On XDA we have an app called Aurora by one of the developers. That app with 100% certainty just wouldnt download updates. No fiddling or steps to reproduce. Install, "sign in secure" (uses their dummy account so your G-Account cant get banned) and try to update your apps. Nothing happens. Reverted to old version of AdGuard, same everything else, works fine.
 

Glad to hear it. Overview AI is driving me nuts. It seems to only affect (or maybe my custom filters worked?) mobile version of Google but desktop version is fine. If you need a Guinea pig, Err I mean Beta or even an Alpha tester, I'm in.

**Comment by maxikuzmin** [comment] 2024-06-17 10:48
@SyCoREAPER about the theme - yes, right now a single dark theme for all devices is implemented, built on variables. Maybe in the future we will add an additional "true" black theme (AMOLED), but not now. Anyway, we will discuss this topic.


Regarding advertising in AI Overviews - Google had an announcement that they would release this in all countries by the end of the year, but since they are having some issues with the AI Overviews themselves right now, it might be a stretch. In May, Google was planning to implement this feature for USA first, as far as I know. Are you located in the USA?

Could you please repeat the steps with trying to update the Aurora app and unload the debug logs?

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Debug

- Reproduce steps, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

- Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):

mention the 5361 number in the subject
specify the exact time when the issue occurred

**Comment by maxikuzmin** [comment] 2024-06-17 11:17
@SyCoREAPER regarding Google AI Overview, you can try recording [HAR logs](https://adguardteam.github.io/KnowledgeBase/guides/collect-har-file/) for now, with screen shots of what you see. And also the saved page code (copied from devtools from inspector).

Send the files by email devteam@adguard.com

**Comment by maxikuzmin** [comment] 2024-06-17 11:18
@SyCoREAPER I assume the main topic we have remains an issue with the Aurora app? Then I'll rename the issue

**Comment by SyCoREAPER** [comment] 2024-06-17 15:36
It's not just Aurora Store, as mentioned that's the one that it can be reproduced without a million steps. Other misbehaved too

**Comment by maxikuzmin** [comment] 2024-06-19 08:20
@SyCoREAPER okay, I get it about the other apps, but why did you close the issue?

**Comment by maxikuzmin** [comment] 2024-06-19 08:22
@SyCoREAPER did you mean the Aurora Store app?

**Comment by SyCoREAPER** [comment] 2024-06-25 14:01
Yes Aurora Store.

I closed it because I got frustrated that I said it happened with multiple apps but the title was changed just to reflect one.

**Comment by maxikuzmin** [comment] 2024-06-25 17:41
@SyCoREAPER I apologize, I didn't mean to upset you. I wanted to concretize the problem. I'll change the title to something more ambitious. What about the logs? Were you able to upload them?

**Comment by maxikuzmin** [comment] 2024-07-01 11:55
@SyCoREAPER any news?

**Comment by maxikuzmin** [comment] 2024-07-05 15:41
@SyCoREAPER we need your logs to figure out the problem

**Comment by maxikuzmin** [comment] 2024-07-08 09:49
@SyCoREAPER for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Closed by maxikuzmin** 2024-07-08 09:49 UTC
Labels: Priority: P4

**Comment by SyCoREAPER** [comment] 2024-07-25 15:47
Test
