### ISSUE TITLE
Android TV 7.0 crash/reboot on Sony Bravia

### ISSUE THREAD

**Issue by jjssoftware** [AdguardTeam/AdguardForAndroid#1392] opened 2017-08-21 19:32 UTC
This issue is described in point #2 here: https://forum.adguard.com/index.php?threads/android-tv.6428/#post-145633

If any VPN is active when the TV is resuming from standby, a core Android service process crashes and the TV performs a full reboot rather than elegantly resuming from standby. 

Jecht_Sin in Adguard forum does a sterling job of explaining a potential fix for this issue in Adguard where Adguard might pause / stop the VPN when the TV is going into standby and then later resume the VPN when the TV is brought out of standby (if Adguard is running / active). 

There is also a thread in the Sony forum that describes the issue further and although it has the title "Android 6.0.1 reboots after enabling VPN apps" I can confirm this also affects Android TV 7.0 on my Sony Bravia KD-65XE8596: https://community.sony.ie/t5/android-tv/bug-android-6-0-1-reboots-after-enabling-vpn-apps/td-p/2284371

I can also confirm that the TV resume from standby is happy and behaves normally when Adguard is installed but protection is off which gives weight to the theory this issue is centered around VPN being active on standby resume.

I hold no hope for Sony to fix this problem even though it really is their problem to fix but the sorry situation is that in my experience Adguard works very well on a Sony Bravia Android TV except for this one issue which really makes it quite unusable. 

Is there any hope that Adguard might investigate a potential fix to this issue as suggested? If so I'll happily trial beta builds of Adguard on my TV to help test this feature out.

**Comment by ameshkov** [comment] 2017-08-21 19:34
Wow, this is a very-very detailed bug report, thank you very much!

**Comment by ameshkov** [comment] 2017-08-21 19:39
In theory, it can be solved by using Tasker to automate disabling VPN when the screen goes off.

**Comment by jjssoftware** [comment] 2017-08-21 22:08
Thanks for the Tasker suggestion. This is something I have considered but unfortunately this idea is not as simple as it first might appear:
1. As far as I'm aware Tasker doesn't make it easy to directly disable / enable VPN connections. I think it might be possible with the OpenVpn Tasker plugin but I haven't tested this yet.
2. Rather than going for the direct VPN control approach, another approach might be to ensure Adguard is launched and visible in the foreground and then simulate an input click but there's a couple of issues with this:
-- Under normal circumstances Tasker requires root to perform / simulate an input click and I'm not willing to pursue rooting the TV (my main reason for using Adguard to begin with is that it doesn't require root)
-- It is supposed to be possible to simulate an input click with the AutoInput app which doesn't require root and then wire this through Tasker. I've not tested this on the Android TV but have tested it on a OnePlus2 phone and found it to be unreliable (with intermittent java exceptions). This unreliability could be related to Adguard not being visible / clickable when the screen is off.

It's at this point I start to think this is not a very clean solution but is actually quite messy and I've uninstalled Adguard on the TV for now but live in hope that one day it will be usable.

**Comment by ameshkov** [comment] 2017-08-22 07:49
> As far as I'm aware Tasker doesn't make it easy to directly disable / enable VPN connections. I think it might be possible with the OpenVpn Tasker plugin but I haven't tested this yet.

Here you are:
https://kb.adguard.com/en/android/solving-problems/tasker

**Comment by ameshkov** [comment] 2017-08-22 07:50
The thing is that we need to find proper triggering even to stop AG. I the display off event will do, but not sure. Even if we integrate it into AG, we still need to find out which even should we hook onto.

**Comment by jjssoftware** [comment] 2017-08-22 21:09
> Here you are:
https://kb.adguard.com/en/android/solving-problems/tasker

Nice thanks, that works well on my phone. I'll be sure to try this out on the TV asap and will report back with results.

**Comment by jjssoftware** [comment] 2017-08-27 13:55
Unfortunately testing on the TV didn't go so well. I did get Tasker installed along with the tasks and profiles added to stop / start Adguard on display off / on but it doesn't work as expected and I still see Android crash TV reboot behaviour at standby resume time. 

I was able to test the Tasker tasks directly within Tasker and I can confirm they work as expected to stop / start Adguard protection however I have a feeling that the Tasker display off / on profiles might actually not be enabled; the Tasker UI appears to be not well suited to Android TV and the option to save / enable Tasker configuration which I did see on my phone isn't being seen when using Tasker on the TV.

I'll have to remove Adguard from the TV again..so close yet so far :)

**Comment by ameshkov** [comment] 2017-08-28 16:30
@jjssoftware 
could you please remind me of this issue after the next AG beta is out? I'll build a test build with display on/off triggers inside of AG, we'll see how it goes then.

**Comment by jjssoftware** [comment] 2017-08-28 17:18
Of course, I'll watch https://github.com/AdguardTeam/AdguardForAndroid/releases and I'll drop a note here when I see the next beta release after the current 2.10.16. I know there are no guarantees here but your help is very much appreciated

**Comment by jjssoftware** [comment] 2017-09-04 05:37
@ameshkov Hi Andrey I see that the 2.10.56 beta has been released so here's the reminder you asked for. Cheers, Joe

**Comment by ameshkov** [comment] 2017-09-07 09:50
Here you are:
[Uploading adguard_issue1392_test1.apk.zip…]()

**Comment by Michelasso** [comment] 2017-09-12 10:47
Hi, I am the user Jecht_Sin in the Sony forum. :)

I confirm that the VPN bug in Android TV for Bravia  propagated from Android 6.0.1 to Android 7.0. In my tests I mage a script that every few seconds was checking the status  screen off (can't check events in a Unix shell script. Or at least I don't know how). If the screen was off I killed Adguard with "am force-close <Adguard package name>".

That obviously was working but it was a bit brutal. Still I can confirm that with the app alive, but with the VPN disabled in the app (round power button off), the reboots do no happen. So my idea is that you should turn the VPN off when the screen switches off (basically the equivalent of removing the VPN key on mobile).

I tried your pkg above and I am not sure if it is because I need to set something but the TV still reboots. I can provide a "logcat *:e" if you're interested. And thanks!

**Comment by ameshkov** [comment] 2017-09-12 10:50
@Michelasso 

> I can provide a "logcat *:e" if you're interested

Yeah, AG log is what I need. You can get it from the cache directory:
https://kb.adguard.com/en/android/solving-problems/log

**Comment by Michelasso** [comment] 2017-09-12 11:48
Ok, I have collected the adguard log. I can tell you already that I know what's going on: with the screen/TV off the VPN is still active. The tun0 interface still shows with ipconfig. That must be off otherwise it will always reboot.

Anyway, here is the attached log file:
[adguard.log.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1295791/adguard.log.zip)

PS: any way you can make the icon showing in the Leanback launcher (Home)? I have to start the app from X-plore.

**Comment by ameshkov** [comment] 2017-09-12 12:24
It seems that Android does not notify us about screen going off. The last intent we got before it crashed was this:
```
Screen receiver got intent: Intent { act=android.intent.action.SCREEN_ON flg=0x50000010 }
```

> PS: any way you can make the icon showing in the Leanback launcher (Home)? I have to start the app from X-plore.

People say you should use sideload launcher for that:
https://www.reddit.com/r/AndroidTV/comments/4i5cx5/how_do_you_add_app_shortcuts_to_the_leanback/

**Comment by ameshkov** [comment] 2017-09-12 12:34
Your custom shell script may be a way to go, but instead of `am force-close` you could use these two commands:

1. To start protection:
```
am startservice -n com.adguard.android/.ServiceManager -a android.intent.action.SEND --ei ACTION 2
```

2. To stop it:
```
am startservice -n com.adguard.android/.ServiceManager -a android.intent.action.SEND --ei ACTION 4
```

**Comment by Michelasso** [comment] 2017-09-12 13:26
Blimey! My script does work now! I have been looking for those two commands forever. 😄 

This is the extract of the script only for this specific issue:

```
#!/system/bin/sh
while [ 1 ]; do
        VPNSTATUS=$(ifconfig | grep tun0 | awk '{ print $1 }')                              
        ISTVOFF=$(service call power 12 | awk '{ print $3 }')                               
        AG_ISOPEN=$(dumpsys window windows | grep -E '(mCurrentFocus.*com.adguard.android)')                      

# The TV is ON the and VPN is OFF                                                                                 
        if [ "$VPNSTATUS" == "" ] && [ $ISTVOFF == "00000001" ]; then                                             
                sleep 2                                                                                           
                am startservice -n com.adguard.android/.ServiceManager -a android.intent.action.SEND --ei ACTION 2
        fi                                                                                                        
                                                                                                                  
# The TV is OFF the and VPN is ON                                                                                 
        if [ "$VPNSTATUS" != "" ] && [ $ISTVOFF == "00000000" ]; then                                             
                am startservice -n com.adguard.android/.ServiceManager -a android.intent.action.SEND --ei ACTION 4
        fi

        sleep 1
done
```

The big downside is that after each reboot I have to remember to run the script again with:

`adb shell '(cd /data/local/tmp; /data/local/tmp/nohup /system/bin/sh /data/local/tmp/huey_kill )'`

The name of the script is huey_kill, because it started with the Service HueyManager (DRM crap for DLNA I believe) randomly crashing. I have stripped out the hueymanager stuff from the script.

But it is also true that if I disable the "enable at boot" option in Adguard it should be safe. yeah, tested it now. The script turns the VPN on. 

Still, since this isn't the optimal solution, any chance it you can make the events working? Checking the logcat I do get some Screen OFF events:

```
09-12 15:24:36.688  1842  1885 I DisplayManagerService: Display device changed state: "Built-in Screen", OFF
09-12 15:24:38.372  1842  2565 D PowerManagerService-JNI: Excessive delay in setInteractive(false) while turning screen off: 1543ms
09-12 15:24:38.374  1842  1842 E ActivityManager: Sending non-protected broadcast com.sony.dtv.intent.action.PRE_SCREEN_OFF from system 1842:system/1000 pkg android
09-12 15:24:38.445  6168  6168 I SonyMetaDataManagerService: onReceive Intent { act=com.sony.dtv.intent.action.PRE_SCREEN_OFF flg=0x10000010 }
09-12 15:24:38.534  7107  7745 I SonyDTVBrowser_CEB: receive broadcastintent PRE_SCREEN_OFF
09-12 15:24:38.536  7126  7126 I SonyDTVBrowser_WAR: receive broadcastintent PRE_SCREEN_OFF
```

**Comment by jjssoftware** [comment] 2017-09-13 12:46
Tester #2 here :) I've tested with the supplied beta apk above too and still see the crash with this test version when coming out of stand by. Here's my verbose log:

[adguard.log.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1299404/adguard.log.zip)

In the log I can see this screen off event caught when I put the TV into stand by:

```
13:26:28.786 [main] DEBUG c.a.a.receivers.ScreenStateReceiver - Screen receiver got intent: Intent { act=android.intent.action.SCREEN_OFF flg=0x50000010 }
```

..interestingly after that the log suggests that AdGuard protection remains active during the time when the display is off.

Then about 60 seconds or so later when I bring the TV out of stand by, I see this screen on event is logged into the log:

```
13:27:25.958 [main] DEBUG c.a.a.receivers.ScreenStateReceiver - Screen receiver got intent: Intent { act=android.intent.action.SCREEN_ON flg=0x50000010 }
```

..and then shortly after 13:27:32.794 in the log I witnessed the crash / reboot

**Comment by Michelasso** [comment] 2017-09-13 13:48
Honestly I don't know if it is worth the effort. The OS is still unstable. The issue isn't really with the sleep state, but with any change in the IP connection. When turning the TV on the OS simply starts to reconnect the TV after the sleep. Which is what really causes the crash. But I can get a reboot with VPN active also changing the DHCP/static setting or any other IP related configuration. This has been discovered time ago by another user (in Germany I think).

Switching the VPN off when turning off the TV would still partially work around the issue. But there is also a problem with timing (and with our slow SoC I doubt the messaging would be immediate). For example with my script I turned off the TV and turned it on again after few seconds and the TV rebooted (well, to be honest it would be better to remove that "sleep 2", it does more damage than benefit). If the messages aren't caught immediately some reboots must be expected.

Then, I don't know if it is a coincidence or else, but with Adguard DNS I wasn't getting any YouTube ads (or at least they were very seldom). Reinstalled Adguard I restored the local DNS server  for testing and the ads appeared again in YouTube.

So I think I'll stick with Adguard DNS. But thanks everyone for your time! 😊

**Comment by ameshkov** [comment] 2017-09-13 17:02
> Then, I don't know if it is a coincidence or else, but with Adguard DNS I wasn't getting any YouTube ads (or at least they were very seldom).

It seems that AG DNS helps with the TV version of Youtube indeed. Maybe they'll update the app to avoid it eventually, hopefully not too soon.

**Comment by ameshkov** [comment] 2017-12-04 12:41
Closing as it's not clear what we can do from our side:(

Are there any good news from Sony?

**Closed by ameshkov** 2017-12-04 12:41 UTC
Labels: question

**Comment by jjssoftware** [comment] 2017-12-04 13:59
There's nothing from Sony to indicate they acknowledge there's a problem that they need to fix. Sony support / Sony moderators in the customer support forums aren't much use at all.

I don't hold any hope for Sony doing anything to fix this and I'm convinced that they outsource everything android related. Their android TV build is poor in a number of areas and their hardware is woefully underspecced so it would struggle to be able to deliver a good user experience even if they did iron out all the bugs.

**Comment by Michelasso** [comment] 2017-12-05 06:03
Yes, what @jjssoftware said. I don't even bother anymore. If it wasn't for the (current) lack of Amazon Video and support of profile vp9 for YouTube I would have bought an Apple TV 4K and forgot about this sorry excuse for an OS implementation, using the TV only as a display.

**Comment by yuriw** [comment] 2018-03-20 21:18
Wow, lots of crashes !  @jjssoftware any workarounds for this issue?  I see it on Sony Bravia XBR43800e

**Comment by jjssoftware** [comment] 2018-03-20 21:42
@yuriw the problem still exists and it's not just Adguard that triggers this Sony Bravia TV crash / restart. I've since seen exactly the same problem when I had the IPVanish VPN Android TV app installed and active. 

My workaround now is to just not bother with any type of ad blocking or VPN software installed on the TV any more. Personally nowadays I have a pihole device on the LAN for DNS based network wide ad block purposes and I use socks5 proxy configuration in SPMC rather than full blown VPN

**Comment by yuriw** [comment] 2018-03-20 21:49
@jjssoftware thanks for quick reply ! 

I have Sony TV and pfSense main router (disabled all ads filtering) and need to find solution to be able to connect to VPN (NordVPN currently in mind).  (Will see if I want to add OpenVPN on my main pfSelnse router soon)

I am still working on having OpenVPN and a separate small router.
And can actually live with a workaround to turn off OpenVPN before turning off TV (annoying a little).

Do you have anything else I should consider ?

**Comment by jjssoftware** [comment] 2018-03-20 22:09
@yuriw I have no first hand experience with pfSense yet but I have considered building a pfSense router / VPN device specifically to solve the VPN client / initiator -> VPN server problem that I have here. I suppose how well it would work would depend on the spec of the pfSense hardware and if I do go down this road, VPN is one of the problems that I hope pfSense will solve.

I'm really not impressed with the performance of my own Sony Bravia Android TV. I've done what I can to strip out all the unwanted Sony bloat and that has noticeably improved general responsiveness..but I generally try to not tax it too much. This means I'll continue to pursue LAN based solutions for ad blocking / VPN etc.

I know this probably doesn't help you much but this is my approach here :)

**Comment by yuriw** [comment] 2018-03-20 22:23
@jjssoftware actually it helped me to do next step maybe, try pfSense
I was hesitant to try VPN client on router as I am using NordVPN for maybe 4 days and not sure if I like it enough to risk my home network.  I have 2 Sony TVs and also got one for my mom, so I am stuck with it for awhile :)

**Comment by Michelasso** [comment] 2018-03-21 08:02
@yuriw Even with the workaround Android TV was crashing every other time. I mean, it isn;t something that one can really manage via a shell script, also given the poor performances of the CPU (if the network interface changes for any reason - usually a wake - before the script is able to turn off Adguard or the VPN, it's a sure crash).

If your goal is just to disable the ads the good news is that Adguard DNS does wonders. It even blocks the Youtube ads!! Also from the Apple TV (which I bought and goodbye Android). My entertainment time is much less miserable, now!! 😄

**Comment by XENNOK** [comment] 2018-04-06 19:11
I have some kind of workaround, which might be not as too complicated and reasonable practical.
You need a programm like remapper: https://play.google.com/store/apps/details?id=flar2.homebutton&hl=en
You cange some key you like (custom button) and give it a new action: "Shortcuts": Adguard.
With a press of a button you enable/disable Adgaurd. [on Sony Remote I took the Button above or under mute]
So, going into standby would be a two buttons action, but with no crash of the tv while resuming from standby.
