### ISSUE TITLE
Add a low-level setting that disables HTTPS filtering yellow snack

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#3315] opened 2020-01-20 17:54 UTC
See the comment:
https://github.com/AdguardTeam/AdguardForAndroid/issues/3225#issuecomment-576057509

**Comment by artemiv4nov** [comment] 2020-01-21 10:01
This task is a duplicate of #3292
Follow the updates in the task.

**Closed by artemiv4nov** 2020-01-21 10:01 UTC
Labels: Enhancement, P4: Low
