### ISSUE TITLE
DNS filtering issues DoT & DoH

### ISSUE THREAD

**Issue by nihilt** [AdguardTeam/AdguardForAndroid#3146] opened 2019-10-16 01:37 UTC
### Issue Details

- **AdGuard version:**
  3.3.81
- **Filtering mode:**
  HTTP Proxy (Auto) or Local VPN
- **Device:**
  Xiaomi Redmi Note 7
- **Operating system and version:**
  Android 9, MIUI 11 xiaomi.eu (11.0.2.0 stable)
- **Root access:**
  Yes (Magisk)

### Actual Behavior
1- Setting Cloudflare's DoT under Private DNS option (1dot1dot1dot1.cloudflare-dns.com) https://blog.cloudflare.com/enable-private-dns-with-1-1-1-1-on-android-9-pie/ and selecting "System Default" under Adguard's DNS server options will prevent some websites from loading e.g. DD-WRT forum

2- IPV6 Test https://ipv6-test.com/ browser fallback fails 

3- This also occurs when manually choosing Cloudflare's DoT under Adguard's DNS server options. 

4- Setting Pie's Private DNS option to default"Automatic" and selecting Cloudflare's **DoH** or **DoT** under Adguard's server settings ends up listing Google DNS resolvers too  dnsleak.com / ipleak.net

5- Setting Cloudflare's DoT under Pie's Private DNS option and then disabling Adguard clears all issues above.  
 

### Screenshots

<details><summary>Screenshot:</summary>

</details>

**Comment by admitrevskiy** [comment] 2019-10-17 11:44
@nihilt hi!
1) I do not recommend you to use Android Private DNS and AdGuard DNS module simultaneously. We have inform message about it for Android Q+, it looks like we should show it for P as well.

2, 3) Please, provide me more information. Did you use VPN or local HTTP Proxy filtering mode? AdGuard DNS module + Android Private DNS may cause unpredictable behaviour, anyway.

4) It's known issue.

5) I think that reverse action (disabling Private DNS and settings Cloudflare DoT in AG) should clear this issues also. But AG provides DNS filtering, in contrast to Private DNS :)

**Comment by nihilt** [comment] 2019-10-18 00:56
Hi @admitrevskiy

Yeah, that was to point out that there are no issues with P Private DNS and Cloudflare's DoT

AG 3.3.87

**Local Proxy Auto mode:**

Private DNS disabled instead of default "Auto" mode

Both AG's Dot and Doh are not working, basically using DD-WRT router DNSMasq settings instead.

domain-needed
bogus-priv
no-negcache
**no-resolv
server=1.0.0.1
server=1.1.1.1
server=2606:4700:4700::1001
server=2606:4700:4700::1111**
interface=br0
dhcp-range=br0,::1000,::FFFF,constructor:br0,ra-stateless,12h
ra-param=br0,10,300
enable-ra
quiet-ra
quiet-dhcp
quiet-dhcp6

![Screenshot_2019-10-17-18-05-41-022_org bromite bromite - Copy](https://user-images.githubusercontent.com/56614537/67056842-ad3a0480-f102-11e9-9103-b6ac3b52f448.jpg)

**Local VPN:**

Private DNS disabled

Both AG's DoH and DoT are working fine. All previously mentioned issues are gone

![Screenshot_2019-10-17-18-23-46-837_org bromite bromite - Copy](https://user-images.githubusercontent.com/56614537/67056994-89c38980-f103-11e9-8200-b65b78c40445.jpg)
![Screenshot_2019-10-17-18-34-15-781_org bromite bromite - Copy](https://user-images.githubusercontent.com/56614537/67056997-8fb96a80-f103-11e9-97bb-ab036a07e8e8.jpg)

AG's DoT and DoH would be a great option for the windows version too, Cloudflare will release a win version of the 1.1.1.1 app soon.

**Comment by ameshkov** [comment] 2019-10-23 12:11
> Local Proxy Auto mode:
> Private DNS disabled instead of default "Auto" mode
> Both AG's Dot and Doh are broken, basically using DD-WRT router DNSMasq settings instead.

Isn't it a duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/2977?

**Comment by nihilt** [comment] 2019-11-07 07:14
Local VPN:
ICMP fails with AG 3.3.129, unlike 3.3.114.
![PSX_20191106_200725](https://user-images.githubusercontent.com/56614537/68366798-f0403400-0112-11ea-9c03-a609dc3dcf50.jpg)

Local proxy auto mode:
Issues with both browser fallback and ICMP.
![PSX_20191106_200758](https://user-images.githubusercontent.com/56614537/68367094-a277fb80-0113-11ea-9d1e-df08d04d06e2.jpg)

**Comment by admitrevskiy** [comment] 2019-11-22 15:59
Both issues with `ipv6-test` are irrelevant to DNS as I can see since both are reproducible with disabled DNS filtering. 
We have an issue with IPv6 UDP traffic redirection in HTTP root proxy mode and we are already looking for a solution.

**Comment by admitrevskiy** [comment] 2019-11-29 09:25
Related CoreLibs issue: https://github.com/AdguardTeam/CoreLibs/issues/1209

**Closed** 2020-08-05 10:05 UTC
Labels: DNS, Enhancement, P3: Medium, Waiting for data
