### ISSUE TITLE
Cannot Exclude dns And root "Apps" From Filtering

### ISSUE THREAD

**Issue by christantoan** [AdguardTeam/AdguardForAndroid#4232] opened 2022-08-29 11:57 UTC
### Issue Details

- **AdGuard version:**
  - v3.6.10 (51)
- **Filtering mode:**
  - HTTP Proxy (Auto)
- **Device:**
  - OnePlus 7 Pro
- **Operating system and version:**
  - Oxygen OS 11.0.9.1.GM21BA
- **Root access:**
  - Yes

### Expected Behavior

dns and root "apps" is excluded from AdGuard filtering when their AdGuard protection are toggled off.

### Actual Behavior

dns and root "apps" are still filtered by AdGuard filtering when their AdGuard protection are toggled off.

### Screenshots

<details><summary>Screenshot: root "app" is excluded from AdGuard protection. Note the failure to load the technical information for the "app".</summary>

![Screenshot_20220829-184111](https://user-images.githubusercontent.com/7300310/187194628-3fbe088e-9f16-4878-bd75-12137e7d54ee.png)

</details>

<details><summary>Screenshot: dns "app" is excluded from AdGuard protection. Note the failure to load the technical information for the "app".</summary>

![Screenshot_20220829-184133](https://user-images.githubusercontent.com/7300310/187194925-8537985e-4694-47d4-b309-9b4e9ebf46dc.png)

</details>

<details><summary>Screenshot: Traffic from dns "app" is still processed by AdGuard despite the exclusion.</summary>

![Screenshot_20220829-184138](https://user-images.githubusercontent.com/7300310/187195062-1172f6c5-9b9f-44aa-af91-0442583829bf.png)

</details>

<details><summary>Screenshot: HTTPS filtering error notification for dns "app" despite the exclusion.</summary>

![Screenshot_20220829-184207](https://user-images.githubusercontent.com/7300310/187195182-df85919c-80f1-457f-a748-3360ac940649.png)

</details>

### Additional Information

I also have tried just toggling off the HTTPS filtering and Ad blocking toggles but the traffic is still processed as if all the toggles are enabled.

The reason why I want to exclude both of these "apps" are that they sometimes generate a lot of HTTPS filtering error notifications and prevent the update of some of my root CLI applications which run under root privileges (SSL Error due to HTTPS filtering, I guess).

Logs: [adguard_logs_3.6.51_2908_184256.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/9444305/adguard_logs_3.6.51_2908_184256.zip)

**Comment by maxikuzmin** [comment] 2022-08-30 14:30
@christantoan we're looking into the problem. Please wait

**Comment by christantoan** [comment] 2022-08-31 23:32
<details><summary>Screenshot: HTTPS filtering error notification for dns and root "apps" despite the exclusion.</summary>

![iMarkup_20220901_063018](https://user-images.githubusercontent.com/7300310/187802620-5baa9590-af24-4235-b11b-1a236587556c.png)


</details>

**Comment by maxikuzmin** [comment] 2022-09-05 09:55
@christantoan this is a take on an already known problem, question closed.
Duplicate of <https://github.com/AdguardTeam/AdguardForAndroid/issues/4170>
Just wait for version 4.0

**Closed by maxikuzmin** 2022-09-05 09:55 UTC
