### ISSUE TITLE
com.spotify.music - broken app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3233] opened 2019-11-28 21:36 UTC
@adguard-bot commented on [Wed Nov 27 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44962)

### Issue URL (Incorrect Blocking)
[https://play.google.com/store/apps/details?id=com.spotify.music&hl=ru](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.spotify.music%26hl%3Dru)
### Comment
Username: @Pashkens
> По совету пробовал отключить DNS от адгуарда (был прописан в роутере, в телефоне изначально отключен): результата не дало. По очереди отключал фильтры и все вместе: результата не дало. Лечится только путем добавления Spotify в исключение "Защита AdGuard" (ползунок выкл).

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/T66oRfa.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/rHiAvld.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 9 pie
AdGuard version: | 3.2.150 (1.4.138cl)
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Self-destructing first-party cookies (По умолчанию), Self-destructing third-party cookies (По умолчанию), Block WebRTC, Block Location API, Hide your Referrer from third-parties (По умолчанию), Hide your User-Agent (По умолчанию)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Security:</b><br/> Malware Domains Blocklist<br/><br/><b>Language-specific:</b><br/> AdGuard Russian
Other extensions used: | Никакие

---

@Pashkens commented on [Wed Nov 27 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44962#issuecomment-559252548)

Пояснение о проблеме: не загружаются обложки треков в Spotify

---

@Alex-302 commented on [Thu Nov 28 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44962#issuecomment-559565682)

@AdamWr could you, please, check it?

---

@AdamWr commented on [Thu Nov 28 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44962#issuecomment-559567894)

If I understand correctly the problem is with not loading covers.
If so, then I can't reproduce it with AdGuard nightly build.
<details><summary>Screenshot</summary>

![Screenshot_20191128-182146_Spotify](https://user-images.githubusercontent.com/29142494/69824577-79c3bd00-120c-11ea-99f4-e5c4fb6b26d8.jpg)

</details>

Could you please install nightly build and check if it still happens?

---

@Pashkens commented on [Thu Nov 28 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44962#issuecomment-559574449)

> If I understand correctly the problem is with not loading covers.
> If so, then I can't reproduce it with AdGuard nightly build.
> 
> Screenshot
> Could you please install nightly build and check if it still happens?

Yes, you understood correctly. Set the nightly build, the problem was not solved. Maybe I can provide any logs?

---

@AdamWr commented on [Thu Nov 28 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44962#issuecomment-559575236)

Please check if HTTPS filtering is disabled for Spotify (AdGuard > Apps Management > Spotify).
<details><summary>Screenshot</summary>

![tempFileForShare_20191128-190120](https://user-images.githubusercontent.com/29142494/69826052-c4940380-1211-11ea-8a19-95293ac546d5.jpg)

</details>

---

@Pashkens commented on [Thu Nov 28 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44962#issuecomment-559575767)

> Please check if HTTPS filtering is disabled for Spotify (AdGuard > Apps Management > Spotify).

Was disabled all time

---

@Alex-302 commented on [Thu Nov 28 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44962#issuecomment-559577967)

@Pashkens нужен отладочный лог. Как его записать:
https://kb.adguard.com/ru/android/solving-problems/log#debug
Время запуска spotify запомните, и укажите его вместе с логом.

---

@Pashkens commented on [Thu Nov 28 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44962#issuecomment-559588889)

[adguard_logs_3.3.156_2911_001651.zip](https://github.com/AdguardTeam/AdguardFilters/files/3902870/adguard_logs_3.3.156_2911_001651.zip)
Запуск Spotify 00:14:45 (запустил и пролистал три трека), отключение логгирования 00:15:20

---

@Alex-302 commented on [Thu Nov 28 2019](https://github.com/AdguardTeam/AdguardFilters/issues/44962#issuecomment-559606822)

Спасибо.

**Comment by artemiv4nov** [comment] 2020-05-25 08:43
@Pashkens check on the latest nightly version, please. Also, use the latest Spotify app version. Perhaps, the problem was gone. (I can't reproduce it)

**Comment by artemiv4nov** [comment] 2020-07-13 19:24
So, the problem can't be reproduced, a user didn't respond. I close this task. If it will happen again, please re-open the task

**Closed** 2020-08-17 10:36 UTC
Labels: Bug, Question, Resolution: Fixed, Status: Resolved
