### ISSUE TITLE
Adgaurd protection disables automatically when the screen turns off

### ISSUE THREAD

**Issue by front360** [AdguardTeam/AdguardForAndroid#4648] opened 2023-05-02 02:22 UTC
### Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

v4.0 Beta 1 (10063190)

### Environment

```markdown
- OS:Android 10
- Device:Samsung Galaxy a10e
- Firmware:
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
1.Unlock phone
2.
3.

### Actual Behavior

9 out of 10 times that I unlock my Samsung Galaxy a10e, AdGuard is disabled automatically, I never manually disable it. I have the app locked in the recent apps window. I have all battery savers, sleep settings disabled. I use AdGuard VPN, same thing happens with that app also. Thanks in advance, Donald

Attachment(s)
[debug.zip](https://adguard.zendesk.com/attachments/token/imT0HDMq5JJDjrqEKTM7iP9O3/?name=debug.zip)

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by jordanswrld94** [comment] 2023-05-02 14:11
There is an option in vpn settings called always on vpn can u check it on and see if this fixes it

**Comment by 0xrxL** [comment] 2023-05-03 18:27
@Versty Any update about this? Is a terrible bug.

**Comment by jordanswrld94** [comment] 2023-05-03 18:33
Mine constantly says its enabling like id say every 20 mins or less. I toggled the always on vpn option in settings idk if adguard would restart with that option not on

**Comment by jordanswrld94** [comment] 2023-05-03 18:38
You can Try toggling that. But then you cant use adguard vpn. U can only use one or the other

**Comment by ScathachSkadi** [comment] 2023-05-03 23:59
Enabling the VPN always on option in the settings didn't help for me. But it does give me a notification when it gets disconnected. So I guess it's better to get more visuals when it crashes.

**Comment by jordanswrld94** [comment] 2023-05-04 00:21
Go to settings general advanced then watcdog and enter in 120 it will check if it stopped working and reenable vpn

**Comment by ScathachSkadi** [comment] 2023-05-04 01:57
@jordanswrld94 No, I already have that on. It reenables by itself like it did before. The most annoying part that it crashes in the first place.

**Comment by 0xrxL** [comment] 2023-05-09 11:24
This bug has been totally ignored...despire its severity. 🤷‍♂️

**Comment by ScathachSkadi** [comment] 2023-05-09 12:19
Fyi, for the mods to see, it still does this. It's annoying but I got used to it.

**Comment by Versty** [comment] 2023-05-19 14:26
@meow-gh Hi! 
We have received your logs. Do you have the same issue as described in the [first post of this discussion](https://github.com/AdguardTeam/AdguardForAndroid/issues/4648#issue-1691676343)?

**Comment by Versty** [comment] 2023-05-23 09:45
@0xrxL Do you have the same issue related to the state of protection when unlocking the device?

**Comment by Versty** [comment] 2023-05-23 09:47
@front360 Any updates? 

Please make sure that you have the "Adaptive power saving" option disabled as well.

**Comment by 0xrxL** [comment] 2023-05-23 14:26
> @front360 Any updates?
> 
> Please make sure that you have the "Adaptive power saving" option disabled as well.

Yeah...I had the same issue (also during the device use). Now I'm currently on stable version.

**Comment by front360** [comment] 2023-05-27 20:08
Yes all adaptive power settings are disabled. Thanks for trying to help.Sent from my Galaxy
-------- Original message --------From: 0xrxL ***@***.***> Date: 5/23/23  10:26 AM  (GMT-05:00) To: AdguardTeam/AdguardForAndroid ***@***.***> Cc: front360 ***@***.***>, Mention ***@***.***> Subject: Re: [AdguardTeam/AdguardForAndroid] Adgaurd protection disables
  automatically when the screen turns off (Issue #4648) 

@front360 Any updates?
Please make sure that you have the "Adaptive power saving" option disabled as well.

Yeah...I had the same issue (also during the device use). Now I'm currently on stable version.

**Comment by front360** [comment] 2023-05-27 20:14
Watchdog feature is disabled, thanks.Sent from my Galaxy
-------- Original message --------From: Diana ***@***.***> Date: 5/19/23  9:39 AM  (GMT-05:00) To: AdguardTeam/AdguardForAndroid ***@***.***> Cc: front360 ***@***.***>, Mention ***@***.***> Subject: Re: [AdguardTeam/AdguardForAndroid] Adgaurd for Android disables
  automatically  (Issue #4648) 
@front360 Hi, Donald.
We are sorry for the long wait for an answer. Do you have the watchdog feature enabled?

**Comment by Versty** [comment] 2023-05-28 21:51
@front360 We would recommend enabling the watchdog option in this case. Please choose any convenient value from 120 to 300. Let's see if it helps.

**Comment by 0xrxL** [comment] 2023-07-07 17:03
@Versty this issue has been fixed after the release of nightly related to the issue https://github.com/AdguardTeam/AdguardForAndroid/issues/4707

**Comment by Versty** [comment] 2023-07-18 09:22
@front360 Could you please confirm if this issue is fixed on your device in the latest nightly version?

**Comment by ScathachSkadi** [comment] 2023-07-18 10:06
@Versty The issue is fixed for me but it doesn't give me update notifications anymore. I have to go to the updates and check it for myself. Before the bugfix, this didn't happen. I guess the crash was related to the automatic update checking?

**Comment by Versty** [comment] 2023-07-18 13:54
@ScathachSkadi Yes, the issue was related to the autoupdate period. 
Does the "app updates" switch enabled in the notification settings? 
*Settings tab -> General -> App notifications*

**Closed** 2023-08-16 15:31 UTC
Labels: Bug, Priority: P4
