### ISSUE TITLE
Blocked requests, sent by an app, are not highlighted

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#2873] opened 2019-07-03 11:19 UTC
### Steps to reproduce

1. Open filtering log;
2. Open any app(not a browser) and block requests;
3. Restart that app

### Expected behavior

Blocked requests are highlighted

### Actual behavior
Blocked requests are not highlighted

### Your environment
* Adguard version: 3.1.58n
* Adguard filtering mode: Local VPN

Log:
[adguard.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/3354725/adguard.zip)

**Comment by Alex-302** [comment] 2019-07-03 11:20
It seems they are blocked, just not highlighted
```
14:03:39.972 [Thread-8] DEBUG Native.AGSslBypassFilter - [id=1000041] URL is blacklisted: https://api.instabug.com by rule ||api.instabug.com^
14:04:54.842 [Thread-9] DEBUG Native.AGSslBypassFilter - [id=1000424] URL is blacklisted: https://a.applvn.com by rule ||a.applvn.com^
14:04:55.489 [Thread-8] DEBUG Native.AGSslBypassFilter - [id=1000425] URL is blacklisted: https://googleads.g.doubleclick.net by rule /googleads.$domain=~googleads.blog|~googleads.media
```

**Comment by sfionov** [comment] 2019-07-03 11:31
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/2863

**Closed** 2019-07-03 11:35 UTC
Labels: Bug, UI
