### ISSUE TITLE
com.dragonflow.android.orbi app is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4253] opened 2022-10-10 10:41 UTC
@adguard-bot commented on [Sat Oct 01 2022](https://github.com/AdguardTeam/AdguardFilters/issues/131117)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=com.dragonflow.android.orbi](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.dragonflow.android.orbi)
### Comment
Username: @AnthonyBe
> AG is blocking Netgear Orbi app login

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/7B42zgd.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/qnnaug8.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 12
AdGuard product: | AdGuard for Android v3.6.10+(51)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Self-destructing third-party cookies (180), <br>Block WebRTC, <br>Hide your Referrer from third-parties (), <br>Hide your Referrer from third-parties, <br>Hide your IP address (209.141.53.254)
DNS filtering: | server: `https://security.cloudflare-dns.com/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt, DnsUserRules`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/>AdGuard Mobile App Banners, <br/>AdGuard Popups, <br/>Adblock Warning Removal List, <br/>AdGuard Other Annoyances, <br/>AdGuard Annoyances, <br/>AdGuard Cookie Notices, <br/>AdGuard Widgets<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List
Userscripts: | https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

---

@Alex-302 commented on [Mon Oct 03 2022](https://github.com/AdguardTeam/AdguardFilters/issues/131117#issuecomment-1265277366)

@AnthonyBe Hi. I don't have Netgear device, but Android app works - I can register and login.
Is the problem related to enabled filters, Stealth Mode or DNS filtering?

---

@AnthonyBe commented on [Sun Oct 09 2022](https://github.com/AdguardTeam/AdguardFilters/issues/131117#issuecomment-1272470206)

Even after being logged into the Netgear Orbi app (by disabling AG), with AG enabled, when I go into 'Account Management' in the Orbi application, I get an error "You are not connected to the internet. Check your internet connection.."
I have to go into the Account Management section to logout to continue testing what in AG is blocking access.

I tried disabling Stealth Mode in AG - no change.
I went into DNS Filtering and disabled DNS Requests blocking - no change
I've set DNS to Cloudflare and Cloudflare for Families (thus bypassing my local Adguard Home DNS) - no change
I've tried disabling individual groups of filters - Ad Blocking, Privacy, Security, Annoyances, Custom, as well as turning them all off at the same time, but nothing unblocks accessing the Netgear account management or login/logoff pages.

As soon as I disable AG, I can get into the Account Management section and login and logout.

**Comment by maxikuzmin** [comment] 2022-10-12 09:31
@Alex-302 @AnthonyBe I think the problem is not with our app. It's worth contacting ORBI support team. I'll close the issue.

https://user-images.githubusercontent.com/101641415/195306153-bb3b7d12-41c1-4535-a2ba-e9aaa6a5579b.mp4

**Closed by maxikuzmin** 2022-10-12 09:31 UTC
Labels: Bug
