### ISSUE TITLE
Websites loads with errors  when filtration is on (Connection is not protected)

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2045] opened 2018-08-10 16:19 UTC
The page loads with errors when AdGuard is on (Connection is not protected)

The new feature to implement : waitQuietly (to avoid connection loss)

### Steps to reproduce

1.Open AdGuard, start service
2.Open any website (news.yandex.ru) 

### Expected behavior

Everything seems to be in order, all pages loads fine without any issues.
### Actual behavior

Page loads with error (see the screenshot)

<details><summary>Screenshot:</summary>
<img src="https://user-images.githubusercontent.com/37797229/43969034-8d271e98-9cd1-11e8-8772-415499674cae.png" width="300">
<img src="https://user-images.githubusercontent.com/37797229/43969035-8d477eea-9cd1-11e8-84ce-0cb72d58a74c.png" width="300">

</details>

### Customer ID 

1405021
### Your environment

* Adguard version: 2.12.140
* Adguard filtering mode: VPN
* Device model: (e.g. Google Pixel) HighScreen Boost IIse
* Operating system and version (e.g. Android 7.1.2) 4.3 sdk=18

**Comment by ameshkov** [comment] 2018-08-10 16:38
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/2003

**Closed by ameshkov** 2018-08-10 16:38 UTC
Labels: feature request
