### ISSUE TITLE
[NIGHTLY] Continued disconnects when changing networks

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1731] opened 2018-02-23 20:56 UTC
Logs available under 1473812

### Steps to reproduce
1. Switch networks
2. The bug will only happen when screen is turned down

### Expected behavior
AdGuard should continue working. Internet should be available

### Actual behavior
Disconnect

### Customer ID 
1473812

### Your environment
* Adguard version: 2.11.23
* Adguard filtering mode: VPN
* Device model: HUAWEI BKL-L09
* Operating system and version (e.g. Android 7.1.2): Android 8.0
* Rooted or not?: None
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None

**Comment by TPS** [comment] 2018-02-26 03:33
Isn't this behavior by design & configurable via [`pref.vpn.disable.pause`](https://blog.adguard.com/en/adguard-for-android-2-1-release/)?

**Comment by Alexandr82** [comment] 2018-02-26 19:46
pref.vpn.disable.pause setting does not solve the problem

**Comment by ameshkov** [comment] 2018-03-03 21:48
Duplicate of #1594

Temporary solution: enable `pref.vpn.disable.reconfiguration`.

```
AdguardVpnService - Error while building VPN file descriptor
java.lang.IllegalStateException: Cannot bind com.adguard.android.vpn.AdguardVpnService
	at android.os.Parcel.readException(Parcel.java:1953) ~[na:0.0]
	at android.os.Parcel.readException(Parcel.java:1891) ~[na:0.0]
	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1987) ~[na:0.0]
	at android.net.VpnService$Builder.establish(VpnService.java:785) ~[na:0.0]
	at com.adguard.android.vpn.AdguardVpnService.a(Unknown Source:403) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.d(Unknown Source:68) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.c(Unknown Source:13) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService$3.run(Unknown Source:2) ~[na:0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:0.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:784) ~[na:0.0]
01:02:19.396 [pool-1-thread-1] INFO  com.adguard.android.ServiceManager - ServiceManager handle status event: VPN_CONFIG_ERROR
01:02:19.402 [pool-1-thread-1] INFO  com.adguard.android.service.bd - Updating widgets for VPN_CONFIG_ERROR protection
```

**Closed by ameshkov** 2018-03-03 21:48 UTC
Labels: duplicate

**Comment by Alexandr82** [comment] 2018-03-03 22:46
pref.vpn.disable.reconfigure helps
