### ISSUE TITLE
socks5 proxy not working with Adguard 4.0

### ISSUE THREAD

**Issue by terrytw** [AdguardTeam/AdguardForAndroid#4812] opened 2023-06-21 01:39 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: Android 12
- Device: Xperia 5 II
- Firmware: Lastest
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter

### Issue Details

Steps to reproduce:
1. Setup any socks5 proxy
2. Connect to said proxy via Adguard
3. Try connecting to google.com

### Expected Behavior

Smooth internet connection.

### Actual Behavior

No internet connection.

**Comment by sfionov** [comment] 2023-06-21 05:10
@terrytw We have a fix for outbound proxies in "4.1 nightly 7", can you please check if helps you? 

Note: _Don't forget to export and save your settings before installing nightly version._

**Comment by sfionov** [comment] 2023-06-21 05:14
UPD: Seems that nightly is not out yet, sorry. It will be available today or tomorrow.

**Comment by terrytw** [comment] 2023-06-21 05:43
Sure, I will check it up and come back to you. Thanks for the response.

**Comment by Versty** [comment] 2023-06-22 17:14
@terrytw The version should be available. Please check if this issue is fixed on your device.

**Comment by terrytw** [comment] 2023-06-24 07:58
@Versty Dear Diana,

Thanks for the follow up, I just tested the 4.1 nightly 8, it seems that connection issue has been fixed. 

However, the "check connection" button in socks5 proxy is still malfunctioning. When i clicked on the "check connection" button, sometimes it says "connection working" and sometimes it says "connection failed".

**Comment by Versty** [comment] 2023-06-26 10:59
@terrytw We would like to take a look at the logs from your device. 

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue related to the button behaviour, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Sent this file to devteam@adguard.com:
      - mention the `4812` number in the subject
      - specify the exact time when the issue occurred

**Comment by terrytw** [comment] 2023-06-28 13:09
Dear Diana,

I have sent the logs via E-mail.

**Comment by Versty** [comment] 2023-06-28 13:54
@terrytw Thanks! 
We have received your logs and are currently examining them.

**Comment by sfionov** [comment] 2023-07-17 16:58
@terrytw We have read your logs. Does you proxy support IPv6? Seems that IPv6 connection via proxy is successful but immediately resets. So it fails when IPv6 is connected faster than IPv4. I think that it is better to fix on proxy side, since this behavior (successful connect + reset) may lead to problems in other apps too.

**Comment by terrytw** [comment] 2023-07-18 10:32
@sfionov Dear dev,

Unfortunately it is not the case you just described. Please refer to the following 2 pictures:
![1](https://github.com/AdguardTeam/AdguardForAndroid/assets/24227628/8bb81a89-ed52-4395-9c3a-34bc84e260cc)
![2](https://github.com/AdguardTeam/AdguardForAndroid/assets/24227628/d9a3b091-676e-4402-9c3e-944b898c490c)

First one is taken with adguard and proxy enabled, second one is taken with adguard and proxy disabled. As you can see, IPv6 is not available at all. 

On top of that, the proxy I have worked perfectly fine with Adguard 3.6.8.

One thing I would like to mention is that the problem only occurs with mobile network, not with wireless.

**Comment by ngorskikh** [comment] 2023-07-20 11:41
@terrytw Hello! So are you using a local proxy (i.e. a proxy that is on the same machine as the client)? What software is it? I'd like to replicate your setup to get a better understanding.

**Comment by terrytw** [comment] 2023-07-20 12:16
@ngorskikh Hi I am using shadowsocks (with v2ray plugin) with proxy only mode.

**Comment by Versty** [comment] 2023-08-07 10:51
@terrytw We have found a root cause. Currently working on the fix, will be available as a part of CoreLibs v1.12.

**Comment by terrytw** [comment] 2023-08-07 11:28
@Versty Thanks for the update, I really appreciate it! 

Happy to know you guys find out the problem, great work as always!

**Closed** 2023-08-10 11:35 UTC
Labels: Bug, Waiting for data, Priority: P4, Version: CoreLibs v1.12
