### ISSUE TITLE
Add editing option to the Android version

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForAndroid#1210] opened 2017-05-04 22:29 UTC
We've got a request about adding an editing option to the mobile version instead of deleting and adding the mistyped domain, for example.

Ticket ID:1550230

**Comment by TPS** [comment] 2017-05-05 23:19
Related to #308 & #828.

**Comment by uBlock-user** [comment] 2017-05-06 04:25
Yes, a very needed option apparently.

**Comment by TPS** [comment] 2017-05-20 05:23
> I guess that's about both user filter & whitelist?

@ameshkov Really, _anyplace_ we can add (freeform) to a list, present & future.

**Comment by TPS** [comment] 2017-05-30 13:20
When in filter-editing mode (either from filtering-log or anyplace else), it'd be great to have additional toggles like `$important` for `$image`, `$script`, &c.

**Comment by ameshkov** [comment] 2017-06-14 15:23
Duplicate of #1279

**Closed by ameshkov** 2017-06-14 15:23 UTC
Labels: Duplicate
