### ISSUE TITLE
Need to limit number of udp connections which are opened at the same time

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1215] opened 2017-05-11 15:22 UTC
ticket id 1554251
2.9.70

<details>

[debug (1).txt.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/993463/debug.1.txt.zip)

</details>

```21:20:49.983 [Thread-451] DEBUG com.adguard.android.filtering.vpn.i - UDP id=1 Connecting to /192.168.1.254:53. Process info: com.adguard.dns unknown unknown 0
21:20:49.986 [Thread-451] DEBUG c.a.android.filtering.commons.d - UDP id=1 Creating new connection com.adguard.dns unknown unknown 0 with packet UDP 172.16.209.1:59506 > 192.168.1.254:53 len=40
21:20:49.988 [pool-2-thread-1] DEBUG c.a.android.filtering.commons.d - UDP id=1 [OUT] UDP 172.16.209.1:59506 > 192.168.1.254:53 len=40
21:20:49.991 [pool-2-thread-1] DEBUG com.adguard.android.FilteringLog - UDP id=1 DNS request: domain=2.android.pool.ntp.org, type=1
21:20:49.992 [pool-2-thread-1] DEBUG c.a.android.filtering.commons.d - UDP id=1 Open UDP connection from /172.16.209.1:59506
21:20:50.005 [Thread-451] DEBUG com.adguard.android.filtering.vpn.i - UDP id=2 Connecting to /192.168.1.254:53. Process info: com.adguard.dns unknown unknown 0
21:20:50.006 [Thread-451] DEBUG c.a.android.filtering.commons.d - UDP id=2 Creating new connection com.adguard.dns unknown unknown 0 with packet UDP 172.16.209.1:39873 > 192.168.1.254:53 len=40
21:20:50.008 [pool-2-thread-1] DEBUG c.a.android.filtering.commons.d - UDP id=2 [OUT] UDP 172.16.209.1:39873 > 192.168.1.254:53 len=40
21:20:50.009 [pool-2-thread-1] DEBUG com.adguard.android.FilteringLog - UDP id=2 DNS request: domain=2.android.pool.ntp.org, type=1
21:20:50.010 [pool-2-thread-1] DEBUG c.a.android.filtering.commons.d - UDP id=2 Open UDP connection from /172.16.209.1:39873

**Comment by vozersky** [comment] 2017-05-11 15:50
might be related to #1168

**Comment by ameshkov** [comment] 2017-05-26 10:15
I can't say that in this particular case the problem is with the connections count.

The problem here is that gateway IP address is added to VPN routes.

DNS request goes to the gateway IP -> intercepted by AG -> sent to the same IP by AG -> intercepted again.

The whole situation is quite weird as the socket is explicitly protected from VPN...

**Comment by ameshkov** [comment] 2017-05-26 13:20
@zebrum please ask the user to enable DNS filtering in AG settings. Does it help?

**Comment by dzamyshlyayeva** [comment] 2017-05-28 21:50
asked the user.

**Comment by ypetruk** [comment] 2017-05-30 00:03
The customer wrote that it still crashed with the same error.
"The problem appears that a Java request is being made with a max-length of
45000 but the Java configuration has a maximum max-length of 32kb.

Is it possible to reconfigure AdGuard to request just under 32kb, or to
change my java configuration to allow the current 45000-byte request?"

**Comment by ameshkov** [comment] 2017-05-30 08:00
Oh, @ypetruk you can ignore that line in the config file, it is irrelevant to the actual problem, just can't parse a certain filter rule.

Meanwhile, I am interested in the new log file

**Comment by OlegSUP** [comment] 2017-06-01 09:50
Log:

[adguard.log.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1044312/adguard.log.zip)

**Comment by ameshkov** [comment] 2017-06-13 12:03
Here is a test build with gateway IP excluded from the VPN:
[adguard_issue1215.apk.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1071280/adguard_issue1215.apk.zip)

Please ask the user to try it.

**Comment by OlegSUP** [comment] 2017-06-13 13:27
Done

**Comment by ameshkov** [comment] 2017-12-04 12:58
Fixed in CoreLibs

**Closed by ameshkov** 2017-12-04 12:58 UTC
Labels: filtering, question
