### ISSUE TITLE
vpn icon blinking although adguard is on

### ISSUE THREAD

**Issue by qiratdahaf** [AdguardTeam/AdguardForAndroid#5222] opened 2024-02-19 12:08 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.1

### Environment

- OS version: android 13
- Device: Samsung 
![Screenshot_20240219_170006_Settings](https://github.com/AdguardTeam/AdguardForAndroid/assets/122544035/85e3fda1-b362-4443-b56e-76ce166b929a)
s22 ultra (not rooted)

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [x] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List, Fanboy's Anti-thirdparty Fonts

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, I don't care about cookies, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, NoCoin Filter List

### Other

Filter unblocking search ads and self-promotion, AdGuard DNS filter, AdGuard Experimental filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters from URLs, Hide your search queries, Ask websits not to track you, Self-destruction of third-party cookies, Block ETag and If-None-Match headers, Block the third-party Authorization header, Disable WebRTC, Block Push API, Block Location API, Hide your Referrer from third-parties, Hide your User Agent, Hide your IP address, Remove X-client-Data header from HTTP request, Protect against DPI

### Issue Details

Steps to reproduce:
1. Whatsapp audio/video call
2. Watch youtube video
3.during gaming or watching netflix

### Expected Behavior

It should not blink or interrupt internet. 

https://github.com/AdguardTeam/AdguardForAndroid/assets/122544035/84ed0de4-aaff-4ebb-9aca-13ec84aa0c66

### Actual Behavior

Dear Dev, 

I have been facing this issue for quite some time now. It is irritating and breaks my internet performance. The vpn icon of adguard starts blinking for no reason, In attached screen recording see filtering logs screen and main screen of adguard, nothing shows up there, I am an old user of adguard, and to my knowledge, it is configured correctly.

I am facing this issue on multiple mobile devices with different android os builds, so it is not unique to my device either. Perhaps you can check  and resolve it in the upcoming update. 

It is a repeatable issue. First, I thought it is because of whatsapp (during calls) or youtube, so i excluded them, but it still persists. I tried to attach logs and send you all info via mobile app, but it failed, so i initiated req manually. 

Thank you for your time and consideration. 

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Please see attached video and observe vpn icon

**Comment by maxikuzmin** [comment] 2024-03-06 10:22
@qiratdahaf you're right, the VPN icon shouldn't be blinking. It would be nice to get your logs.

* Enable debug logging:
Settings -> General -> Advanced -> Logging level -> Debug

* Reproduce the issue, then remember the exact time when it happened

* Collect logs:

Settings -> General -> Advanced -> Export logs and system info

* Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):
mention the 5222 number in the subject
specify the exact time when the issue occurred

**Comment by qiratdahaf** [comment] 2024-03-11 08:52
Generated logs were more than 25mb, so I couldn't attach logs directly into attachments, but i have attached them via Google Drive link.

**Comment by maxikuzmin** [comment] 2024-03-11 13:24
@qiratdahaf I got your logs, it's gonna take us a while to figure it out

**Comment by maxikuzmin** [comment] 2024-03-21 08:38
@qiratdahaf please clarify if you have other VPN applications? 
You need to check if this behavior is repeated when connecting to another VPN profile. It would be nice to check this with any other VPN application connected to the location

**Comment by qiratdahaf** [comment] 2024-03-21 08:47
No, i do not use another vpn, but i can check it.
I forgot to mention that I can export and share my settings configuration too if you need so you can look into it.

**Comment by qiratdahaf** [comment] 2024-03-25 11:51
I used solid vpn (paid version), and i did see vpn interruption. But not like adguard. And it's not repeatable either. 

I have it installed on 2 different mobiles right now. And trying to record during my use.

I will get back to you in 2 days.

**Comment by qiratdahaf** [comment] 2024-03-27 13:56
It's not occurring in other vpns.
Some how its related to adguard only. 

I have upgraded to the latest firmware now. Attached is the picture for your reference. I will be testing adguard on this now. Should i uninstall and reinstall adguard ? Or should i continue using previous installation. 

![Screenshot_20240327_185433_Settings.jpg](https://github.com/AdguardTeam/AdguardForAndroid/assets/122544035/91f09b66-22a3-4524-b6ba-1685de8f0040)

**Comment by qiratdahaf** [comment] 2024-03-28 08:59
https://github.com/AdguardTeam/AdguardForAndroid/assets/122544035/5f77de17-046a-41ec-9f1a-ba200cb48c08

The problem persists. Although i have reinstalled  Adguard and updated filters , I imported my settings configuration.

Unfortunately, I can't figure it out what is causing the issue.

There is only one thing i haven't tried, that is
Reinstalling adguard with no changes to default settings.

Please guide me on what should i do. Do you have any suggestions?

**Comment by maxikuzmin** [comment] 2024-04-10 09:22
@qiratdahaf could you check what is happening in the VPN profile in the system at this moment?
Usually it can be found at Settings -> Connections -> More connection settings -> VPN 
Is the status of the AdGuard VPN profile "Connected" or is it reconnecting?
You can also record a video of the screen

**Comment by maxikuzmin** [comment] 2024-04-12 16:58
@qiratdahaf any news?

**Comment by qiratdahaf** [comment] 2024-04-12 17:44
I am away from home due to eid (muslim holiday). I will check it soon.

**Comment by qiratdahaf** [comment] 2024-04-15 06:18
https://github.com/AdguardTeam/AdguardForAndroid/assets/122544035/7157b57f-b75b-48a3-a8b3-098f02b58fd6

I did that and you can see there is no change in status change but i can confirm that it affects internet (connects/disconnects).

As telegram is banned in my country, i used (orbot: tor for android, integrated it with adguard). It happends with that too. I have attached video for your observation.

**Comment by qiratdahaf** [comment] 2024-04-16 11:35
Yes with or without orbit blinking is there.
Vpn profile does not show any changes during this issue. 
But i do face internet disconnection as I mentioned earlier, whatsapp call shows reconnecting. I have reattached video for you. 

https://github.com/AdguardTeam/AdguardForAndroid/assets/122544035/9d186f89-6624-454a-a06b-ebda475f70af

**Comment by maxikuzmin** [comment] 2024-04-16 14:03
@qiratdahaf unfortunately the video is still not available for viewing

But if you try a WhatsApp call with AdGuard VPN enabled (i.e. with AdGuard VPN's vpn profile, not AdGuard's ad blocker), does the problem recur?

**Comment by qiratdahaf** [comment] 2024-04-16 14:06
I dont understand what you are suggesting.

I use adblocker (mode: local vpn)

I do not use adguard vpn itself.

Should i email you the video.

**Comment by maxikuzmin** [comment] 2024-04-16 15:15
@qiratdahaf it would be nice to understand the pattern, whether this repeats globally with AdGuard VPN profile or only the ad blocker is the problem, so I asked you to test this with AdGuard VPN if you have the ability to 
You can email the video to devteam@adguard.com

**Comment by maxikuzmin** [comment] 2024-04-16 15:32
@qiratdahaf so far I tried repeating this also on Samsung, with Android 13, version of AdGuard 4.3.1, your settings. 
But it doesn't reproduce for me

**Comment by qiratdahaf** [comment] 2024-04-16 16:55
I will try to use adguard vpn in the coming days to see how it goes. Meanwhile, I have emailed you the video.

**Comment by qiratdahaf** [comment] 2024-04-21 04:41
It's been two days using adguard VPN. And it's working fine as it should. I have not faced that issue during this period.

**Comment by maxikuzmin** [comment] 2024-04-22 17:37
@qiratdahaf so the problem only appears when only AdGuard is enabled? 
If you use AdGuard + AdGuard VPN then the problem does not recur?

**Comment by qiratdahaf** [comment] 2024-04-22 18:01
I used only adguard vpn. I did not integrate it with adguard.
I can check this, too.
As i previously checked with solid vpn, and with that too, i noticed it only happens with adguard ad blocker.

I will post you on this. Give me few more days.

**Comment by maxikuzmin** [comment] 2024-04-25 10:44
@qiratdahaf any news?

**Comment by qiratdahaf** [comment] 2024-04-25 11:33
Actually, testing since then. 

The problem is that Adguard vpn was not causing issues. Only adguard Ad blocker is having issues.

1. When I integrate both of them, adguard vpn takes over Ad blocker.
2. My issue is not permanent. It only occurs at specific moments. 
3. Even if it occurs while in integration mode, it's really difficult for me to notice it.

Till now, it's working fine in this mode. 
Another problem is that the free account has a limitation of 3gb data for vpn. I can not use it for a longer period as its quota will run out without testing. 

I am losing interest in this issue. I guess i have to use it as is.

**Comment by qiratdahaf** [comment] 2024-04-26 06:27
Guess what. It happened just right now with integration.

I was on whatsapp, a voice call, and the vpn logo blinked. I guess it was blinking (not 100% sure), but i was able to screen record it, and i took logs for it, too. 

I am sending you logs and screen recording.https://github.com/AdguardTeam/AdguardForAndroid/assets/122544035/a8cb9859-44d8-4cbf-85e0-26fde17a455c

**Comment by qiratdahaf** [comment] 2024-04-26 06:37
Attached here are the google drive links for logs as its size were more
than allowed by gmail and screen recording. You can telly the time with
logs to identify the exact issue occurring moment.

I hope this time it's identified.

Logs:

https://drive.google.com/file/d/13_8iOWgyfsVFiu1TQ0YhZVyFHOGNr_dn/view?usp=drivesdk

Screen recording:

https://drive.google.com/file/d/13bfFYUXoL67Xvx9LHpUraT4l58ghJ5Tg/view?usp=drivesdk


Regards,
Fahad

**Comment by maxikuzmin** [comment] 2024-05-06 17:24
@qiratdahaf thanks for the materials.
Did I understand correctly that the last time the vpn profile icon blinked only once?

**Comment by qiratdahaf** [comment] 2024-05-07 09:52
After all that, It's happening again... 
Really fedup right now...

**Comment by qiratdahaf** [comment] 2024-05-13 13:46
Ahan waiting.

**Comment by qiratdahaf** [comment] 2024-05-20 18:08
Updated to agudard 4.4 today. 
It has many fixes. I will test this issue on this version now and update you on my findings.

**Comment by maxikuzmin** [comment] 2024-05-22 08:51
@qiratdahaf any news?

**Comment by qiratdahaf** [comment] 2024-05-22 10:50
Not tested yet, been busy. Will keep you updated.

**Comment by qiratdahaf** [comment] 2024-05-24 13:30
![Screenshot_20240524_180836_TikTok.jpg](https://github.com/AdguardTeam/AdguardForAndroid/assets/122544035/9db7c6d7-aef5-4c97-a5e4-67b813302e8f)

![Screenshot_20240524_180849_AdGuard.jpg](https://github.com/AdguardTeam/AdguardForAndroid/assets/122544035/6794a257-bce3-4132-8158-12f771bc5227)

![Screenshot_20240524_180911_Settings.jpg](https://github.com/AdguardTeam/AdguardForAndroid/assets/122544035/88ff0296-2bea-43b3-bfd0-7554a986b983)

![Screenshot_20240524_180907_Settings.jpg](https://github.com/AdguardTeam/AdguardForAndroid/assets/122544035/0fe6d5e7-2a89-4e30-bb36-8c38e3c0011b)

Till now:

1. I have yet to see blinking now as it has not happened yet as i have not used mobile that much, but it is still randomly disconnecting and reconnecting (adguard restarts, and it does take more than few seconds to reconnect).

2.Whenever it disconects, Under "More Conection Settings" in android settings, you can see it says "none" for VPN whenever it happens, and it does not change to adguard until it has stabilized.

**Comment by maxikuzmin** [comment] 2024-05-27 15:08
@qiratdahaf how often does the protection restart? How long does it take to happen?

**Comment by maxikuzmin** [comment] 2024-05-27 15:19
@qiratdahaf it sounds like you had a filter update check happening. The restart happens because the configuration changes. Once the filters are updated, the protection is restored again. It takes 2-3 seconds for the protection to restart.

**Comment by qiratdahaf** [comment] 2024-05-27 15:21
![Screenshot_20240527_202041_AdGuard.jpg](https://github.com/AdguardTeam/AdguardForAndroid/assets/122544035/a0001b70-083c-469f-a184-07fcec0a9db5)

It is configured to check after 6 hours.
I will keep this in mind. But i think it's random or linked to something that I don't know.

**Comment by maxikuzmin** [comment] 2024-06-01 15:56
@qiratdahaf restarting protection occurs not only after updating filters, but also if the configuration of the network has changed or you can tap something in the application that will change the configuration - this also provokes restart of the protection

**Comment by qiratdahaf** [comment] 2024-06-05 08:29
I can confirm that the new update has solved my blinking problem. I haven't seen it since then.

Cherry, on top, is that the restarting problem was solved when I switched the update duration to 2 days.

You can close this issue now :)

**Comment by qiratdahaf** [comment] 2024-06-30 09:35
Dear dev. It's happening again now. Although no update of any kind (nor phone nor adguard).

I made zero changes to settings, and still, i am facing that blinking & network connection issue. 

Please reopen.

**Comment by qiratdahaf** [comment] 2024-07-01 12:49
I have 2.4ghz 5ghz via the same router and another router. 

I will try to use one one band from one router only and will inform you later.

But it is happening during the whatsapp video mostly. Even though it is exempted from adguard.

**Comment by maxikuzmin** [comment] 2024-07-05 16:03
@qiratdahaf any news? Did you manage to find out anything? Did I understand correctly that the problem with the VPN profile repeats even without AdGuard?

**Comment by qiratdahaf** [comment] 2024-07-05 16:08
It only happens with adguard. Not with other vpns. Unfortunately, I am quite busy to check this issue right now. But I will come back to you. Once i collect logs and confirm wifi suggestions you gave me back then.

**Comment by maxikuzmin** [comment] 2024-07-08 09:56
@qiratdahaf ok, I'll be waiting

**Comment by qiratdahaf** [comment] 2024-07-10 14:08
I forgot to enable debugging log collection settings.
So i noticed 2 3 times by now that it does happen, although I have only one wifi saved in my phone now. 

I am busy these days, so I can't focus on the phone. But I will let you know the details once i get free and collect logs. 

But i can confirm that frequency has reduced quite a lot from the previous build.

**Comment by qiratdahaf** [comment] 2024-07-10 15:06
Just noted restart.
Collected logs.
Sent to you via email. 

Please check.

**Comment by maxikuzmin** [comment] 2024-07-17 14:10
@qiratdahaf I have received the logs, we will need some time, please wait

**Comment by maxikuzmin** [comment] 2024-07-18 10:02
@qiratdahaf we checked your logs. At 19:57 you had a request for license status, the status changed and we restarted, there seems to be no problem, this is normal behavior

**Comment by qiratdahaf** [comment] 2024-07-18 10:04
But I did not do that. Is it normal for adguard to check this on routine ?

**Comment by maxikuzmin** [comment] 2024-07-25 16:59
@qiratdahaf obviously you didn't :) it's an automatic check "under the hood"

**Comment by qiratdahaf** [comment] 2024-07-25 17:37
Oh, alright. I didn't know that. 

I am unable to reproduce blinking again. But I am on the lookout. Will update you once I have something.

**Comment by maxikuzmin** [comment] 2024-07-30 12:46
@qiratdahaf I'm closing this issue for now. Let me know if the problem happens again. Anyway I think it's recurring with certain processes "under the hood"

**Closed by maxikuzmin** 2024-07-30 12:46 UTC
Labels: Bug, Resolution: Done, Status: Closed, Priority: P4

**Comment by qiratdahaf** [comment] 2024-07-30 13:03
Ok.
