### ISSUE TITLE
err_name_not_resolved error when switching to WiFi

### ISSUE THREAD

**Issue by FutureSharks** [AdguardTeam/AdguardForAndroid#5433] opened 2024-08-18 14:12 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.1

### Environment

- OS version: 14
- Device: Samsung Galaxy S21 5G

### HTTPS filtering

- [ ] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, EasyList

### Which DNS server do you use?

Automatic DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Use mobile data to access internet
2. Enable Wifi and join Wifi network
3. Open a Chrome tab

### Expected Behavior

No chrome browser error

### Actual Behavior

Error `err_name_not_resolved` will be shown.

### Additional Information

When I get home and my phone switches to WiFi, for some time I get the error `err_name_not_resolved` when opening sites in Chrome browser. It's like new DNS resolution stops working for some time. Sites that were previously resolved before joining wifi work fine. It seems to start working again after 2-5 mins. I can reproduce it reliably.

**Comment by maxikuzmin** [comment] 2024-08-20 18:01
@FutureSharks it would be nice to get your logs.

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Debug

- Reproduce the issue, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

- Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):

mention the 5433 number in the subject
specify the exact time when the issue occurred

**Comment by wqrw** [comment] 2024-08-21 06:08
Same here, POCO X5 Pro, Android 14. Extremely annoying.

**Comment by FutureSharks** [comment] 2024-08-21 12:17
OK well the other day I could reproduce it over and over but now not 😐 I'll leave this open for while and see if I catch the issue and get the logs.

**Comment by maxikuzmin** [comment] 2024-08-21 13:48
@wqrw are you having this problem recurring consistently? Could you please send us the logs as instructed in the instructions above?

**Comment by maxikuzmin** [comment] 2024-08-21 13:55
@wqrw @FutureSharks looks like this issue is a duplicate of an earlier open issue. I'm closing this issue, please let's continue communication here #5429

**Closed by maxikuzmin** 2024-08-21 13:55 UTC
Labels: Bug, Priority: P4
