### ISSUE TITLE
AdGuard for Android freezes and hangs when changing Local VPN status (protection on/off, updating filters, etc.) [logs]

### ISSUE THREAD

**Issue by vitek29** [AdguardTeam/AdguardForAndroid#4240] opened 2022-09-14 08:25 UTC
### Issue Details

- **AdGuard version:**
  - v.3.6.10 (51)
- **Filtering mode:**
  - Local VPN
- **Device:**
  - realme GT 2 Pro / RMX3301
- **Operating system and version:**
  - Android 12
- **Root access:**
  - No

### Expected Behavior

I expect a usual behavior without periodical VPN disconnects and app freezes. 

### Actual Behavior

1. (see logs#1 section). App freezes when changing protection switch from on to off (see last 3 mins).
2. (see logs#2 section). After some short period of time VPN disconnects on it's own without further restarting. When this happens and I am trying to open the app to start ad protection manually, AdGuard freezes totally with no response until force stop.
Tried to enable Wachdog option but it didn't help.
Sometimes I got a CONNECTION_RESET error in browser when web surfing and the only workaround is to disable protection or restart the smartphone.

### Screenshots

<details><summary>Screenshot:</summary>

Example of frozen AdGuard (1)
![Screenshot_2022-09-14-11-31-06-47_a93965f46c4a4b0ed1be737bdf2bc8fc](https://user-images.githubusercontent.com/45712948/190100076-40bb2041-9ba5-4e21-ac0a-6a6c38b05045.jpg)

Example of frozen AdGuard (2)
![Screenshot_2022-09-14-11-31-53-50_b783bf344239542886fee7b48fa4b892](https://user-images.githubusercontent.com/45712948/190100148-8e7af86d-4bf3-47c6-ac4b-3be3af20012a.jpg)

Example of connection reset error
![Screenshot_2022-09-14-12-36-37-11_df198e732186825c8df26e3c5a10d7cd](https://user-images.githubusercontent.com/45712948/190100400-7f371a5c-6fd7-4ca4-9551-9281cf057a93.jpg)

</details>

### Additional Information

Logs#1, app freezes when changing protection switch from on to off (see last 3 mins)
[adguard_logs_3.6.51_1509_201013.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/9576514/adguard_logs_3.6.51_1509_201013.zip)
+ extra logcat (see last 3 mins)
[logcat7.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/9576540/logcat7.zip)

Logs#2:
Logs when I was unable to reach fjsoft.at:
[adguard_logs_3.6.51_1409_123658.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/9564223/adguard_logs_3.6.51_1409_123658.zip)

There were 3 additional support requests from app related with this issue: #637804, #637908, #638385.

**Comment by vitek29** [comment] 2022-09-15 06:41
The issue reproduces constantly after device went to sleep. All battery optimizations are switched off and background activities for AdGuard are turned on

**Comment by maxikuzmin** [comment] 2022-09-15 22:27
@vitek29 we’re looking into the problem. Please wait

**Comment by vitek29** [comment] 2022-09-16 06:43
> @vitek29 we’re looking into the problem. Please wait

Got another set of logs with a screen capture video. App doesn't respond even after app restart (end of video) until force stop. 

Screen capture:
https://user-images.githubusercontent.com/45712948/190572861-30995fdc-adb6-4bc7-945b-ae4beee18217.mp4

AdGuard logs:
[adguard_logs_3.6.51_1609_113410.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/9581353/adguard_logs_3.6.51_1609_113410.zip)

Logcat:
[logcat10.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/9581354/logcat10.zip)

**Comment by maxikuzmin** [comment] 2022-09-20 12:21
@vitek29 thank you! Issue in the works

**Comment by maxikuzmin** [comment] 2022-09-20 12:55
@maxikuzmin thank you, we're still working it out. Did I understand correctly that there is also a problem with the VPN? Can you record a video as well and attach the extended logs with the time stamp? You can email that to devteam@adguard.com

**Comment by vitek29** [comment] 2022-09-20 14:59
@maxikuzmin 
> there is also a problem with the VPN?
At the moment I don't use any VPN software, and by "VPN" I meant android VPN function or "Local VPN" in terms of AdGuard.

**Comment by maxikuzmin** [comment] 2022-09-22 10:34
@vitek29 we’re looking into the problem. Please wait

**Comment by boyedarat** [comment] 2022-09-23 10:43
@maxikuzmin I am having the same issue as @vitek29.
I have the same phone as @vitek29 .

**Comment by maxikuzmin** [comment] 2022-09-23 13:45
@boyedarat we’re looking into the problem. You can also send your extended logs with the time of the problem to [devteam@adguard.com.](mailto:devteam@adguard.com)

**Comment by boyedarat** [comment] 2022-09-30 10:39
@maxikuzmin any progress on the issue?

The app freezes when I attempt to reproduce the issue for logging. Making it hard to capture logs.

**Comment by maxikuzmin** [comment] 2022-10-03 12:56
@boyedarat we are still investigating this problem. Do you also have adguard that hangs and won't start when you go to sleep mode? As far as I understand, restarting the app helps solve this hang? Try restarting adguard after it hangs again and unload the logs

**Comment by vitek29** [comment] 2022-10-03 15:51
@maxikuzmin 
The issue is not related to device sleep.
You can find fresh logs made after firmware update. The app hung after some time. Logs collected right after stop/restart.
@
[adguard_logs_3.6.51_0310_203039.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/9698958/adguard_logs_3.6.51_0310_203039.zip)

**Comment by maxikuzmin** [comment] 2022-10-05 14:52
@vitek29 please try without third-party vpn (Judging by the logs, you have Proton enabled immediately after turning off AdGuard) 
Also try running AdGuard in local vpn mode 
Will it hang in this case?

**Comment by vitek29** [comment] 2022-10-06 03:14
@maxikuzmin 
It's very strange, cause ProtonVPN is installed but not enabled and I am turning it on only occasionally.
Btw, here is the logs collected when ProtonVPN is uninstalled and right after AdGuard hanging.
[adguard_logs_3.6.51_0610_090733.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/9720841/adguard_logs_3.6.51_0610_090733.zip)

**Comment by maxikuzmin** [comment] 2022-10-06 10:07
@vitek29 did local VPN mode help you?

**Comment by maxikuzmin** [comment] 2022-10-10 12:03
@vitek29 we’re looking into the problem. Please wait

**Comment by vitek29** [comment] 2022-10-14 11:50
@maxikuzmin 
I collect logs right after the hang. It hung when I click check for update button, then I force stopped it and saved logs right after the opening app.
Please try to look for a check for update action and then it points you to the right time.

**Comment by sfionov** [comment] 2022-10-19 09:23
@vitek29 Sorry, it seems to be a problem on stopping local VPN tunnel. We're added additional logging to nightly version, which may help to debug this issue. Unfortunately, we can't reproduce it on our side and we need your help!

Can you please install Nightly from https://agrd.io/android_nightly and record debug log and logcat again?

**Comment by vitek29** [comment] 2022-10-20 10:07
@sfionov 
Few days ago I have updated the device firmware to Android 13 beta and it seems like the hang gone. I will try to reproduce the issue but I am not sure if it is still here.

**Comment by maxikuzmin** [comment] 2022-10-24 13:57
@vitek29 any news?

**Comment by vitek29** [comment] 2022-10-27 06:57
@maxikuzmin 
Sorry, at the moment no news, because I am currently on a business trip and use VPN app all the time to avoid restrictions. 
I installed a nightly build and try to reproduce the issue.

**Comment by maxikuzmin** [comment] 2022-10-27 15:08
@vitek29 okay, I'm waiting

**Comment by maxikuzmin** [comment] 2022-10-31 10:23
@vitek29 any news?

**Comment by boyedarat** [comment] 2022-11-02 04:29
@vitek29 it looks like the issue has been resolved in the latest Realme Android 13 (C.08) release.

Besides issues with AdGuard, I've also had similar issues with Windscribe, on the older Realme builds. All resolved in the latest Android 13 build.

**Comment by vitek29** [comment] 2022-11-02 08:03
@maxikuzmin 
I can't reproduce the issue on Android 13. I suppose we can suspend this bug report at the moment. If I face this issue I will raise it again.

**Comment by maxikuzmin** [comment] 2022-11-02 10:41
@boyedarat @vitek29 for the moment, I'm closing this issue. You can reopen the issue in the future if the problem persists

**Closed by maxikuzmin** 2022-11-02 10:41 UTC
