### ISSUE TITLE
New feature requirements

### ISSUE THREAD

**Issue by anye1998** [AdguardTeam/AdguardForAndroid#2200] opened 2018-10-19 16:02 UTC
I hope that I can add new url of filtering rules to the Ad blocker and app can update them automatically like the PC version.
What I what is just like the picture blow. I want the android version can have the same features.
![snipaste_2018-10-19_23-54-47](https://user-images.githubusercontent.com/43033792/47229813-325ce180-d3fb-11e8-8339-74351001f0da.png)
![snipaste_2018-10-19_23-55-17](https://user-images.githubusercontent.com/43033792/47229818-3ab51c80-d3fb-11e8-9121-41db98b417f2.png)

**Comment by ameshkov** [comment] 2018-10-19 16:04
Duplicate of #1806 

You'll soon have this feature, v3.0 is close:)

**Closed by ameshkov** 2018-10-19 16:04 UTC
