### ISSUE TITLE
The application freezes completely if the proxy service in the background is disabled

### ISSUE THREAD

**Issue by bropines** [AdguardTeam/AdguardForAndroid#5299] opened 2024-04-25 12:51 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.4.161

### Environment

- OS version: HyperOS 1.0.4.0
- Device: Redmi note 12s

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [ ] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-TLS

### Custom DNS

Comms

### Issue Details

Steps to reproduce:
1. Run the proxy in the settings
2. Kill the proxy service to which the adguard is connected.
3. The adguard dies after a while without errors. It just hangs there.

### Expected Behavior

Working normaly

### Actual Behavior

It freezes completely

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by bropines** [comment] 2024-05-03 05:20
@Versty here is the video as confirmation. The same bug is on nightly 43,44,45
https://github.com/AdguardTeam/AdguardForAndroid/assets/57861007/c66c0fce-20d5-4839-ab9e-346095887860

**Comment by Versty** [comment] 2024-05-06 10:16
@bropines, thank you for reporting! 
We are currently working on a fix, will be available with DNSLibs 2.5.25. 

Duplicate of https://github.com/AdguardTeam/CoreLibs/issues/1880

**Closed** 2024-05-06 10:17 UTC
Labels: Bug, Priority: P4
