### ISSUE TITLE
Editing AdGuard's Text Boxes Causes Keepass2Android to Crash

### ISSUE THREAD

**Issue by christantoan** [AdguardTeam/AdguardForAndroid#4801] opened 2023-06-17 06:32 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: Android 11
- Device: OnePlus
- Firmware: Oxygen OS 11.0.9.1.GM21BA
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Edit a text box in AdGuard

### Expected Behavior

Keepass2Android doesn't crash

### Actual Behavior

Keepass2Android crashes with the following stack trace:
`FATAL EXCEPTION: main
Process: keepass2android.keepass2android, PID: 19362
android.runtime.JavaProxyThrowable: System.ArgumentNullException: Value cannot be null.
Parameter name: key
  at System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) [0x00008] in <4087c528abc04d8290db635003aa826f>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryGetValue (TKey key, TValue& value) [0x00000] in <4087c528abc04d8290db635003aa826f>:0 
  at Kp2aAutofillParser.AutofillHintsHelper.ToCanonicalHint (System.String hint) [0x00000] in <b3fff3fe4c1d4e8994fd67a2f50d0277>:0 
  at System.Linq.Enumerable+SelectEnumerableIterator`2[TSource,TResult].MoveNext () [0x00048] in <052d4ffc295b472ebae9750a0d92739d>:0 
  at System.Collections.Generic.HashSet`1[T].UnionWith (System.Collections.Generic.IEnumerable`1[T] other) [0x00026] in <052d4ffc295b472ebae9750a0d92739d>:0 
  at System.Collections.Generic.HashSet`1[T]..ctor (System.Collections.Generic.IEnumerable`1[T] collection, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x0004c] in <052d4ffc295b472ebae9750a0d92739d>:0 
  at System.Linq.Enumerable.ToHashSet[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x0000e] in <052d4ffc295b472ebae9750a0d92739d>:0 
  at System.Linq.Enumerable.ToHashSet[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in <052d4ffc295b472ebae9750a0d92739d>:0 
  at Kp2aAutofillParser.StructureParserBase`1[FieldT].Parse (System.Boolean forFill, System.Boolean isManualRequest, Kp2aAutofillParser.AutofillView`1[TField] autofillView) [0x000b3] in <b3fff3fe4c1d4e8994fd67a2f50d0277>:0 
  at keepass2android.services.AutofillBase.StructureParser.Parse (System.Boolean forFill, System.Boolean isManualRequest, Kp2aAutofillParser.AutofillView`1[TField] autofillView) [0x0000d] in <fb40c821fb5144dda464d1c7539af8a0>:0 
  at keepass2android.services.AutofillBase.StructureParser.ParseForFill (System.Boolean isManual) [0x00018] in <fb40c821fb5144dda464d1c7539af8a0>:0 
  at keepass2android.services.AutofillBase.AutofillServiceBase.OnFillRequest (Android.Service.Autofill.FillRequest request, Android.OS.CancellationSignal cancellationSignal, Android.Service.Autofill.FillCallback callback) [0x0009f] in <fb40c821fb5144dda464d1c7539af8a0>:0 
  at Android.Service.Autofill.AutofillService.n_OnFillRequest_Landroid_service_autofill_FillRequest_Landroid_os_CancellationSignal_Landroid_service_autofill_FillCallback_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_request, System.IntPtr native_cancellationSignal, System.IntPtr native__callback) [0x00020] in <3e1504268cb1422b8c7c2994fae408c2>:0 
  at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLLL_V (_JniMarshal_PPLLL_V callback, System.IntPtr jnienv, System.IntPtr klazz, System.IntPtr p0, System.IntPtr p1, System.IntPtr p2) [0x00005] in <3e1504268cb1422b8c7c2994fae408c2>:0 
	at crc6402e1bf64a3331322.AutofillServiceBase.n_onFillRequest(Native Method)
	at crc6402e1bf64a3331322.AutofillServiceBase.onFillRequest(AutofillServiceBase.java:42)
	at android.service.autofill.-$$Lambda$I0gCKFrBTO70VZfSZTq2fj-wyG8.accept(Unknown Source:8)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:307)
	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)`

### Screenshots

<details><summary>Screenshot 1: in search text box</summary>

![Screenshot_20230617-084908](https://github.com/AdguardTeam/AdguardForAndroid/assets/7300310/709f061f-b5c5-49b5-b6e6-039dc8107d80)

</details>
<details><summary>Screenshot 2: in custom filter text box</summary>

![Screenshot_20230617-084946](https://github.com/AdguardTeam/AdguardForAndroid/assets/7300310/9125ad4e-f1f7-4f7a-8246-6e80cc7873a3)

</details>
<details><summary>Screenshot 3: more details</summary>

![Screenshot_20230617-084916](https://github.com/AdguardTeam/AdguardForAndroid/assets/7300310/11827dc4-00e8-4956-b072-ebda0f54dd20)

</details>

### Additional Information

This didn't happen with older AdGuard version.

**Comment by maxikuzmin** [comment] 2023-06-29 07:55
@christantoan I have not had this problem repeated.

It would be nice to get your logs.

- Enable debug logging:

Settings -> General -> Advanced -> Logging level -> Debug

- Reproduce the issue related to the button behaviour, then remember the exact time when it happened

- Collect logs:

Settings -> General -> Advanced -> Export logs and system info

- Sent this file to [devteam@adguard.com](mailto:devteam@adguard.com):

mention the 4801 number in the subject
specify the exact time when the issue occurred

Also please could you please record a screen video to understand your steps. You can attach the video here or send it to the mail as well. Do you have additional plugins or settings installed in the Keepass2Android app?

**Comment by christantoan** [comment] 2023-06-29 08:20
Hi, I've sent the logs. Here's the video: 

https://github.com/AdguardTeam/AdguardForAndroid/assets/7300310/f48afc5e-9548-466b-bdf7-93aa5ca5269f



For unknown reason, I now can't reliably trigger the ANR for app/log filter text boxes though it still sometimes trigger.

I have QR Plugin, KP2A AutoFillPlugin, and KeyboardSwap Plugin installed.

**Comment by maxikuzmin** [comment] 2023-07-03 12:16
@christantoan I see. In this case you need to contact the Keepass2Android developers, because their application crashes.
I'm closing this issue

**Closed by maxikuzmin** 2023-07-03 12:16 UTC
Labels: Bug, Priority: P4

**Comment by maxikuzmin** [comment] 2023-07-03 12:56
@christantoan by the way I tried to reproduce your problem, but the problem did not repeat, even with your settings. I recommend you try resetting Keepass2Android to factory settings and try again
