### ISSUE TITLE
AGA is not routing Play Services traffic at Local VPN mode

### ISSUE THREAD

**Issue by ZeroClover** [AdguardTeam/AdguardForAndroid#3569] opened 2020-09-05 15:15 UTC
### Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
v3.5 RC 1 (61)
- **Filtering mode:**
Local VPN
- **Device:**
Samsung Note 20 Ultra
- **Operating system and version:**
Android 10
- **Root access:**
No

### Expected Behavior

AGA can route Google Play Services traffic normally.

### Actual Behavior

Since I have to access the network through an upstream proxy, I set up the upstream proxy in the AGA.

Then, I make sure that AdGuard Protection is enabled in Apps Management for apps like Play Store and Play Services and that MitM is not enabled.

When I open AGA, all Play Services based apps such as Play Store and YouTube show "No Network Connection," while all other apps and web browsers can access the internet usually.

There are also no network requests from Play Store and YouTube in the filter logs, so I can only assume that AGA is not routing network traffic from these applications.

### Additional Information

The same configuration works fine on my Google Pixel 3.

**Comment by TheHasagi** [comment] 2020-09-07 16:39
@ZeroClover 

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug).
2. Remember the exact time when the issue was reproduced, we will need it to find the corresponding records in the log file.
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report).
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by mmyz1234** [comment] 2020-09-09 13:28
look here #3280

**Comment by ZeroClover** [comment] 2020-09-09 20:34
@TheHasagi A bug report has been submitted.

@mmyz1234 It doesn't seem to work, and I've tried removing UID 1000 from pref.excluded.packages, but the problem remains the same.

**Comment by Chinaski1** [comment] 2020-09-16 12:53
@ZeroClover 
Hello, unfortunately I cant find your email with the log files, can you send the received archive one more time, please?

**Comment by Chinaski1** [comment] 2020-09-22 10:07
Since the user does not answer and the issue is not reproduced on our side. 
I'm closing the task, If more information is provided, I will reopen it.

**Closed by Chinaski1** 2020-09-22 10:07 UTC
Labels: Question, Waiting for data
