### ISSUE TITLE
T-Mobile counts traffic as Tethering when VPN is active

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1741] opened 2018-02-28 20:21 UTC
### Steps to reproduce
1. Activate protection
2. Switch to cellular internet
3. Significant speed slowdown: download capped at ~2 Mbit/s, upload is not impacted

The customer reports that the issue has appeared ONLY after updating to Oreo. The same phone with same settings but running Nougat is not affected.

### Expected behavior
No slowdown

### Actual behavior
Heavy slowdown

### Customer ID 
1772808
Logs available there

### Your environment
* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: Samsung Galaxy S8+
* Operating system and version (e.g. Android 7.1.2): Android 8.0
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None detected

**Comment by ameshkov** [comment] 2018-03-03 22:13
No idea what's going on yet, we'll need to reproduce it on a test device.

**Comment by mr-robert** [comment] 2018-03-28 19:48
I am the one who first reported this issue via email and sending logs. I have determined a possible cause for the issue which is related to the service provider, T-Mobile. On reddit today the following post was made: https://www.reddit.com/r/tmobile/comments/87stfw/vpn_traffic_considered_as_tethering_data_and/

I have determined that since my bill cycle happened the throttling has stopped, so it seems very likely that something has changed on tmobile side and this traffic is falling into the same bucket, and that any traffic which goes thru a "vpn" is counting as a hotspot on t-mobile side. If this is true, I'm not sure its possible for adguard to fix, but maybe adguard is in a better position as a company to contact T-Mobile directly and investigate if this is truly the cause.

**Comment by ameshkov** [comment] 2018-04-02 08:54
Yeah, I've heard about the same issue with T-Mobile and Galaxy S9.

Moreover, afaik, the issue concerns any VPN app, not just AdGuard. We'll collect the details and report this to T-Mobile.

**Comment by mr-robert** [comment] 2018-04-02 15:41
I brought this issue up to T-Mobile engineering and they effective said they don't intend to fix it. I'm not sure if their opinion will change with pressure from other companies, but this basically means that my AdGuard is limited to 10GB a month on the plan which I have, before my speeds are throttled. I think my average usage is 15-20GB a month so this kind of sucks :(. I understand it's not in AdGuard's control but because of T-Mobile's actions AdGuard is effectively running in what feels like "trial" mode. Some AdGuard is better than no AdGuard but it's definitely a letdown that we paid for the software and T-Mobile throttles it. I hope AdGuard will at least lay the pressure on T-Mobile hard with this one. Or, if AdGuard would lead the class action lawsuit I will gladly jump on board.

**Comment by ameshkov** [comment] 2018-04-02 15:53
This is so weird. Have they supplied any technical details on the issue?

**Comment by mr-robert** [comment] 2018-04-02 16:08
Their official response is quite simple: "VPN services prevent the network from identifying and categorizing data usage which can cause the data to appear to be hotspot/tethering data."

They basically just repeated the statement of the problem back to me, which is absolutely useless, but clearly acknowledging that they are aware of the problem. And in my opinion sort of implying that they don't intend to do anything about it.

**Comment by ameshkov** [comment] 2018-04-02 17:15
What's kinda funny is that Android prevents routing tethered data through a VPN tunnel. It means that on the contrary to what's done, they must not count traffic towards hotspot if there is an active VPN service.

**Comment by ameshkov** [comment] 2018-04-02 22:10
@mr-robert do you have any idea on how exactly do they detect the VPN presence? Is there a system app pre-installed?

My idea is that maybe it would help to exclude that system app from the VPN tunnel? For instance, you can try excluding all system apps by disabling AG for "Android OS" in the apps management settings?

**Comment by mr-robert** [comment] 2018-04-03 15:30
I don't know the answer but I will definitely give your suggestion a shot once I hit the cap again. The annoying this is that when the bill cycles you have to use 10GB in order to go over the high speed limit for the throttle to kick in, which is a bit tedious to do intentionally and takes awhile to do naturally.

**Comment by shanep2300** [comment] 2018-04-12 14:48
@ameshkov Excluding Android OS did not work. On Note8 Oreo, TMobile, AG 2.11n, with the same issue.

**Comment by ameshkov** [comment] 2018-04-15 20:43
@shanep2300 do you experience a slowdown or do you have your traffic counted towards tethering?

**Comment by shanep2300** [comment] 2018-04-16 02:11
@ameshkov Both. Only while using data. This issue doesn't happen when connected to WiFi.

**Comment by Kaiser23k** [comment] 2018-05-08 01:18
@shanep2300 Can you try using AdClear like I did in #1804 to see if you still have the same issue?  Trying to figure out if its a Carrier issue or an AG issue.

**Comment by hexonxonx** [comment] 2018-05-17 18:20
I don't think this is T-Mobile counting VPN as tethering. I have three S7 Edge phones here on Nougat running Adguard successfully with no download slowdowns. This is  a change that Oreo has made and why only my Note 8 is experiencing this problem. The S7 Edge phones are not on Oreo.

**Comment by ameshkov** [comment] 2018-05-17 18:26
This IS connected indeed, it's not just T-Mobile issue, it is T-Mobile + VPN + Samsung Oreo.

There is an interesting thing in @Kaiser23k logs. I see multiple "mobile data" network interfaces available there. I don't fully understand why would they need multiple network interfaces, but we can assume that one of them is used for Hotspot traffic and the other one is used for regular traffic. 

Also, I assume that when the VPN is active, the outgoing traffic might be routed through a wrong interface. The question is how can we influence this OS decision from our side.

**Comment by Kaiser23k** [comment] 2018-05-18 23:29
@hexonxonx Can you try using AdClear like I did in #1804 to see if you still have the same issue? Trying to figure out if its a Carrier issue or an AG issue.

**Comment by hexonxonx** [comment] 2018-05-18 23:46
As for T-Mobile, I've tried using Block This and I get the slow data speeds with it as well. Seems it is a carrier issue.

**Comment by Kaiser23k** [comment] 2018-05-18 23:48
I've tried multiple VPN apps and AdClear is the only one that works for me.

**Comment by hexonxonx** [comment] 2018-05-19 07:25
Adclear is working for me without slowing down my data speeds.

**Comment by Kaiser23k** [comment] 2018-05-19 07:27
This is some progress at least :)

**Comment by ameshkov** [comment] 2018-05-21 12:26
Resolved in `adguard-android/pull-requests/432`

**Closed** 2018-07-31 18:46 UTC
Labels: P3: Medium, android bug
