### ISSUE TITLE
App management is very slow when changing App firewall settings

### ISSUE THREAD

**Issue by shriganesh** [AdguardTeam/AdguardForAndroid#5432] opened 2024-08-17 01:15 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.6.1

### Environment

- OS version: 14
- Device: Samsung Galaxy S24 Ultra

### HTTPS filtering

- [X] yes, I do

### Root access

- [ ] yes, I have it

### Integration with AdGuard VPN

- [X] yes, I do

### Routing mode

Local VPN

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List

### Security

Online Malicious URL Blocklist

### Other

AdGuard DNS filter

### Which DNS server do you use?

Cloudflare DNS

### DNS protocol

DNS-over-HTTPS

### Issue Details

Steps to reproduce:
1. Go-to app management
2. Select an app, then go-to app firewall settings
3. Enable or disable use wi-fi 
4. Go back
It'll take about 40-60

### Expected Behavior

It shouldn't take 40-60s.

### Actual Behavior

It's taking around 40-60s

https://github.com/user-attachments/assets/38b27fe3-adc5-42e1-90cd-b5071699cc5e

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Versty** [comment] 2024-08-19 11:51
@shriganesh Thank you for reporting! 
We would like to take a look at the logs from your device, please follow the steps below. 

1.  Enable debug logging: 
*Settings -> General -> Advanced -> Logging level -> Debug*

2. Reproduce the issue, then remember the exact time when it happened 

3. Collect logs: 
*Settings -> General -> Advanced -> Export logs and system info* 

4. Send this file to devteam@adguard.com:
      - mention the `5432` number in the subject
      - specify the exact time when the issue occurred

**Comment by shriganesh** [comment] 2024-08-20 08:50
Hi,

I tried enabling debug logs, reproduced the issue. But when I tried
exporting logs, it keeps failing. I tried several times and it keeps
failing.




Thanks,

Shri

**Comment by Versty** [comment] 2024-08-22 15:40
@shriganesh Please open Developer options screen in the device settings and make sure that the `Don't keep activities` option is disabled.

**Comment by shriganesh** [comment] 2024-08-22 19:50
Hi,

I've verified and it's disabled only.

Thanks

**Comment by shriganesh** [comment] 2024-08-22 22:01
Hi,

I also tried reinstalling adguard, tried nightly builds. Still facing the
same problem. One thing that I noticed is the problem appears only after I
import my firewall rules.

I'll try exporting debug logs once again.

Thanks

**Comment by shriganesh** [comment] 2024-08-22 22:02
Hi,

I just tried exporting the logs again. And it failed again.

Thanks,
Shri

**Comment by Versty** [comment] 2024-08-23 08:32
@shriganesh Alright then, let's try to sort out the crash first. 

Please follow these steps: 
1. Reproduce the crash, then remember the exact time when it happened 

2. Collect a bug report in the system settings
*Device settings -> Developer options -> Bug report*

3. Send this file to devteam@adguard.com:
      - mention the `5432` number in the subject
      - specify the exact time when the issue occurred

**Comment by shriganesh** [comment] 2024-08-24 00:10
Hi,

It's not actually crashing but it's just very slow and now my mobile
battery is dying much faster (my mobile became unusable as filtering became
unstable). So I reverted back to v4.5.2. after reverting I'm no longer
facing any issues.

**Comment by Versty** [comment] 2024-09-02 14:23
@shriganesh The crash when exporting logs will be addressed in #5447, stay tuned!

**Comment by shriganesh** [comment] 2024-09-02 19:35
@Versty Thanks. I'm looking forward for a fix as I'm stuck on v4.5. Any version above that is causing this slowness (v4.6.1, v4.6.2 and 2 nightly builds after that).

Was there any change done in 4.6.x and later?

I'm using Adguard in 2 other mobiles. And one of that is again Samsung. But 4.6.2 is working fine on those. Issue appears to happen only in 4.6.2 in S24 ultra (possibly after importing configuration).

I regularly backup and export my firewall rules in all my phones.

**Comment by Versty** [comment] 2024-09-03 15:13
@shriganesh Would you mind resetting the AdGuard app to default settings and check if the issue persists with the default settings on the problematic device? It would help us a lot to find the root of this issue. 

If so, please clear the app data in the system settings and let me know the result.

**Comment by Versty** [comment] 2024-09-04 09:45
@shriganesh The crash during logs export is fixed in the latest nightly version. Please update AdGuard to 4.7 nightly 16 and collect debug logs as described in the https://github.com/AdguardTeam/AdguardForAndroid/issues/5432#issuecomment-2296388335

**Comment by shriganesh** [comment] 2024-09-04 09:55
> @shriganesh Would you mind resetting the AdGuard app to default settings and check if the issue persists with the default settings on the problematic device? It would help us a lot to find the root of this issue.
> 
> If so, please clear the app data in the system settings and let me know the result.

Yes. I've tried it already. It becomes slow only after I import my firewall rules backup. Until then it's reasonably fast.

**Comment by shriganesh** [comment] 2024-09-04 09:56
> @shriganesh The crash during logs export is fixed in the latest nightly version. Please update AdGuard to 4.7 nightly 16 and collect debug logs as described in the [#5432 (comment)](https://github.com/AdguardTeam/AdguardForAndroid/issues/5432#issuecomment-2296388335)

Okay will do it in a couple of days.

**Comment by ericzeez** [comment] 2024-09-06 19:46
I'm experiencing the exact same issue on my Galaxy S24.  Once I add roughly 10 custom firewall rules, I experience a lot of lag interacting with the app, it's slow to open the different sections within the firewall module, slow to execute an action, etc.  The more custom firewall rules I add the slower the app feels, to the point I can no longer even disable firewall notifications.  I will toggle to disable a firewall rule notification and it will automatically toggle it right back.  Downgrading back to version 4.5 solves all these issues.  Avoiding version 4.6.x for now as I use the firewall heavily with many rules.

**Comment by Versty** [comment] 2024-09-23 15:06
@shriganesh Have you sent the logs?

**Comment by Versty** [comment] 2024-09-23 15:11
@ericzeez Hi! 
Is it possible for you to send the logs from latest (4.6.3) AdGuard version in order to help us find the cause? 

If so, please follow the steps: 
1. Enable debug logging:
*Settings -> General -> Advanced -> Logging level -> Debug*.

2. Reproduce the problem, then remember the exact time when it happened.
3. Collect logs:
*Settings -> General -> Advanced -> Export logs and system info*.

4. Send this file to [qa@adguard.com](mailto:qa@adguard.com):
    - include `[android]` keyword and `5432` in the subject of your email
    - specify the exact time when the issue occurred

**Comment by Versty** [comment] 2024-10-04 11:52
@ericzeez @shriganesh 
Does this problem still occur on the latest beta (4.6.4 beta 1)?

**Comment by shriganesh** [comment] 2024-10-05 05:54
I tried downloading beta from https://adguard.com/en/beta.html
Is it the right URL? Because I downloaded and installed. It took over 5 mins to open the app. I only saw the Adguard splash screen for 5 mins. After a force stop, and a 5 min wait it finally opened. Within the app the version shows 4.6.4 beta 1

Well test it out and share an update. In the mean time if the version is incorrect, please share the URL to download the correct version from.

**Comment by shriganesh** [comment] 2024-10-05 06:59
I tried 4.6.4 Beta 1.
![Screenshot_20241005_195706_AdGuard](https://github.com/user-attachments/assets/acbdcc2b-fe50-429d-a854-8683230625e4)

It's still slow (probably slower than before). I enabled debug and log export failed just like last time ☹️

**Comment by Versty** [comment] 2024-10-07 10:32
@shriganesh 
> It took over 5 mins to open the app. I only saw the Adguard splash screen for 5 mins. After a force stop, and a 5 min wait it finally opened. Within the app the version shows 4.6.4 beta 1

This is obviously a problem. We need an additional investigation to eliminate the cause. 

How many firewall rules and statistics do you have in the application? 
Please provide screenshots of Statistics tab.

**Comment by shriganesh** [comment] 2024-10-07 10:51
![Screenshot_20241007_234110_AdGuard](https://github.com/user-attachments/assets/743c426b-01f7-4c1a-b499-5b3cb026daad)
Here is the screenshot.

I've around 255 firewall rules. I vaguely remember after I imported them after reverting back to v4.5.x

**Comment by Versty** [comment] 2024-10-07 11:06
@shriganesh Thank you!

**Comment by Versty** [comment] 2024-10-07 16:01
@shriganesh Could you provide a system bug report from your device so we could have a better understanding on this issue? 

Please follow the steps below: 
1. Launch AdGuard application and go to Settings tab 
2. Enable the `Auto-report crashes` option 
3. Go to Advanced and set the `Logging level` to `Debug`
4. Reproduce the problem (try to export logs), note current time 
5. Collect a system bug report according to [this instruction](https://adguard.com/kb/adguard-for-android/solving-problems/logcat/) 
6. Send this file to [qa@adguard.com](mailto:qa@adguard.com):
    - include `[android]` keyword and `5432` in the subject of your email
    - specify the exact time when the issue occurred (step 4)

**Comment by shriganesh** [comment] 2024-10-07 19:56
> @shriganesh Do you have any other customizations besides firewall rules?

Like which filters or something else?
I've firewall with ad blocking, tracking protection, annoyance removal, DNS protection, browsing security with Adguard VPN integrated. But the VPN is almost always off.

**Comment by Versty** [comment] 2024-10-08 09:22
@shriganesh Most likely a crash occurs when you try to export logs. The option from step two sends us a detailed crash report so we could see the exact cause of the crash. 

If step 4 fails, this is exactly what we need in order to figure out the cause of this behavior.

**Comment by shriganesh** [comment] 2024-10-08 09:33
@Versty noted. I'll try it and share an update here. It's bit painful because I've to update Adguard, test and then revert it again. If I don't my phone gets hot and battery dies quickly.

**Comment by Versty** [comment] 2024-10-14 08:54
@shriganesh Have you sent the logs?

**Comment by shriganesh** [comment] 2024-10-14 09:12
Hi,

Sorry not yet. I will try and get this done this weekend.

Thanks

**Comment by Versty** [comment] 2024-10-22 11:47
@shriganesh Have you managed to find time to reproduce the issue and send logs?

**Comment by shriganesh** [comment] 2024-10-25 10:15
Hi,
Sorry not yet. Hopefully I'll be able to do it in 2-3 days.
Thanks

**Comment by shriganesh** [comment] 2024-10-28 05:04
Hi @Versty 
I have started facing the issue in the older version of AdGuard (v4.5). I'll provide logs from this version itself in few hours. Hopefully that should be okay.

**Comment by shriganesh** [comment] 2024-10-28 05:14
I had already enabled Auto-report crashes.

Started 6.04 PM local time.
Installed new app that didn't have any rules. Started allowing all rules for this app at 6.04/6.05 PM. This task was completed at 6.12 PM (visually the icons turned green from red).

Tried exporting logs and in this version (v4.5) it actually asked me the location to save the debug logs. After I provided that, it failed at 6.12 PM NZDT.

Hope you've received an auto crash report.

**Comment by shriganesh** [comment] 2024-10-31 23:05
Hi @Versty,

I saw the latest 4.6.4 update and noticed a fix for log export failing.
So I updated to 4.6.4, enabled auto submit crash reports and enabled debug. Reproduced the issue, but the export failed again. This time at 12.00 pm NZDT 1st Nov. Did you get crash report?

**Comment by shriganesh** [comment] 2024-11-05 01:49
Hi @Versty 
Updated to latest Adguard today. Enabled debug and then started to enable rules for an app at 2.40 pm NZDT on 5th Nov. The operation was complete at 2.46 pm NZDT.

Log export failed again.

**Comment by Versty** [comment] 2024-11-05 14:50
@shriganesh Hi! 
Thank you for new attempts.

Have you tried to collect system bug report as described in the https://github.com/AdguardTeam/AdguardForAndroid/issues/5432#issuecomment-2397325025?

In order to find the crash logs from your device, we need to know the model of your device. 
Please open system settings -> About phone, and specify the model name listed on the "About phone" screen.

**Comment by shriganesh** [comment] 2024-11-05 18:45
> @shriganesh Hi! Thank you for new attempts.
> 
> Have you tried to collect system bug report as described in the [#5432 (comment)](https://github.com/AdguardTeam/AdguardForAndroid/issues/5432#issuecomment-2397325025)?
> 
> In order to find the crash logs from your device, we need to know the model of your device. Please open system settings -> About phone, and specify the model name listed on the "About phone" screen.

Hi @Versty ,
Yes all these attempts I've been following the steps from https://github.com/AdguardTeam/AdguardForAndroid/issues/5432#issuecomment-2397325025 only. 

Model is Galaxy S24 Ultra - SM-S928B/DS

**Comment by shriganesh** [comment] 2024-11-13 06:15
Hi @Versty 

Updated to v4.6.5.
Followed everything like before. Tried again at 7.08 pm nzdt. The process finished at 7.14 pm on 13th Nov. Log export failed again.

**Comment by Versty** [comment] 2024-11-18 09:18
@shriganesh First of all, please take my apologies for the long response time.

The logs export at the step 4 should fail, this behaviour is caused by the bug. We have tried to reproduce it on our side, but to no avail. Therefore, after performing step 4, we need you to export system logs as described at step 5 https://github.com/AdguardTeam/AdguardForAndroid/issues/5432#issuecomment-2397325025, then send it to our email.

**Comment by Versty** [comment] 2024-11-29 09:21
@shriganesh Hi! 
Please install the latest nightly version (4.7 nightly 59), the problem should be resolved.

**Comment by shriganesh** [comment] 2024-11-30 11:52
Hi @Versty 
I just installed the nightly v4.7 and it's very fast now! May I know why was it slow before?

Thanks!

**Comment by Versty** [comment] 2024-12-04 10:26
@shriganesh There was a bug in the firewall notification logic, it was triggered by deleting one of the applications in the list and caused the firewall notification rules to multiply. We have fixed this problem in 4.7 release and nightly channels.

**Closed** 2024-12-04 10:26 UTC
Labels: Bug, Priority: P3
