### ISSUE TITLE
Occasionally losing Internet connection

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1331] opened 2017-07-18 16:48 UTC
### Expected behavior
Using the Internet without any issues.

### Actual behaviour
Losing Internet connection at random.

[1456058_logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1156626/1456058_logs.zip) (18:10)

### Customer ID 
1456058

### Your environment

* Adguard version: 2.9.135
* Adguard filtering mode: VPN
* Device model: Samsung Galaxy Note 10.1 LTE (2014)
* Operating system and version: Android 7.1.2
* Not rooted
* No other VPN or antivirus are running.

Forcing an icon didn't help. Adguard excluded from battery saving in Android.

**Comment by altokarev** [comment] 2017-07-18 16:50
There is some kind of `intervention` mentioned in logs:
```
TCP id=1001652 GET /pagead/show_ads.js HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Host: pagead2.googlesyndication.com
Accept-Language: sv-SE,sv;q=0.8,en-US;q=0.6,en;q=0.4
DNT: 1
Referer: http://www.talkandroid.com/317121-whatsapp-updates-out-of-beta-rolling-out-to-users/?utm_source=feedburner-ta&utm_medium=feed&utm_campaign=Feed%3A+AndroidNewsGoogleAndroidForums+%28TalkAndroid%29
User-Agent: Mozilla/5.0 (Linux; Android 7.1.2; SM-P605 Build/NJH47B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.50 Safari/537.36
Intervention: <https://www.chromestatus.com/feature/5718547946799104>; level="warning"
Connection: keep-alive
```

**Comment by altokarev** [comment] 2017-07-18 16:57
A user surfing the Internet but suddenly it drops off:
```
18:09:21.610 [pool-2-thread-1186] DEBUG c.a.android.filtering.commons.d - TCP id=6248 Cannot connect to /151.101.84.134:80 for com.chrome.beta 
java.net.SocketTimeoutException: null
    at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:133) ~[na:0.0]
    at com.adguard.android.filtering.vpn.l.b(Unknown Source) ~[na:0.0]
    at com.adguard.android.filtering.vpn.a$1.run(Unknown Source) ~[na:0.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) ~[na:0.0]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) ~[na:0.0]
    at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
18:09:21.611 [pool-2-thread-1242] DEBUG c.a.android.filtering.commons.d - TCP id=6248 com.chrome.beta /172.16.209.1:37923 /151.101.84.134:80 10120 redirect /151.101.84.134:80 to /127.0.0.1:57300
18:09:21.612 [pool-2-thread-1242] DEBUG c.a.android.filtering.commons.d - TCP id=6248 Connecting to /127.0.0.1:57300
```
The problem is that we don't close connections to the browser and they continue to come more and more to connect to our service. From the user side, it looks like losing the connection to the Internet. Restarting Adguard solving the problem.

**Comment by ameshkov** [comment] 2017-07-22 22:16
This looks like a firmware issue. Happens absolutely randomly, as if system just denied network access for our process.

Could it be that user has some sort of a background network access limitation enabled?

**Comment by vozersky** [comment] 2017-07-24 13:06
@altokarev

**Comment by Revertron** [comment] 2017-07-25 09:19
@ameshkov May be right. But instead of firmware issue it may be the network issue as well.
Let the user try the new beta at https://adguard.com/apkb

**Comment by ypetruk** [comment] 2017-07-25 21:25
The issues are not resolved with the latest beta. Our devs thought it might be something with the rom he`s using.
Ticket ID: 1456058

**Comment by evgeniy-ADG** [comment] 2017-07-27 05:40
Hi, here's another set of logs from the user 1456058.

>  I have previously reported that Internet connection breaks randomly on my Android tablet. Now it happened again at 21.35. No connections possible inside Firefox but when I switched to Adguard the filter updates worked flawlessly at 21.36. 

[debug (1).txt.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1178922/debug.1.txt.zip)

Do we have any further ideas?

**Comment by ameshkov** [comment] 2017-07-31 08:31
@altokarev please check all the tickets -- could it be that these all are Lineage OS users? The error is the same as in their case.

**Comment by altokarev** [comment] 2017-07-31 09:30
Asked the user 1456058 does he uses LineageOS or not.

Found another user (ticket ID 1570320, Samsung Galaxy Note 3@LineageOS 14.1) reports that he solved an issue through switching from a VPN mode to the HTTP proxy mode.

**Comment by ameshkov** [comment] 2017-07-31 09:34
Proxy + auto?

**Comment by altokarev** [comment] 2017-07-31 09:39
Not specified, but I think auto, yep. Shall I figure it out?

**Comment by ameshkov** [comment] 2017-07-31 09:43
> Shall I figure it out?

Not really, I guess it's enough to know that proxy mode helps

**Comment by altokarev** [comment] 2017-07-31 11:10
Yep, user 1456058 using LineageOS, like the other one. 

#1345

**Comment by ameshkov** [comment] 2017-07-31 17:42
Closing this as duplicate of #1345

**Closed by ameshkov** 2017-07-31 17:42 UTC
Labels: P4: Low, waiting for data
