### ISSUE TITLE
MMS unable to be downloaded for Verizon users

### ISSUE THREAD

**Issue by DrSuSE** [AdguardTeam/AdguardForAndroid#4474] opened 2023-02-15 13:06 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.599

### Environment

```markdown
- OS: Android 13
- Device: Google Pixel 7 Pro
- Firmware: February Release
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Widgets filter, AdGuard Other Annoyances filter, AdGuard DNS filter

### Issue Details

Steps to reproduce:
1.  Be a Verizon user (connected to wifi or mobile doesn't matter)
2.  Some sends you an MMS pic or video
3.  You get an alert about the message but it cannot be downloaded until you disable Adguard

### Expected Behavior

MMS should be received

### Actual Behavior

Only a notification and download progress that lasts forever is received

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by maxikuzmin** [comment] 2023-02-17 18:00
@DrSuSE to troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by DrSuSE** [comment] 2023-02-18 15:26
I probably won't do this. I understand if that means you won't resolve unless others reply. This was a big issue for Adguard in the past so you probably have a lot of data on it.

**Comment by maxikuzmin** [comment] 2023-02-20 19:01
@DrSuSE unfortunately we have no way to test this, nor do we have any data on this problem. Without debug logs we won't be able to figure out what the problem is

**Comment by DrSuSE** [comment] 2023-02-20 19:02
@maxikuzmin Understood.

**Comment by maxikuzmin** [comment] 2023-02-21 16:09
@DrSuSE for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists, but without the logs we can't figure out what the problem is.

**Closed by maxikuzmin** 2023-02-21 16:09 UTC

**Comment by DrSuSE** [comment] 2023-02-23 00:11
Just putting this here in case someone else has time to do the full troubleshooting.

The issue only exists in proxy filtering mode. In VPN mode, it's fine.

**Comment by DrSuSE** [comment] 2023-02-27 17:47
I was able to resolve the issue by deactivating app-level routing for EVERYTHING and then selectively enabling it only where I want to filter ads.

So in the latest builds/redesign, there is something being routed by default that is causing the issue.  I don't know what it because there is a ton of stuff, but there you go...

**Comment by maxikuzmin** [comment] 2023-02-27 18:29
@DrSuSE strange behavior. Still, if you manage to record logs in the future, it would be better to take a look at the logs. Does this behavior repeat itself with other applications?

**Comment by DrSuSE** [comment] 2023-02-27 18:32
I am not sure what you mean in the last part.  MMS is only handled one way, I don't think it is related to the specific MMS app (in this case, Googles Messages).  That's really just accessing the SMS/MMS database.  Google Messages was also not routed through Adguard.  My guess is that it is one of the system level app items.

**Comment by maxikuzmin** [comment] 2023-03-01 11:31
@DrSuSE unfortunately, we don't have the opportunity to test this case with Verizon.
We don't have this problem with other operators. Have you tried it again with other operators?
What is your Routing mode?

**Comment by DrSuSE** [comment] 2023-03-01 12:54
lol, no... I am not part of any developer or testing groups nor any reason to have SIMs for multiple carriers.  As noted previously, I use automatic proxy/root mode.  The issue does not exist with VPN mode.  I am not that worried about it... I sort of feel like it is fine for me to disable Adguard for everything and then only selectively enable it where I want it.  That is a perfectly fine solution for me.

**Comment by maxikuzmin** [comment] 2023-03-03 14:01
@DrSuSE glad to hear about the solution found!
