### ISSUE TITLE
After installing certificate AdGuard can't see it

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForAndroid#1543] opened 2017-10-17 12:30 UTC
It happens on android 7 if you have cert installed before
### Steps to reproduce

1. uninstall AG
2.install AG, install cert by turning on HTTPS filtering

### Expected behavior

Cert status: installed into user certificate store
### Actual behavior

Cert status: not installed

you need to stop protection, quit AG and run it again to make AG see the cert. 

### Your environment

* Operating system and version: reproducible on android 7
* Rooted or not?  both

**Comment by nkartyshov** [comment] 2017-10-17 12:42
fix, adguard-android/pull-requests/167

**Comment by ameshkov** [comment] 2017-11-08 22:41
It seems that it misbehaves when the certificate is moved to the "system" store:
https://www.reddit.com/r/Adguard/comments/7avfqb/bug_adguard_says_certs_are_installed_in_the_user/

**Comment by ameshkov** [comment] 2017-11-08 22:46
LineageOS 14, do we have a test device with it?

**Comment by nkartyshov** [comment] 2017-11-09 08:54
The problem cannot reproduce on Nexus 9 with the last LineageOS 14. 
Information about the certificate will be in the log of the user that we are waiting for.

**Closed by nkartyshov** 2017-11-09 08:54 UTC
Labels: bug
