### ISSUE TITLE
Custom filters subtext says "Disabled", but switch button is enabled

### ISSUE THREAD

**Issue by kylhill** [AdguardTeam/AdguardForAndroid#3156] opened 2019-10-20 13:06 UTC
Starting with v3.3 beta 1 (64-1.5.74cl), I noticed that I can't disable to Custom filters switch button from the filters settings page.  If I have no custom filters added, and I then turn the switch to disabled, the switch will turn itself back on and there is a mismatch between the "Disabled" subtext and the switch.  If I go into the Custom filters page the switch will automatically re-enable when I return to the filter setting page.
![Screenshot_20191015-061453](https://user-images.githubusercontent.com/549761/67159914-805b3c80-f310-11e9-852a-ef17bcf170fa.png)

**Comment by artemiv4nov** [comment] 2019-10-20 19:37
This task is duplicate of #3119.
It already was done​ in `nightly` and will be available in `beta 2`.

**Closed by artemiv4nov** 2019-10-20 19:37 UTC
