### ISSUE TITLE
Ads on Jiotv applcation

### ISSUE THREAD

**Issue by kumar041** [AdguardTeam/AdguardForAndroid#4160] opened 2022-05-09 18:33 UTC
Hi, i have oneplus 6t running LOS custom Rom version 19.1,  with April patch, and i am running Adguard nightly version 4.0.75. Having vpn mode to filter the ads, and it is in automatic mode. Problem is after new update of jiotv application ads are playing when i start any channel. It is video ad for full screen for almost 13 seconds and when i change the channel again video ad  is playing in video player space for same thirteen seconds like ads playing in youtube when we open the channel to watch. If you want any more information then i am ready to share

**Comment by maxikuzmin** [comment] 2022-05-18 12:35
@kumar041 can you  tell me please  you have https filtering enabled for this application?

**Comment by maxikuzmin** [comment] 2022-05-18 13:50
@kumar041 but it's better to first  please do the following steps:

- Go to the Filtering log
- Clear the Filtering log
- Enter the Jio TV app
- Wait for ads
- Take screenshots of the Filtering log
- Email devteam@adguard.com

**Comment by maxikuzmin** [comment] 2022-05-23 06:38
@kumar041 ping

**Comment by kumar041** [comment] 2022-05-24 18:22
Hi,

As per your request I am sending the filtering log when ads are playing.

Thanks and regards,
Rajkumar



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by maxikuzmin** [comment] 2022-06-08 07:41
@kumar041 you never said, do you have https filtering enabled for this application?

**Comment by kumar041** [comment] 2022-06-08 07:44
Yes, I am using https filtering for all applications, not only for jiotv.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by maxikuzmin** [comment] 2022-06-08 08:24
@kumar041 apparently, an application that does not trust our certificate. Then reset the https filtering to its previous position. Try to reproduce the problem and then send logs.

Here's what we need you to do:

Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment] 2022-06-14 10:34
@kumar041 you sent a message to the mail [devteam@adguard.com](mailto:devteam@adguard.com) but did not attach the logs, please send us the logs according to the instructions

**Comment by maxikuzmin** [comment] 2022-06-22 15:57
@kumar041 ping

**Comment by kumar041** [comment] 2022-06-25 17:34
Hi,

I am trying to capture the log for almost three days as per your mail, but when i click the specific channels they never play anything just blank, so filter log is empty, so i don't know what to do,  i will send screenrecord later.
Thanks,
Rajkumar

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by maxikuzmin** [comment] 2022-06-27 08:24
@kumar041 maybe you have "Request type" and "Request origin" configured? The filter log should always show all queries

**Comment by kumar041** [comment] 2022-06-29 18:35
Hi,

When adguard is enabled, ads are not playing so how can I log and send those to you, anyway i try tomorrow and send it to you.

Thanks,
Rajkumar

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by maxikuzmin** [comment] 2022-07-01 09:44
@kumar041 did you make it?

**Comment by maxikuzmin** [comment] 2022-07-04 07:00
@kumar041 ping

**Comment by maxikuzmin** [comment] 2022-07-07 13:55
@kumar041   if you're getting ads, we need to understand what's going on internally. Enable AdGuard protection, log in to the app, wait for ads. After ads appear, take a screenshot and upload advanced logs. Send everything to devteam@adguard.com 
 We can't help you without this information

**Comment by maxikuzmin** [comment] 2022-07-11 09:58
@kumar041 ping

**Comment by kumar041** [comment] 2022-07-13 10:56
Hi,

You can close the case but here are the ads when I played.

Thanks,
Rajkumar

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kumar041** [comment] 2022-10-11 09:19
Hi,

As per your instructions i have captured filter log, let see, the ad started to play on 4.06 to 4.07


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by maxikuzmin** [comment] 2023-01-24 18:54
@kumar041 can you reproduce this again and send screen shots of the filtering log to devteam@adguard.com?

**Comment by maxikuzmin** [comment] 2023-02-06 13:34
@kumar041 I got screenshots. Could you also reproduce it again and record the debug logs? This is quite difficult to understand, because we don't have access, because we haven't local number to log in

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

Please remember to mention the Github issue number when submitting logs or screenshots

**Comment by kumar041** [comment] 2023-02-07 01:11
Hi,

Give me one or two days I will upload the information. 

Regards,
Rajkumar

**Comment by kumar041** [comment] 2023-02-09 05:37
Sorry due to the magisk module corrupted my data partition, I am reinstalling everything, so sorry for the delay. 😭

**Comment by maxikuzmin** [comment] 2023-02-09 11:43
@kumar041 we are waiting. Hopefully the problem can be solved

**Comment by kumar041** [comment] 2023-02-10 16:43
Hi,
As per your request I have captured some logs. So adguard log having some details like when I start History Tv channel then ad are playing almost for 11 seconds, exact time of ad started at 9.28. Again I started the same channel at 9.29. so I think they are using https protocol for communication from jiotv and their sever, so mostly they obfuscate the communication between them.

anyway I have attached detail log from adguard adblocker and from system wide log cat reader application. I think your instruction does not updated. Because I have try to enable bugreport option in developer setting, but it is not enabled in my rom by its maintainer. So that I have used external logcat reader to capture some logs, I hope it will be some useful.
I am using Adguard adblocker nightly (version 4.0.500) in Oneplus 6t custom rom called pixelexperience A13.
[adguard_logs_4.0.585_1002_213011.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/10709494/adguard_logs_4.0.585_1002_213011.zip)
[Log_2023-02-10_21-50-05.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/10709495/Log_2023-02-10_21-50-05.txt)

**Comment by maxikuzmin** [comment] 2023-04-12 10:42
@kumar041 please try manually adding the domains or addresses you can see in the filtering log to the blocklist. Make sure that there are no more ads when blocking them and that the application does not crash.
So far, this is the only solution to this problem

**Comment by maxikuzmin** [comment] 2023-04-17 09:28
@kumar041 any news?

**Comment by maxikuzmin** [comment] 2023-04-26 16:41
@kumar041 for the moment, I’m closing this issue. You can reopen the issue in the future if the problem persists

**Closed by maxikuzmin** 2023-04-26 16:41 UTC
Labels: Bug

**Comment by kumar041** [comment] 2023-04-26 16:48
Hi,

Sorry for the late reply, actually I had hospital emergency so I am not able to reply to your mail, I had tried but it is not working, so I have compromised myself, i.e. I can watch the advertisement rather than fighting with the iodic application (jiotv).  So you may close the case.

Regards,
Rajkumar


Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by maxikuzmin** [comment] 2023-04-26 17:16
@kumar041 take care
