### ISSUE TITLE
Pruned

### ISSUE THREAD

**Issue by The-Commissioner** [AdguardTeam/AdguardForAndroid#1358] opened 2017-08-05 09:54 UTC

**Comment by ameshkov** [comment] 2017-08-07 08:30
I've seen such a complaints before and I guess it's caused by the changes required for Android O compatibility (network state receiver is registered dynamically now instead of declaring it in the app manifest).

@vozersky please try to reproduce the issue with a test device.

@The-Commissioner could you please collect AG log for me? Default logging level is enough.

**Comment by The-Commissioner** [comment] 2017-08-07 11:41
@ameshkov How do you want me to collect the logs?
Enable protection,enable logging > then disconnect wifi > let adguard go into pausing state > then enable wifi connection > wait for adguard to resume?
Is this the procedure you want me to follow while collecting logs?
Or after the last step I should forcefully resume protection and then stop logging?

**Comment by The-Commissioner** [comment] 2017-08-07 12:04
ID: 1023133
Sub: AG Android Bug Report

**Comment by ameshkov** [comment] 2017-08-07 12:52
Got it, thank you!

> Received a mail from your side with an error msg

Yep, will be fixed

**Comment by The-Commissioner** [comment] 2017-08-07 13:36
Resent the original mail in easy copy/paste format.
Pls check and tell if it's ok or not.

**Comment by vitbortnik** [comment] 2017-08-12 18:20
1500878 - автоматически не включает защиту при включении интернета
1611601 - сервис не запускается автоматически при подключении к интернету
@ameshkov Do you still need logs or the bug has been detected?

**Comment by veronikasav** [comment] 2017-08-13 01:19
> При включенном полном логгировании и, если ждать полного 
подключения Wi-Fi, а потом подключить 3G, то программа адгуард не 
"слетает". Но при отключении "записывать все" все опять не работает как 
надо. Чтобы этого глюка не было, надо полностью дождаться пока один тип 
подключения сконнектится, потом включать другой. Тогда Адгуард не слетает.

Время 3:45-3:50

[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1220173/state.txt)
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1220172/debug.txt)

Ticket ID: 1608118

**Comment by ameshkov** [comment] 2017-08-13 12:28
@vitbortnik yes, I sure do.

The logs I've received all look weird. This should not be happening and yet it does:( I may need to build a couple of test builds to narrow it down.

**Comment by The-Commissioner** [comment] 2017-08-14 16:05
This issue is closed from my side. Don't have the problem anymore. ;-)

**Comment by ypetruk** [comment] 2017-08-16 01:48
Сегодня снова повторилась проблема с автоматическим обнаружением
активного интернет-подключения(активное соединение не обнаруживается и защита
не запускается). По вашему запросу направляю подробные логи. Проблема
возникла в 11:30. Соединение (3G) устанавливалось трижды, adguard не
запускал защиту автоматически, хотя процесс висит в шторке. Приложение начинает реагировать после перехода на главный экран программы с кнопкой запуска защиты вручную. 

логи в тикете: 1611601

**Comment by Revertron** [comment] 2017-08-16 08:49
В логах налицо проблема сети:

```
Current active network info: [type: MOBILE[UNKNOWN], state: SUSPENDED/SUSPENDED, reason: (unspecified), extra: internet.mts.ru, roaming: false, failover: false, isAvailable: true]
Current active network info: [type: MOBILE[UNKNOWN], state: SUSPENDED/SUSPENDED, reason: (unspecified), extra: internet.mts.ru, roaming: false, failover: false, isAvailable: true]
Current active network info: [type: MOBILE[UMTS], state: DISCONNECTED/BLOCKED, reason: (unspecified), extra: (none), roaming: false, failover: false, isAvailable: true]
Current active network info: [type: MOBILE[HSPA+], state: DISCONNECTED/BLOCKED, reason: (unspecified), extra: (none), roaming: false, failover: false, isAvailable: true]
Current active network info: [type: MOBILE[HSPA+], state: DISCONNECTED/BLOCKED, reason: (unspecified), extra: (none), roaming: false, failover: false, isAvailable: true]
Current active network info: [type: MOBILE[UMTS], state: CONNECTED/CONNECTED, reason: (unspecified), extra: internet.mts.ru, roaming: false, failover: false, isAvailable: true]

```
И сразу после этого пошел нормальный лог трафика. А заход в Адгард и восстановление работы передергиванием кнопки просто совпадение.

**Comment by evgeniy-ADG** [comment] 2017-08-17 11:51
1504520 - another one, we have logs and the timing in the ticket

**Comment by The-Commissioner** [comment] 2017-08-17 12:42
It's amazing how more and more people are turning up to report this very issue now. I wonder why they were not doing so, since this bug has been there in the past builds as well(I can personally vouch for the last two builds).

**Comment by altokarev** [comment] 2017-08-17 17:02
Got a log mentioned by @evgeniy-ADG and another one:
- [1504520_logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1232045/1504520_logs.zip) (22:33)
- [adguard.2017-08-16.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1232048/adguard.2017-08-16.zip)
- [adguard_all_night_log.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1232049/adguard_all_night_log.zip)

**Comment by veronikasav** [comment] 2017-08-18 13:18
> При переключении с Wi-Fi на мобильную
сеть или наоборот, программа
отключается и приходится её вновь
запускать в ручную каждый раз.

Ticket ID: 1614361

**Comment by altokarev** [comment] 2017-08-18 13:22
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1234513/debug.txt)

**Comment by ameshkov** [comment] 2017-08-18 13:22
@The-Commissioner 
> I can personally vouch for the last two builds

You're right, the problem started with v2.9.135 when we started targeting SDK level 25. Who knows why some of the issues were noticed so late. The other major issue is #1383

**Comment by The-Commissioner** [comment] 2017-08-18 14:06
> Who knows why some of the issues were noticed so late. 

Maybe people are not so sure whether it's a problem in their phone or the product.
Majority of them will simply uninstall the app and find an alternative rather than find the issue.
That's why you need beta testers. Ever since you made the beta section public, I personally feel that the level of beta bug reporting has gone down several notch. I don't see many of the beta testers, active at the forum or reporting bugs.

I will not say anything about your QA team but I can, as of this very moment, report atleast 5 bugs each in the extension, android and windows repository. But I wait, wait for people to realise what's the problem. 

I told at wilders that there was problem in [export/import options](https://www.wilderssecurity.com/threads/adguard-ad-blocker.342850/page-88#post-2667095) in windows program in April, nobody believed in me till I reported them here in July. Same was the case with exit adguard completely functionality, I had to specifically show the problem areas. Even that [browsing sec grammatical error](https://www.wilderssecurity.com/threads/adguard-ad-blocker.342850/page-89#post-2668777), I showed on wilders in April but then also nobody reported that(imagine that even after showing it).
Nobody took me seriously at that time but I proved it here that I don't lie.

**Closed** 2017-08-22 10:31 UTC
Labels: bug, P2: High
