### ISSUE TITLE
Google Play: jp.co.johospace.jorte

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#3770] opened 2021-02-26 09:46 UTC
@adguard-bot commented on [Mon Feb 22 2021](https://github.com/AdguardTeam/AdguardFilters/issues/75530)

### Issue URL (Ads)
 [https://play.google.com/store/apps/details?id=jp.co.johospace.jorte](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Djp.co.johospace.jorte)
### Comment
Username: `@KAMIYAMINORU`
> 
> --
> The information below is automatically generated. Do not delete it.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/d1oE1Dg.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/6bJPZpu.jpg)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/qEq7B3t.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v3.6.1 (11)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode options: | Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (0)
DNS filtering: | server: `ADGUARD-DNS`<br>
Filters: | <b>Ad Blocking:</b><br/> Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads, <br/>AdGuard Base, <br/>EasyList<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Chinese, <br/>EasyList China
Other extensions used: | NO

---

@KamiyaMinoru commented on [Mon Feb 22 2021](https://github.com/AdguardTeam/AdguardFilters/issues/75530#issuecomment-782993672)

I think it "sometimes" block google ad successfully but most of time failed.

---

@KamiyaMinoru commented on [Tue Feb 23 2021](https://github.com/AdguardTeam/AdguardFilters/issues/75530#issuecomment-783772802)

p.s. translation of error msg:

XXX does not accept our certificate...

(I just tried to reinstall AdGuard cert but does not change any thing)

---

@akmLaVx commented on [Wed Feb 24 2021](https://github.com/AdguardTeam/AdguardFilters/issues/75530#issuecomment-784778336)

received logs: 1774474

**Comment by Chinaski1** [comment] 2021-02-26 11:15
Hello @KAMIYAMINORU

Enabling HTTPS filtering for the specified application is not a good idea as it does not trust user certificates, this, in turn, can cause the application to malfunction.
First, you can try clearing the application cache, disabling EasyList and Peter Lowe's Blocklist, and then check if the issue with missing ads persists.

**Comment by KamiyaMinoru** [comment] 2021-02-26 16:16
> Hello @KamiyaMinoru
> 
> Enabling HTTPS filtering for the specified application is not a good idea as it does not trust user certificates, this, in turn, can cause the application to malfunction.
> First, you can try clearing the application cache, disabling EasyList and Peter Lowe's Blocklist, and then check if the issue with missing ads persists.

Hi, I tried to do that, and...
![Uploading Screenshot_2021-02-27-00-14-06-83_64107c223cea4d59a3fab61ca0c3d50f.jpg…]

![Screenshot_2021-02-27-00-14-13-34_64107c223cea4d59a3fab61ca0c3d50f](https://user-images.githubusercontent.com/78710607/109325540-025a5e80-7891-11eb-9b87-1ba878deefd8.jpg)

**Comment by KamiyaMinoru** [comment] 2021-02-26 16:36
![Screenshot_2021-02-27-00-34-19-90_a93965f46c4a4b0ed1be737bdf2bc8fc](https://user-images.githubusercontent.com/78710607/109327919-d12f5d80-7893-11eb-8226-2030b14bb5b2.jpg)

By the way it looks like the reason?

**Comment by KamiyaMinoru** [comment] 2021-02-26 16:37
![Screenshot_2021-02-27-00-36-58-43_a93965f46c4a4b0ed1be737bdf2bc8fc](https://user-images.githubusercontent.com/78710607/109328033-f0c68600-7893-11eb-93bb-b99f69fcc765.jpg)

even I tried to do this

**Comment by Chinaski1** [comment] 2021-03-02 10:39
Unfortunately, can't reproduce your issue, even using identical filter settings.

The rules you added to the custom filters are already contained in the [AdGuard Base filter](https://uploads.adguard.com/Chinaskiwowrh.png).

**Comment by Chinaski1** [comment] 2021-03-10 10:14
Try to disable all user rules, update filters and check if the ads still there?

**Comment by Chinaski1** [comment] 2021-03-22 09:08
I am closing this task as we are not getting a response from the user. The issue does not reproduce on our end.
Reopen it if necessary.

**Closed** 2021-03-22 09:09 UTC
