### ISSUE TITLE
[NIGHTLY] AdGuard gets randomly killed on Oxygen OS

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1766] opened 2018-03-13 19:09 UTC
### Steps to reproduce
1. Launch AdGuard, keep it running
2. App will crash within a short time period

The customer has set the AdGuard icon and notification as FULL, but the system keeps downgrading the app status to LOW_PRIORITY.

### Expected behavior
AdGuard should work fine

### Actual behavior
AdGuard crashes over a seemingly random period of time

### Customer ID & Debug Logs
1407952
Log timing: ~11-12am, 7pm

### Your environment
* Adguard version: 2.11.46
* Adguard filtering mode: VPN
* Device model: OnePlus One 5T
* Operating system and version (e.g. Android 7.1.2): Android 8.0 + OxygenOS
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None

**Comment by ameshkov** [comment] 2018-03-14 16:24
Could it be that this is a duplicate of #1385?

**Comment by akmLaVx** [comment] 2018-03-14 16:28
OnePlus should've fixed that back in December, and it's the only issue of this sort we've received from a OnePlus user over the last few months. Doubt that.

**Comment by ameshkov** [comment] 2018-03-14 16:42
But anyway, have you suggested pinning AG?

**Comment by akmLaVx** [comment] 2018-03-14 17:38
Told him to do so. Will see whether this helps.

**Comment by ameshkov** [comment] 2018-03-20 14:52
Reopen if it does not help

**Closed by ameshkov** 2018-03-20 14:52 UTC
Labels: waiting for data
