### ISSUE TITLE
Adguard for Android app blocking video ads on aps like 10Play but video I want to watch won't play. 

### ISSUE THREAD

**Issue by Jacko24** [AdguardTeam/AdguardForAndroid#3942] opened 2021-08-15 06:54 UTC
Hi there. If I use the Adguard extension for Firefox or Chrome it works perfectly to block video ads on Australian TV streaming sites like 10Play, SBS on demand etc. If I use the Android app and use the corresponding apps to block video ads it doesn't work. It stops the advert but makes the apps unusable as the stream won't play either. Any idea on how I can fix this. Thanks!

**Comment by anastenko** [comment] 2021-08-16 12:51
@Jacko24 Hello.
Could you please send us the debug logs?

Here's how to do it:

1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
3. Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
4. Send both files to `devteam@adguard.com`. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by anastenko** [comment] 2021-08-24 08:07
@Jacko24 Didn't receive the logs. Did you send it?

**Comment by anastenko** [comment] 2021-08-31 08:59
I'm closing this issue due to no reply. Please re-open it if the issue still occurs.

**Closed** 2021-08-31 08:59 UTC
Labels: Waiting for data
