### ISSUE TITLE
AdGuard certificate is not trusted

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#3316] opened 2020-01-21 13:20 UTC
@TheHasagi commented on [Tue Jan 21 2020](https://github.com/AdguardTeam/CoreLibs/issues/1247)

Somehow, after update of Chrome browser for Android (07.01.2020) every page you reach will notify about CA issue (see attachments). This can be only reproduced if AdGuard CA is installed in System store.

<details>

![image](https://user-images.githubusercontent.com/37797229/72804670-f77ed480-3c61-11ea-91d1-fe1bc667984b.png)

![image](https://user-images.githubusercontent.com/37797229/72804677-fd74b580-3c61-11ea-845c-8b6d753d685e.png)

![image](https://user-images.githubusercontent.com/37797229/72804682-01083c80-3c62-11ea-84d4-83ab1e5682f1.png)

</details>

### Steps to reproduce:

Preconditions:

You should have root access on your mobile device

1. Install AdGuard and enable protection
2. Enable HTTPS filtering and move the certificate from user to system store
3. Reboot the device
4. Try to open any webpage

---

@ameshkov commented on [Tue Jan 21 2020](https://github.com/AdguardTeam/CoreLibs/issues/1247#issuecomment-576659708)

> Reboot the device

Isn't it a Magisk issue?

**Comment by vadu71** [comment] 2020-01-21 14:02
Can't see any such an issue. Latest chrome, rooted, Magisk, the certificate in the system store.
![Screenshot_20200121-185703](https://user-images.githubusercontent.com/44457310/72810954-797df600-3c80-11ea-8e3a-fff2fc92cfe1.png)

**Comment by akmLaVx** [comment] 2020-01-27 00:36
New case.

Helpdesk ID & logs: 1556449
Device info: Samsung SM-M405F (M40 6G), Android 9, rooted, cert moved to system storage
Application: in.startv.hotstar

**Comment by artemiv4nov** [comment] 2020-05-15 19:41
@TheHasagi Can you reproduce on the latest nightly, please?

**Comment by artemiv4nov** [comment] 2020-07-13 19:21
So, the problem is not repeated anymore, I close this task. If it will happen again, please re-open the task.

**Closed** 2020-08-17 10:31 UTC
Labels: Bug, Compatibility, P2: High, Resolution: Fixed, Status: Resolved
