### ISSUE TITLE
Applications are hanging while Adguard is on

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForAndroid#1168] opened 2017-04-13 23:31 UTC
Our customer has complained about some applications are hanging while Adguard is on (like Chrome or SMS backup program).
He noticed it only began doing this after the latest update. 
Icon is active
He had troubles with sending logs, we suspect some cleaning application
disabling pref.vpn.disable.pause didn't help

Logs are here: 1448020

**Comment by whatinthenameofgod** [comment] 2017-04-14 00:56
Hi! Yes. It's weird. The Internet connectivity will basically hang. Google maps, music, play store, etc. It won't say its offline, but it won't load. If I toggle Adguard protection in and off, the whatever was hanging will load instantly.

I can't find any other culprit which is frustrating. I've been using Adguard since November without issue. This began within the last few weeks.

Happy to test anything needed to get to the bottom of this!

**Comment by vozersky** [comment] 2017-04-14 16:03
[debug.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/922418/debug.txt)
[state.txt](https://github.com/AdguardTeam/AdguardForAndroid/files/922419/state.txt)

**Comment by ameshkov** [comment] 2017-04-16 20:04
@whatinthenameofgod as I see, you're on one of the older beta versions. Could you please check the app updates? The latest version is 2.9.64

**Comment by ameshkov** [comment] 2017-04-16 20:05
There were some major bugs fixed between 2.9.53 and 2.9.64, so it might be important.

**Comment by KozelElena** [comment] 2017-04-29 02:23
Our customer updated the info and it still doesn't work

**Comment by vozersky** [comment] 2017-05-02 14:46
@KozelElena ask user to communicate on GitHub please


`199 active TCP connections left.` Looks like there is an app that creates a lot of TCP connections on the device. It would be great to know which one is that.


What we have to ask him to do:

- activate a debug logging (record everything level)
- use the device until the problem is reproduced
- send the log to us _manually_ (it's important).
   use any file manager and  find the log file at:

/storage/Android/data/com.adguard.android/cache/log

or, depending on device,

/sdcard/Android/com.adguard.android/cache/log or

/sdcard/data/Android/com.adguard.android/cache/log or

/sdcard/Android/data/com.adguard.android/

**Comment by whatinthenameofgod** [comment] 2017-05-04 01:45
So I have 4 logs in my file and all of them are reasonably-sized except the most recent one... that's ~430 mb which was not exactly what I expected. SO I am uploading them to my Dropbox and I'll share a link so you can download them.

The time I hit an error is 2:11 PM today, 5/3/17, although it did happen multiple times besides that. That was just one of the times I noted.

Sorry for the size? I had no idea it'd be that big... please let me know if there's anything else I can provide!

https://www.dropbox.com/sh/0u2v7smlls2wdh1/AABn1gxRvK55gt5iszAsmorZa?dl=0

**Comment by TPS** [comment] 2017-05-04 01:59
@whatinthenameofgod For @AdGuardTeam's sake, maybe you want to 7-Zip or @ least Zip before uploading?!  It should compress extremely well!

**Comment by TPS** [comment] 2017-05-04 02:05
According to https://www.dropbox.com/help/desktop-web/download-entire-folders, they can be _downloaded_ compressed after the fact, so don't worry, I guess.

**Comment by KozelElena** [comment] 2017-05-05 02:24
The issue appeared again and we have logs in 1448020
Kindly check

**Comment by whatinthenameofgod** [comment] 2017-05-09 05:33
May have a possible culprit. The app Join (https://joaoapps.com/join/) is my go-to for keeping my devices connected to my phone. It's like Pushbullet in nature.

**Comment by ameshkov** [comment] 2017-05-09 21:00
@whatinthenameofgod according to the log, CityMapper creates thousands UDP connections and it might be the culprit.

Try disabling AG for CityMapper (in AG settings -> Apps Management -> CityMapper -> uncheck Enabled)

**Comment by ameshkov** [comment] 2017-05-09 21:06
Connection example:
```
15:08:43.395 [Thread-102] DEBUG com.adguard.android.filtering.vpn.i - UDP id=214992 Connecting to /17.253.20.253:123. Process info: com.citymapper.app.release /:::40213 /:::0 10123
15:08:43.395 [Thread-102] DEBUG c.a.android.filtering.commons.d - UDP id=214992 Creating new connection com.citymapper.app.release /:::40213 /:::0 10123 with packet UDP 172.16.209.1:40213 > 17.253.20.253:123 len=48
15:08:43.396 [pool-2-thread-28461] DEBUG c.a.android.filtering.commons.d - UDP id=214992 [OUT] UDP 172.16.209.1:40213 > 17.253.20.253:123 len=48
15:08:43.397 [pool-2-thread-28461] DEBUG c.a.android.filtering.commons.d - UDP id=214992 Open UDP connection from /172.16.209.1:40213
15:08:43.498 [Thread-5] DEBUG com.adguard.commons.b.s - UDP id=214992 Read 48 bytes from datagram channel
15:08:43.502 [Thread-5] DEBUG c.a.android.filtering.commons.d - UDP id=214992 [IN] UDP 38.7.119.0:123 > 172.16.209.1:40213 len=48
15:08:43.503 [Thread-5] DEBUG com.adguard.commons.b.s - UDP id=214992 Read 48 bytes from datagram channel
15:08:43.503 [Thread-5] DEBUG c.a.android.filtering.commons.d - UDP id=214992 [IN] UDP 17.253.20.253:123 > 172.16.209.1:40213 len=48
15:09:03.706 [pool-3-thread-1] DEBUG com.adguard.android.filtering.vpn.i - UDP id=214992 Cleaning up connection. Idle for 20202ms.
15:09:03.724 [pool-3-thread-1] DEBUG c.a.android.filtering.commons.d - UDP id=214992 Closing VPN connection
15:09:03.728 [pool-3-thread-1] DEBUG c.a.android.filtering.commons.d - UDP id=214992 Closing UDP connection to /17.253.20.253:123.
15:09:03.728 [pool-3-thread-1] DEBUG c.a.android.filtering.commons.d - UDP id=214992 VPN connection has been closed
```

It's weird that we the source IP is different for two UDP packets received, we might be on something here.

**Comment by whatinthenameofgod** [comment] 2017-05-10 21:26
Thank you for filtering through all those logs! This seems weird. I sent CityMapper support a message as well as disabled it from being routed through AdGuard. We'll see what happens and I'll keep you posted. Thank you!!!

**Comment by whatinthenameofgod** [comment] 2017-05-11 15:23
Bad news... Even with CityMapper traffic not being routed through AG, I ran into the issue again. I was attempting to load a YouTube video and it just hung for over a minute. I reset AG service by turning on and off and like magic, it worked. I suspect the app Join that I mentioned earlier, so going to try to disable that like CityMapper and see what happens...

**Comment by ameshkov** [comment] 2017-05-11 15:25
@whatinthenameofgod bad:( it'd be better if I could take a look in the log file again, there should be something else I guess

**Comment by whatinthenameofgod** [comment] 2017-05-11 16:02
I didn't have the track everything on, but here are all the logs. Email me if you need anything else.



[logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/993636/logs.zip)

**Comment by whatinthenameofgod** [comment] 2017-05-12 00:53
Caught it in action with "everything" being logged. YouTube wouldn't work at loading anything. It happened between 545 and 548. You'll see when I turned protection on and off and then YouTube began working instantly.

**Comment by whatinthenameofgod** [comment] 2017-05-12 00:53
[logs-1.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/994762/logs-1.zip)

**Comment by ameshkov** [comment] 2017-05-23 09:09
@whatinthenameofgod sorry for the late reply:( Now I am back, will look into it.

**Comment by ameshkov** [comment] 2017-05-23 09:14
The TCP state is not okay that's for sure, but I don't yet understand what's causing it.

You know what, we will soon migrate Adguard to the new network stack implementation: https://github.com/AdguardTeam/CoreLibs/issues/9

It is MUCH faster and better than the current one. Let's wait a bit and re-test it then on a newer version.

Assigned this issue to v2.10 so that I didn't forget about it.

**Comment by whatinthenameofgod** [comment] 2017-05-25 08:33
Sounds good! Ping me via email and let me know when you want me to test!

**Comment by Revertron** [comment] 2017-08-07 16:20
The native stack is on it's way in the master. This issue is not relevant anymore.

**Comment by ameshkov** [comment] 2017-08-07 16:25
@Revertron let's keep it open until beta version is out and @whatinthenameofgod confirms that it's fixed

**Comment by ameshkov** [comment] 2017-08-23 14:14
@evgeniy-ADG 
Could you plz ask @whatinthenameofgod to check the latest beta version?

**Comment by Bohdan-SUP** [comment] 2017-08-23 14:23
Asked in *1448020*, will update.

**Comment by ameshkov** [comment] 2017-09-06 14:23
@Bohdan-SUP anything?

**Comment by Bohdan-SUP** [comment] 2017-09-06 14:30
@ameshkov Still crashing, fresh logs in _1448020_

**Comment by ameshkov** [comment] 2017-09-07 10:37
Errors in the log:
```
TCP id=3 Unexpected exception in the onTcpConnectRequest handler

java.lang.NullPointerException: null
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1019) ~[na:0.0]
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1014) ~[na:0.0]
	at com.adguard.android.filtering.filter.c.a(Unknown Source:7) ~[na:0.0]
	at com.adguard.android.filtering.vpn.a.onTcpConnectRequest(Unknown Source:71) ~[na:0.0]
	at com.adguard.corelibs.tcpip.NativeTcpIpStackImpl$Callbacks$1.run(Unknown Source:16) ~[na:0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:764) ~[na:0.0]
09:15:27.854 [VpnService-main] DEBUG Native.TCPIP.TCPMNGR - [LWIP id=3] complete_tcp_connect_request
```

**Comment by ameshkov** [comment] 2017-09-07 10:50
Guys, I've fixed this error, but the crashes seem to be caused by the Native code.

To find out what's the reason, we need to get the logcat log:
https://kb.adguard.com/en/android/solving-problems/logcat

**Comment by ameshkov** [comment] 2017-12-04 13:02
Please reopen if there is new information in the ticket.

**Closed** 2017-12-04 13:01 UTC
Labels: bug, waiting for data
