### ISSUE TITLE
Random crashes on Huawei STF-L09

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#1767] opened 2018-03-13 20:16 UTC
### Steps to reproduce
1. Launch AdGuard, keep it running
2. App will crash within a random time period, usually once per 24h

All basic diagnostics have been completed, but the problem keeps re-occuring.

### Expected behavior
AdGuard should work fine

### Actual behavior
AdGuard crashes over a seemingly random period of time

### Customer ID & Debug Logs
1786226

### Your environment
* Adguard version: 2.10.176
* Adguard filtering mode: VPN
* Device model: Huawei STF-L09
* Operating system and version (e.g. Android 7.1.2): Android 8.0 + EMUI
* Rooted or not?: No
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed?: None

**Comment by nkartyshov** [comment] 2018-03-14 11:21
Duplicate of #1594

Temporary solution: enable `pref.vpn.disable.reconfiguration`.

```
AdguardVpnService - Error while building VPN file descriptor
java.lang.IllegalStateException: Cannot bind com.adguard.android.vpn.AdguardVpnService
	at android.os.Parcel.readException(Parcel.java:1953) ~[na:0.0]
	at android.os.Parcel.readException(Parcel.java:1891) ~[na:0.0]
	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1987) ~[na:0.0]
	at android.net.VpnService$Builder.establish(VpnService.java:785) ~[na:0.0]
	at com.adguard.android.vpn.AdguardVpnService.a(Unknown Source:403) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.d(Unknown Source:68) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.c(Unknown Source:13) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService$3.run(Unknown Source:2) ~[na:0.0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457) ~[na:0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:0.0]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:784) ~[na:0.0]
01:02:19.396 [pool-1-thread-1] INFO  com.adguard.android.ServiceManager - ServiceManager handle status event: VPN_CONFIG_ERROR
01:02:19.402 [pool-1-thread-1] INFO  com.adguard.android.service.bd - Updating widgets for VPN_CONFIG_ERROR protection
```

**Closed by nkartyshov** 2018-03-14 11:21 UTC
Labels: duplicate
