### ISSUE TITLE
Enable Filtering HTTPS traffic in Cromite Browser (`org.cromite.cromite`) by default 

### ISSUE THREAD

**Issue by johnconner122** [AdguardTeam/AdguardForAndroid#4974] opened 2023-09-15 16:43 UTC
### Issue Details

. 

### Proposed solution

. 

### Alternative solution

.

**Comment by Versty** [comment] 2023-10-02 15:43
@johnconner122 Closed as a duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/4997

**Closed** 2023-10-02 15:43 UTC
Labels: Feature request, Priority: P4
