### ISSUE TITLE
Filtering Log shows most of traffic that is explicitly allowed by the User Filter without the green background color

### ISSUE THREAD

**Issue by SergeiShir** [AdguardTeam/AdguardForAndroid#2474] opened 2019-01-27 07:59 UTC
After the latest upgrade, I encounter the following issue:
Most of the traffic that my User Filter allows is shown without a background color (and as "Status = Processed") instead of the green background (and as "Status = Whitelisted"). There is no apparent pattern - this issue occurs for different User Filter rules - rules for DNS connections, rules for connections from specific apps, rules for URL connections.
However, the traffic that is explicitly blocked the User Filter, is still always shown with the red background color.

### Steps to reproduce

1. Open an app, or browse to some sites to initiate connections that are explicitly allowed by the User Filter.
2. Open Filtering Log.
3. Most of these connections are shown without a background color - when you open such log entries, it shows "Status = Processed" + "Filter Name = User Filter".
4. There are still connections that are shown with the green background - such log entries show "Status = Whitelisted" + "Filter Name = User Filter".

### Expected behavior

All connections that are explicitly allowed by the User Filter should be shown as green

### Actual behavior

Most of the allowed connections are shown without a background color

<details><summary>Screenshot:</summary>
Will be attached shortly

(1 of 2) Example of allowed connections that are shown without background color:

![filteringlog_no_background_color](https://user-images.githubusercontent.com/17823400/51798530-92de9480-221c-11e9-84c7-23e98996885b.gif)

(2 of 2) Example of an entry:

![filteringlog_entry](https://user-images.githubusercontent.com/17823400/51798531-9bcf6600-221c-11e9-9557-d8261b04ce87.gif)

</details>

### Customer ID 

Premium 1146569

### Your environment

* Adguard version: 3.0.195n (1.3.94cl)
* Adguard filtering mode: VPN
* Device model: Google Pixel 2 XL
* Operating system and version: stock Android 9, security patch 05 Jan 2019
* Rooted or not? Not rooted
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? No

### Logs and Settings
[adguard_logs_3.0.195_27Jan_09h30m.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2799848/adguard_logs_3.0.195_27Jan_09h30m.zip)

**Comment by ameshkov** [comment] 2019-01-28 06:56
@SergeiShir you have this issue with DNS requests only, right?

**Comment by SergeiShir** [comment] 2019-01-28 06:59
Mostly with DNS rules, but also with rules for specific apps and with rules
for URLs.

**Comment by ameshkov** [comment] 2019-01-28 07:00
@Revertron I guess it's caused by the CL 1.3 pull request you were implementing, please take a look.

Try unblocking requests from the filtering log to reproduce the issue.

**Comment by lancelot-moon** [comment] 2019-01-28 10:50
This is actually duplication with mine.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2471

**Comment by SergeiShir** [comment] 2019-01-30 13:11
Just upgraded to the latest Nightly.
The situation is much better (~85% are whitelisted as expected), but still there are many missed (just processed).
See the attached logs.
[adguard_logs_3.0.205_30Jan2019_15h01m.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/2812645/adguard_logs_3.0.205_30Jan2019_15h01m.zip)

**Comment by ameshkov** [comment] 2019-01-30 13:14
@SergeiShir plz send logs to `devteam@adguard.com` next time, it might be not okay to share the file here

**Comment by ameshkov** [comment] 2019-01-30 13:15
@SergeiShir could you please show or describe a couple of examples of such wrongly "processed" requests?

**Comment by SergeiShir** [comment] 2019-02-01 09:53
Can you GREP the attached logs for these 2 conditions?
Status = Processed
AND
Filter name = User Filter

If not, let me know...

**Comment by ameshkov** [comment] 2019-02-01 10:01
Well, the filtering log events aren't written to the log file, the data there is raw. So the question is which requests representation in the filtering log is wrong.

**Comment by SergeiShir** [comment] 2019-02-01 15:37
As requested, I sent the new log files to devteam@adguard.com
Subject = Files for GitHub bug 2474
Sent = 17:34 GMT+2

I attached 2 sets of logs together with screenshots from the Filtering Log that show the problematic entries

**Comment by ameshkov** [comment] 2019-02-06 10:06
@SergeiShir got the logs and screenshots, thank you!

@Revertron it seems that HTTPS Tunnel evens with a whitelisted rule applied falsely marked as "Processed" instead of "Whitelisted". The problem might be on the CL side, though.

**Closed** 2019-03-14 20:00 UTC
Labels: Bug, P2: High
