### ISSUE TITLE
The official VK app won't enable the built-in proxy due to AdGuard

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForAndroid#2346] opened 2018-11-25 13:34 UTC
You have to be in Ukraine to be able to reproduce the issue.

### Steps to reproduce

1. Enable AdGuard with default settings
2. Open the VK app (com.vkontakte.android; version 5.23) and head to Genera > Use Proxy-server
3. Try to enable it 

### Expected behavior

The proxy server is enabled 

### Actual behavior

It won't enable, stating that it has found no reasons for that. Disabling the ad blocking for the VK app does not help. 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/48979669-1538c400-f0c7-11e8-9c02-9f2eb8cb2b52.png)

</details>

### Your environment

* Adguard version: 2.12.247
* Adguard filtering mode: VPN
* Device model: Xiaomi Mi A2 Lite
* Operating system and version: 8.1.0
* Rooted or not?  n/a
* Any other apps that can start VPN/Antiviruses/Cleaners etc. installed? n/a

**Comment by ameshkov** [comment] 2018-11-25 16:07
@Eugene-Savenko this is a duplicate of #1646 and we can do nothing about it.

The problem is in the VK app -- they detect an existing VPN connection and that's why they don't enable proxy.

**Closed by ameshkov** 2018-11-25 16:07 UTC
