### ISSUE TITLE
AdGuard always run in root mode in VPN mode

### ISSUE THREAD

**Issue by cyberboh** [AdguardTeam/AdguardForAndroid#4486] opened 2023-02-20 11:03 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 nightly 51

### Environment

```markdown
- OS:Android 13
- Device: Xiaomi Poco F3
- Firmware: Custom ROMS PixelOS
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Chinese filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Annoyances filter, AdGuard DNS filter, EasyList, ABPindo, EasyList China, AdBlockID, Fanboy's Annoyances, Online Malicious URL Blocklist, RU AdList - Counters, Fanboy's Enhanced Tracking List, List-KR, NoCoin Filter List

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Block Push API, Block Location API

### Issue Details

Steps to reproduce:
1. Install adguard nightly latest
2. Turn it on
3. It will ask for root access

### Expected Behavior

It wont ask like on 3.6.x stable version bcz i dont turn on proxy mode

### Actual Behavior

It asking for root access

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment] 2023-02-20 12:21
@cyberboh Hi! 
This is a duplicate of #4452 
The issue will be fixed very soon.

**Closed** 2023-02-20 12:21 UTC
