### ISSUE TITLE
AdGuard does not intercept links to install User scripts

### ISSUE THREAD

**Issue by Renjh5218** [AdguardTeam/AdguardForAndroid#4145] opened 2022-04-16 21:07 UTC
greasy fork网站安卓版貌似移除了adguard
    ![Screenshot_20220417-044955.jpg](https://user-images.githubusercontent.com/79973902/163691164-f97fbe5b-b203-4f55-909c-7f6dae1cb407.jpg)![Screenshot_20220417-044923.jpg](https://user-images.githubusercontent.com/79973902/163691171-1838d622-97cd-4700-88ad-6b1f11423130.jpg)
adguard添加的扩展全部失效了
![Screenshot_20220417-050054.jpg](https://user-images.githubusercontent.com/79973902/163691229-f6d20c73-ee08-4c33-845d-ebb2c57d0b59.jpg)
以前可以使用![Screenshot_20210926-214746.jpg](https://user-images.githubusercontent.com/79973902/163691295-712fc046-93b8-4517-9322-894447f8c232.jpg)![Screenshot_20210926-205048.jpg](https://user-images.githubusercontent.com/79973902/163691310-4ff74f73-cd2f-4420-ba61-c3ddf3a74638.jpg)
但是现在不工作了![Screenshot_20220417-050629.jpg](https://user-images.githubusercontent.com/79973902/163691354-2216eef6-98d7-4624-83e3-5170a4718d5f.jpg)

**Comment by maxikuzmin** [comment] 2022-09-05 14:24
@Renjh5218 I apologize endlessly. Please tell me if the issue is still relevant?
As far as I can see, the issue is in the "AdGuardForAndroid" repository, but the "Greasy Fork" script is only for desktop applications

**Comment by maxikuzmin** [comment] 2022-09-13 13:44
@Renjh5218  I am closing the issue. If the issue is relevant in the future, you can reopen the issue

**Closed by maxikuzmin** 2022-09-13 13:44 UTC
