### ISSUE TITLE
Adg is turning off by itself

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForAndroid#1264] opened 2017-06-05 06:41 UTC
Adg is turning off by itself
[state (4).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1051266/state.4.txt)
[debug (3).txt](https://github.com/AdguardTeam/AdguardForAndroid/files/1051267/debug.3.txt)

from the customer: "I noticed that adguard wasn't filtering, and restarted the app at 2:31am"

CustomerID: 1154953

**Comment by vozersky** [comment] 2017-06-05 10:34
01:04:14.060 [Thread-6] ERROR com.adguard.android.commons.c - Thread: Thread[Thread-6,5,main]; Uncaught exception:

java.lang.OutOfMemoryError: Could not allocate JNI Env
	at java.lang.Thread.nativeCreate(Native Method) ~[na:0.0]
	at java.lang.Thread.start(Thread.java:730) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941) ~[na:0.0]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1359) ~[na:0.0]
	at com.adguard.android.filtering.vpn.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.i.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.h(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService.a(Unknown Source) ~[na:0.0]
	at com.adguard.android.filtering.vpn.FilteringVpnService$1.run(Unknown Source) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]

**Comment by ameshkov** [comment] 2017-06-13 14:32
The problem is that the log is trimmed and I don't see what actually caused OOM error. If this happens again, please ask user to get the full file from the device.

**Comment by vozersky** [comment] 2017-06-13 14:58
@Michael23456

**Comment by Yana-SUP** [comment] 2017-06-13 15:29
emailed the user

**Comment by Noyabronok** [comment] 2017-06-15 22:55
Have you tested adguard on galaxy s7 edge? It's a very popular phone.

**Comment by ameshkov** [comment] 2017-06-16 08:29
Sure, there're quite a lot of people using AG on Galaxy S7 (and S8).

Also, this particular issue is not about the device model itself. It might be caused by some third-party app installed, that's why I need to get the full log -- to figure which app caused it.

**Comment by vozersky** [comment] 2017-06-20 09:07
closed until we receive a reply from the user

**Comment by Noyabronok** [comment] 2017-06-20 09:47
https://drive.google.com/folderview?id=0B7Wh_5FUWGBQcVRlMFF5QUFrTjA

Logs in link

**Comment by ameshkov** [comment] 2017-06-28 12:59
@Noyabronok 

The issue is caused by the `Too many open files` error. This is a sign that there's an app that opens too many connections.

The problem is that the log level is "default", hence I don't see what exact app created all those connections. Could you please switch the logging level at least to "Record HTTP requests" and record it again?

**Comment by Noyabronok** [comment] 2017-06-30 07:26
working on it.  will provide the files as soon as possible.

**Comment by ypetruk** [comment] 2017-07-01 10:25
updated logs
https://drive.google.com/drive/u/0/folders/0B7Wh_5FUWGBQcVRlMFF5QUFrTjA

**Comment by ameshkov** [comment] 2017-07-02 11:27
Guys, I am very sorry, it seems that I should've requested "record everything"-level log :(

Requests log is rather "clean", I just see that Chrome makes tons of requests, but that's okay.

Please, do the same with the "record everything" level. Log will be HUGE, but there will be information about non-HTTP and non-HTTPS requests, which is missing in the requests log.

**Comment by Noyabronok** [comment] 2017-07-27 01:11
it has gotten worse.  now, instead of adguard crashing, internet access
stops working.  I have to stop or restart adguard to get internet to work
again.  Here are some logs

https://drive.google.com/open?id=0B7Wh_5FUWGBQVk1la1JwQlA4cXM

https://drive.google.com/open?id=0B7Wh_5FUWGBQTy1ZbURLdElnTlU

**Comment by Noyabronok** [comment] 2017-07-27 01:22
updated log link:
https://drive.google.com/open?id=0B7Wh_5FUWGBQVk1la1JwQlA4cXM

**Comment by ameshkov** [comment] 2017-07-31 08:29
> updated log link:
> https://drive.google.com/open?id=0B7Wh_5FUWGBQVk1la1JwQlA4cXM

404 Not found by the link :(

**Comment by Noyabronok** [comment] 2017-07-31 09:40
I removed it. Too much private info in the logs. I don't want it on github.
Send me an email address to provide logs to.

**Comment by ameshkov** [comment] 2017-07-31 09:43
@Noyabronok sure, here it is: `devteam@adguard.com`

**Closed** 2017-12-04 12:54 UTC
Labels: waiting for data
