### ISSUE TITLE
[TV] App wake up TV from Standby to check for filter updates

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdguardForAndroid#5182] opened 2024-01-22 17:56 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.3.1

### Environment

```markdown
- OS: Android TV 10 
- Device: Sony Bravia XR-55A75K
- Firmware: 6.7480
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Since I have installed Adguard for TV on my Bravia XR-55A75K I have noticed that typical click noise from my TV when turn on and turn off, without turn on the TV.

Except Smarttube and AdGuard, I have no other App installed and several other Apps are disabled. Thats why I am almost sure that the issue comes from AdGuard.

When this issue happen, no image is displayed on TV and the TV "turn off" after about 5 minutes (second click).

I have checked the network what the TV is doing during that time. This are all called domains.
For me it looks like, AdGuard was scheduled to update filters:

![grafik](https://github.com/AdguardTeam/AdguardForAndroid/assets/6276915/53ac4346-d037-494d-bb12-9b6283eb01b7)

But here is the thing: **This is a TV**, not a Smartphone.
There is no need to have latest filters and be protected as long the TV is in Standby. (usually my TV goes in deep sleep without any domain calling)
And thats the second issue: The GUI is so low in customizable that there is no way to disable Filterrefresh to prevent this behavior. I don't even know what kind of filters are active here?

Now I have disabled Internet security, to prevent the call of `sb.adtidy.org` and monitor the issue. But why is the App calling `userscripts.adtidy.org`? I don't even see an option for userscripts. It's just saying AdBlocking.

Imaging you have guests over night, sleeping in the living room. Suddenly the loud click appears. Unpleasant moment:

https://github.com/AdguardTeam/AdguardForAndroid/assets/6276915/acc163fb-130e-4827-b65e-fdbc561969f5

**Comment by Morku** [comment] 2024-01-24 16:20
It turns out, after disabling AdGuard, the issue is the same.

So there are two possibilitys. There is an overlap with the installation of AdGuard and maybe a TV Firmware. Or AdGuard changed some general system setting to establish the wifi connection once a day.

It would be nice to know, if the App is designed to check once a day, even when the device (TV) is in deep sleep mode.
If no, feel free to close ticket.

**Comment by Morku** [comment] 2024-02-06 09:13
@maxikuzmin 
Hi again, I have sent the logfile now (AdGuard Support Request #869867). As it is difficult to give a long decription on TV, I entered the "Issue #5182" in message.
I am observing the unexpected turn on moment on:

- 2nd February 20:16
- 3rd February 15:59
- 3rd February 22:00
- 4th February 15:58
- 4th February 22:00
- 5th February 15:57

In short: The TV wasn't turn on the whole weekend, but was calling home on this times with the "ping" noise. Interestingly, the TV decided to have two turn on moments now 🤔

I have found like two posts on reddit, reporting the same, but already 2 years ago. But people just say "nah, thats probably the pixelrefresh", but thats to easy. Why should the TV do this multiple time without turning on.

If the issue is not caused by AdGuard, close the ticket. If you can see in the Logfile what App is causing the wake up and calling home, it would be great to know 😊

**Comment by maxikuzmin** [comment] 2024-02-12 15:29
@Morku I apologize, but for some reason your logs are missing the time you specified.
Could you please re-record the logs again?

**Comment by Morku** [comment] 2024-02-12 16:09
@maxikuzmin 
Are you sure? I can find related days in the Log. Maybe time stamps are logged in different timezone?

![Screenshot 2024-02-12 163223](https://github.com/AdguardTeam/AdguardForAndroid/assets/6276915/cbac3447-4bcd-4c6e-94b6-e10be5c5589e)

Especially Logs for 3rd and 4th February shouldn't exist at all as I left the flat on Friday and returned Monday. The TV wasn't used.

Here are the contacted domains during that time:

<details><summary>Screenshot-1:</summary>

![Screenshot 2024-02-12 163543](https://github.com/AdguardTeam/AdguardForAndroid/assets/6276915/e32c7d24-e928-447e-a359-fd31ec44d1cd)


</details><br/>

Also I can find related timestamps in the Logfile, e.g. 4th February 15:58:

```
15:58:25.108 [DefaultDispatcher-worker-1] DEBUG n6.d - The network 105 has an IPv6 interface
15:58:25.108 [DefaultDispatcher-worker-1] DEBUG c.a.c.network.CoreNetworkUtils - getSystemDnsServers(): skipVpn: true, useFallback: true
15:58:25.110 [DefaultDispatcher-worker-1] DEBUG c.a.c.network.CoreNetworkUtils - getSystemDnsServers(): skipVpn: false, useFallback: true
15:58:25.125 [DefaultDispatcher-worker-1] INFO  Protection Manager - Parameters from DNS filtering are not the same, let's restart the DNS Proxy
15:58:25.125 [DefaultDispatcher-worker-1] INFO  l1.c - Request 'restart a DnsProxy' received
15:58:25.126 [DefaultDispatcher-worker-1] INFO  com.adguard.dnslibs.proxy.DnsProxy - DNS proxy deinit: Joining event loop
15:58:25.126 [DefaultDispatcher-worker-1] DEBUG com.adguard.dnslibs.proxy.DnsProxy - EventLoop join: Joining
15:58:25.126 [Thread-60] INFO  com.adguard.dnslibs.proxy.DnsProxy - DNS proxy operator(): Deinitializing proxy module...
15:58:25.126 [Thread-60] INFO  com.adguard.dnslibs.proxy.DnsProxy - DNS proxy operator(): Shutting down listeners...
15:58:25.126 [Thread-60] INFO  com.adguard.dnslibs.proxy.DnsProxy - DNS proxy operator(): Shutting down listeners done
15:58:25.126 [Thread-60] INFO  com.adguard.dnslibs.proxy.DnsProxy - DNS forwarder deinit: Deinitializing...
15:58:25.126 [Thread-60] INFO  com.adguard.dnslibs.proxy.DnsProxy - DNS forwarder deinit: Destroying DNS64 state...
```
Have you received the correct logfile?

------------------

To the current situation:

I have factory reset the TV on 7th February and debloated/reinstalled the same way as before, except installing AdGuard for now.
I have seen internet connections once with TV off, but I didn't realize a "Pling" noise.
It's to early to say if I am able to see a 24h task scheduler from the TV itself and when it happens, if with or without a "pling" noise.

------------------

_My conspiracy theory at this point:_

That "relay pling" noise is obvious when the TV is draining power. Maybe with AdGuard running in background, the TV is draining more power at this "24h wake up" that some kind of threshold is exceeded that the "Pling" is necessary.

When I check the Logfiles, the Logs are completely spammed with that error:
```
07:00:52.629 [Thread-55] DEBUG com.adguard.dnslibs.proxy.DnsProxy - ResponseCache get: Cache miss for key 1|1|00|www.youtube.com.
07:00:52.630 [Thread-55] DEBUG com.adguard.dnslibs.proxy.DnsProxy - UdpSocket connect: [id=3767] connect(): Failed to connect: Error at ag::dns::UdpSocket::connect:56: network is unreachable
07:00:52.631 [Thread-55] DEBUG com.adguard.dnslibs.proxy.DnsProxy - UdpSocket connect: [id=3768] connect(): Failed to connect: Error at ag::dns::UdpSocket::connect:56: network is unreachable
07:00:52.632 [Thread-55] DEBUG com.adguard.dnslibs.proxy.DnsProxy - UdpSocket connect: [id=3769] connect(): Failed to connect: Error at ag::dns::UdpSocket::connect:56: network is unreachable
07:00:52.633 [Thread-55] DEBUG com.adguard.dnslibs.proxy.DnsProxy - UdpSocket connect: [id=3770] connect(): Failed to connect: Error at ag::dns::UdpSocket::connect:56: network is unreachable
07:00:52.633 [Thread-55] DEBUG com.adguard.dnslibs.proxy.DnsProxy - UdpSocket connect: [id=3771] connect(): Failed to connect: Error at ag::dns::UdpSocket::connect:56: network is unreachable
07:00:52.634 [Thread-55] DEBUG com.adguard.dnslibs.proxy.DnsProxy - UdpSocket connect: [id=3772] connect(): Failed to connect: Error at ag::dns::UdpSocket::connect:56: network is unreachable
07:00:52.634 [Thread-55] DEBUG com.adguard.dnslibs.proxy.DnsProxy - UdpSocket connect: [id=3773] connect(): Failed to connect: Error at ag::dns::UdpSocket::connect:56: network is unreachable
07:00:52.635 [Thread-55] DEBUG com.adguard.dnslibs.proxy.DnsProxy - UdpSocket connect: [id=3774] connect(): Failed to connect: Error at ag::dns::UdpSocket::connect:56: network is unreachable
07:00:52.635 [Thread-55] DEBUG com.adguard.dnslibs.proxy.DnsProxy - DNS forwarder log_packet: [56048] Server failure response:
;; ->>HEADER<<- opcode: QUERY, rcode: SERVFAIL, id: 56048
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; www.youtube.com.	IN	A
```

If you wonder, the `www.youtube.com` requests are performed by the App [SmartTube](https://github.com/yuliskov/SmartTube), probably to keep the Subscription list up2date.

**Comment by maxikuzmin** [comment] 2024-02-13 11:52
@Morku there are filter updates in the logs, but they start after TV has woken up and not in every timing. So the problem is not in AdGuard.
Judging by the logs, some application goes online, and AdGuard starts too. 
It is not clear which application

**Comment by maxikuzmin** [comment] 2024-02-15 18:54
@Morku since the problem is not with the AdGuard app, I'm closing this issue. I hope you can figure out which application is going online

**Closed by maxikuzmin** 2024-02-15 18:54 UTC
Labels: Bug, Priority: P4

**Comment by Morku** [comment] 2024-02-15 19:01
@maxikuzmin 
Since I have factory reset my TV, it doesn't do that 24h "online" thing anymore, but I also don't have installed AdGuard again.

I may will install AdGuard at some later point and I will see if the issue recover.
If so, I will let you know. But even then it is unknown what it trigger that behavior. Maybe the creation of the local VPN and the TV checks its establish VPN connection? Who knows, I am no Android expert.
But thank you for checking.
