### ISSUE TITLE
When you import dns user list, AG should ignore blank lines

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdguardForAndroid#4971] opened 2023-09-14 11:02 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.1

### Environment

```markdown
- OS: Android 13
- Device: Samsung
```

### Root access

- No.

### What filters do you have enabled?

No filters

### What Stealth Mode options do you have enabled?

None

### Issue Details

Steps to reproduce:
1. Go to DNS protection -> DNS filters -> user rules
2. select "Import"
3. choose this example list

```
! title

||example.org^
```

### Expected Behavior

AG should ignore blank lines

### Actual Behavior

AG imports and selects blank lines too.
Then, maybe it shouldn't select commented lines (! ||example.com^ , # ||example.com^ )

### Screenshots

<details><summary>Screenshot 1:</summary>

![osdfkl](https://github.com/AdguardTeam/AdguardForAndroid/assets/1375223/4c65c6cf-ec30-4528-94b4-0089fcf231eb)

</details>

**Comment by Versty** [comment] 2023-09-18 10:11
@superlex Hi! 
This issue is a duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/4888.

**Closed** 2023-09-18 10:11 UTC
Labels: Bug, Duplicate, Priority: P4
