### ISSUE TITLE
The position in the list is not saved after exiting any setting in Tracking protection tab 

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdguardForAndroid#4475] opened 2023-02-15 17:32 UTC
### Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0

### Environment

```markdown
- OS: android 10
```

### Root access

- [ ] Yes, I have it.

### Issue Details

Steps to reproduce:
Go to Protection tab -> Tracking protection -> Custom
Scroll down and select any setting, then enter it and exit again

### Expected Behavior

The position in the list is saved after exiting any setting

### Actual Behavior

The position in the list is not saved after exiting any setting

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by jordanswrld94** [comment] 2023-02-20 22:08
Also isnt saved in the recent activity if u click on something in the log then go back it goes back to top

**Comment by artemiv4nov** [comment] 2023-06-15 15:32
Closed as a duplicate of another private task

**Closed** 2023-06-15 15:33 UTC
Labels: Bug, Resolution: Duplicate, Status: Resolved, Version: AdGuard v4.1, Priority: P4
