### ISSUE TITLE
Always-on VPN Android Setting?

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForAndroid#1815] opened 2018-04-03 01:21 UTC
I notice on my device the ability to enable and disable an Always-on feature for the AdGuard VPN. Would there be any benefit for AdGuard to allow an option in the app to have AdGuard use an 'always-on' feature and work with the Android Always-on VPN setting?

I'm also guessing that the 'Block connections without VPN' would not be a good thing, if AdGuard purposely whitelist apps and what-not.

If the AdGuard VPN should not have this enabled, if the user enables this, is there a way for AdGuard to warn the user about enabling it?

![image](https://user-images.githubusercontent.com/36845626/38223999-38017bee-3731-11e8-8fef-f1174c6de257.png)

**Comment by TPS** [comment] 2018-04-03 04:05
@planet0 #760 #774 #1240 (& linked/associated issues) show the public trail of how much this feature _is_ wanted & worked on, so that it _could_ be an _option_ for users (like ourselves 😉).

My suggestion?  If you feel comfortable, try it in all toggle positions. For me, it balances an extra level of security with convenience by leaving the 1st option on (& I'd leave the 2nd off, if I could [which I can't w/ Android 7.1.1/Nougat, but that's how it acts by default], for the sake of whitelisting, as you mentioned).  If it bugs you, leave it off all the way — there's a reason the AG devs don't _require_ it, just enable it.

**Comment by planet0** [comment] 2018-04-03 04:26
Oops. I should have done further searching, as I only saw one regarding Samsung Always On.

I'll turn the setting to always-on, but not to block. Might help with issue #1768.

**Comment by TPS** [comment] 2018-04-03 04:49
That's an interesting thought.  Let us know what you find out.  Feedback like that helps all of us.

1 of mine:  Have you tried fiddling w/ `Settings > Advanced > Watchdog period` re: maintaining AG VPN?

**Comment by TPS** [comment] 2018-04-05 16:55
@planet0 How's everything working?   Do you wish to close this?

**Comment by planet0** [comment] 2018-04-05 17:09
@TPS Because of #1768 I've been waiting for a response on that before I started to fiddle around with any settings, either with the Always-on setting or the Watchdog period.

I'm also waiting for a response for the question if AdGuard will properly support the Always-on setting or not in Oreo (the app actually having it set it by default), so far it seems valuable so that the VPN connection to the AdGuard app never drops suddenly.

If I'm not mistaken, why isn't this used by default at the moment for AdGuard on Oreo? Isn't this potential for an added benefit?

**Comment by ameshkov** [comment] 2018-04-14 16:11
> Because of #1768 I've been waiting for a response on that before I started to fiddle around with any settings, either with the Always-on setting or the Watchdog period.

"Always-ON" is indeed a legit solution for the Android killing AG issue. However, we don't plan to support it on older versions of Android -- requesting device admin seems too invasive.

While working on #1819 I've found out that there're some things about Always-ON that we didn't handle properly. When always-on kicks in, Android does not initialize the app, and just initialize the VpnService instance. So AdGuard did start the local VPN, but it was simply empty with no filters loaded.

The issue is resolved now and it will work as it should in the next nightly build.

> I'm also guessing that the 'Block connections without VPN' would not be a good thing, if AdGuard purposely whitelist apps and what-not.

When "block connections" is enabled, all the apps that are whitelisted by AG will simply lose connectivity. You'll need to manually enable AG for every app to make them work. Other than that there shouldn't be any problem.

**Closed by ameshkov** 2018-04-14 16:11 UTC
Labels: question
