### ISSUE TITLE
Enable HTTPS filtering for Soul Browser

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForAndroid#4238] opened 2022-09-06 18:19 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

HTTPS filtering is not enabled for [com.mycompany.app.soulbrowser](https://play.google.com/store/apps/details?id=com.mycompany.app.soulbrowser)

### Proposed Solution

HTTPS filtering works fine if it is enabled in Apps Management.

**Comment by maxikuzmin** [comment] 2022-09-07 11:38
@Alex-302 duplicate of <https://github.com/AdguardTeam/AdguardForAndroid/issues/4202>
A solution to the problem is planned for version 4.0

**Closed by maxikuzmin** 2022-09-07 11:38 UTC
Labels: Enhancement
