### ISSUE TITLE
dns filter (custom) doesn't work in http proxy mode (root)

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2975] opened 2019-07-30 22:23 UTC
on vpn it works fine,

please fix

**Comment by TheHasagi** [comment] 2019-07-31 10:13
@patrickdrd 

Hello!

You are using IPv6 only?

**Comment by patrickdrd** [comment] 2019-07-31 10:41
I'm using ipv4,
what kind of details?
all I know is I've got no dns blocking at all

**Comment by TheHasagi** [comment] 2019-07-31 10:59
@patrickdrd 

Can you gather and send the log files according to this [KB article](https://kb.adguard.com/en/windows/solving-problems/adguard-logs) to devteam@adguard.com?

Can you remember when this problem has started? From what version exactly?

**Comment by patrickdrd** [comment] 2019-08-01 20:59
it's working on .119 nightly,
but it needs monitoring,
because it has broken once more before,
the problem was on .118 nighty, maybe one before that too

**Comment by ameshkov** [comment] 2019-08-01 21:35
Duplicate of #2977

**Closed by ameshkov** 2019-08-01 21:35 UTC
Labels: Duplicate

**Comment by TheHasagi** [comment] 2019-08-02 16:28
@patrickdrd 

The common question - Do you use private DNS? :)

**Comment by patrickdrd** [comment] 2019-08-02 19:14
nope. just simple, regular cloudflare dns

**Comment by patrickdrd** [comment] 2019-08-25 07:50
this still happens for me in .140, 
dns filtering is broken after filters update

**Comment by ameshkov** [comment] 2019-08-28 09:37
https://github.com/AdguardTeam/AdguardForAndroid/issues/2977
