### ISSUE TITLE
Internet fails to work when network is changing from wifi to mobile data on some networks

### ISSUE THREAD

**Issue by nastavoi** [AdguardTeam/AdguardForAndroid#4265] opened 2022-10-27 16:53 UTC
I'm facing an issue causing internet failing to work when my Network is changing from wifi to mobile data (e.g. when I move outside of my wifi network). Restarting AdGuard resolves the issue (until the next network change). 

### Issue Details

- **AdGuard version:**
  - 4.0 nightly 35
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Pixel 7 Pro
- **Operating system and version:**
  - Android 13
- **Root access:**
  - No

### Expected Behavior

Internet access should be active at all times when network change from wifi to mobile data e.g. due to poor wifi signal, without the need  to restart AdGuard.

### Actual Behavior

internet failing to work when my Network is changing from wifi to mobile data (e.g. when I move outside of my wifi network). Restarting AdGuard resolves the issue (until the next network change). I'm able to reproduce it every time.

### Additional Information

I will send debug logs to [devteam@adguard.com](mailto:devteam@adguard.com) in a minute. Recorded at around 18:28 27.10.2022.

EDIT: I've sent the logs.

**Comment by Tornhoof** [comment] 2022-10-29 11:11
Same thing here on an Android 12, OnePlus 2 with Adguard 3.6.10. according to the filter logs, the DNS lookups fail until I restart Adguard.

**Comment by floxigen** [comment] 2022-11-02 09:00
I've the same issue here with pixel 7 pro as well

**Comment by floxigen** [comment] 2022-11-06 11:24
It's driving me nuts everytime I get home I've to restart adguard

**Comment by maxikuzmin** [comment] 2022-11-07 11:07
@Tornhoof @nastavoi @floxigen is AdGuard VPN installed with kill switch setting? This behavior happens with this setting. I've checked, but I don't have this behavior repeated, everything works correctly.

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

It is also a good idea to export your AdGuard settings and attach them to an email

**Comment by nastavoi** [comment] 2022-11-07 16:54
@maxikuzmin 
I've sent all the data to [devteam@adguard.com](mailto:devteam@adguard.com). The issue was recorded at around 17:39-17:41.

I don't use any VPN software.

**Comment by XBadFellaX** [comment] 2022-11-10 08:03
I have also had this issue for a long time on my samsung smartphone but never reported it. When I go out of the house and in my car and drive away, as soon as the network switches from WiFi to Mobile Data the internet stops working, I notice that because I run spotify when I sit in my car when I am still on Wifi. Then I have to turn off adguard and turn ot back on or even turn mobile data off and on sometimes for it to work again.

**Comment by maxikuzmin** [comment] 2022-11-15 12:12
@nastavoi @XBadFellaX we are looking into this issue, we need a little more time

**Comment by nastavoi** [comment] 2022-12-01 18:32
@maxikuzmin hey, any updates?

**Comment by maxikuzmin** [comment] 2022-12-07 09:56
@nastavoi later will need to check in version 4.0 
For now you can try to choose another DNS. Try AdGuard DNS Regular or Non-Filtering Regular. That might help

**Comment by nastavoi** [comment] 2022-12-07 10:05
@maxikuzmin do you mean 4.0 stable when its released or nightly? I'm on 4.0 nightly right now.

**Comment by maxikuzmin** [comment] 2023-01-10 11:25
@nastavoi yes, the stable version. Did changing to a different DNS help you?

**Comment by nastavoi** [comment] 2023-01-10 13:43
@maxikuzmin yes, it does work fine if I change the DNS to e.g. cloudflare or Google (but it's just a workaround for me)

**Comment by maxikuzmin** [comment] 2023-01-13 18:24
@nastavoi @floxigen @Tornhoof  we solved your problem in the 3.6.11 Beta 1 update. Please update to this version and check it out. Let us know the result

**Comment by nastavoi** [comment] 2023-01-13 18:26
@maxikuzmin thanks, great news, i'll test it, but before I do, can you confirm that 3.6.11 beta is actually more up-to-date than 4.0 nightly 37 which I'm currently using?

**Comment by maxikuzmin** [comment] 2023-01-16 10:31
@nastavoi actually, version 4.0 nightly 37 should also fix this problem. You can check it on the version you want :) 
Please let us know the result

**Comment by Tornhoof** [comment] 2023-01-16 10:39
Looks like the fix in 3.6.11 Beta 1 is working for me. I don't have any failing DNS requests. Thanks.

**Comment by maxikuzmin** [comment] 2023-01-18 17:15
@Tornhoof great! I'll close this issue then

**Closed by maxikuzmin** 2023-01-18 17:15 UTC
Labels: Bug, Resolution: Fixed, Status: Resolved, Middle, Version: AdGuard v3.6.11

**Comment by nastavoi** [comment] 2023-01-18 17:20
@maxikuzmin fixed for me too, thanks for the help!

**Comment by Batman2814** [comment] 2023-01-22 20:17
would this issue explain when I get a message saying connected without internet. i would have to toggle the wifi on and off or would this be a issue that not related to Adgaurd because when i researched this issue it did say the the DNS could be related why I'm having this issue. so if you could get back to me if we are talking about the same issue?

**Comment by Phyore** [comment] 2024-09-10 17:05
I get this issue also, finally found out it was when switching between mobile data and wifi

Pixel 8 pro, latest adguard
