### ISSUE TITLE
transparent updates?

### ISSUE THREAD

**Issue by patrickdrd** [AdguardTeam/AdguardForAndroid#2915] opened 2019-07-11 08:20 UTC
can the updates of filters etc be made transparent?

I mean when updating, AG goes down for quite a long time,
at least for me that I'm using 20 filters + one dns filter,
I have to wait for 2-3 minutes till it starts again,
and for that time the device is either unusable or I will have to bear ads,

have you thought of an implementation that this process would be made transparent?
I mean update without stopping the blocking engine

I'm using automation too, 
but how can I determine an interval in the future in which my device would be not used or my screen will be off?
It's not possible of course

**Comment by artemiv4nov** [comment] 2019-07-11 13:30
Duplicate of #2881

**Closed by artemiv4nov** 2019-07-11 13:30 UTC
