### ISSUE TITLE
Add "org.mozilla.fennec_fdroid" to "pref.enforce.https.filtering" by default

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdguardForAndroid#3556] opened 2020-08-29 03:23 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (v3.5 RC 1 (61))
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Problem Description

I notice that [Fennec F-Droid](https://f-droid.org/en/packages/org.mozilla.fennec_fdroid/) is absent from the list of HTTPS-supportive browsers in `pref.enforce.https.filtering`.

### Proposed Solution

Add `org.mozilla.fennec_fdroid` to `pref.enforce.https.filtering` by default.

### Alternatives Considered

I presume it'd be reasonably easy for users to add that line to `pref.enforce.https.filtering` themselves, but in this case it's mostly (but not exclusively) the thought that counts here.

### Additional Information

The background story is that I was deeply displeased when Firefox on Android had an update some weeks ago that reduced the amount of supported extensions to less than 10, so after some desperate attempts to remain on the old version and not have it auto-update to the new version, I found out that switching to Fennec F-Droid was the easiest method by far to do so. Thus I take an unqualified guess that Fennec F-Droid's userbase surely must've increased considerably recently, if other people out there have thought like I did.

**Comment by artemiv4nov** [comment] 2020-09-18 12:24
Duplicate of #3587

**Closed by artemiv4nov** 2020-09-18 12:24 UTC
Labels: UI, low

**Comment by DandelionSprout** [comment] 2020-09-18 13:37
I would say that my issue report was made before his, but I'm not someone who complains about a problem getting fixed.
