### ISSUE TITLE
Some dialog boxes do not have any input fields

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3145] opened 2019-10-15 19:04 UTC
### Issue Details

- **AdGuard version:**
  - 3.3.72
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Galaxy A8
- **Operating system and version:**
  - Android 9
- **Root access:**
  - Yes (via Magisk)

### Expected Behavior

Dialog windows w/text input fields should display said fields

### Actual Behavior

Text input fields are not displayed.
Only affects **Settings > Stealth Mode > Strip URL from tracking parameters**, **Settings > Network > Filtering Mode > Local HTTP Proxy Port**, **Settings > DNS > Chosen Server > %server% > Server Type**

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_2019-10-13-22-32-52-227](https://user-images.githubusercontent.com/33634917/66861484-c5414500-ef97-11e9-9faa-46c6bd8df15c.jpg)
![Screenshot_2019-10-13-22-33-09-605](https://user-images.githubusercontent.com/33634917/66861486-c5414500-ef97-11e9-8076-43e4ebb1eca4.jpg)
![Screenshot_2019-10-13-22-33-40-029](https://user-images.githubusercontent.com/33634917/66861487-c5414500-ef97-11e9-9369-9e6bb0274b8a.jpg)

</details>

### Additional Information

Helpdesk ID: 1307673

**Comment by artemiv4nov** [comment] 2019-10-17 11:22
Duplicate of #3133, that task is already done.

**Closed by artemiv4nov** 2019-10-17 11:22 UTC
