### ISSUE TITLE
Android 14 blocks the usual method of system certificate install

### ISSUE THREAD

**Issue by androidacy-user** [AdguardTeam/AdguardForAndroid#4964] opened 2023-09-07 17:55 UTC
### Issue Details

Android 14 introduced an APEX for the certificate store, which is far harder to modify. The old method of using a Magisk module won't work. 

### Proposed solution

I'm curious if Adguard has or is working on a solution for this. 

### Alternative solution

N/A

**Comment by sfionov** [comment] 2023-09-07 18:24
Hello! We have this issue in adguardcert module: https://github.com/AdguardTeam/adguardcert/issues/32. 

However, we didn't looked into it yet. Since it is becoming clear what happened, we will look into this.

For example, APEX'es for timezone data bind-mounted. So there's a chance that cert data is bind-mounted too, in this case Magisk systemless bind-mounts may override bind mounts of apex.

**Comment by maxikuzmin** [comment] 2023-09-18 17:43
@androidacy-user duplicate of https://github.com/AdguardTeam/adguardcert/issues/32
There are plans to fix this in the 4.2 update.
For the moment, I'm closing this issue

**Closed by maxikuzmin** 2023-09-18 17:43 UTC
Labels: Feature request, Priority: P4

**Comment by Skorpion96** [comment] 2023-11-30 12:41
I probably found an alternative solution, enable a screen lock, install the cert as user cert, then from pc:
adb root
restarting adbd as root
adb shell
tdgsi_arm64_ab:/ # cd /data/system
tdgsi_arm64_ab:/data/system # rm -rf gatekeeper.password.key
tdgsi_arm64_ab:/data/system # rm -rf gatekeeper.pattern.key
tdgsi_arm64_ab:/data/system # rm -rf locksettings.db
tdgsi_arm64_ab:/data/system # rm -rf locksettings.db-shm
tdgsi_arm64_ab:/data/system # rm -rf locksettings.db-wal
tdgsi_arm64_ab:/data/system # reboot
after this the screen lock will be gone and the cert will still be in the user store with no warnings from the os at all (at least from me it was), hope this will help
