### ISSUE TITLE
Wrong "Internet is not available" message on UpdatesActivity

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#3095] opened 2019-09-27 11:19 UTC
### Issue Details

- **AdGuard version:**
  - 3.3 n2
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Samsung Galaxy Note 9 SM-N960F
- **Operating system and version:**
  - Android 9
- **Root access:**
  - None

### Expected Behavior

AdGuard application updates should be downloaded without any issues

### Actual Behavior

When using Wi-Fi, AdGuard is unable to download app updates. Filter updates go through without any problems.

### Screenshots & Logs

See helpdesk ticket 1456058.

### Additional Information

None provided.

**Comment by admitrevskiy** [comment] 2019-09-27 13:29
As I see in logs, the user has 3.3 n5 installed. Update will be available after 3.3 n6 release.

**Comment by Xophile** [comment] 2019-09-27 14:46
Correct, I have 3.3 n5. Is the issue fixed in n6?

**Comment by admitrevskiy** [comment] 2019-09-27 15:12
@Xophile hi!
3.3 n6 version not released yet, thats why app can't be updated: there is just nothing to update.

**Comment by Xophile** [comment] 2019-09-27 18:46
Ok, got that. But it still says "Internet not available" when there is no problem with my connection

**Comment by admitrevskiy** [comment] 2019-09-27 20:44
Oh, now I see. We try to resolve `example.org` to check if internet connection is available and for some reason this check failed in your network 🤔 
Can you give me more information about your wifi network? Maybe you have AGHome or other filtering app right in the router? Is `example.org` reachable via browser?

**Comment by Xophile** [comment] 2019-09-28 05:50
I haven't done any changes at all in my network for over a year. This behavior happened solely after an AG update. Fiber connection, Technicolor TG799vac Xtream router.

I cannot access example.org from my Firefox browser on my phone.

Thanks

**Comment by Xophile** [comment] 2019-09-28 18:43
Updated to n6 and went to a friend's house. Completely different location, router etc but the same error message.

**Comment by admitrevskiy** [comment] 2019-09-28 21:02
Is `example.org` unreachable on this network too?

We should try to reproduce this issue on our side.
Please, enable `Record everything` in `Advanced` settings and try to reproduce the issue with n6. After that try to reach `example.org` via browser. Send this logs to `devteam@adguard.com` and specify time when issue happened. 

You can enable DNS filtering and we will see some additional info in logs.

BTW. Is `example.org` reachable from any other device in your network?

**Comment by Xophile** [comment] 2019-09-29 05:34
Hi!

I forgot to try example.org on my friends network.

I have already sent in logs with record everything and timestamps in helpdesk ticket 1456058.

Do you need more logs from n6 you mean?

Thanks

**Comment by Xophile** [comment] 2019-09-29 07:51
Example.org does not work with any other phone in my house where AG is enabled. There are no errors on a Samsung Galaxy S8 when I try to update it on the very same network.

**Comment by admitrevskiy** [comment] 2019-09-30 08:07
@Xophile  hi!
Yes, I ask you to record more logs with DNS filtering enabled.
The difference with previous logs is an explicitly attempt to reach `example.org` via browser. I'd like to find out what's wrong with this domain in your case :)

**Comment by Xophile** [comment] 2019-10-01 04:28
New logs sent!

**Comment by artemiv4nov** [comment] 2019-10-04 10:19
@Xophile hi!
Is example.com unreachable on this network too?

**Comment by Xophile** [comment] 2019-10-04 14:29
Hi!

I only tested example.com on my home network which is where my two logs are from.

**Comment by admitrevskiy** [comment] 2019-10-08 16:04
@Xophile hi!
I asked you about example.`org` since @artemiv4nov asked you about example.`com`. Please, check `example.com`, we need to find domain that is available on all networks including yours.

**Comment by Xophile** [comment] 2019-10-08 19:49
I can't reach example.com, nor example.org

**Comment by Xophile** [comment] 2019-10-11 16:34
Fixed in 3.3 nightly build 12 for me

**Comment by admitrevskiy** [comment] 2019-10-11 16:36
@Xophile thank you for response!

Testing instructions for QA: no needs.

**Closed** 2019-10-25 10:12 UTC
Labels: Bug, P4: Low
