### ISSUE TITLE
AdGuard prevents Xbox remote play

### ISSUE THREAD

**Issue by anastenko** [AdguardTeam/AdguardForAndroid#3889] opened 2021-06-28 14:49 UTC
### Prerequisites

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Issue Details

- **Device:**
  Android 11 on a Pixel 4a 5G

### Issue

Xbox remote play (streaming from Xbox Series X on the local network using the Xbox android app) does not work while AdGuard is active. This is true even when AdGuard is set only to filter in browser apps.

Ticket number [#515497](https://adguard.zendesk.com/agent/tickets/515497)

**Comment by anastenko** [comment] 2021-07-01 11:17
XBox tries to use ipv6, perhaps that's what kills it. Alternatively, you can turn off IPv6 in low-level settings to give it a try.

**Comment by monreal** [comment] 2021-07-10 21:11
After disabling the Xbox app in app management everything works fine. My problem actually was that I did not know AdGuard had the app management feature: I always looked for it in settings.

**Comment by artemiv4nov** [comment] 2021-08-01 13:26
I closed this issue due to the problem is solved.

**Closed** 2021-08-01 13:27 UTC
Labels: Bug, Resolution: Fixed, Status: Resolved
