### ISSUE TITLE
Adguard blocking internet connection until updating filters

### ISSUE THREAD

**Issue by Konfetti030** [AdguardTeam/AdguardForAndroid#4478] opened 2023-02-17 06:34 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4 nightly 36 and above 

### Environment

```markdown
- OS: A11 and A12
- Device: Xiaomi Mi 9 and OnePlus Nord 2
- Firmware: latest stable
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Mobile Ads filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, EasyList Germany

### Issue Details

Steps to reproduce:
1. Opening chrome but no website loading 
2. Open Adguard and clicking update button
3. Adguard is checking for updates and updating
4. Chrome and internet connection is working again.
5. Involved Adguard function: DNS protection if setting is set to default system setting.
6. After changing to Google DNS it might be fixed (not 100% sure)

### Expected Behavior

Adguard is not blocking internet connection

### Actual Behavior

No internet connection

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Konfetti030** [comment] 2023-02-17 14:52
Yes. But i think that updating filters is just a workaround because issue is being caused by DNS protection default setting.
In the Adguard forum there are several threads of it (i think in combination with Xiaomi devices, but issue also appearing with OnePlus Nord 2).

**Comment by Batman2814** [comment] 2023-02-17 16:30
I believe I'm having the same problem. Haven't been able to figure it out for weeks but I would get a message that says connected without internet. Even tried changing the DNS which didn't do anything to fix it.

**Comment by Konfetti030** [comment] 2023-02-17 18:11
Please upvote everybody because this is a big issue/bug because it's heavy interfering daily use of the app

**Comment by Batman2814** [comment] 2023-02-17 22:27
So I changed the Private Adguard DNS in the Android version of Adgaurd to the regular Adguard DNS protocol set on quic and it hasn't disconnected with that message connected without Internet so far but if any else can check to see if the problem on the regular Adguard DNS doesn't have that problem then the issue might be with setting up Adgaurd Private DNS in the Android version of Adgaurd.

**Comment by Batman2814** [comment] 2023-02-18 15:53
I still have no idea what is causing this problem with Adgaurd seems to happen with all DNS  for 8 hours and 30 minutes it cuts off my internet connection what's the message saying connected without internet. This is getting exhausting trying to figure this out. This problem is interfering every second and I can't even use my device on my wifi network.

**Comment by Konfetti030** [comment] 2023-02-18 17:37
> I still have no idea what is causing this problem with Adgaurd seems to happen with all DNS for 8 hours and 30 minutes it cuts off my internet connection what's the message saying connected without internet. This is getting exhausting trying to figure this out. This problem is interfering every second and I can't even use my device on my wifi network.

Try Google DNS. With that DNS I have the "best connection". But this can't be the solution nor an acceptable workaround.

**Comment by Konfetti030** [comment] 2023-02-19 12:56
As I found out, it's not even necessary that certain filters get updated or if they are latest. After update check is made, chrome is loading websites again.

Please developers fix that huge bug.

**Comment by Batman2814** [comment] 2023-02-19 16:15
tried google DNS in Adguard still got that message connected without Internet.

**Comment by Konfetti030** [comment] 2023-02-19 16:29
Yeah me too. Useless

**Comment by Batman2814** [comment] 2023-02-19 17:33
it's not just Adguard Private DNS it's happening on every DNS that is setup in the Adguard Android App even where I have Adguard Private DNS setup on my router it gives me that message connected without Internet. So I been forced to use eero secure on my eero router which uses Amazon's DNS Service.

**Comment by Konfetti030** [comment] 2023-02-19 17:51
That's an important information for the developers. Thank you for that

**Comment by Batman2814** [comment] 2023-02-19 19:24
What router do you have?

**Comment by Konfetti030** [comment] 2023-02-19 19:26
I have an AVM Fritzbox router.
But I only use Adguard for Android.

**Comment by Konfetti030** [comment] 2023-02-20 06:59
Happy news, I received an answer today. I hope they will keep their word:

Thank you for letting us know.

One of our QA engineers has been assigned to test this issue, so you'll eventually receive an update on how long it will take to fix the issue.
But don't worry, this problem will be definitely fixed, we won't release our update with such a major bug.

Thank you for your patience. 

Sincerely,
AdGuard Support Team

**Comment by Konfetti030** [comment] 2023-02-21 11:37
> @Konfetti030 Hi! Let's find out what is wrong with the app and why. Have you performed a clean installation? Are you on the cellular or Wi-Fi? If you disable DNS protection, is the issue gone?

Yes I made also a clean install several times. I am on cellular and wifi with the same problem. If I don't use DNS there aren't any disconnections from internet.

**Comment by Versty** [comment] 2023-02-21 11:54
@Konfetti030 So the issue is clearly related to DNS. 
If you disable DNS filters option, does the issue persist?

**Comment by Versty** [comment] 2023-02-21 11:57
@Konfetti030 Could you provide a full settings set and logs from your device to help us investigate? 

Please follow the steps below to properly collect debug logs and settings: 
1. Open AdGuard and go to Settings tab -> General.
2. Choose "Advanced".
3. Set Logging level to "Debug". It's desirable to close all background apps that don't concern the problem beforehand.
4. Reproduce the issue, then return to "Advanced" and set the logging level back to "Default". Notice the exact time when it happened. 
5. Use the "Export logs and system info" option to save the log file to the phone storage 
6. Go back to the Settings tab 
7. Click the context menu in the top right corner -> Export 
8. Attach both files to the email and send it to `devteam@adguard.com`, mention the issue number `#4336` in the subject and time when the issue was reproduced.

**Comment by Konfetti030** [comment] 2023-02-21 20:29
Ok I just set it up to debug.
Last error was at 7:04pm but this was before I started this debug logging. But i will follow the instructions and send it after next bug.

**Comment by Batman2814** [comment] 2023-02-22 22:41
was your phone a samsung Phone?

**Comment by Konfetti030** [comment] 2023-02-24 18:08
> it's not just Adguard Private DNS it's happening on every DNS that is setup in the Adguard Android App even where I have Adguard Private DNS setup on my router it gives me that message connected without Internet. So I been forced to use eero secure on my eero router which uses Amazon's DNS Service.

Do you still have the connection interruptions?
Stove a few days I don't have this bug anymore. Right now using Adguard DNS over HTTPS

**Comment by Batman2814** [comment] 2023-02-26 14:33
https://www.androidcentral.com/phones/samsung-galaxy-s23-ultra-wi-fi-issues

**Comment by Konfetti030** [comment] 2023-02-27 06:49
> https://www.androidcentral.com/phones/samsung-galaxy-s23-ultra-wi-fi-issues

I don't own a Samsung S23. Issue happens with Xiaomi Mi 9 and OnePlus Nord 2 with different routers in different environments!

**Comment by Versty** [comment] 2023-02-28 08:17
@Konfetti030 @Batman2814 
Does the issue still reproduce on the latest nightly? 
We have released a couple of nightly versions with the new DNSLibs, so this issue might be fixed.

**Comment by Konfetti030** [comment] 2023-02-28 08:40
On my side it looks really like issue might be fixed. Since the maybe last 2 nightys no issue anymore.
I am using Adguard DNS over HTTPS right now. And you @Batman2814 ?

**Comment by Konfetti030** [comment] 2023-02-28 12:31
@Versty 
Does it make sense to test especially other Adguard DNS? Would be awesome if issue is fixed but i am still a little bit conservative with it because issue existed for years.

Nevertheless many thanks so far to all devs.

**Comment by Versty** [comment] 2023-02-28 12:43
@Konfetti030 We have completely renewed the source code, the old issues should be gone now.
So it definitely makes sense!

**Comment by Konfetti030** [comment] 2023-02-28 12:45
Sounds really really awesome and i can confirm that since 2 nightys no DNS issue anymore.

**Comment by Konfetti030** [comment] 2023-03-04 09:44
@Versty 
I am facing this issue again.
I am starting chrome and opening website but loading process stands still and website is blank.
Then I opened Adguard and wanted to change logging in debug modus so that I can send it to you but after switching to debug logging website was loading like with workaround by updating filters.

I don't know... :(

**Comment by Versty** [comment] 2023-03-06 10:45
@Konfetti030 Weird thing. Please keep monitoring this issue with debug logs turned on, if possible.

**Comment by Konfetti030** [comment] 2023-03-07 17:00
> @Konfetti030 Weird thing. Please keep monitoring this issue with debug logs turned on, if possible.

It's so weired, because when the issue causes and website is not loading and stays blank, then i change to Adguard settings and switching to debug logging and after that website is also loading. Same like the workaround with filter updates.
I will stay in debug logging now

**Comment by Versty** [comment] 2023-03-23 16:31
@Konfetti030 How is it going?

**Comment by Konfetti030** [comment] 2023-03-23 22:52
@Versty Hi Diana, thanks for asking. Right now it seems to be good, nevertheless I never got a reply of my sent in debug log last time. I think it's working good since 2 nightly builds. A few seconds ago i just updated to latest. Right now i am using DNS over HTTPS which made always issues in the past.
I would like to monitor it and follow it up so don't close this topic :)

**Comment by Versty** [comment] 2023-03-29 13:34
@Konfetti030 Is everything working properly on your device? If so, would be better to close the issue. 
In case you notice this problem reproducing again, simply reopen it.

**Comment by Konfetti030** [comment] 2023-03-29 19:31
> @Konfetti030 Is everything working properly on your device? If so, would be better to close the issue. In case you notice this problem reproducing again, simply reopen it.

I am not really sure what to answer. Since latest update and update before it seems to work better again. The updates between our last contact and the updates i mentioned it was bad again

**Comment by Konfetti030** [comment] 2023-03-30 19:00
@Versty 
Next thing what is interesting:
Always when I am facing the issue again in the last time I do my workaround by manually updating filters.
And the last times it was always happening when a new update is available. After update the website is loading in chrome normally again.

**Comment by Versty** [comment] 2023-04-04 09:25
@Konfetti030 Would you mind staying on the nightly 79 for a couple of days and monitoring this issue? 
We would like to corroborate the case you described above. Some details about your `Auto-update filters` setting will be useful as well.

**Comment by Konfetti030** [comment] 2023-04-04 10:20
@Versty 
I am on 4.0.722 right now. Is this okay?
Yesterday I mentioned that in one app the ads were not blocked as like before btw.

**Comment by Versty** [comment] 2023-04-04 12:38
@Konfetti030 Yes, perfect version. What are your current settings for `Auto-update filters`?

**Comment by Konfetti030** [comment] 2023-04-04 21:48
@Versty 
Adguard Basic
Adguard Mobile ads
Adguard tracking 
Adguard social media filter
Adguard harassment filter
Online malicious url Blocklist
Nocoin filter list
Adguard German filter
Easylist Deutsch
Serbo Croatian list from dandelion

And DNS over HTTPS right now

**Comment by Konfetti030** [comment] 2023-04-05 22:41
@Versty 
Since the new update is available, I had to do the workaround a few times.

**Comment by Versty** [comment] 2023-04-06 09:13
@Konfetti030 Got it. We would like to take a look into your logs one more time. Could you wait for the issue to reproduce (use debug logging mode), then collect the logs and send it to `devteam@adguard.com`?
Please mention the number `#4478` in the subject line and the time when the issue occurred.

**Comment by Konfetti030** [comment] 2023-04-06 18:15
@Versty 
Hi, just sent a few mins ago debug log to devteam.

Hope you can find and fix it.

**Comment by Versty** [comment] 2023-04-10 17:25
@Konfetti030 Thanks, your logs have been received. We are investigating further.

**Comment by Konfetti030** [comment] 2023-05-20 15:14
@Versty 
Since around a week this bug came back again. Very often no connection until manual filter update or turn off WiFi ins turn on again.
Very bad at the moment :(

**Comment by Konfetti030** [comment] 2023-05-26 12:50
@Versty 
Since I have roaming internet connection I have disconnection errors most of the time but only on WiFi network. This WiFi network is over a LTE/4G router.
The last times in roaming I had this issue also very more often than before.
Do you need debug log?

**Comment by Versty** [comment] 2023-05-28 21:30
@Konfetti030 Yes, the debug logs would help a lot. 
Please mention the reproduction time in the description and this issue number `4478` in the subject.

**Comment by Konfetti030** [comment] 2023-06-03 04:12
@Versty sent you debug log a few days ago

**Comment by Konfetti030** [comment] 2023-06-30 16:14
Problem still exist. I am opening chrome clicking on website. Website stays blank for mins. I go to adguard and manually update filter. Switching back to chrome website is loading immediately

**Comment by Konfetti030** [comment] 2023-07-03 08:48
@Versty 
Never got any reply to my last log I sent in.
Bug still annoying me.
Same problem on Xiaomi Mi 9, Mi 11 Pro and OnePlus Nord 2

**Comment by Versty** [comment] 2023-07-06 15:39
@Konfetti030 The fix will be included in one of the next DNSlibs updates, watch this issue https://github.com/AdguardTeam/DnsLibs/issues/200

**Comment by Konfetti030** [comment] 2023-07-29 10:14
@Versty 
One more information which maybe help to understand the bug:
EVERY time when a new nightly is available the internet connection is not working too. Then I search for filter updates and are downloading also the update. The download sometimes does not start immediately and I have to turn off WiFi for example. Then download starts

**Comment by Versty** [comment] 2023-10-04 15:48
@Konfetti030 
This issue should be fixed in the AdGuard for Android 4.2 beta. Could you confirm that the issue is gone?

**Comment by Konfetti030** [comment] 2023-10-05 18:57
@Versty Oh yes Diana it looks like finally this bug is solved.
I don't know if it's because I am following the message by deactivating miui battery optimization (miui is switching toggle always back but with hidden Xiaomi settings app you can prevent it not to switch back) or because there is no nightly update anymore since weeks (??).
Thank you very much again to all Devs. I think it was one of the longest lasting issues ain't it :)

**Closed** 2023-10-09 15:37 UTC
Labels: Waiting for fix, Priority: P4

**Comment by Konfetti030** [comment] 2023-10-14 16:00
@Versty 
Hey, I am facing this error again and also the whole app is freezing often since one of the last 3-4 updates.
I think the only version which seem to solved this bug for the first and only time was 4.2 Nightly 42, Release date: September 18, 2023.

Please check it again and try to find out what changed again since next nightly from October 3. Thank you
