### ISSUE TITLE
No internet connection via root proxy (T-mobile)

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForAndroid#2428] opened 2019-01-06 04:15 UTC
Users report that in the root proxy mode and by the T-mobile provider, the Internet connection is missing or broken. Also, the WiFi calling function does not work. With VPN mode everything works fine.

### Customer ID 
1055120

### Your environment

* Adguard version: 2.12.247 - 3.0
* Adguard filtering mode: Proxy (auto)
* Device model: (e.g. Google Pixel) 
* Operating system and version (e.g. Android 7.1.2)
* Rooted or not? - Yes

**Comment by marcmv1** [comment] 2019-01-08 00:58
WiFi calling works. I said in my email to you that if I disabled IPv6 like you suggested that WiFi calling would stop working.

Device Pixel 2 XL
Android 9 December 2018 patch

**Comment by ameshkov** [comment] 2019-01-09 04:06
@Revertron please check the logs in the ticket. Marked this issue as "waiting for data" for now until we figure what's the real cause.

**Comment by ameshkov** [comment] 2019-03-11 13:48
Wi-Fi calling issue is resolved in #2550

**Comment by marcmv1** [comment] 2019-03-11 13:53
Andrey,

I have these exclusions setup, you helped me with that a while ago and Wi-Fi calling has worked perfectly. My issue isn't wifi calling, it's the fact that with AdGuard enabled I lose internet access for Chrome and any other apps routed through adguard in proxy mode. LTE is the issue at this point.

**Comment by ameshkov** [comment] 2019-03-11 14:22
Huh, got it, reopening

**Comment by ameshkov** [comment] 2019-03-11 14:24
@marcmv1 could you please do the following:

1. Install the latest AG for Android nightly build: https://agrd.io/android_nightly
2. Go to settings - advanced - logging level -> set it to "record everything"
3. Reproduce the issue
4. Go to settings - advanced - export logs
5. Send the logs to `devteam@adguard.com`

In the nightly versions we added more system info to the exported archive so it will be helpful to check it.

**Comment by marcmv1** [comment] 2019-03-11 14:26
Thanks Andrey. I'm working now. As soon as I can break away I'll send you all the info you asked for

**Comment by ameshkov** [comment] 2019-03-21 10:35
@marcmv1 got the logs, thank you!

@Revertron @sfionov the logs are in our ncloud, take a look when you have some time. iptables configuration is quite crazy.

**Comment by ameshkov** [comment] 2019-04-23 14:21
It's hard to figure what exactly is wrong here. Let's wait for any other similar complaints.

**Comment by Nomadic-Knight78** [comment] 2019-07-03 13:12
Canadian wireless carrier Freedom Mobile recently did OTA June 1, 2019 Security Patch for 9-PIE. My device is a Samsung Galaxy A8, UNROOTED. Initially thought I was losing connection as well due to a little over 3 day's of attempting to maintain Proxy connection as directed by the KB on the AdGuard information pages. Outbound Proxy notification says device is routed through the Proxy server. Protection Service notification says no proxy is configured for the connection on port 8080. Mobile Data & Wi-Fi cause a disconnection notice anywhere from 15-30 minute's roughly, depending on the source of Internet supply. Local VPN is steady while creating connection issues for Wi-Fi, 2.0 & standard. Service tech of carrier reflashed OS to current as well as speed testing, that gave an average of 400 Mbps. Still intermittent Proxy connection. Tried Private DNS on/off. Local VPN. Https Filtering on/off. Combination of all these mixed together in various combinations.
Only non-variable is Pie-9 OS. 4 other Android devices in home, 1 running Beta v4 of Q. Only when 9-Pie is OS attempting to use Proxy Service is any disconnection noticed.

**Closed** 2019-09-08 14:37 UTC
Labels: Waiting for data, Wontfix
