### ISSUE TITLE
"Block Connections Without VPN" On Android 10 Blocks Wifi

### ISSUE THREAD

**Issue by Cybo1927** [AdguardTeam/AdguardForAndroid#3331] opened 2020-02-03 22:35 UTC
### Prerequisites

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [X] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

### Issue Details

- **AdGuard version:**
  - 3.3.1
- **Filtering mode:**
  - Local VPN
- **Device:**
  - Google Pixel 3
- **Operating system and version:**
  - Android 10 (Android security patch level: January 1, 2020)
- **Root access:**
  - No

### Expected Behavior

Enabling "Block Connections Without VPN" in the VPN settings should only block internet when the VPN isn't on

### Actual Behavior

It blocks wifi unless I turn the setting off

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot_20200203-162447](https://user-images.githubusercontent.com/39284087/73696734-864c1200-46a2-11ea-9204-ba26b6704577.png)

![Screenshot_20200203-162518](https://user-images.githubusercontent.com/39284087/73696740-8ba95c80-46a2-11ea-8f6f-54b2cd8a31bb.png)

</details>

**Comment by artemiv4nov** [comment] 2020-02-04 07:56
It's duplicate of #3327

**Closed by artemiv4nov** 2020-02-04 07:56 UTC
Labels: Duplicate
