### ISSUE TITLE
AdGuard crashes to desktop when open

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForAndroid#2762] opened 2019-05-30 07:12 UTC
### Steps to reproduce
1. Just try to open AdGuard UI. Doesn't matter how - either by opening the app via a shortcut or by tapping on Assistant.
2. App will show a black screen for a few seconds and crash to desktop.

### Expected behavior
AdGuard should display the user interface

### Actual behavior
The app crashes to desktop

<details><summary>Screen captures:</summary>

Available in ticket 1981369.

</details>

### Customer ID 
1981369

### Your environment
* Adguard version: Latest Nightly build
* Adguard filtering mode: Local VPN, HQ filtering
* Device model: Huawei FRD-L19
* Operating system and version: Android 8
* Root access:  No
* Any other apps that can start VPN / Antiviruses / Cleaners etc. installed?:  None found

**Comment by akmLaVx** [comment] 2019-06-23 09:10
The user had reported back.
The crashes persist through moving to the latest nightly release, but they now happen when he is attempting to access Settings.

**Comment by TheHasagi** [comment] 2019-07-10 10:46
Ask a customer to check for the updates and try to reproduce the issue.

**Comment by akmLaVx** [comment] 2019-07-26 21:00
Still reproduces on 7.2.100n

**Comment by ameshkov** [comment] 2019-08-01 20:53
Moved back to the "in progress" pipeline.

@admitrevskiy please take a look at this bug tomorrow.

**Comment by ameshkov** [comment] 2019-08-05 17:12
Reassigned to v3.3

**Comment by artemiv4nov** [comment] 2019-08-28 14:07
@akmLaVx check this issue on latest nightly, please.
If it problem is still, send debug logs, please.

**Comment by akmLaVx** [comment] 2019-09-04 18:01
Logs available in ticket 1981369

**Comment by artemiv4nov** [comment] 2019-11-15 16:15
@akmLaVx I moved this bug fix to the other issue (#3212) because it has nothing to do with this (#2762) task.

The real point of this issue is about another bug when the application crashed because of Android Package manager cannot get list of all applications. We fixed this trouble few months ago, so I'll close the task.

**Closed** 2019-11-15 16:15 UTC
Labels: Bug, P3: Medium, Waiting for repro
