### ISSUE TITLE
Tap and hold app icon toggle protection

### ISSUE THREAD

**Issue by Exmanman** [AdguardTeam/AdguardForAndroid#4965] opened 2023-09-08 10:11 UTC
### Issue Details

Please reintroduce the toggle protection shortcut when tapping and holding the app icon.
This feature is highly valuable, especially given that the only available widget is a 3x1 size, which is relatively large.

![Screenshot](https://github.com/AdguardTeam/AdguardForAndroid/assets/144440764/ab81a951-1934-438a-983d-48accb94d569)

**Comment by Versty** [comment] 2023-09-20 17:36
@Exmanman Hi! 
This issue is a duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/4780. 
Please vote for the feature by putting a `thump up` emoji on the linked issue.

**Closed** 2023-09-20 17:36 UTC
Labels: Feature request, Priority: P4
