### ISSUE TITLE
Some apps not working with IPV6 filtering enabled

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForAndroid#4467] opened 2023-02-14 20:16 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.594

### Environment

```markdown
- OS:A13
- Device:Oneplus 8T
- Firmware: F15
```

### Root access

- [X] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Annoyances filter, EasyList, Fanboy's Annoyances, Web Annoyances Ultralist, Others

### Issue Details

Steps to reproduce:
Enable IPV6 filtering from advanced and reboot while using auto proxy mode 

### Actual Behavior

Apps keep on loading and doesnt load contents.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

Applications: Unsplash, Mobilism, Youtube Revanced (broken/ very slow loading)

**Comment by maxikuzmin** [comment] 2023-02-20 19:16
I don't have this problem repeatedly. Which applications are having problems?

To troubleshoot this issue, we need to get additional logs.

Here's what we need you to do:

- Collect the debug log as it's [explained here](https://kb.adguard.com/en/android/solving-problems/log#debug);
- Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file;
- Additionally, capture the system bug report after reproducing the issue. [Here's the instruction](https://developer.android.com/studio/debug/bug-report);
- Send both files to devteam@adguard.com. Mention the Github issue number and the exact time when the issue was reproduced.

**Comment by maxikuzmin** [comment] 2023-02-27 18:36
Since we do not have this problem repeatedly. I am closing this issue. If anyone has this problem in the future, please reopen the issue

**Closed by maxikuzmin** 2023-02-27 18:36 UTC
