### ISSUE TITLE
OnePlus BgDetect: System randomly kills `com.adguard.android` process

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForAndroid#1385] opened 2017-08-18 14:10 UTC
### Expected behavior
Adguard works with no issues.

### Actual behavior
System stops and kills the `com.adguard.android` process at random. This causes the Internet to be blocked.

```
08-08 17:23:56.527 I/OHPD    ( 1370): [BgDetect][PD] total usage 6 over thold, force stop com.adguard.android (uid 10273) level 0
08-08 17:23:56.527 I/ActivityManager( 1370): Force stopping com.adguard.android appid=10273 user=0: from pid 1370
08-08 17:23:56.527 I/ActivityManager( 1370): Killing 20509:com.adguard.android/u0a273 (adj 200): stop com.adguard.android
08-08 17:23:56.529 D/ActivityManager( 1370): cleanUpApplicationRecord -- 20509
08-08 17:23:56.530 W/ActivityManager( 1370): Scheduling restart of crashed service com.adguard.android/.ServiceManager in 10999ms
08-08 17:23:56.530 D/EmbryoManager( 1370): prepare com.adguard.android
08-08 17:23:56.533 I/ActivityManager( 1370):   Force stopping service ServiceRecord{1919ec7 u0 com.adguard.android/.ServiceManager}
```

### Related reports
1603480, 939612, 1551336

### Your environment

* Adguard version: 2.9.136
* Adguard filtering mode: VPN and Proxy (auto)
* Device model: Philips I928 and One Plus 3 
* Android 4.4.2 and 7.1.1
* No other apps that could affect this issue. Adguard added to battery exceptions.

### Logs 
- [1603480_logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1234630/1603480_logs.zip)
- [939612_logs.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/1234631/939612_logs.zip)

**Comment by AidanGee7** [comment] 2017-08-18 23:25
Exact same happens to me.

**Comment by AidanGee7** [comment] 2017-08-19 10:32
Update: It hasn't done it since updating to the latest beta (fingers crossed).

**Comment by ameshkov** [comment] 2017-08-22 13:52
This is a known OnePlus issue. Sometimes it even kills foreground apps.

https://forums.oneplus.net/threads/oxygenos-4-bgdetect-is-killing-background-processes.498234/
https://forums.oneplus.net/threads/workout-tracking-apps-runkeeper-polar-beat-edmondo-closing-down.495162/
https://forums.oneplus.net/threads/oxygenos-3-bgdetect-killing-legitimate-background-processes.454330/

**Comment by ypetruk** [comment] 2017-08-22 20:29
update from the customer:(ticket ID:939612)
Setting the watchdog to 10 and changing the notification status have not helped

**Comment by janguv** [comment] 2017-10-20 19:34
I've had this issue for yonks as well. 

Things that haven't worked: 

- changing OOS battery optimization settings
- adjusting watchdog settings in AdGuard
- adding AdGuard as an app whose background tasks shouldn't be cancelled (third-party app)
- updating AdGuard to latest beta/release

I'm yet to try:

- making AdGuard a system app

Maybe it'll help though.

**Comment by ameshkov** [comment] 2017-10-22 13:13
Please let me know if the system app trick helps. At the moment the only thing that we can advise besides that is reinstalling OxyOS (it may reset stats BgDetect operates to make its weird decisions)

**Comment by AidanGee7** [comment] 2017-11-30 13:36
Hi there, this is sadly still happening even on the new Oreo Beta (It actually appears to be happening more often now too) :( 

I am trying going to try the following things now to see if they help fix this:

- Increased **ro.sys.fw.bg_apps_limit** value in build.prop
- I will try "Pinning/Locking" the AdGuard app on the recents app screen so that it cannot be closed.

I would try installing AdGuard as a System App however I am struggling to do it (Not experienced in this stuff).

Thank you,
Aidan

**Comment by ameshkov** [comment] 2017-11-30 17:56
@AidanGee7 thank you for reporting it! Please let us know if pinning helps.

Btw, what filtering mode do you use? VPN or proxy?

**Comment by AidanGee7** [comment] 2017-11-30 22:27
Hi @ameshkov - No problem at all!

So far (Fingers crossed) pinning the app appears to have fixed this issue. 

**Android Version:** 8.0.0
**OxygenOS:** 5.0 (Open Beta)
**AdGuard:** 2.10.176
Using Local HTTP proxy setting.

I hope this helps! I'll let you know if this issue happens to me again. 

I am quite confident that it has fixed the issue, since pinning the app it has gone from happening a few times an hour to not happening at all (5+ hours so far) but a few days of testing should give a clearer picture.

**Comment by janguv** [comment] 2017-11-30 22:55
> I am quite confident that it has fixed the issue, since pinning the app it has gone from happening a few times an hour to not happening at all (5+ hours so far) but a few days of testing should give a clearer picture.

I've learnt in my time with this issue to set my expectations extremely low. OOS has a mind of its own. 

I've tried this trick with every version of OOS since it started, and it never made a difference. It would be fantastic if pinning stops bgdetect doing its dirty work. I'm sceptical, unless OnePlus or Google changed something really significant with how the Recents menu works under the hood. 

Do keep us updated!

**Comment by ameshkov** [comment] 2017-12-01 08:02
> unless OnePlus or Google changed something really significant

@janguv this BgDetect nonsense is purely OnePlus :)

I am also very interested in this topic. We periodically receive complaints on the issue. What've I learned is that BgDetect educates itself and changes behavior with time. Reinstalling OOS fixes its behavior.

**Comment by AidanGee7** [comment] 2017-12-04 13:38
**Update:** I can confirm that pinning the AdGuard app has fixed this issue!

I'm not sure how you could use this knowledge though, maybe a messages that popups up if it detects you're running OxygenOS saying you may need to pin the app if you're having issues or just an FAQ entry somewhere? (Or just do nothing if this isn't really a common issue).

Thanks for AdGuard by the way, it's one of the best apps I've ever used and now that it's working fully on OxygenOS it's even better :)

**Comment by janguv** [comment] 2017-12-04 13:45
@ameshkov >this BgDetect nonsense is purely OnePlus :)

Haha don't worry, I realised that! I think what could explain a difference in efficacy of pinning, though, are changes to the recents menu, which could be Google or OnePlus. 

@aidengee7 >I can confirm that pinning the AdGuard app has fixed this issue! 

- great that it's worked for you! I will say that this solution doesn't work on Nougat builds of OOS. Not in my case, anyway.

**Comment by janguv** [comment] 2017-12-12 17:00
@AidenGee7 - seems I was too rash in my former assessment! Mercifully, the pinning method now works for me as well. I wish I had tried it earlier, but after successive OS upgrades it never made a difference before. No idea what's changed to make it work, but I'm super glad it now does. 

For general info - I'm using the last beta build of OOS Nougat. 

It's definitely still a workaround, since you'll get periodically notified that "Adguard" is draining your battery. But importantly, that's no longer followed imminently by a force close without your awareness. Much, much more convenient to just dismiss the warning than have to find out the connection has kaput because Adg has been killed. 

So I'm happy, for now!

**Comment by ameshkov** [comment] 2017-12-12 17:01
Omg, guys, you just made me happy as well:)

I'll pass this information to the support service, finally we can help poor OnePlus users:)

**Comment by janguv** [comment] 2017-12-12 17:05
@ameshkov - haha no worries! I should add: I tested this for a whole week to be sure. Not one time has it been killed. I'm still using the permanent notification, including on lockscreen - am yet to try without the notif.

**Comment by beeeeswax** [comment] 2018-02-25 21:04
Thanks to everyone here for the work on figuring out a solution. As a OnePlus 3 user, this problem has been bugging me for months.

I was so sick of seeing the adguard notification disappearing at random and my internet connection dying that is created a macrodroid macro to restart adguard whenever it's notification was cleared. This actually worked really well but I'd still lose internet for 10-20s every time it happened (which was every few hours at least).

Now I've pinned adguard I've got a notification that's lasted a full day, which I don't remember ever seeing before.

**Closed** 2020-03-20 16:23 UTC
Labels: Android bug
