### ISSUE TITLE
Add Quad9 as a custom DNS Server

### ISSUE THREAD

**Issue by TommiHynynen** [AdguardTeam/AdguardForAndroid#1602] opened 2017-11-21 12:05 UTC
By now everyone probably knows 8.8.8.8, Google's public DNS service which is as neutral as possible... except they collect your data and you implicitly agree to it merely by using it.

Project Quad9 aims to reduce the global spreading of malware by making sure your computer can't communicate with servers that are known to host malware, botnets, and other baddies. So, unlike Google it's not neutral - in that you may get an error on a domain that actually exists, but they don't collect your queries for advertising purposes. If you wish to use it, all you need to do is set your DNS to 9.9.9.9, they have servers all over the world already to make sure access is fast for everyone.

I think this would be a good addition to the adguard.

https://www.globalcyberalliance.org/initiatives/quad9.html

**Comment by ameshkov** [comment] 2017-11-21 12:27
Will do, thank you!

**Comment by ameshkov** [comment] 2017-12-04 12:00
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/1613

**Closed by ameshkov** 2017-12-04 12:00 UTC
Labels: enhancement
