### ISSUE TITLE
[FEATURE REQUEST] Multiple firewall/app management rules

### ISSUE THREAD

**Issue by sam20e** [AdguardTeam/AdguardForAndroid#2695] opened 2019-04-09 00:36 UTC
Hi Guys,

One thing I really love about adguard - your app management system where i can restrict data/wifi access to individual apps. 

I'd really like to see different set of firewall/app-management rules at least 3 pre-defined rules i can switch whenever i need.

Let me give you an example - Last week, i had to travel overseas. Unfortunately I had to use my data roaming feature. So you all know data roaming is very expensive so i cannot let facebook/instagram and few other apps to use any data (normally i dont restrict these apps when im using local data/wifi). So i literally had to open app management and update these apps one by one to restrict data access. I had to do it for like 10-15 apps. 

Lets say if i can create and save different type of app management list. for example 1) normal profile 2) roaming profile 3) sleep mode and when im using data roaming i can simply load the roaming profile and that will restrict data access to facebook and any other apps i;ve selected. that way i dont have to go one by one and change app settings. 

I'm using unrooted device. so i found this 1-2 other apps in playstore which can block an app running for a predefined period but that requires a VPN profile. so its impossible for me to run that app along side adguard. Since adguard is already utilizing a VPN mode, this feature will be a GREAT addition. I'm 100% sure your users will appreciate this feature and I dont see many apps which offers this feature. 

If it's not clear, let me know. Will be more than happy to explain further.

**Comment by ameshkov** [comment] 2019-04-09 08:28
Duplicate of https://github.com/AdguardTeam/AdguardForAndroid/issues/1239

Please vote for the feature requests. More votes -- higher chances that we will do it.

**Closed** 2019-04-09 08:28 UTC
Labels: Duplicate
