### ISSUE TITLE
Adguard does not send authentication to proxies

### ISSUE THREAD

**Issue by androidacy-user** [AdguardTeam/AdguardForAndroid#4733] opened 2023-05-27 03:07 UTC
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0 nightly 110

### Environment

```markdown
- OS: android 13
- Device: pixel 7 pro 
- Firmware: stock
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:
1. Try to connect to a proxy of any type with authentication
2. See "proxy tcp failed" 
3. Export debug logs and see it's getting a 407.

### Expected Behavior

Adguard connects successfully

### Actual Behavior

Proxy doesn't work whatsoever

### Screenshots

N/A

### Additional Information

```
22:52:15.718 [Thread-18] ERROR Native.AGUrlRequest - [id=3003] http://captive.apple.com/hotspot-detect.html: Error connecting via outbound proxy to captive.apple.com:80. Error: 14(HTTP 407)
22:52:15.719 [Thread-18] DEBUG Native.TEST_PROXY - HTTP request failed: http://captive.apple.com/hotspot-detect.html: Error connecting via outbound proxy to captive.apple.com:80. Error: 14(HTTP 407)
22:52:15.722 [Thread-18] DEBUG Native.AGEventLoop - run(): Stopped event thread
```

**Comment by Versty** [comment] 2023-07-03 11:33
@androidacy-user Hi! Sorry for not getting back to you sooner. 
We have made some improvements since you reported the problem. 

Does the issue persist on the latest AdGuard for Android nightly version?

**Comment by Versty** [comment] 2023-08-01 10:54
@androidacy-user Could you check you proxy credentials in AdGuard? 
The problem described in #4884 can be the cause.

**Comment by Versty** [comment] 2023-08-11 15:54
@androidacy-user Have you checked the linked issue on your device?

**Comment by Versty** [comment] 2023-09-04 09:33
@androidacy-user  Closed as a duplicate of the issue linked above.

**Closed** 2023-09-04 09:33 UTC
Labels: Bug, Waiting for data, Priority: P4
